- modules/store/index.ts
- modules/store/spec/selector.spec.ts
- modules/store/src/models.ts
- modules/store/src/selector.ts
Adds a Reselect-inspired `createSelector` and `createFeatureSelector`. Only implements a minimal set of Reselect's features.
> feat(store): Add 'createSelector' and 'createFeatureSelector' utils

- .gitignore
- build/config.ts
- build/deploy-build.ts
- build/index.ts
- build/tasks.ts
- build/util.ts
- circle.yml
- modules/effects/package.json
- modules/router-store/package.json
- modules/store-devtools/package.json
- modules/store/package.json
- package.json
This PR will add auto-deployment for each ngrx package to a `package}-builds` on green builds of master. Will allow install of the latest code in master from the github repos.
> WIP feat(build): Added deployment to build repos

- modules/router-store/spec/integration.spec.ts
- modules/router-store/src/router_store_module.ts
- lint errors
- typos
- import optimizations
> chore: fix lint errors

- MIGRATION.md
- docs/effects/README.md
- docs/effects/api.md
Updated migration guide and minor fixes for @ngrx/effects documentation
> docs(Effects): Updated migration guide for @ngrx/effects

- modules/store/src/index.ts
- modules/store/src/store_module.ts
- modules/store/src/tokens.ts
> fix(Store): Exported initial state tokens

- build/tasks.ts
This MR cuts the build time in half and adds the "mangle" flag to the uglify step, which reduces bundle size (even after gzip).
> Parallelize cp.exec and add mangle flag to uglify

- modules/effects/src/actions.ts
This change allows for better type inference when using @effetcs.
> Modified ofType to return Actions with the associated generic.

- modules/store/src/store.ts
> fix(Store): Removed readonly from type

- modules/store/src/selector.ts
> fix(selector): pass all required arguments to projector

- modules/store/src/state.ts
> fix(Store): Remove parameter destructuring for strict mode (#33)

- MIGRATION.md
- docs/effects/README.md
- docs/effects/testing.md
- docs/store/api.md
- example-app/app/app.module.ts
- example-app/app/books/books.module.ts
- example-app/app/reducers/index.ts
Added testing example to effects documentation and removed reducerFactory snippet from example app
> chore(docs): Updated migration guide for testing effects

- example-app/app/books/reducers/index.ts
State in Book should inherit from root, not books.
See issue #89.
> Fix Book State interface parent

- docs/store/selectors.md
Hello,
I thought this document did a great job of explaining *how* to use the selector helpers but there could be some confusion with new users regarding *why* they should use them. I added a brief explanation to try to clear this up. Awesome work as always!
> Added selector function explanation

- modules/effects/testing/src/testing.ts
> fix(Effects): Wrap testing source in an Actions observable

- MIGRATION.md
See https://github.com/ngrx/platform/issues/103
> Updated the migration guide address @ngrx-store-init action transition

- MIGRATION.md
- docs/effects/README.md
- docs/store/README.md
- docs/store/actions.md
- example-app/README.md
> chore(docs): Added more migration and API documentation

- example-app/app/app.module.ts
- example-app/app/auth/components/login-form.component.ts
- example-app/app/auth/reducers/login-page.ts
- example-app/app/books/effects/book.spec.ts
- example-app/app/books/effects/collection.spec.ts
- example-app/app/books/reducers/index.ts
- example-app/app/core/services/google-books.spec.ts
- example-app/app/reducers/index.ts
- package-lock.json
Hi!
I was checking the example part of the repository and saw that some imports aren't used.
This PR just clean this to avoid confusion.
> fix(example): remove unused imports

- example-app/app/auth/reducers/auth.spec.ts
- example-app/app/auth/reducers/login-page.spec.ts
Hi!
This PR adds some tests for the example application.
Feel free to ask any change, available to do so!
> test(example): add auth and login-page tests

- MIGRATION.md
angular-cli variable is production, not prod
> fix(docs): update angular-cli variable

- README.md
minor edit of effects description
> fix(docs): update effects description

- CHANGELOG.md
- package.json
- yarn.lock
> chore(Platform): add changelog and changelog script

- .github/ISSUE_TEMPLATE.md
Changed issue template based on multiple examples.
Will help resolve #62
> chore(template): Issue Template

- MIGRATION.md
- docs/store/README.md
- docs/store/api.md
- docs/store/testing.md
- example-app/app/books/containers/collection-page.ts
- example-app/app/books/effects/collection.ts
Also moved loading of collection into collection container
Closes #107
> chore(docs): Added migration docs for router-store and testing store

- modules/router-store/spec/integration.spec.ts
- modules/router-store/src/router_store_module.ts
> fix(RouterStore): Add support for initial cancellation with CanLoad guard

- modules/effects/src/effects_feature_module.ts
- modules/effects/src/effects_root_module.ts
> fix(Effects): Ensure StoreModule is loaded before effects

- docs/effects/api.md
- modules/effects/src/index.ts
Also updated documentation and added to example app
Closes #174
> fix(Effects): Export EffectsNotification interface

- modules/store/spec/integration.spec.ts
- modules/store/src/reducer_manager.ts
Closes #206, #233
cc: @lucastheisen
> fix(Store): Set initial state for feature modules

- docs/store/README.md
Update minor store/README.md text description.
The text:
> ...function in the imports array them...
is not very understandable.
> Update minor store/README.md text description

- e2e/app.e2e-spec.ts
- e2e/app.po.ts
- protractor.conf.js
Fix for this: https://github.com/ngrx/platform/issues/241
> Fix e2e tests: fix path to tsconfig.json and fix spec to pass tests

- docs/store/testing.md
Thx @Coscocat for finding this
> docs: fix spyOn (jasmine api) arguments in testing docs example

- modules/store/spec/modules.spec.ts
- modules/store/spec/utils.spec.ts
- modules/store/src/utils.ts
This reverts commit 683013c47acc6446e7ea88872ded7f6a9d1fb867.
> Revert "fix(Store): Update usage of compose for reducer factory (#252)"

- docs/store/testing.md
Just a small docs fix.
Anything else small & fast what I didn't notice?
> docs: fix missing Store import

- modules/router-store/src/router_store_module.ts
> fix(RouterStore): Only serialize snapshot in preactivation hook

- modules/effects/src/effects_module.ts
> fix(Effects): Use factory provide for console

- modules/store/src/utils.ts
> provide default value for 2nd argument to keep Closure compiler happy

- MIGRATION.md
> chore(docs): Added payload interface options to migration docs

- example-app/README.md
- package.json
Also added npm script to run a production build of the example app. Closes #334
> docs(example-app): update example-app url

- docs/effects/api.md
> chore(docs): Fix import for EffectNotification

- modules/store/spec/selector.spec.ts
- modules/store/src/selector.ts
> feat(Store): createSelector with an array of selectors

- docs/store/api.md
> fix(docs) Change providing injected reducers by factory instead of value

- docs/entity/interfaces.md
- Fixes the type for the selectedUserId in the example.
- Fixes the link to creating an entity adapter.
> Minor fixes to entity/interfaces.md

- example-app/README.md
- example-app/app/core/components/nav-item.ts
- example-app/app/core/containers/app.ts
- package.json
- yarn.lock
> chore(Example): Add login info to example app. Fix sidenav issue with IE

- modules/effects/spec/effects_root_module.spec.ts
- modules/effects/src/effects_root_module.ts
- modules/effects/src/index.ts
> feat(Effects): Add root effects init action

- modules/store/spec/modules.spec.ts
- modules/store/src/state.ts
> fix(Store): Set initial value for state action pair to object

- modules/effects/src/effects_metadata.ts
This has a strange bug with closure compiler
> Remove Export Decorator

- README.md
Hi!
Small PR here to add the official channel on Medium for @ngrx. Though it was a good idea to add it there.
> docs(readme): Add official Medium editor link

- example-app/app/books/actions/book.ts
- example-app/app/books/components/book-search.ts
- example-app/app/books/containers/find-book-page.ts
- example-app/app/books/effects/book.spec.ts
- example-app/app/books/effects/book.ts
- example-app/app/books/reducers/index.ts
- example-app/app/books/reducers/search.ts
- modules/router-store/spec/integration.spec.ts
> feat(Example): improve handling of book search error

- modules/effects/package.json
- modules/entity/package.json
- modules/router-store/package.json
- modules/store-devtools/package.json
- modules/store/package.json
> feat(platform): add @angular@5.0.0-beta support

- modules/entity/src/models.ts
> fix(Entity): EntitySelectors selectIds typing error

- docs/store/selectors.md
> chore(Docs) Document `selector.release()` method

- modules/router-store/src/router_store_module.ts
> fix(RouterStore): support objects for options of StoreRouterConnectingModule

- example-app/app/books/reducers/books.ts
I found invalid comments and correct it.
> docs(Example): correct invalid comment format and indentation

- example-app/app/auth/containers/login-page.component.spec.ts
- example-app/app/books/components/book-detail.ts
- example-app/app/books/reducers/index.ts
Hi!
Found some typos in the example, made some corrections.
> doc(example): fix some typos

- example-app/app/auth/effects/auth.effects.spec.ts
Hi!
This PR adds some marble tests for _authEffects_ in the example application.
Feel free to ask any change, available to do so!
> chore(Example): Add auth effects marble tests

- modules/store/src/selector.ts
- modules/store/src/state.ts
* Simplify how `stateAndAction$` is subscribed to
* Refactor `createFeatureSelector` to take advantage of existing
`createSelector` functionality
> refactor(Store): Small Refactor

- example-app/README.md
- Adds the go to directory section in the script file
- Improves comments consistency just a little bit
> example-app: Small improvements on documentation

- example-app/app/books/containers/__snapshots__/collection-page.spec.ts.snap
- example-app/app/books/containers/__snapshots__/find-book-page.spec.ts.snap
- example-app/app/books/containers/__snapshots__/selected-book-page.spec.ts.snap
- example-app/app/books/containers/__snapshots__/view-book-page.spec.ts.snap
- example-app/app/books/containers/collection-page.spec.ts
- example-app/app/books/containers/find-book-page.spec.ts
- example-app/app/books/containers/selected-book-page.spec.ts
- example-app/app/books/containers/view-book-page.spec.ts
- example-app/app/books/containers/view-book-page.ts
Hi!
This adds some tests in `books/containers` in the example application.
Feel free to ask any change, available to do so!
> chore(Example): Add books containers test

- docs/router-store/README.md
- docs/router-store/api.md
- example-app/app/app.module.ts
- example-app/app/reducers/index.ts
- example-app/app/shared/utils.ts
> chore(docs): Document RouterStore forRoot method and configuration options

- modules/schematics/src/feature/index.ts
- modules/schematics/src/store/index.spec.ts
- modules/schematics/src/store/index.ts
> refactor(Schematics): Use wildcard for feature store imports

- docs/effects/README.md
- docs/entity/README.md
- docs/router-store/README.md
- docs/store-devtools/README.md
- docs/store/README.md
> Remove redundant links to 4.1.1 docs

- modules/effects/spec/actions.spec.ts
- modules/effects/src/actions.ts
> fix(Effects): Provide instance from Actions to ofType lettable operator

- README.md
- docs/schematics/README.md
- docs/schematics/action.md
- docs/schematics/container.md
- docs/schematics/effect.md
- docs/schematics/entity.md
- docs/schematics/feature.md
- docs/schematics/reducer.md
- docs/schematics/store.md
- modules/schematics/src/action/schema.json
- modules/schematics/src/effect/schema.json
- modules/schematics/src/feature/schema.json
- modules/schematics/src/reducer/schema.json
> chore(docs): Add documentation for @ngrx/schematics

- docs/schematics/README.md
Updated Inital -> Initial in two places.
> docs(Readme) Fixing spelling mistakes

- docs/schematics/README.md
- docs/schematics/store.md
> docs(Store) Fixing spelling mistake

- modules/effects/src/actions.ts
- modules/schematics/src/container/index.spec.ts
Closes: #753 
Based on [https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#build-your-own-operators-easily](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#build-your-own-operators-easily).
> fix(Effects): make ofType strict

- example-app/app/books/reducers/index.ts
> doc(example): Update books/reducers/index.ts

- docs/effects/README.md
- docs/effects/api.md
Hi!
This add some info on how to run some code when the effect is loaded, in the readme.
> doc(effects): add note on initializing effects

- docs/entity/adapter.md
- example-app/app/books/reducers/books.ts
- modules/schematics/src/entity/files/__path__/__name@dasherize@if-flat__/__name@dasherize@group-actions__.actions.ts
- modules/schematics/src/entity/files/__path__/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts
Also adds upsert methods to documentation
Closes #592
> feat(Schematics): Add upsert adapter methods to entity blueprint

- docs/schematics/entity.md
Small fix of schematics/entity document.
> doc(schematics): Fix option parameter type

- CHANGELOG.md
Linked changelogs for @ngrx/entity and @ngrx/schematic in main changelog
> Cover all packages in changelog

- docs/effects/README.md
Here should be a mistake in writing. It should be `EffectsModule` rather than `NgModule`.
> docs(effects): fix document issues

- modules/router-store/src/router_store_module.ts
> fix: type mismatch when upgrade to ts2.6

- docs/store/testing.md
> docs(store): document selector testing using .projector

- modules/store/spec/edge.spec.ts
- modules/store/src/store.ts
> Fix select overload type annotations

- tools/defaults.bzl
> fix: Declare global NgRx packages for UMD bundles

- README.md
- example-app/README.md
Removed the section, not to confuse the users. 
In some way it fixes #956
> Update Try it on StackBlitz section as URL is broken

- docs/entity/adapter.md
- docs/router-store/api.md
- docs/store/actions.md
- docs/store/testing.md
Make the docs and example consistent.
Related #867
> docs(Example): Make imports for actions consistent

- docs/schematics/README.md
Updated README for configuring Angular CLI with @ngrx/schematics. Fixes #1018
> fix(schematics) Angular CLI config

- docs/store/selectors.md
Ready for review.
Closes #1002
> docs: describe composition of selectors in pipeable operators

- docs/schematics/README.md
.angular-cli.json > angular.json for `@angular/cli@6.x`
> a small update of schematics docs

- docs/router-store/README.md
I was looking for a good description for `StoreRouterConnectingModule` and found in `https://github.com/vsavkin/router-store` a good short explanation.
> improve documentation

- docs/entity/adapter.md
Forgot to change the docs while doing #1042 yesterday.
Today with a fresh head, I've thought about it :sweat_smile:
> docs(Entity): update upsert code sample to match new signature

- modules/schematics/package.json
- modules/store/migrations/6_0_0/index.spec.ts
- modules/store/migrations/6_0_0/index.ts
- modules/store/migrations/migration.json
- modules/store/package.json
- tools/defaults.bzl
> feat(Store): add ng update

- modules/effects/schematics-core/utility/find-module.ts
- modules/entity/schematics-core/utility/find-module.ts
- modules/router-store/schematics-core/utility/find-module.ts
- modules/schematics-core/utility/find-module.ts
- modules/schematics/schematics-core/utility/find-module.ts
- modules/schematics/src/container/index.spec.ts
- modules/store-devtools/schematics-core/utility/find-module.ts
- modules/store/schematics-core/utility/find-module.ts
> fix(Schematics): remove ts extension when importing reducer in container

- modules/effects/schematics-core/utility/find-module.ts
- modules/entity/schematics-core/utility/find-module.ts
- modules/router-store/schematics-core/utility/find-module.ts
- modules/schematics-core/utility/find-module.ts
- modules/schematics/schematics-core/utility/find-module.ts
- modules/schematics/src/store/index.spec.ts
- modules/schematics/src/store/index.ts
- modules/store-devtools/schematics-core/utility/find-module.ts
- modules/store/schematics-core/utility/find-module.ts
> fix(Store): environment path when generating a new store

- modules/schematics/src/store/index.spec.ts
- modules/schematics/src/store/index.ts
Closes #1090.
I broke this in #1071, reverted back to the original code.
> fix(Schematics): environments path for module

- docs/store/api.md
At the first glance as a new user of ngrx it was difficult to understand whats a metaReducer is! After some researches i found in https://netbasal.com/implementing-a-meta-reducer-in-ngrx-store-4379d7e1020a that a metaReducer is something similar to middleware or rather it can achieve the same effects with metaReducers.
> improve documentation for metaReducers

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/support-request.md
Add some custom issue templates to help with filing issues and requests.
> docs: Add issue templates

- docs/store/README.md
- docs/store/downgrade.md
Hi!
This adds a small introduction on how to use a downgraded version of the Store service in an AngularJS application.
Have a nice day!
Ben
> docs(Store): add how to downgrade Store service

- docs/schematics/README.md
> docs(Schematics): edit the generate command to work with angular cli 6

- docs/store/README.md
Summary:
- Fix Markdown lint issues
- NPM no longer has `--save` option
- Minor edits
> Edit README (minor) and use Angular code style in examples

- example-app/app/books/components/book-detail.component.ts
- example-app/app/books/components/book-preview.component.ts
- modules/effects/schematics/ng-add/index.spec.ts
- modules/store-devtools/BUILD
- modules/store-devtools/package.json
- modules/store-devtools/schematics/BUILD
- modules/store-devtools/schematics/collection.json
- modules/store-devtools/schematics/ng-add/index.spec.ts
- modules/store-devtools/schematics/ng-add/index.ts
- modules/store-devtools/schematics/ng-add/schema.json
- modules/store-devtools/schematics/ng-add/schema.ts
Adds ng add for store-devtools and a maxAge option (defaults max age to 25 based on docs and comment https://github.com/ngrx/platform/issues/920#issuecomment-392279675
There were also 2 files that got changed via prettier
Related to #920
> add ng-add to store-devtools re #920

- modules/effects/schematics/ng-add/index.ts
- modules/schematics/src/effect/index.ts
- modules/schematics/src/reducer/index.ts
- modules/schematics/src/store/index.ts
- modules/store-devtools/schematics/ng-add/index.ts
- modules/store/schematics/ng-add/index.ts
Closes #1102
Some stats on an empty project:
Effects: before 8s, with these changes 2s
Store: before 6s, with these changes 1s
Reducer: before 9s, with these changes 1s
Feature: before 15s, with these changes 3s
> Schematics performance

- example-app/app/auth/effects/auth.effects.spec.ts
- example-app/app/books/effects/book.effects.spec.ts
- example-app/app/books/effects/collection.effects.spec.ts
- tsconfig.json
> refactor(ExampleApp): use provide mock actions

- modules/effects/src/effects_metadata.ts
- modules/store-devtools/src/reducer.ts
- prettier.config.js
setting to none was an overkill, let's deal with them on case-by-case basic. Don't forget to install the latest TS for development and analyze if it complains about anything :)
> Turn prettier back on and just use the comment to ignore places that TS2.9 doesn't like

- modules/effects/schematics-core/utility/find-module.ts
- modules/effects/schematics-core/utility/ngrx-utils.ts
- modules/entity/schematics-core/utility/find-module.ts
- modules/entity/schematics-core/utility/ngrx-utils.ts
- modules/router-store/schematics-core/utility/find-module.ts
- modules/router-store/schematics-core/utility/ngrx-utils.ts
- modules/schematics-core/utility/find-module.ts
- modules/schematics-core/utility/ngrx-utils.ts
- modules/schematics/schematics-core/utility/find-module.ts
- modules/schematics/schematics-core/utility/ngrx-utils.ts
- modules/schematics/src/effect/index.ts
- modules/schematics/src/store/index.ts
- modules/store-devtools/schematics-core/utility/find-module.ts
- modules/store-devtools/schematics-core/utility/ngrx-utils.ts
- modules/store/schematics-core/utility/find-module.ts
- modules/store/schematics-core/utility/ngrx-utils.ts
Update error messages in schematics and schematics-core modules.
Please see the relavant issue.
Closes https://github.com/ngrx/platform/issues/1200
> feat(schematics): display provided path when displaying an error

- example-app/app/books/components/book-search.component.ts
You can see the behavior in the official [stackblitz](https://stackblitz.com/github/ngrx/platform/tree/61cbfe537f9df8cef3dd4a6ee0b8f483e49653f4).
> fix(example): spinner not working as expected

- docs/effects/testing.md
- example-app/app/books/effects/book.effects.spec.ts
- example-app/app/books/effects/book.effects.ts
> docs(Effects): document defining effects as function

- example-app/app/core/components/sidenav.component.ts
- example-app/app/core/containers/app.component.ts
> fix(example-app): Sidenav closes with Esc

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[ ] angular.io application / infrastructure changes
```
Issue Number: #1166
Document created.
```
[ ] Yes
[x] No
```
I submit a draft proposal of pull request template for this project. This is copied from Angular. (https://raw.githubusercontent.com/angular/angular/master/.github/PULL_REQUEST_TEMPLATE.md)
Please use this and additionally revise, thank you.
Closes #1166
> docs: add pull-request-template and update contributing with commit message guidelines

- modules/schematics/src/reducer/files/__name@dasherize@if-flat__/__name@dasherize__.reducer__dot__spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1265
Correct description in template according to the proposal.
```
[ ] Yes
[x] No
```
Closes #1265
> fix(schematics): correct spec description in reducer template

- example-app/app/books/reducers/books.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 1264
```
[ ] Yes
[x] No
```
> Remove unnecessary code from books reducer

- example-app/app/app.module.ts
- example-app/app/auth/auth.module.ts
- example-app/app/auth/services/auth-guard.service.spec.ts
- example-app/app/auth/services/auth-guard.service.ts
- example-app/app/auth/services/auth.service.ts
- example-app/app/books/books.module.ts
- example-app/app/books/guards/book-exists.guard.ts
- example-app/app/core/core.module.ts
- example-app/app/core/services/google-books.service.spec.ts
- example-app/app/core/services/google-books.service.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1126
- Refactor all services and guards with treeshakable providers.
- Remove unnecessary `forRoot` methods from CoreModule and AuthModule.
This change affects only to example-app.
```
[ ] Yes
[x] No
```
Closes #1126
> refactor(example): enable treeshakable providers

- projects/example-app/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1270
The application name for devtools is renamed with more suitable one.
```
[ ] Yes
[x] No
```
Closes #1270
> refactor(example): rename app name for devtools

- projects/example-app/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I was so eager to check out the working stackblitz link in #1274 and bumped into some old links.
> docs(example): update stackblitz link

- package.json
- yarn.lock
lint staged was processing all files with the update it only processes the modified files
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
lint staged was processing all files, with the update it only processes the modified files
> chore: update lint-staged

- modules/store-devtools/spec/store.spec.ts
- modules/store-devtools/src/reducer.ts
- use prettier@1.13.7
```
[ ] Bugfix
[ ] Feature
```
Code is not formatted with latest prettier.
Reformat code with prettier@1.13.7
```
[ ] Yes
[x] No
```
We should check whether code is formatted with latest prettier in CI.
> style(store-devtools): reformat code by using latest prettier

- .circleci/bazel.rc
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: further constrain Bazel resource usage in CI

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: persist build across jobs for deployment

- .circleci/config.yml
- build/tasks.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: fix persistance of build artifacts for deployment

- projects/example-app/src/app/reducers/index.ts
* Use collapsed console group in logger metareducer
```
[ ] Bugfix
[ ] Feature
Example app refactoring
```
Shows dispatched action and state in a collapsed `console.group`
```
[ ] Yes
[x] No
```
> refactor(example-app): Update logger metareducer

- docs/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
> Provide next (interface) method

- projects/ngrx.io/content/marketing/index.html
- projects/ngrx.io/src/404-body.html
- projects/ngrx.io/src/app/app.component.html
- projects/ngrx.io/src/index.html
- projects/ngrx.io/src/styles/2-modules/_code.scss
- projects/ngrx.io/src/styles/2-modules/_notification.scss
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: accessibility 
```
The ngrx.io project has some minor accessibility flaws, tested with aXe and pa11y.
Most of the flaws are fixed with this PR.
```
[ ] Yes
[x] No
```
The notification bar had an Angular look, I used the branding colors of NgRx to style this notification.
There is still one flaw we have on our accent buttons (eg the get started button on the landing page) and code snippets (the orange color), "Elements must …
> Ngrx.io accessibility

- modules/router-store/src/actions.ts
```
[ ] Bugfix
[ ] Feature
```
n/a
```
[ ] Yes
[x] No
```
> docs(router-store): fix typos

- modules/effects/src/effects_metadata.ts
- modules/store/src/store.ts
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
Bringing the types up to date. Remove casting "as string".
same
```
[ ] Yes
[ x] No
```
> refactor(effects,store) update typings since ngrx is at TS 2.8 already

- docs/schematics/README.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1365
```
[ ] Yes
[x] No
```
> docs(schematics): Fix wrong optional collection

- modules/router-store/src/router_store_module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1373
```
[ ] Yes
[x] No
```
Closes #1373
> fix(RouterStore): don't navigate on NavigationStart router event

- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/styles/2-modules/_deploy-theme.scss
Remove style guide from nav for now
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add nav links to previous versions, clean up theme for next

- projects/ngrx.io/content/guide/migration/v7.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1230 
```
[ ] Yes
[x] No
```
Closes #1230
> docs: add migration guide for v7

- modules/store/src/store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
See discussion at https://github.com/ngrx/platform/pull/1361
> feat(Store): un-deprecate select

- modules/router-store/src/reducer.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1344
Move action type cast to inside the reducer
```
[ ] Yes
[ ] No
```
Closes #1344
cc: @rkirov
> fix(RouterStore): allow compilation with strictFunctionTypes

- modules/store/spec/integration.spec.ts
- modules/store/src/store.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1386
An extra typing is added to allow `store.select(selector, props)`
```
[ ] Yes
[x] No
```
Closes #1386
> fix(Store): add typing to allow props with store.select

- modules/router-store/src/router_store_module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1373 
```
[ ] Yes
[ ] No
```
Closes  #1373
> fix(RouterStore): don't navigate on NagivationStart

- projects/ngrx.io/content/guide/store/actions.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: rewrite Actions guide

- projects/ngrx.io/content/guide/store/index.md
- projects/ngrx.io/content/guide/store/reducers.md
- projects/ngrx.io/content/marketing/docs.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: rewrite reducers guide

- projects/ngrx.io/package.json
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[v] Documentation content changes
```
https://github.com/ngrx/platform/blob/ccc99e9f7818ff10829876224af38e9ee5874270/projects/ngrx.io/package.json#L2
Issue Number: #1408 
`"name": "ngrx.io"`
```
[ ] Yes
[x] No
```
> docs: update docs app name in package.json

- projects/ngrx.io/content/marketing/resources.html
- projects/ngrx.io/content/marketing/resources.json
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1411 
```
[ ] Yes
[x] No
```
> docs: add NgRx resources page

- README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: fix links to website in readme

- projects/ngrx.io/src/index.html
- projects/ngrx.io/src/pwa-manifest.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1410
```
[ ] Yes
[x] No
```
> docs: PWA in style of NgRx

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
n/a
Added link to new medium article that I wrote under the community resources section. Link here: https://itnext.io/ngrx-best-practices-for-enterprise-angular-applications-6f00bcdf36d7
```
[ ] Yes
[x] No
```
n/a
> docs(resources): add link to article detailing pattern for organizing store

- .circleci/config.yml
- build/deploy-preview.ts
- build/tasks.ts
- build/util.ts
- package.json
- projects/ngrx.io/scripts/build-404-page.js
- projects/ngrx.io/src/app/documents/document.service.ts
- projects/ngrx.io/src/app/shared/location.service.ts
- yarn.lock
Closes #1423
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: add support for docs preview builds

- docs/store/selectors.md
- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
No space between " `createFeatureSelector`functions".
Added space (ie. " `createFeatureSelector` functions").
```
[ ] Yes
[x] No
```
> docs: add missing space

- projects/ngrx.io/content/marketing/resources.json
> docs: add Pizza Sync to example resources

- .circleci/config.yml
- package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Removes dependency on separate Bazel installation
> build: use Bazel installed from npm

- package.json
- [ -] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ -] Tests for the changes have been added (for bug fixes / features)
> I am sorry, how to update documentation I do not know, I did run `npm run changelog` however it did not update automatically changelog.md. Am I suppose to update `changelog.md` by myself  if yes then can someone explain how ? 
Added new Script in package.json file.
```
[ -] Bugfix
[ ] Feature
[ ] Other... …
```
> #1434 created new script example:build so it can work with http-server

- projects/ngrx.io/package.json
- projects/ngrx.io/yarn.lock
Fixes a security hole, ref https://github.com/dominictarr/event-stream/issues/116
```
[ ] Bugfix
[ ] Feature
```
Closes #N/A
```
[ ] Yes
[x] No
```
> docs: update npm-run-all dependency

- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
> docs: fixed usage of selector with .select()

- projects/example-app/src/app/auth/effects/auth.effects.ts
- projects/example-app/src/app/books/effects/book.effects.ts
- projects/example-app/src/app/books/effects/collection.effects.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
#1461 
```
[ ] Yes
[x] No
```
> refactor(example): refactor effects ofType

- projects/ngrx.io/content/marketing/index.html
```
[ ] Bugfix
[ ] Feature
```
This remove the unnecessary closing tag `</ngrx-code-block>` on the marketing page for the ngrx.io website.
Closes #
Same behaviour.
```
[ ] Yes
[x] No
```
> fix(ngrxio): unnecessary closing tag

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/lifecycle.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1456
```
[ ] Yes
[x] No
```
> docs(effects): add the effects lifecycle page

- projects/ngrx.io/content/marketing/events.html
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1463 
Events was moved into the top bar navigation. Events page was updated with upcoming events.
Let me know if there are any other events that I should add or remove any from those that I've added.
```
[ ] Yes
[x] No
```
> docs: add events to top bar navigation

- projects/ngrx.io/content/guide/entity/adapter.md
This PR adds documentation for the enhancements made in https://github.com/ngrx/platform/commit/d7daa2f and https://github.com/ngrx/platform/commit/4e4c50f.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: add new entity features

- package.json
Will re-enable once yarn is updated in the docker images
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: temporarily disable code coverage

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/testing.md
- projects/ngrx.io/content/guide/entity/adapter.md
- projects/ngrx.io/content/guide/entity/interfaces.md
- projects/ngrx.io/content/guide/router-store/configuration.md
- projects/ngrx.io/content/guide/router-store/index.md
- projects/ngrx.io/content/guide/store-devtools/index.md
- projects/ngrx.io/content/guide/store/actions.md
- projects/ngrx.io/content/guide/store/metareducers.md
- projects/ngrx.io/content/guide/store/recipes/downgrade.md
- projects/ngrx.io/content/guide/store/recipes/injecting.md
- projects/ngrx.io/content/guide/store/reducers.md
- projects/ngrx.io/content/guide/store/selectors.md
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Part of #1454 
Show code snippets in the same style everywhere.
```
[ ] Yes
[ ] No
```
I also noticed that the opening and closing arrows aren't show at some pages, e.g. https://ngrx.io/guide/entity/adapter - therefore I've also used `&lt;` and `&gt;`. I also had to do this in the code snippets, because they're parsed as html.
> docs: use code-example for snippets

- modules/effects/src/lifecycle_hooks.ts
- projects/ngrx.io/content/guide/effects/lifecycle.md
- removes `UPDATE_EFFECTS` from the docs
- removes `Initializing effect (via defer)` from the docs
- wraps snippets with `code-example`
- adds `OnInitEffects` and `EffectWithIdentifier` to the docs
- formats the snippets inside `modules/effects/src/lifecycle_hooks.ts` to stay consistent
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add new lifecycles

- projects/ngrx.io/content/guide/store/actions.md
```
[ ] Bugfix
[ ] Feature
```
"The `Login` text after the category is a description about what event occurred from this actions."
"Actions only responsibility are to express unique events and intents. Learn how they are handled in the guides below."
"The `Login` text after the category is a description about what event occurred from this action."
"Action's only responsibilities are to express unique events and intents. Learn how they are handled in the guides below." …
> docs: Improvements to Actions documentation

- modules/entity/package.json
- modules/entity/schematics/BUILD
- modules/entity/schematics/collection.json
- modules/entity/schematics/ng-add/index.spec.ts
- modules/entity/schematics/ng-add/index.ts
- modules/entity/schematics/ng-add/schema.json
- modules/entity/schematics/ng-add/schema.ts
Adds the `ng add` schematic to @ngrx/entity.
It will only install the entity package and add it to the `package.json`.
```
[ ] Bugfix
[x] Feature
```
Closes #920 
```
[ ] Yes
[x] No
```
With this, we've covered all of the modules to have a `ng add` command.
> feat(Schematics): add ng add for @ngrx/entity

- modules/effects/schematics/ng-add/schema.json
- modules/router-store/schematics/ng-add/schema.json
- modules/schematics/src/action/schema.json
- modules/schematics/src/container/schema.json
- modules/schematics/src/effect/schema.json
- modules/schematics/src/entity/schema.json
- modules/schematics/src/feature/schema.json
- modules/schematics/src/reducer/schema.json
- modules/schematics/src/store/schema.json
- modules/store-devtools/schematics/ng-add/schema.json
- modules/store/schematics/ng-add/schema.json
```
[ ] Bugfix
[ ] Feature
```
Schematics project flag not visible.
Closes #1512
Schematics project flag is now visible.
```
[ ] Yes
[X] No
```
> refactor(schematics): make project option visible

- projects/ngrx.io/content/guide/store/recipes/injecting.md
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x ] No
```
> docs: add feature config injection token

- .circleci/config.yml
- WORKSPACE
- package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: re-enable code coverage

- modules/entity/BUILD
- modules/router-store/BUILD
```
[x] Bugfix
[ ] Feature
```
Ref #1523 
```
[ ] Yes
[x] No
```
> fix: build missing schematics

- modules/effects/schematics-core/utility/libs-version.ts
- modules/entity/schematics-core/utility/libs-version.ts
- modules/router-store/schematics-core/utility/libs-version.ts
- modules/schematics-core/utility/libs-version.ts
- modules/schematics/schematics-core/utility/libs-version.ts
- modules/store-devtools/schematics-core/utility/libs-version.ts
- modules/store/schematics-core/utility/libs-version.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1489 
```
[ ] Yes
[x] No
```
> feat(schematics): bump platformVersion to ^7.0.0 per issue #1489

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(effects): typo

- projects/ngrx.io/content/guide/store-devtools/config.md
Updated documentation on Store Devtools Config page as per #1519 
```
[ ] Bugfix
[ ] Feature
```
Closes #1519 
```
[ ] Yes
[x] No
```
> docs(store-devtools): Added documentation for new extension options for Store Devtools

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
n/a
Updated link to the ngrx best practices community resource to new URL [https://wesleygrimes.com/angular/2018/05/30/ngrx-best-practices-for-enterprise-angular-applications](https://wesleygrimes.com/angular/2018/05/30/ngrx-best-practices-for-enterprise-angular-applications)
```
[ ] Yes
[x] No
```
n/a
> docs(resources): update community ngrx best practices article href

- projects/ngrx.io/content/guide/schematics/action.md
- projects/ngrx.io/content/guide/schematics/effect.md
- projects/ngrx.io/content/guide/schematics/feature.md
- projects/ngrx.io/content/guide/schematics/reducer.md
```
[ ] Bugfix
[ ] Feature
```
Documentation is missing for API flag.
Closes #1574 
Added documentation for `api` flag introduced in #1530. 
```
[ ] Yes
[x] No
```
> docs(Schematics): adding docs for api flag (ngrx/platform#1574)

- modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Deprecates the overload that will be removed in #1579
> fix(Store): deprecate projector selector

- projects/ngrx.io/src/styles/_constants.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #1588
```
[ ] Yes
[x] No
```
> docs: add missing icon for NgModules

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1602
```
[ ] Yes
[x] No
```
> docs: add Angular Checklist link to Resources page

- docs/effects/testing.md
- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1581 #1571
```
[ ] Yes
[x] No
```
> docs: split effects testing examples

- projects/ngrx.io/src/app/layout/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> Update year to 2019

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add Goose Weather to example resources

- projects/example-app/src/app/auth/services/auth-guard.service.spec.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Auth Guard test uses StoreModule
Provide a working code sample using MockStore and provideMockStore
```
[ ] Yes
[x] No
```
I can add this complete example to the existing MockStore docs when this is approved.
> refactor(example): use MockStore in Auth Guard test

- package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> chore: update lodash dependency for security alert

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1618
```
[ ] Yes
[x] No
```
> docs: add MDB Angular Boilerplate to example resources

- projects/ngrx.io/content/guide/entity/interfaces.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ x] Yes
[ ] No
```
> docs: typo fix

- projects/ngrx.io/README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: add note for Windows developers

- projects/example-app/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1645 
```
[ ] Yes
[x] No
```
> docs: point documentation references to ngrx.io

- .circleci/config.yml
- build/cleanup-previews.ts
- build/tasks.ts
- package.json
Closes #1620
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> ci: add task to cleanup docs previews on merge commits

- projects/ngrx.io/content/guide/schematics/container.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1650 
```
[ ] Yes
[x] No
```
> docs: add guide to generate a container with scss

- .circleci/config.yml
- BUILD.bazel
- WORKSPACE
- angular-metadata.tsconfig.json
- modules/effects/BUILD
- modules/effects/spec/BUILD
- modules/effects/testing/BUILD
- modules/entity/BUILD
- modules/entity/spec/BUILD
- modules/router-store/BUILD
- modules/router-store/spec/BUILD
- modules/store-devtools/BUILD
- modules/store-devtools/spec/BUILD
- modules/store/BUILD
- modules/store/spec/BUILD
- modules/store/testing/BUILD
- package.json
- tools/defaults.bzl
- tools/testing/bootstrap_node_tests.ts
- yarn.lock
This means we only depend on npm packages, rather than fetching angular and rxjs repositories
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> build: update to latest bazel rules

- projects/example-app-cypress/cypress.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore: update timeout for Applitools eyes

- modules/effects/spec/actions.spec.ts
- modules/store/spec/store.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1658
```
[ ] Yes
[x] No
```
> test: using Injector instead of ReflectiveInjector (#1658)

- package.json
- projects/example-app-cypress/integration/round-trip.spec.ts
- projects/example-app/src/app/core/services/google-books.service.spec.ts
- projects/example-app/src/app/core/services/google-books.service.ts
Closes #1636
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> refactor(example): update search query for book search

- modules/router-store/src/router_store_module.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1662
```
[x] Yes
[ ] No
```
> feat(router-store): Make usage of forRoot required (#1662)

- modules/store/src/index.ts
- modules/store/src/tokens.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1657 
```
[x] Yes
[ ] No
```
Internal functions and tokens are removed from the public API
> refactor(Store): don't export internal functions and tokens

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1661 
```
[ ] Yes
[x] No
```
> docs: add Spartacus to resources page

- projects/ngrx.io/content/examples/store/src/app/counter.actions.ts
- projects/ngrx.io/content/examples/store/src/app/counter.reducer.ts
- projects/ngrx.io/content/examples/store/src/app/my-counter/my-counter.component.ts
- projects/ngrx.io/content/guide/effects/testing.md
- projects/ngrx.io/content/guide/entity/adapter.md
- projects/ngrx.io/content/guide/store/actions.md
- projects/ngrx.io/content/guide/store/metareducers.md
- projects/ngrx.io/content/guide/store/reducers.md
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1671 
```
[ ] Yes
[x] No
```
> docs: update usage of actions to use action creators

- projects/ngrx.io/content/guide/effects/testing.md
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1694 which follows up #414 
- Adds example snippet of testing an effect that injects Store and uses `withLatestFrom`
- Example uses the `MockStore` to set the state for the test
```
[ ] Yes
[x] No
```
> docs: add section to testing guide for Effects that inject state

- projects/example-app/README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1712 
```
[ ] Yes
[x] No
```
> docs(example): update all package links to ngrx.io

- projects/ngrx.io/content/examples/ngrx-start/src/app/app.component.css
- projects/ngrx.io/content/examples/ngrx-start/src/app/app.component.html
- projects/ngrx.io/content/examples/ngrx-start/src/app/app.component.ts
- projects/ngrx.io/content/examples/ngrx-start/src/app/app.module.ts
- projects/ngrx.io/content/examples/ngrx-start/src/index.html
- projects/ngrx.io/content/examples/ngrx-start/src/main.ts
- projects/ngrx.io/content/examples/ngrx-start/stackblitz.json
- projects/ngrx.io/content/guide/store/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1702
```
[ ] Yes
[x] No
```
> Docs  create example from stackblitz fork in tutorial

- modules/effects/src/index.ts
Adding the `EffectMetadata` back to exports (left out during the refactoring)
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> fix(effects): add the export of EffectMetadata

- projects/ngrx.io/content/guide/migration/v7.md
Closes #1705
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
Closes #1705
```
[ ] Yes
[X] No
```
> docs: v7 update guide mention minimum dependencies

- modules/store/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
See https://github.com/angular/angular/pull/29735
> feat(Store): run migration schema for v8 beta

- modules/effects/spec/BUILD
- modules/effects/spec/effect_creator.spec.ts
- modules/effects/src/effect_creator.ts
- projects/example-app/src/app/books/effects/collection.effects.ts
```
[ ] Bugfix
[x] Feature
```
Follow up to #1667
```
[ ] Yes
[x] No
```
> feat(effects): allow non-dispatching effects to not return an action

- modules/store/spec/meta-reducers/immutability_reducer.spec.ts
- modules/store/src/meta-reducers/immutability_reducer.ts
~Remove `true && ` which is always `true`.~
add the bracket 
```
[x] Bugfix
[ ] Feature
[] Refactoring (no functional changes, no api changes)
```
Closes #
```
[ ] Yes
[x] No
```
> fix(store): add the missing bracket

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1714 
Adds a section on using state with effects.
Includes:
- Explanation that effects should rely on actions + metadata for handling an effect.
- Example of incorporating state in an effect.
- Left note on using flattening operator so that the selector isn't fired (discussed in #1713)
- Included examples
```
[ ] Yes
[x] No
```
> docs: add section to Effects overview about using state with effects

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Minor syntax error in documentation.
Syntax fixed in documentation.
```
[ ] Yes
[X] No
```
> docs(effects): fix minor syntax typo

- projects/ngrx.io/.firebaserc
- projects/ngrx.io/firebase.json
- projects/ngrx.io/src/app/layout/mode-banner/mode-banner.component.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> build: add archive target for docs deployment

- modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/effect/index.ts
- modules/schematics/src/effect/schema.json
- modules/schematics/src/effect/schema.ts
- modules/schematics/src/feature/schema.json
- modules/schematics/src/feature/schema.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1682 
add support for `createEffect` function in effect schematics
```
[ ] Yes
[ ] No
```
> feat(schematics): add support for create effect to schematics

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/lifecycle.md
- projects/ngrx.io/content/guide/effects/testing.md
- projects/ngrx.io/content/guide/schematics/effect.md
- projects/ngrx.io/content/guide/schematics/feature.md
- projects/ngrx.io/src/app/custom-elements/ngrx/code-block.component.ts
Closes #1681
```
[ ] Bugfix
[ ] Feature
```
Closes #1681 
```
[ ] Yes
[x] No
```
> docs: update usage of effects to use effect creators

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Follow up to #1745
> ci: re-enable building of example app during testing

- projects/ngrx.io/src/styles/0-base/_typography.scss
- projects/ngrx.io/src/styles/2-modules/_deploy-theme.scss
- projects/ngrx.io/src/styles/_constants.scss
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation styling
```
Closes #1732
Content links now have more contrast, using #84438a.
```
[ ] Yes
[x] No
```
> docs: update anchor color to have more contrast

- projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
- projects/ngrx.io/content/guide/store/runtime-checks.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1726
```
[ ] Yes
[ ] No
```
> docs: add runtime checks page

- modules/data/src/dispatchers/entity-dispatcher-base.ts
- modules/data/src/reducers/entity-change-tracker-base.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> fix(data): handle the undefined in Dictionary

- tsconfig.json
remove the duplicate (this entry is already there at line 25)
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> fix(all): remove duplicate entry from tsconfig

- projects/ngrx.io/tools/transforms/angular-api-package/index.js
- projects/ngrx.io/tools/transforms/authors-package/api-package.js
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add @ngrx/data to public api pages

- projects/ngrx.io/content/guide/migration/v8.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1701
```
[ ] Yes
[x] No
```
> docs: add v8 migration guide

- projects/ngrx.io/content/marketing/resources.json
```
[x] Bugfix
[ ] Feature
```
Closes #1768
```
[ ] Yes
[x] No
```
> docs: remove ngrx-data and ngrx-store-freeze from resources

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ci: clean Bazel workspace before tests

- projects/ngrx.io/content/guide/store/recipes/injecting.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1753 
simplify `REDUCER_TOKEN` injection in documentation example.
> docs(reducer): simplify reducer injection setup in doc (#1753)

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Adds the newly introduced data module to the list of supported scopes.
```
[ ] Yes
[x] No
```
> docs: add 'data' contribution scope to CONTRIBUTING

- projects/ngrx.io/content/guide/data/install.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1750
Adds an installation page for the NgRx Data module.
```
[ ] Yes
[x] No
```
> docs: add data installation page

- modules/data/BUILD
- modules/data/migrations/BUILD
- modules/data/migrations/migration.json
- modules/data/package.json
- modules/data/schematics-core/BUILD
- modules/data/schematics-core/index.ts
- modules/data/schematics-core/utility/ast-utils.ts
- modules/data/schematics-core/utility/change.ts
- modules/data/schematics-core/utility/config.ts
- modules/data/schematics-core/utility/find-module.ts
- modules/data/schematics-core/utility/libs-version.ts
- modules/data/schematics-core/utility/ngrx-utils.ts
- modules/data/schematics-core/utility/package.ts
- modules/data/schematics-core/utility/parse-name.ts
- modules/data/schematics-core/utility/project.ts
- modules/data/schematics-core/utility/strings.ts
- modules/data/schematics-core/utility/update.ts
- modules/data/schematics/BUILD
- modules/data/schematics/collection.json
- modules/data/schematics/ng-add/index.spec.ts
- modules/data/schematics/ng-add/index.ts
- modules/data/schematics/ng-add/schema.json
- modules/data/schematics/ng-add/schema.ts
- projects/ngrx.io/content/guide/migration/v8.md
- tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Related to #1554
```
[ ] Yes
[x] No
```
The flag `migrate` is to rename keywords as in #1780, it will also uninstall `ngrx-data`.
> feat(data): add schematics and migrations

- modules/schematics/src/action/creator-files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts.template
- modules/schematics/src/action/index.spec.ts
- modules/schematics/src/action/index.ts
- modules/schematics/src/action/schema.json
- modules/schematics/src/action/schema.ts
- modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/effect/index.ts
- modules/schematics/src/effect/schema.json
- modules/schematics/src/effect/schema.ts
- modules/schematics/src/entity/creator-files/__name@dasherize@if-flat__/__name@dasherize@group-actions__.actions.ts.template
- modules/schematics/src/entity/creator-files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template
- modules/schematics/src/entity/index.spec.ts
- modules/schematics/src/entity/index.ts
- modules/schematics/src/entity/schema.json
- modules/schematics/src/entity/schema.ts
- modules/schematics/src/feature/index.ts
- modules/schematics/src/feature/schema.json
- modules/schematics/src/feature/schema.ts
- modules/schematics/src/reducer/creator-files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template
- modules/schematics/src/reducer/index.spec.ts
- modules/schematics/src/reducer/index.ts
- modules/schematics/src/reducer/schema.json
- modules/schematics/src/reducer/schema.ts
- projects/ngrx.io/content/guide/schematics/action.md
- projects/ngrx.io/content/guide/schematics/effect.md
- projects/ngrx.io/content/guide/schematics/entity.md
- projects/ngrx.io/content/guide/schematics/feature.md
- projects/ngrx.io/content/guide/schematics/reducer.md
Closes #1764, 1766
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[x] Yes
[x] No
```
Adds support for generating reducers using `createReducer`. Also consolidates using creator functions for actions, reducers, and effects into one flag, `creators`.
> feat(schematics): add support for reducer creators

- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1790
Add blog links
```
[ ] Yes
[x] No
```
> docs: add blog link (#1790)

- projects/ngrx.io/content/marketing/docs.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1789 
Adds an entry for NgRx Data on the docs page under Entity
```
[ ] Yes
[x] No
```
> docs: add @ngrx/data to packages on docs page

- projects/ngrx.io/content/marketing/resources.json
Please check if your PR fulfils the following requirements:
```
[ ] Bugfix
[ ] Feature
```
The link for [ngrx-ducks](https://github.com/co-IT/ngrx-ducks) points to an outdated repository.
I just added the link to the new repository.
```
[ ] Yes
[x] No
```
> docs(resources): update repository url of ngrx-ducks

- modules/data/src/dispatchers/entity-commands.ts
- modules/data/src/dispatchers/entity-dispatcher-base.ts
- modules/data/src/entity-services/entity-collection-service-base.ts
Fixes #1812
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(data): rename @params to @param

- projects/ngrx.io/src/styles/2-modules/_table.scss
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: fix table styles bug uncovered with latest CLI update

- projects/example-app/src/app/auth/auth.module.ts
- projects/example-app/src/app/auth/index.ts
```
[x] Bugfix
[ ] Feature
```
The #1808 PR introduced a circular dep, and the example-app couldn't be served locally.
Related to #1684 
```
[ ] Yes
[x] No
```
> fix(example): circular dep

- modules/store/spec/reducer_creator.spec.ts
- modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1837
```
[ ] Yes
[ ] No
```
This reverts commit ecda5f71faafb00477182d7468e359db81120ff2
> revert: warn when same action is registered (#1801)

- projects/ngrx.io/content/guide/data/index.md
- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/entity/index.md
- projects/ngrx.io/content/guide/router-store/index.md
- projects/ngrx.io/content/guide/schematics/index.md
- projects/ngrx.io/content/guide/store-devtools/index.md
- projects/ngrx.io/content/guide/store/index.md
- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/styles/1-layouts/_sidenav.scss
Updating main store side nav links to use package names. Also updated page titles to match sidenav links.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: update section titles to use package names

- projects/ngrx.io/content/marketing/resources.json
Adds library ngrx-wieder for undo-redo to resources page
```
[ ] Bugfix
[ ] Feature
```
Library is not referenced on resource page
Library is referenced on resource page
```
[ ] Yes
[x] No
```
> docs(resources): add ngrx-wieder to resources

- projects/ngrx.io/tools/stackblitz-builder/builder.js
Fixes #1857
```
[ ] Bugfix
[ ] Feature
```
Closes #1857
```
[ ] Yes
[x] No
```
> docs: remove deprecated Buffer function

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Resources page does not show the talk I added with this PR.
Resources page does show the talk I gave at iJS London.
```
[ ] Yes
[x] No
```
> docs(resources): add iJS London talk and slide link

- modules/store/src/runtime_checks.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> style(Store): make it clear that it's possible to opt-out of runtime checks

- projects/ngrx.io/content/examples/store/src/app/counter.reducer.ts
- projects/ngrx.io/content/guide/entity/adapter.md
- projects/ngrx.io/content/guide/store/actions.md
- projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
- projects/ngrx.io/content/guide/store/reducers.md
Fixes #1853
```
[ ] Bugfix
[ ] Feature
```
Closes #1853
```
[ ] Yes
[x] No
```
> docs: update docs to use createReducer() function

- projects/ngrx.io/src/app/custom-elements/ngrx/code-block.component.ts
- projects/ngrx.io/src/styles/1-layouts/_homepage.scss
- projects/ngrx.io/src/styles/2-modules/_heading-anchors.scss
- projects/ngrx.io/src/styles/_ngrx.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #1866
```
[ ] Yes
[x] No
```
* Screenshots before and after the changes were created.
> docs(home): improve responsiveness on the home page for small screens

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/operators.md
```
[ ] Bugfix
[ ] Feature
```
typo 
Closes #
correct usage of `.pipe`
```
[ ] Yes
[x] No
```
> docs(effects): typo correction and formatting

- .circleci/config.yml
- projects/example-app-cypress/integration/round-trip.spec.ts
- projects/example-app-cypress/plugins/index.js
- projects/example-app-cypress/support/index.js
```
[ ] Bugfix
[ ] Feature
```
Due to some flakiness in Applitools, E2E tests were disabled.
Closes #1879
The Applitools eyes have been disabled by commenting
the relevant code out.
```
[ ] Yes
[x] No
```
> ci(example): re-enable E2E tests in CI

- projects/ngrx.io/content/guide/entity/adapter.md
import missing dependencies for createReducer and on
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: import missing dependencies

- projects/ngrx.io/content/guide/migration/v8.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add return type changes + example of resubscribe on errors

- projects/ngrx.io/content/guide/entity/adapter.md
- projects/ngrx.io/content/guide/store/actions.md
- projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
Fixes #1884
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: Pending review comments from createReducer()

- .circleci/config.yml
- build/publish-latest.ts
- build/publish-next.ts
- package.json
- projects/ngrx.io/src/extra-files/stable/robots.txt
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #1555 
```
[ ] Yes
[x] No
```
This will allow us to automate publishing of releases to NPM and deployment of docs to Firebase.
- When a new beta/rc tag is pushed up, such as `8.0.0-rc.1` the packages are published on `next`.
- When a new release tag is pushed up, such as `8.0.0` the packages are published on `latest`.
- The release job is disabled for now, so we can verify the beta/rc job works first.
For reference: …
> ci: add scripts to automate publishing of releases

- projects/ngrx.io/content/marketing/contributing.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1583 
Adds new Contributing page to the NgRx.io website.
```
[ ] Yes
[x] No
```
> docs: add contributing page

- .github/FUNDING.yml
GitHub allows you to define Funding buttons.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> chore: add sponsorship button to OpenCollective

- projects/ngrx.io/content/guide/entity/recipes/additional-state-properties.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
For a beginner, it is not clear, how to update the additional entities state properties in adapter state.
This PR adds an action to update the additional state properties (selectedUserId) and adds a case statement in the reducer to handle the update.
```
[ ] Yes
[x ] No
```
> docs: additional entities state properties update

- README.md
Closes #1909
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> Docs: Add status badges for CircleCI and NPM to README

- projects/ngrx.io/src/app/app.component.spec.ts
- projects/ngrx.io/src/app/app.component.ts
Closes #1926
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(data): fix versions link in the versions menu dropdown

- modules/effects/src/act.ts
- package.json
- projects/ngrx.io/content/guide/migration/v8.md
- tools/defaults.bzl
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(effects): replace NotificationKind with a string literal 

- projects/ngrx.io/content/guide/nightlies.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1941
ngrx/data Nightly builds is displayed
```
[ ] Yes
[X] No
```
> docs: add ngrx/data to Recipes - Nightly builds

- projects/ngrx.io/content/guide/store/reducers.md
Later in the docs  resetScore is used on(ScoreboardPageActions.resetScore, state => ({ home: 0, away: 0 }))
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> reset -> resetScore

- projects/ngrx.io/content/marketing/events.json
```
[ ] Bugfix
[ ] Feature
```
- ngDenver should be Angular Denver
- Adding Angular In Depth Conference which @alex-okrushko spoke at
```
[ ] Yes
[x] No
```
> docs: add Angular In Depth and update Angular Denver on Events page

- projects/ngrx.io/content/guide/store/recipes/injecting.md
It should have been either:
- (...) use an InjectionToken (...) (preferred, IMHO)
or
-  (...)  you should use an InjectionToken  (...)
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: fix inconsistent word

- projects/ngrx.io/content/marketing/events.json
add ngTalks to the list of the events that NgRx team is presenting at
```
[ ] Bugfix
[ ] Feature
```
> docs: add ngTalks to the list of events

- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Added a $ sign to the `actions$` observable in effect testing guide in order to keep the other examples convention
```
[ ] Yes
[ x] No
```
> docs: add $ sign to actions observable

- modules/effects/schematics/ng-add/files/__name@dasherize@if-flat__/__name@dasherize__.effects.spec.ts.template
- modules/effects/schematics/ng-add/index.spec.ts
- modules/schematics/src/container/files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- modules/schematics/src/container/index.spec.ts
- modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.spec.ts.template
- modules/schematics/src/effect/index.spec.ts
- projects/ngrx.io/content/examples/testing-store/src/app/auth-guard.service.spec.ts
- projects/ngrx.io/content/guide/effects/testing.md
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
[ x ] Refactoring (no functional changes, no api changes)
```
##What kind of change does this PR introduce?
Update schematics to generate the new `Testbed.get()` signature with the generic type
Closes #1968
> refactor(schematics) update schematics to use the new get token signature

- modules/store/src/tokens.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fix spelling in token description.  Was not causing functional issues.
```
Closes #1972 
Fixes typo in `_ACTIVE_RUNTIME_CHECKS` injection token description.
```
[ ] Yes
[x] No
```
> fix(store): fix typo in runtime checks injection token description

- projects/ngrx.io/content/examples/store/src/app/my-counter/my-counter.component.html
- projects/ngrx.io/content/examples/store/src/app/tests/integration.spec.ts
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
The current section was outdated.  It replicated the [v6 general testing documentation](https://github.com/ngrx/platform/blob/6.1.2/docs/store/testing.md), which discussed conditioning states.  That should now be done by the MockStore.
Also simplified the example to not dispatch actions that are usually done by an effect.
Closes #1952 (partially)
I'd like to do a follow up PR to add an integration testing section to effects/testing. …
> docs: Clean Up Store Integration Testing Section

- projects/ngrx.io/content/guide/store/reducers.md
```
[ ] Bugfix
[ ] Feature
```
Fixing syntax error in example code.
```
[ ] Yes
[x] No
```
> docs: fix action syntax in reducer page example code

- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
MockStore was being used in the example, but wasn't being imported.
Closes #
MockStore is now imported
```
[ ] Yes
[x] No
```
> docs: Import MockStore in example

- projects/example-app/src/app/books/effects/book.effects.spec.ts
- projects/example-app/src/app/books/effects/book.effects.ts
Closes #1953
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: Update book search failure action with only error message

- projects/ngrx.io/content/guide/router-store/actions.md
```
[ ] Bugfix
[ ] Feature
```
Documentation update
Closes #
```
[ ] Yes
[x] No
```
> docs(router-store): add closing parentheses 

- modules/data/schematics/ng-add/index.ts
```
[x] Bugfix
[ ] Feature
```
The ng-add schematic only looks for replacements on one CLI project.
It should look at all of the source files (in for example a monorepo).
```
[ ] Yes
[x] No
```
> fix(data): search for replacements in all files

- projects/ngrx.io/content/guide/store-devtools/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> small typo - environment

- modules/effects/schematics/ng-add/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
- modules/effects/schematics/ng-add/index.spec.ts
- modules/effects/schematics/ng-add/index.ts
- modules/effects/schematics/ng-add/schema.json
- modules/effects/schematics/ng-add/schema.ts
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/effect/index.ts
- modules/schematics/src/effect/schema.json
- modules/schematics/src/effect/schema.ts
- modules/schematics/src/store/index.spec.ts
- modules/schematics/src/store/index.ts
- modules/schematics/src/store/schema.json
- modules/schematics/src/store/schema.ts
- modules/store/schematics/ng-add/index.spec.ts
- modules/store/schematics/ng-add/index.ts
- modules/store/schematics/ng-add/schema.json
- modules/store/schematics/ng-add/schema.ts
- projects/ngrx.io/content/guide/effects/install.md
- projects/ngrx.io/content/guide/schematics/effect.md
- projects/ngrx.io/content/guide/schematics/store.md
- projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[x] Feature
```
Closes #1992, #1994 
```
[ ] Yes
[x] No
```
> feat: add minimal setup option for store and effects

- projects/ngrx.io/content/guide/entity/adapter.md
```
[ ] Bugfix
[ ] Feature
```
Closes #1887
```
[ ] Yes
[x] No
```
> docs(entity): mention shorthand syntax alternative

- modules/data/schematics-core/utility/strings.ts
- modules/effects/schematics-core/utility/strings.ts
- modules/entity/schematics-core/utility/strings.ts
- modules/router-store/schematics-core/utility/strings.ts
- modules/schematics-core/utility/strings.ts
- modules/schematics/schematics-core/utility/strings.ts
- modules/store-devtools/schematics-core/utility/strings.ts
- modules/store/schematics-core/utility/strings.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[X] No
```
> style(schematics): small error in pluralize function comment

- projects/ngrx.io/content/guide/store/recipes/injecting.md
```
[ ] Bugfix
[ ] Feature
```
* The [Dependency Injection -> Injecting Feature Config](https://ngrx.io/guide/store/recipes/injecting#injecting-feature-config) example doesn't have information on using a meta-reducer factory.
* The DI guide refers to `META_REDUCERS`, whereas [V8 Upgrade Guide -> `META_REDUCERS` token](https://ngrx.io/guide/migration/v8#meta_reducers-token) refers to `USER_PROVIDED_META_REDUCERS`
Closes #2019 
I've updated and expanded examples.
```
[ ] …
```
> Docs: Added meta-reducer to injected feature config example.

- modules/effects/spec/effect_sources.spec.ts
- modules/effects/src/effects_resolver.ts
This reverts commit 5b489124f7e6d1f211603cca92aab658dc1688da.
```
[ ] Bugfix
[ ] Feature
```
Reverting due to stability issues caused in CI that need investigation.
Closes #
```
[ ] Yes
[ ] No
```
> Revert "fix(effects): resubscribe every time an error occurs "

- projects/ngrx.io/content/guide/store/reducers.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2054 
```
[ ] Yes
[X] No
```
> Docs reducer set score action

- projects/ngrx.io/content/guide/data/entity-actions.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(data) update entityActionFactory.create examples

- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Just fixing a small grammatical typo
N/A
```
[ ] Yes
[x] No
```
> docs(testing): fix small typo in intro

- projects/ngrx.io/content/marketing/docs.md
"By normalizing state changes and pass them through observables"
is incorrect grammar. Changing to "passing them through observables."
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: fix verb conjugation typo

- modules/data/src/dispatchers/entity-dispatcher-base.ts
```
[X] Bugfix
[ ] Feature
```
Closes #2059
```
[ ] Yes
[X] No
```
> fix(data): use correct guard when handling optimistic update

- projects/ngrx.io/content/examples/store/src/app/counter.reducer.ts
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Current docs only mentions the way of importing modules by `imports: [StoreModule.forRoot({'game': scoreboardReducer})]`. However, this will fail when using AOT. Error like `Function calls are not supported in decorators ...` will be thrown. There is a solution of using InjectionToken, but this …
> docs(store): Add warning notes for AOT error and add solution of creating injection token

- projects/ngrx.io/content/guide/entity/adapter.md
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(example): fixed typo in sample code

- modules/effects/spec/BUILD
- modules/effects/spec/integration.spec.ts
- modules/effects/src/effects_module.ts
- modules/effects/src/effects_root_module.ts
- modules/effects/src/tokens.ts
- modules/store/spec/BUILD
- modules/store/spec/integration.spec.ts
- modules/store/src/store_module.ts
- modules/store/src/tokens.ts
```
[ ] Bugfix
[x] Feature
```
Using `StoreModule.forRoot()` and `EffectsModule.forRoot()` multiple times, by accident, in an application will result in unexpected behavior without knowing where it's coming from. 
This PR throws an error when this occurs, so developers can quickly troubleshoot.
Yes...?
```
[ ] Yes
[ ] No
```
This implementation is based on the `Router.forRoot()` guard.
> feat(store/effects): add forRoot guards

- modules/store/spec/selector.spec.ts
- modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
See description in #2100
Closes #2100
See description in #2100
```
[ ] Yes
[x] No
```
> fix(store): improve consistency of memoized selector result when projection fails

- projects/ngrx.io/content/guide/data/entity-collection-service.md
```
[ ] Bugfix
[ ] Feature
```
No mention about runtime checks feature.
Update docs to point to the runtime checks guide.
```
[ ] Yes
[X] No
```
> docs: update alert about runtime checks

- modules/data/src/actions/entity-cache-change-set.ts
- modules/data/src/entity-data-without-effects.module.ts
- modules/data/src/entity-metadata/entity-metadata.ts
- modules/data/src/entity-services/entity-services-base.ts
- modules/data/src/index.ts
- modules/data/src/reducers/entity-cache-reducer.ts
- modules/data/src/utils/guid-fns.ts
```
[ ] Bugfix
[ ] Feature
```
Language referencing `ngrx-data` in commments and TSDoc annotations
Closes #
Language referencing @ngrx/data
```
[ ] Yes
[x] No
```
> docs(data): replace ngrx-data with @ngrx/data

- modules/store/testing/spec/mock_store.spec.ts
- modules/store/testing/src/mock_store.ts
- [TODO] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
Follow up to #2044 
After each test, we'll clean the mock selectors. 
```
[ ] Yes
[x] No
```
First commit, shows the failing test
With the introduction of the auto cleanup in the second commit, the test passes
/cc @jtcrowson
> Auto cleanup selectors

- modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
See description in #2144
Closes #2144 
```
[ ] Yes
[x] No
```
> docs(store): document new behavior of createReducer for multiple actions of the same type

- modules/store-devtools/spec/extension.spec.ts
- modules/store-devtools/src/config.ts
- modules/store-devtools/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
feature property was of type any.
Closes #
changed to interface to assign the type.
```
[ ] Yes
[x] No
```
> Refactor:type safe feature option in dev tools

- projects/ngrx.io/content/guide/data/extension-points.md
Closes #2124
```
[ ] Bugfix
[ ] Feature
```
Undocumented [EntitySelectorsFactory](https://ngrx.io/api/data/EntitySelectorsFactory)
Closes #
Documents an example of using [EntitySelectorsFactory](https://ngrx.io/api/data/EntitySelectorsFactory)
```
[ ] Yes
[x] No
```
This is a first pass, is it ok to have it in the advanced section or do you prefer it somewhere else?
> docs(data): selectors

- modules/store/spec/selector.spec.ts
- modules/store/src/selector.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #2116 
```
[ ] Yes
[x] No
```
> fix(store): improve createFeatureSelector warning

- projects/ngrx.io/content/guide/data/entity-metadata.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> Remove duplicate "the" in entity metadata description

- projects/ngrx.io/content/guide/data/entity-metadata.md
replace `PagePersistenceResultHandler` with `AdditionalPersistenceResultHandler`, which is what is mentioned above. Also PagePersistenceResultHandler seems to not be present anywhere on this page
```
[ ] Bugfix
[ ] Feature
```
> docs(data): Update example to reflect the narrative

- projects/ngrx.io/content/guide/data/entity-metadata.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: Minor grammar changes

- build/tasks.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> build: use existing comment for docs preview links

- modules/schematics/collection.json
- modules/schematics/src/feature/index.spec.ts
- modules/schematics/src/feature/index.ts
- modules/schematics/src/selector/files/__name@dasherize@if-flat__/__name@dasherize__.selectors.spec.ts.template
- modules/schematics/src/selector/files/__name@dasherize@if-flat__/__name@dasherize__.selectors.ts.template
- modules/schematics/src/selector/index.spec.ts
- modules/schematics/src/selector/index.ts
- modules/schematics/src/selector/schema.json
- modules/schematics/src/selector/schema.ts
- projects/ngrx.io/content/guide/schematics/feature.md
- projects/ngrx.io/content/guide/schematics/selector.md
```
[ ] Bugfix
[x] Feature
```
Closes #2140 
This PR adds selector schematics with:
```bash
ng g selector selectorName
ng g s selectorName
ng g feature featureName
```
```
[ ] Yes
[x] No
```
> feat(schematics): selector schematics

- modules/store/src/index.ts
```
[ ] Bugfix
[X] Feature
```
Currently if you need to import `On` (to wrap or create your own `createReducer`), it will be imported from `@ngrx/store/src/reducer_creator`
Closes #
`On` will be imported from `@ngrx/store`
```
[ ] Yes
[X] No
```
> feat(store): Expose On in public api

- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2179
```
[ ] Yes
[x] No
```
> docs(effects): add tests with test scheduler

- projects/ngrx.io/content/guide/data/entity-dataservice.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2177 
```
[ ] Yes
[x] No
```
> docs(data): add http method with endpoint

- projects/ngrx.io/content/guide/data/entity-reducer.md
- projects/ngrx.io/content/guide/data/extension-points.md
Closes #2126
```
[ ] Bugfix
[ ] Feature
```
References to an `EntityReducerFactory` which no longer exists.
Closes #2126 
Updates references
```
[ ] Yes
[x] No
```
> docs(data): update refs to EntityReducerFactory

- modules/effects/src/effects_root_module.ts
- modules/effects/src/index.ts
https://github.com/ngrx/platform/issues/2218
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ROOT_EFFECTS_INIT actions as ActionCreators

- projects/ngrx.io/content/guide/data/index.md
trying to impl a PR for an [issue request] (https://github.com/ngrx/platform/issues/2220)
```
[ ] Bugfix
[ ] Feature
```
Closes #2220 
```
[ ] Yes
[x] No
```
> ngrx data module needs HttpClientModule 

- modules/effects/src/effect_creator.ts
- modules/effects/src/index.ts
- modules/effects/src/models.ts
Re-exports `CreateEffectMetadata` that was added to the `createEffect(...)` signature recently.
```
[x] Bugfix
[ ] Feature
```
Closes # https://github.com/ngrx/platform/issues/2243
```
[ ] Yes
[x] No
```
> fix(effects): export CreateEffectMetadata

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> build: fix tag filters for deployments

- projects/ngrx.io/content/guide/effects/index.md
Closes #2221
```
[ ] Bugfix
[ ] Feature
```
Closes #2221 
```
[ ] Yes
[X] No
```
> docs(effects): add Observable type in Effects Overview

- modules/store-devtools/spec/extension.spec.ts
- modules/store-devtools/src/utils.ts
Closes #2228
```
[x] Bugfix
[ ] Feature
```
Closes #2228
```
[ ] Yes
[x] No
```
> fix(store-devtools): escaping the safelist and blocklist strings

- modules/effects/src/index.ts
PR Checklist
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[x] Yes
[ ] No
```
Fixes Ivy support in Bazel: https://github.com/angular/angular/issues/33373
> fix(effects): add EffectsRootModule and EffectsFeatureModule to public API

- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Matched the bullet list items at the top, removed some of the "re-" words where the non-hyphenated variant was common enough, and changed "function" to "functions" where appropriate.
```
[ ] Yes
[x] No
```
> A few tweaks for readability

- modules/store-devtools/spec/config.spec.ts
- modules/store-devtools/src/config.ts
- modules/store-devtools/src/devtools.ts
- modules/store-devtools/src/extension.ts
- modules/store-devtools/src/reducer.ts
- modules/store-devtools/src/utils.ts
```
[ ] Bugfix
[ ] Feature
```
Hi there, :raised_hand_with_fingers_splayed: this PR removes unused module imports and sorts remaining one.
```
[ ] Yes
[x] No
```
> refactor(store-devtools): improve imports

- projects/ngrx.io/content/guide/data/save-entities.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(data): fix save entities typos

- projects/ngrx.io/README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: fix typo in README

- projects/ngrx.io/content/guide/data/extension-points.md
```
[ ] Bugfix
[ ] Feature
```
N/A
Closes N/A
N/A
```
[ ] Yes
[X] No
```
N/A
> docs: add an example how to replace the DefaultHttpUrlGenerator

- projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(ngrx-router): clarify that the extracted variables are functions

- projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(ngrx-router): fix typo in selectors code example

- projects/ngrx.io/content/guide/entity/index.md
https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state
- [ x] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(entity): updated FAQ url for Redux docs

- modules/store/schematics/ng-add/index.spec.ts
- modules/store/schematics/ng-add/schema.json
- projects/ngrx.io/content/guide/store/install.md
It will introduce a breaking change based on the flag option that has been changed.
```
[ ] Bugfix
[ ] Feature
```
By default the minimal flag is false.
Closes #2250 
By default the minimal flag is true
```
[X] Yes
[ ] No
```
> refactor minimal option

- .circleci/config.yml
Uses the standalone test runner is CI instead of Bazel while we investigate the out of memory issues.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ci: use fallback runner for CI tests

- modules/data/spec/actions/entity-action-factory.spec.ts
- modules/data/spec/actions/entity-action-operators.spec.ts
- modules/data/spec/dataservices/default-data.service.spec.ts
- modules/data/spec/dataservices/entity-data.service.spec.ts
- modules/data/spec/dispatchers/entity-dispatcher.spec.ts
- modules/data/spec/effects/entity-effects.marbles.spec.ts
- modules/data/spec/effects/entity-effects.spec.ts
- modules/data/spec/entity-data.module.spec.ts
- modules/data/spec/entity-metadata/entity-filters.spec.ts
- modules/data/spec/entity-services/entity-collection-service.spec.ts
- modules/data/spec/entity-services/entity-services.spec.ts
- modules/data/spec/reducers/entity-cache-reducer.spec.ts
- modules/data/spec/reducers/entity-collection-reducer-registry.spec.ts
- modules/data/spec/reducers/entity-collection-reducer.spec.ts
- modules/data/tsconfig-build.json
- modules/effects/tsconfig-build.json
- modules/entity/tsconfig-build.json
- modules/router-store/src/router_store_module.ts
- modules/router-store/tsconfig-build.json
- modules/schematics/tsconfig-build.json
- modules/store-devtools/src/config.ts
- modules/store-devtools/src/extension.ts
- modules/store-devtools/tsconfig-build.json
- modules/store/testing/spec/mock_store.spec.ts
- modules/store/testing/src/mock_store.ts
- modules/store/tsconfig-build.json
- tsconfig.json
- add strictness to Typescript by removing `strictPropertyInitialization: false` flag
- adjust files that were not meeting that requirement (tests just got ! added)
- cleans up `mock_store` a bit 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(all): revive strictPropertyInitialization

- modules/effects/schematics/ng-add/schema.json
- projects/ngrx.io/content/guide/effects/install.md
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
default value of  minimal is false
Closes #2251
default value of  minimal is true
```
[x ] Yes
[ ] No
```
Before:
When adding effects using schematics minimal flag by default was false.
After:
When adding effects using schematics minimal flag by default is true.
> refactor(schematics): change default value of minimal to true

- modules/effects/schematics/ng-add/index.spec.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> fix(effects): fix specs for ng-add tests

- .circleci/bazel.rc
- .circleci/config.yml
- WORKSPACE
- package.json
- tools/defaults.bzl
- yarn.lock
Splits test, and build jobs
Adds further memory-saving flags for Bazel in CI
Reference: https://docs.bazel.build/versions/master/memory-saving-mode.html
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: update Bazel to 1.1.0, and update CI configuration for build/test

- modules/effects/src/effect_sources.ts
- modules/effects/src/lifecycle_hooks.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(effects): lifecycle methods guards

- modules/store/testing/src/testing.ts
see https://github.com/ngrx/platform/issues/2328
```
[ ] Bugfix
[x] Feature
```
Closes # https://github.com/ngrx/platform/issues/2328
```
[ ] Yes
[x] No
```
> feat(store): testing - expose MockStore provider

- build/publish-latest.ts
- build/publish-next.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
This change prevents the `@ngrx/component` package from being published for now.
> build: exclude component package from publishing script

- modules/store/spec/meta-reducers/immutability_reducer.spec.ts
- modules/store/spec/meta-reducers/serialization_reducer.spec.ts
- modules/store/spec/runtime_checks.spec.ts
- modules/store/src/meta-reducers/immutability_reducer.ts
- modules/store/src/meta-reducers/serialization_reducer.ts
- modules/store/src/runtime_checks.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2109
```
[ ] Yes
[x] No
```
This only skips the checks on the action.
The state checks remain as is.
> feat(store): ignore ngrx actions for runtime checks

- modules/data/src/entity-data.module.ts
```
[x] Bugfix
[ ] Feature
```
NgRx Data does not compile with Angular 9. Gives error `EntityDataModule.forRoot returns a ModuleWithProviders type without a generic type argument.`
Closes #2356 
NgRx Data now compiles flawlessly with Angular 9.
```
[ ] Yes
[x] No
```
> fix(data): Angular 9 style ModuleWithProvider (#2356)

- modules/data/src/entity-services/entity-collection-service-base.ts
Fixes #2337
```
[x] Bugfix
[ ] Feature
```
Closes #2337
```
[ ] Yes
[x] No
```
> fix(data): wrong type of filter

- modules/data/src/entity-data-without-effects.module.ts
…Angular 9
```
[x] Bugfix
[ ] Feature
```
Related to #2356. Should have updated this one as well. 
Closes #2356 
```
[ ] Yes
[x] No
```
How do i build this locally for testing so that i can test changes locally in before pushing the PR?
> fix(data): EntityDataModuleWithoutEffect ModuleWithProviders

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #2377
```
[ ] Yes
[x] No
```
> docs: update AngularInDepth NgRx resource link

- projects/ngrx.io/content/marketing/resources.json
Please check if your PR fulfils the following requirements:
```
[ ] Bugfix
[ ] Feature
```
NgRx Ducks GitHub repo is referenced.
NgRx Ducks docs website is referenced.
```
[ ] Yes
[x] No
```
> docs(resources): update entry for ngrx-ducks

- modules/store/testing/spec/mock_store.spec.ts
- modules/store/testing/src/testing.ts
```
[x] Bugfix
[ ] Feature
```
Currently, `TestBed.inject(Store)` returns a different instance to `TestBed.inject(MockStore)`. So the test below fails.
```
beforeEach(async(() => {
TestBed.configureTestingModule({
declarations: [AppComponent],
providers: [
provideMockStore(),
]
}).compileComponents();
}));
it("mockstore providers", () => {
const storeA = TestBed.inject(Store);
const storeB = TestBed.inject(MockStore);
expect(storeA).toBe(storeB); // => FAIL
});
``` …
> fix(store): provide the same instance of MockStore

- modules/data/BUILD
- modules/data/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
- Updates build to use `ng_package` instead of `pkg_npm`
- Exports all symbols from public API explicitly to match other packages
- Rebase and merge to retain individual commits
Closes #2367, #2384
> refactor: update build for @ngrx/data, public API exports

- projects/example-app/src/app/auth/containers/login-page.component.spec.ts
- projects/example-app/src/app/auth/effects/auth.effects.spec.ts
- projects/example-app/src/app/auth/services/auth-guard.service.spec.ts
- projects/example-app/src/app/books/containers/collection-page.component.spec.ts
- projects/example-app/src/app/books/containers/find-book-page.component.spec.ts
- projects/example-app/src/app/books/containers/selected-book-page.component.spec.ts
- projects/example-app/src/app/books/containers/view-book-page.component.spec.ts
- projects/example-app/src/app/books/effects/book.effects.spec.ts
- projects/example-app/src/app/books/effects/collection.effects.spec.ts
- projects/example-app/src/app/core/effects/router.effects.spec.ts
- projects/example-app/src/app/core/effects/user.effects.spec.ts
- projects/example-app/src/app/core/services/book-storage.service.spec.ts
- projects/example-app/src/app/core/services/google-books.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> refactor(example): replace TestBed.get with TestBed.inject

- projects/example-app/src/app/books/effects/book.effects.spec.ts
- projects/example-app/src/app/books/effects/book.effects.ts
- projects/example-app/src/app/books/guards/book-exists.guard.ts
- projects/example-app/src/app/core/services/google-books.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
leftover from previous refactoring
Closes #
```
[ ] Yes
[x] No
```
> refactor(example): use barrel import for GoogleBooksService

- projects/ngrx.io/content/guide/data/faq.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix typo in NgRx Data FAQs

- projects/ngrx.io/content/examples/testing-store/src/app/user-greeting.component.spec.ts
- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
Update the documentation with the usage of MockStore and TestBed
```
[ ] Yes
[ ] No
```
>  docs: update MockStore usage

- modules/effects/spec/integration.spec.ts
- modules/effects/src/effect_sources.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2398
```
[ ] Yes
[x] No
```
> fix(effects): ngrxOnRunEffects loses context

- projects/ngrx.io/content/guide/data/extension-points.md
pluralizer spelled correctly
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> pluralizzer spelled wrong

- projects/ngrx.io/content/guide/data/entity-change-tracker.md
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
Closes #
```
[ ] Yes
[X ] No
```
> docs: fixed typo

- projects/ngrx.io/content/guide/entity/adapter.md
Add missing import types so the example is correct when copied.
```
[ ] Bugfix
[ ] Feature
```
The example when copied is invalid and missing two imports.
The example is now valid when copied.
```
[ ] Yes
[x] No
```
> docs(entity): add missing imports types

- projects/ngrx.io/content/guide/migration/v9.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #2216 
```
[ ] Yes
[ ] No
```
> docs: add v9 migration

- projects/ngrx.io/content/guide/data/index.md
Closed PR 2397 suggests that we were not entirely clear on what we mean by "Entities" and the fact that NgRx Data is designed exclusively for managing entity data.
This PR attempts to correct that deficiency.
Clarifies the *Entity* concept in NgRx Data
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(ngrx/data): clarify "entity" concept.

- docs/entity/adapter.md
- modules/entity/spec/fixtures/book.ts
- modules/entity/spec/sorted_state_adapter.spec.ts
- modules/entity/spec/unsorted_state_adapter.spec.ts
- modules/entity/src/models.ts
- modules/entity/src/sorted_state_adapter.ts
- modules/entity/src/unsorted_state_adapter.ts
- projects/ngrx.io/content/guide/entity/adapter.md
```
[] Bugfix
[X] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Build related changes
[] CI related changes
[] Documentation content changes
[] Other... Please describe:
```
Closes #2369
```
[] Yes
[X] No
```
> feat(entity): add 'setOne' method

- projects/ngrx.io/content/guide/store/testing.md
s/reducer/selectors/ as the example shows selectors, and tests of selectors.
```
[ ] Bugfix
[ ] Feature
```
Typo / cut & paste error
Fixed description
```
[ ] Yes
[x] No
```
> docs: fix code example filenames to match contents

- modules/entity/spec/sorted_state_adapter.spec.ts
- modules/entity/spec/unsorted_state_adapter.spec.ts
This is a small fix suggested by @alex-okrushko here: https://github.com/ngrx/platform/pull/2410#discussion_r386036013
> fix(entity): fix a 'setOne' test case

- projects/ngrx.io/content/guide/router-store/selectors.md
- [n/a] ~~Tests for the changes have been added (for bug fixes / features)~~
- [n/a] ~~Documentation has been added / updated (for bug fixes / features)~~
N/A
N/A
N/A
> docs: Added missing selectCurrentRoute selector

- .circleci/bazel.rc
- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
Uses the bazel disk cache for caching actions from the build process. This will help speed up future builds because Bazel will use the cache in determining what to rebuild.
```
[ ] Yes
[x] No
```
> ci: use disk cache for Bazel build

- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #2435
```
[ ] Yes
[ ] No
```
> docs: add v8 docs

- projects/example-app/src/app/app.module.ts
These checks are enabled by default in NgRx 9
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> refactor(example): remove immutability checks

- projects/ngrx.io/content/guide/store/actions.md
```
[ ] Bugfix
[ ] Feature
```
"javascript" is lowercase. "POJOS" is uppercase.
"JavaScript" and "POJOs"
```
[ ] Yes
[x] No
```
> docs: Fix capitalization of the word JavaScript

- projects/ngrx.io/content/guide/data/entity-metadata.md
- [ x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Class name switches to `AdditionalPropertyPersistenceResultHandler`
Closes #
Keep class name as `AdditionalPersistenceResultHandler` for all 3 steps.
Clarify that `action.payload.data` need to be set for default reducer to work.
```
[ ] Yes
[ x ] No
```
> docs(data): clarify step one and keep same class name

- modules/data/schematics-core/index.ts
- modules/data/schematics-core/utility/angular-utils.ts
- modules/data/schematics-core/utility/json-utilts.ts
- modules/effects/schematics-core/index.ts
- modules/effects/schematics-core/utility/angular-utils.ts
- modules/effects/schematics-core/utility/json-utilts.ts
- modules/entity/schematics-core/index.ts
- modules/entity/schematics-core/utility/angular-utils.ts
- modules/entity/schematics-core/utility/json-utilts.ts
- modules/router-store/schematics-core/index.ts
- modules/router-store/schematics-core/utility/angular-utils.ts
- modules/router-store/schematics-core/utility/json-utilts.ts
- modules/schematics-core/index.ts
- modules/schematics-core/utility/angular-utils.ts
- modules/schematics-core/utility/json-utilts.ts
- modules/schematics/schematics-core/index.ts
- modules/schematics/schematics-core/utility/angular-utils.ts
- modules/schematics/schematics-core/utility/json-utilts.ts
- modules/schematics/src/entity/creator-files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template
- modules/schematics/src/entity/index.spec.ts
- modules/schematics/src/entity/index.ts
- modules/schematics/src/reducer/creator-files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template
- modules/schematics/src/reducer/index.spec.ts
- modules/schematics/src/reducer/index.ts
- modules/store-devtools/schematics-core/index.ts
- modules/store-devtools/schematics-core/utility/angular-utils.ts
- modules/store-devtools/schematics-core/utility/json-utilts.ts
- modules/store/schematics-core/index.ts
- modules/store/schematics-core/utility/angular-utils.ts
- modules/store/schematics-core/utility/json-utilts.ts
```
[ ] Bugfix
[x] Feature
```
Closes (partially): #2241
```
[ ] Yes
[x] No
```
> feat(schematics): export reducer directly for ivy

- projects/example-app/src/app/books/actions/collection-page.actions.ts
- projects/example-app/src/app/books/containers/collection-page.component.spec.ts
- projects/example-app/src/app/books/containers/collection-page.component.ts
- projects/example-app/src/app/books/effects/collection.effects.spec.ts
- projects/example-app/src/app/books/effects/collection.effects.ts
- projects/example-app/src/app/books/reducers/collection.reducer.ts
Closes #2334
```
[ ] Bugfix
[ ] Feature
```
Closes #2334
Renames action to improve action hygiene.
```
[ ] Yes
[X] No
```
> ref(example): update loadCollection initialize action name

- projects/ngrx.io/content/navigation.json
Closes #2454
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add missing page to the nav
```
Selector schematic is not in the nav bar for the docs
Closes #2454 
Selector schematic is in the nav bar for the docs
```
[ ] Yes
[x] No
```
> docs: add selector schematic to navigation

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> ci: update cache key, remove cache key fallback

- modules/component/src/let/let.directive.ts
- projects/ngrx.io/content/guide/component/let.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(component): add missing `async` pipe and change `0` to falsy

- modules/data/schematics-core/utility/libs-version.ts
- modules/effects/schematics-core/utility/libs-version.ts
- modules/entity/schematics-core/utility/libs-version.ts
- modules/router-store/schematics-core/utility/libs-version.ts
- modules/schematics-core/utility/libs-version.ts
- modules/schematics/schematics-core/utility/libs-version.ts
- modules/store-devtools/schematics-core/utility/libs-version.ts
- modules/store/schematics-core/utility/libs-version.ts
```
[x] Bugfix
[ ] Feature
```
`ng-add` installs v8
`ng-add` installs v9
```
[ ] Yes
[x] No
```
> fix(schematics): install v9 with ng-add

- projects/ngrx.io/content/guide/component/index.md
- projects/ngrx.io/content/guide/component/install.md
- projects/ngrx.io/content/guide/component/let.md
- projects/ngrx.io/content/guide/component/push.md
- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/app/search/search-worker.js
- projects/ngrx.io/src/styles/1-layouts/_homepage.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component): add component pages to nav menu, and update docs

- projects/ngrx.io/content/guide/component/let.md
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Closes #
```
[ ] Yes
[ x ] No
```
> docs(component): spelling and grammar

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ci: use bazel cache key first

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ci: don't use cache for deployment

- projects/ngrx.io/src/app/search/search-worker.js
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: fix import for search service worker

- modules/router-store/src/models.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2486 
Could be a breaking change, if these types were being used
```
[ ] Yes
[ ] No
```
> fix(router-store): selectors should return MemoizedSelector

- modules/store/spec/meta-reducers/immutability_reducer.spec.ts
- modules/store/spec/meta-reducers/serialization_reducer.spec.ts
- modules/store/src/meta-reducers/immutability_reducer.ts
- modules/store/src/meta-reducers/serialization_reducer.ts
- modules/store/src/meta-reducers/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2404
```
[ ] Yes
[x] No
```
> fix(store): ignore Ivy in runtime checks

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> ci: fix cypress install for example e2e tests

- projects/ngrx.io/content/guide/component/install.md
- projects/ngrx.io/content/guide/data/install.md
- projects/ngrx.io/content/guide/effects/install.md
- projects/ngrx.io/content/guide/entity/install.md
- projects/ngrx.io/content/guide/router-store/install.md
- projects/ngrx.io/content/guide/schematics/install.md
- projects/ngrx.io/content/guide/store-devtools/install.md
- projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[ ] Feature
```
- Current link is NOT FOUND
- https://yarnpkg.com/docs/usage
- New link is [here](https://yarnpkg.com/getting-started/usage#installing-all-the-dependencies)
```
[ ] Yes
[x] No
```
> docs: fix the URL for installing with yarn

- .circleci/bazel.rc
- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> ci: make saving of cache keys consistent

- modules/router-store/src/models.ts
This reverts commit 39a4b91c89d98ee48a77346c123aa2a456fa4824.
```
[x] Bugfix
[ ] Feature
```
Closes #2514 
```
[ ] Yes
[x] No
```
> Revert "fix(router-store): selectors should return MemoizedSelector"

- modules/router-store/spec/BUILD
- modules/router-store/spec/types/selectors.spec.ts
- modules/router-store/spec/types/utils.ts
- modules/router-store/src/models.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2516
```
[ ] Yes
[ ] No
```
This time with tests... 🤦‍♂️
> fix(router-store): selects should return selectors

- modules/schematics/src/container/files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- modules/schematics/src/container/index.spec.ts
- modules/schematics/src/container/index.ts
- modules/schematics/src/container/integration-files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
```
[x] Bugfix
[ ] Feature
```
- In the component the store is injected with a generic
- During tests, the store is mocked as `any`
Closes #
We can just `Store` without having to provide a generic
```
[ ] Yes
[x] No
```
> fix(schematics): components should inject the store without generic

- .circleci/config.yml
- projects/ngrx.io/package.json
- projects/ngrx.io/yarn.lock
Updates the `firebase-tools` dependency for deployment of the docs
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> chore(docs): update firebase tools for deployment

- projects/ngrx.io/content/guide/data/entity-dataservice.md
```
[ ] Bugfix
[ ] Feature
```
Missing _infinitive particle_ in the sentence
```
[ ] Yes
[x] No
```
> docs: fix missing word on entity dataservice

- modules/store/src/reducer_creator.ts
The function calls work now, so removing extra function call
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(store): remove the extra function call

- modules/component/spec/let/let.directive.spec.ts
- modules/component/src/core/cd-aware/cd-aware_creator.ts
- modules/effects/schematics/ng-add/index.spec.ts
- modules/schematics/src/effect/index.spec.ts
run `yarn prettier` to format any files that got through
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style: run yarn prettier for the entire codebase

- modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> fix(store): remove circular dependency for mock import

- modules/router-store/spec/router_selectors.spec.ts
- modules/router-store/src/models.ts
- modules/router-store/src/router_selectors.ts
- projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #
Creates a new selector for the current route fragment.
```
[ ] Yes
[x] No
```
> feat(router-store): add route fragment selector

- package.json
- yarn.lock
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: add @angular/bazel dependency for Bazel

- projects/ngrx.io/content/marketing/index.html
- projects/ngrx.io/src/app/custom-elements/element-registry.ts
- projects/ngrx.io/src/app/custom-elements/ngrx/mff.component.ts
- projects/ngrx.io/src/app/custom-elements/ngrx/mff.module.ts
- projects/ngrx.io/src/styles/1-layouts/_homepage.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #
Adds a temporary call to action to the homepage encouraging visitors to donate to the [Minnesota Freedom Fund[(https://www.https://minnesotafreedomfund.org/).
```
[ ] Yes
[X] No
```
> docs(marketing): Add Minnesota Freedom Fund call to action to the homepage

- .circleci/config.yml
- build/tasks.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: fix deploy job and more cleanup CI config

- modules/component-store/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: run ngcc after install

- angular.json
- modules/component-store/tsconfig-build.json
- modules/component-store/tsconfig.schematics.json
- modules/component/tsconfig-build.json
- modules/data/tsconfig-build.json
- modules/data/tsconfig.schematics.json
- modules/effects/tsconfig-build.json
- modules/effects/tsconfig.schematics.json
- modules/entity/tsconfig-build.json
- modules/entity/tsconfig.schematics.json
- modules/router-store/tsconfig-build.json
- modules/router-store/tsconfig.schematics.json
- modules/schematics/tsconfig-bazel-build.json
- modules/schematics/tsconfig-build.json
- modules/schematics/tsconfig.schematics.json
- modules/store-devtools/tsconfig-build.json
- modules/store-devtools/tsconfig.schematics.json
- modules/store/tsconfig-build.json
- modules/store/tsconfig.schematics.json
- nx.json
```
[ ] Bugfix
[ ] Feature
[] CI related changes
```
Path resolution for the types is broken for libraries that depend on other libraries
Closes #
Updating to use ng-packagr builder to correctly resolve
external dependencies for built packages
```
[ ] Yes
[x] No
```
> build: fix path resolution with library dependencies

- modules/component-store/src/component-store.ts
Closure Compiler is having hard times believing that `initializationError` would be of type `Error` and throws conformance error. I'm adding a little help for it to ignore that check.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(component-store): make Closure Compiler happy with Error

- modules/data/spec/reducers/entity-cache-reducer.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore(data): fix assertions for merge strategy tests

- modules/schematics/src/store/index.spec.ts
- modules/schematics/src/store/index.ts
```
[x] Bugfix
[ ] Feature
```
@LayZeeDK  encountered this issue while using the schematics to scaffold a new project.
There's an missing `,` between the the `StoreModule` and `StoreDevToolsModule`.
```ts
@NgModule({
imports: [
StoreModule.forRoot(reducers, {
metaReducers, 
runtimeChecks: {
strictStateImmutability: true,
strictActionImmutability: true,
},
})!environment.production ? StoreDevtoolsModule.instrument() : []]
})
export class SharedDataAccessModule {}
``` …
> fix(schematics): add comma before devtools for empty imports

- .circleci/config.yml
- angular.json
- modules/schematics/src/entity/index.spec.ts
- modules/schematics/src/reducer/index.spec.ts
- nx.json
- package.json
- projects/example-app/src/app/auth/containers/__snapshots__/login-page.component.spec.ts.snap
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: use build target instead of build-release for bundling packages

- modules/component/spec/push/push.pipe.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore: remove globalThis leftovers
