build/util.ts, docs/effects/README.md, docs/effects/api.md, modules/effects/spec/effects-subscription.spec.ts, modules/effects/spec/singleton-effects.service.spec.ts, modules/effects/src/effects-subscription.ts, modules/effects/src/effects.module.ts, modules/effects/src/singleton-effects.service.ts
As discussed in https://github.com/ngrx/effects/pull/148 and https://github.com/ngrx/effects/issues/123.
Changed the default behaviour of effect classes to only run once.
This means doing `EffectsModule.run` multiple times for an Effect from different modules (e.g. via lazy loading) does not cause duplicate effect subscriptions.
I have removed the config option - this is now just always on. This means people will get No Provider errors for `SingletonEffectsService` if they forget to call `EffectsModule.forRoot()` in their root app module.
I also made a minor tweak to `./build/utilities.ts` to make the build run on Windows.
=> Effect classes only run once

modules/store-devtools/src/config.ts
Using `StoreDevToolsModule.instrument()` fails to compile with AOT enabled on AngularCLI. This fixes the problem.
=> Fix typings for AOT

modules/store/spec/modules.spec.ts, modules/store/spec/ngc/main.ts, modules/store/src/models.ts, modules/store/src/reducer_manager.ts, modules/store/src/selector.ts, modules/store/src/store.ts, modules/store/src/store_module.ts
Also allows feature modules to declare just one reducer function instead
of a complete action reducer map.
cc @vsavkin 
Closes #34
=> feat(Store): Allow parent modules to provide reducers with tokens

modules/store-devtools/src/config.ts, modules/store-devtools/src/index.ts, modules/store-devtools/src/instrument.ts, modules/store/src/index.ts
We were previously using the SHOULD_INSTRUMENT token to decide whether the instrumentation should occur due to AOT. Since this is no longer needed as NgModules can be conditionally included, this code that introduces eager providers can be removed.
Also exports the MemoizedSelector type
Fixed #30 , #49
=> fix(Devtools): Removed SHOULD_INSTRUMENT token

docs/store/api.md, modules/store/spec/store.spec.ts, modules/store/src/models.ts, modules/store/src/store_module.ts, modules/store/src/tokens.ts
=> Allow initial state function for AoT compatibility

modules/store/src/utils.ts
The type improvements are optional, but obviously `omit` needs to be fixed, as without it, `removeReducer` on both `Store` and `ReducerManager` will fail to work.
I'm going to write the unit tests to prove these work with the new `omit` before this is merge, but I wanted to get some eyes on this, so I'm opening this now.
Edit: It looks like this was tested, but was the test was omitted (tee hee) using `xit`? I didn't look at the test, but it is passing now.
Edit: Edit: Test passes locally, but not in Circle CI, so still needs to be invested. Please disregard the above!
=> Fix 'omit' function and improve typing

example-app/app/app.module.ts, example-app/app/routes.ts, modules/store-devtools/src/extension.ts
This will not serialize the data before sending it to the Devtools extension, allowing it to handle complex structures including circular references from the RouterState when using @ngrx/router-store.
Closes #61
=> refactor(Devtools): Show complex structures in monitor

example-app/app/app.module.ts, modules/store-devtools/src/config.ts
Fixes example-app compiler warning:
```
WARNING in ./modules/store-devtools/src/devtools.ts
"126:562-581 export 'StoreDevtoolsConfig' was not found in './config'
```
=> Fix devtools compiler warning.

README.md, build/tasks.ts, build/util.ts, circle.yml
- Add CircleCI override to use latest yarn for deterministic builds
- Refactor some overly obtuse functions
- Use async throughout
- Add commitizen-friendly badge
=> build(platform): Improve consistency (yarn), and async

docs/effects/api.md
Adding effects via `forRoot()` and `forFeature()` is functionally identical. This PR makes that clearer in the docs.
=> Clarify difference between forRoot and forFeature

build/tasks.ts
=> fix(effects): make correct export path for testing module

MIGRATION.md
ngrx/core can conflict with ngrx 4. This is a note in the migration guide to remove ngrx/core when you upgrade.
I got the following error compiling my ts before I removed ngrx/core:
`ERROR in /Users/karp/Documents/git/bgg/geekui2/node_modules/@ngrx/store/src/store.d.ts (13,5): Class 'Observable<T>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function.`
I believe the conflicting code was here:
https://github.com/ngrx/core/blob/master/src/add/operator/select.ts
=> Add note about removing @ngrx/core

modules/effects/spec/effects_metadata.spec.ts, modules/effects/src/effects_metadata.ts
tldr: applications using Google Closure Compiler with Angular's `ngc` can opt into downleveling specifically marked decorators into static properties. This change enables that usage.
closes #93
=> fix(effects): allow downleveled annotations

docs/store/actions.md
when forcing type that is not `keyof state' on select, typescript expects the parameter to be a map function
=> doc - remove wrong generic type

modules/store/src/selector.ts, modules/store/src/store.ts
See issue #118.
This PR removes the dependency on ngrx selector in store.ts. The previous implementation would have been incompatible with using reselect in place of the ngrx implementation of `createSelector()`. It also would have forced memoization of selectors, even in cases where memoization might have caused a performance penalty.
I also removed the `isSelector()` function, which was not used anywhere else in the codebase, and would have been confusing in that it would have returned false for selectors that were created by reselect (I believe).
=> Remove dependency on ngrx selector from store.ts

MIGRATION.md
The problem with devtools and router-store is pretty severe, and will get anyone who just follows the migration guide.
Until it is fixed, I suggest that we disclose the issue in the guide.
=> Update docs to mention know issue with devtools

modules/effects/src/actions.ts
On a simple effect, having to type an action like that is not too much of trouble:
```typescript
@Effect()
someEffect$: Observable<Action> = this.actions$
.ofType(MyActions.SOME_ACTION)
.map((action: MyActions.SomeAction) => ...);
```
But when we start using `withLatestFrom` and some `filter` for example, it can become quite repetitive to define the type:
```
@Effect()
someEffect$: Observable<Action> = this.actions$
.ofType(MyActions.SOME_ACTION)
.withLatestFrom(this.store$.select(state => state.someProp))
.filter(([action, someProp]: [MyActions.SomeAction, SomePropType]) => ...)
.map(([action, someProp]: [MyActions.SomeAction, SomePropType]) => ...);
```
In the filter, we do not know the type of the action but we do know the type of the prop selected from the store (which we have to …
=> improvement(Effects): Type parameter on ofType

README.md
There is a new gitter channel. We should direct people to it.
=> Update gitter link to ngrx/platform

modules/effects/spec/effects_metadata.spec.ts, modules/effects/src/effects_metadata.ts
Hi all,
this PR solves the problem of effects defined in package library, and compiled following the Angular Package Format , for instance: 
if I have this effect : 
```
@Effect()
loadModels$: Observable<CMSActions> = this.actions$
.ofType(CMS_ACTIONS.LOAD_MODELS)
.map(toPayload)
.map(models => new LoadModelsSuccessAction(models));
```
Compiled the propDecorators look like this : 
```
CMSEffects.propDecorators = {
'loadModels$': [{ type: Effect },]
};
```
which causes the following error in this [line](https://github.com/ngrx/platform/blob/master/modules/effects/src/effects_metadata.ts#L31) 
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
```
Also it seems that the args attribute is marked as optional see this …
=> fix(effects) : handle case if no args is defined in annotations

build/tasks.ts
Hi,
as I mentioned on Gitter I'm currently studying the build process of ngrx which you have set up for another project of mine. During that phase the build process broke a couple of times on the `copyTypeDefinitionFiles` step giving sometimes random errors on files. Some people (like @og-carefree) also mentioned it in the Gitter Channel: 
After applying this fix the error didn't happen to me any more, so it should hopefully be ok now :)
=> chore(Platform): fix type def files search path

modules/store/spec/selector.spec.ts, modules/store/src/selector.ts
This is a fix for: https://github.com/ngrx/platform/issues/226
With this fix, the projector function is memoized as well.
=> fix(createselector): memoize projector function

docs/router-store/README.md, docs/router-store/api.md, example-app/app/app.module.ts, example-app/app/reducers/index.ts, example-app/app/shared/utils.ts, modules/router-store/spec/integration.spec.ts, modules/router-store/src/index.ts, modules/router-store/src/router_store_module.ts, modules/router-store/src/serializer.ts
This adds a serializer that can be customized for returning the router state snapshot. By default, the entire RouterStateSnapshot is returned. Documentation has been updated with example usage.
```ts
import { StoreModule } from '@ngrx/store';
import {
StoreRouterConnectingModule,
routerReducer,
RouterStateSerializer
} from '@ngrx/router-store';
export interface RouterStateUrl {
url: string;
}
export class CustomSerializer implements RouterStateSerializer<RouterStateUrl> {
serialize(routerState: RouterStateSnapshot): RouterStateUrl {
const url = routerState ? routerState.url : '';
// Only return an object including the URL
// instead of the entire snapshot
return { url };
}
}
@NgModule({
imports: [
StoreModule.forRoot({ routerReducer: routerReducer }),
RouterModule.forRoot([
// routes
]), …
```
=> feat(RouterStore): Added serializer for router state snapshot

modules/store/src/store_module.ts
Closes #250, Also fixes similar AOT issue in #116
=> fix(Store): Use existing reducers when not using an InjectionToken

modules/store/src/store_module.ts
The injector behavior is different when compiled through AOT such that
provided tokens aren't resolved before the factory function is executed.
This fix uses the injector to get the reducers provided through tokens.
Reference #189 
cc: @Christian24
=> fix(Store): Use injector to get reducers provided via InjectionTokens

modules/store/spec/modules.spec.ts, modules/store/spec/utils.spec.ts, modules/store/src/utils.ts
=> fix(utils): meta reducers conflicting with initial state

docs/store/README.md
The select method from the Store expects a function, when I put the `this.counter = store.select<number>('counter');` the compiler says: `Argument of type '"counter"' is not assignable to parameter of type '(state: AppState) => string'.`
=> docs: fix selection of state using arrow function

docs/effects/api.md, example-app/app/books/effects/book.ts, modules/effects/src/util.ts
As discussed here, https://github.com/ngrx/platform/pull/161#issuecomment-321128856, this is a pull request to deprecate toPayload. It also adds a bit of documentation for the type-safe `ofType` method. 
Do you think it needs to be mentioned anywhere else in the docs? I could add something to the Migration notes as well, but I wasn't sure it really needed to be there.
This shouldn't be merged until a 4.1 release.
=> Deprecate toPayload utility function

docs/store/api.md, example-app/app/reducers/index.ts, modules/store/spec/utils.spec.ts, modules/store/src/index.ts, modules/store/src/models.ts, modules/store/src/store_module.ts, modules/store/src/utils.ts
Fixes the type signature issue for the array of metareducers. Each function should take a reducer and return a new reducer function.
Closes #264, Related to #170
=> fix(Store): Add type signature for metareducer

CONTRIBUTING.md, README.md, docs/store/api.md, docs/store/selectors.md, example-app/README.md, example-app/app/auth/components/login-form.component.ts
=> chore(docs): Add more information on contributing and API docs

docs/router-store/api.md, example-app/app/reducers/index.ts, example-app/app/shared/utils.ts, modules/router-store/spec/integration.spec.ts, modules/router-store/src/router_store_module.ts
This allows the type of the `routerState` to be set to match the custom serializer type. Example app updated also.
Closes #289
=> fix(RouterStore): Add generic type to RouterReducerState

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effect_sources.ts
=> fix(Effects): Do not complete all effects if one source errors or completes

README.md
Current link does not work. It contains */blob/master* at the moment (I think if another branch will be active link will be changed too).
Any ideas how to save relativeness of link but make it working?
=> chore: fix contributors link in readme

modules/store/spec/selector.spec.ts, modules/store/src/selector.ts
=> feat(createSelector): Ability to test the projectorFn independent from the selectors it is composed of

package.json, yarn.lock
Using [lint-staged](https://github.com/okonet/lint-staged) to automatically stage the files prettier changes. This should only run `prettier` on the changed files. This will fix the issue where someone commits their staged files, but the fixes don't get added since `prettier` isn't being run until after the `git add`, which leads to unstaged changes.
=> chore(precommit): fix precommit hook to git add after changing files

docs/router-store/api.md
Move `RouterStateSnapshot` to import from `@angular/router` instead of `@ngrx/router-store` in the `api.md` docs.
=> docs(api): fix imports typo to show imports from correct package

example-app/app/books/actions/book.ts, example-app/app/books/actions/collection.ts, example-app/app/books/containers/collection-page.ts, example-app/app/books/containers/find-book-page.ts, example-app/app/books/containers/selected-book-page.ts, example-app/app/books/containers/view-book-page.ts, example-app/app/books/effects/book.spec.ts, example-app/app/books/effects/book.ts, example-app/app/books/effects/collection.spec.ts, example-app/app/books/effects/collection.ts, example-app/app/books/guards/book-exists.ts, example-app/app/books/reducers/book.spec.ts, example-app/app/core/actions/layout.ts, example-app/app/core/containers/app.ts
=> chore(Example): rename Actions to be consistent

build/util.ts
Closes #234.
Tested on windows, with and without a space in path.
=> fix(Build): fix build with space in path

docs/store/README.md, docs/store/api.md
Ref https://github.com/ngrx/platform/issues/310, maybe some people were wondering the same thing as me :).
=> Add meta reducers injection in the Store docs

docs/router-store/README.md
Readme is a little bit mis-leading here. It tells that the signature of the action is `RouterNavigationPayload`. In fact, it is a `RouterNavigationAction` with a payload of the above type.
=> docs(RouterStore): type signature of ROUTER_NAVIGATION action

modules/router-store/spec/integration.spec.ts, modules/router-store/src/router_store_module.ts
Fix for #354, see more details there.
Contains unit test which fails without the fix.
=> fix(RouterStore): Fix cancelled navigation with async guard (fixes #354)

example-app/app/reducers/index.ts
Previously, the router state snapshot prevented the use of the `ngrx-store-freeze` due to circular references. With a custom serializer in place, an example of freezing the state can be added back to the example app.
Closes #327, #240
=> chore(Example): Added ngrx-store-freeze meta-reducer to example app

.github/ISSUE_TEMPLATE.md, docs/entity/README.md, docs/entity/adapter.md
=> chore(docs): Updated @ngrx/entity documentation examples and usage

modules/store/src/store_module.ts
forFeature method accepts also InjectionToken as reducer, but this was disallowed by typescript definition.
=> fix(StoreModule) Fix typing to accept InjectionToken

docs/entity/adapter.md, example-app/app/books/reducers/books.ts, modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/src/create_adapter.ts, modules/entity/src/models.ts
See issue #370.
Because there has been no official release of ngrx/platform yet, now seems to be the time to make this change.
=> Rename EntityAdapter option sort to sortComparer

modules/store/src/reducer_manager.ts
According to closure compiler, you cannot have non-optional arguments after optional ones.
=> Another change to keep closure compiler happy

docs/effects/README.md
`toPayload` is [listed as deprecated](https://github.com/ngrx/platform/blob/master/docs/effects/api.md#topayload-deprecated), but the effects docs still use them in the example.
=> docs(effects): Remove usage of deprecated `toPayload` util in example

docs/effects/README.md
just a minor fix, does not compile for me otherwise .. 
typescript: `2.5.2`
rxjs: `5.4.2`
angular: `4.2.4`
=> added missing import for `rxjs/add/operator/catch` in example doc

modules/effects/spec/effects_metadata.spec.ts, modules/effects/src/effects_metadata.ts
removes the downleveling behavior because it's currently broken with closure advanced optimization. this refactors to use angular's basic behavior (see: https://github.com/angular/angular/blob/master/packages/core/src/util/decorators.ts#L141-L146) 
removes any need for Reflect API and doesn't need to be down-leveled. 
edit: ready to roll
=> fix(effects): simplify decorator handling to align with ng

build/tasks.ts, package.json, yarn.lock
Rollup 0.50.0 requires to specify which module format through -f option
=> build(rollup): Update rollup to version 0.50.0

modules/entity/src/entity_state.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/state_adapter.ts, modules/entity/src/state_selectors.ts, modules/entity/src/unsorted_state_adapter.ts
=> feat(Entity): Add support for string or number type for entity ID

circle.yml, modules/entity/src/entity_state.ts, modules/entity/src/models.ts, package.json
=> fix(Entity): Change type for EntityState to interface

docs/entity/adapter.md
Example run into error, because there is no @ngrx/action package. The Action interface comes from @ngrx/store.
=> There is no @ngrx/action, but @ngrx/store

docs/effects/testing.md
* Add link to article that describes the mechanics and syntax used for marble testing and refer to it within the body of the example.
* Add imports that increase the clarity of the example flow: Observable and MyActions.
* Add 'imports' property to Testing module configuration for further completeness.
* Showcase an example of how Actions are created for the test and how they are used - the semantics of the Action names help paint a flow of the timeline and what is to be tested.
=> Boost the provideMockActions example for @ngrx/effects testing

docs/store/selectors.md
Add an example extending the `createSelector` documentation explaining how to use it with multiple state slices.
It wasn't obvious to me how powerful `createSelector` could be until @nicobytes pointed it out.
=> Add example for createSelector with multiple selector functions

.gitignore, modules/router-store/src/router_store_module.ts
I am sending a fix for the bug reported as #561.
You should probably consider better names for type parameters (for example `R` for router state and `S` for store state) since now `T` and `V` are used quite wildly in the code and every time they mean something different. But I did not want to do such big changes.
=> fix(RouterStore): Match RouterAction type parameters

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/reducer.ts
=> fix(StoreDevtools): Only recompute current state when reducers are updated

docs/router-store/api.md
Hi!
I was facing the same issue as describe [here](https://github.com/ngrx/platform/issues/382)(getting `params` object from the url) and spent some time finding this thread. I found that it could be useful to add the information to the documentation.
=> chore(RouterStore): add documentation on custom RouterStateSerializer

docs/store-devtools/README.md, example-app/app/app.module.ts
Hi!
This adds all information needed to be able to pass a valid configuration object into `StoreDevtoolsModule.instrument()` in the documentation. Adds a small update to the example, showing that the devtool name can be changed.
=> chore(StoreDevtools): improve documentation and example

package.json
Its depends from 
https://github.com/isaacs/node-glob/issues/309
If we use glob path begin ./ , then we include 'node_modules' folders (exists in modules packages).
This affects only OS - such as Linux, MacOS.
=> fix(prettier) ignore node_modules if glob path begins with dot

modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts
Closes #571
Needed to create a DidMutate enum, tell me what your think.
This PR only fixes the unsorted state adpater.
=> fix(Entity): updateOne/updateMany should not change ids state on existing entity

build/builder.ts, build/tasks.ts
Remove `JavaScript` from `src` folder as this is not required by the consumers with `Angular 4.x.x`, `@ngtools/webpack` and `paths` in `tsconfig.json` it causes the `src` to be bundled togather with the `FESM`.
Closes: #629
=> fix(*): packages are being bundled twice

example-app/app/auth/actions/auth.ts, example-app/app/auth/effects/auth.effects.ts, example-app/app/auth/reducers/auth.ts, example-app/app/auth/reducers/login-page.ts, example-app/app/books/actions/book.ts, example-app/app/books/actions/collection.ts, example-app/app/books/effects/book.ts, example-app/app/books/effects/collection.ts, example-app/app/books/reducers/books.ts, example-app/app/books/reducers/collection.ts, example-app/app/books/reducers/search.ts, example-app/app/core/actions/layout.ts, example-app/app/core/reducers/layout.ts
Suggestion, update actions types to use enum instead of const in example-app. See Issue #597 .
I've only updated two files as an example, but can update the rest if approved. Let me know what you think.
=> example-app: Update actions types to use enum instead of const

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effect_notification.ts, modules/effects/src/error_reporter.ts, modules/effects/src/index.ts
Fixes #626 
Could potentially change:
* What (if any) extra error information is exposed. Right now this information is quite specific to dumping it to the console. I think for any non-console error reporting this information (such as the instance of `Observable` and `Notification`) wouldn't be very useful.
* How that extra information is exposed. Right now it is direct properties on the `Error`, typed using interfaces extending `Error`.
In the `EffectError` case it would be nice to expose the real `Notification.error` better so custom `ErrorHandler`s will (by default) be handling the real underling error that was thrown.  Again... if we weren't building the custom `EffectError` for the console logging purposes I think just invoking `ErrorHandler.handleError(Notification.error)` would be …
=> feat(ErrorReporter): expose ErrorReporter as a ErrorHandler for ngrx

docs/store-devtools/README.md
https://github.com/ngrx/platform/issues/647
Fixing a typo in the store-devtools readme
=> docs(store-devtools): Typo

docs/effects/README.md, docs/effects/api.md, docs/entity/adapter.md, docs/router-store/api.md, docs/store-devtools/README.md, docs/store/README.md, docs/store/actions.md, docs/store/api.md, docs/store/selectors.md, docs/store/setup.md, docs/store/testing.md, example-app/app/books/reducers/index.ts
The contents in docs directories are useful and I often refer to it.
And I found unnecessary trailing whitespaces and hard-tabs in markdown files.
I want to remove trailing whitespaces and replace hard-tabs with 2 spaces to improve the code appearance.
please check this and feedback.
thanks.
=> Remove trailing whitespaces and replace hard tab from document files

build/util.ts
Copying schematic files gives:  
Error: ENOENT: no such file or directory,  
cause path not created recursive by `fsExtra.copy`
#660
=> fix build error on windows

docs/entity/adapter.md, modules/entity/src/index.ts, modules/schematics/src/entity/files/__path__/__name@dasherize__.actions.ts
=> refactor(Entity): Provide Update at top level import, closes #670

build/builder.ts, build/tasks.ts, build/util.ts, package.json
Fixes a regression introduced when javascript files were removed from the build output.
Closes #678
=> chore(build): Exclude testing files from being removed

README.md
Adds a small section to the README that we can use to boost conferences and events the NgRx core team will be attending.
=> docs(README): Add Events section to README

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/actions.ts, modules/store-devtools/src/devtools.ts, modules/store-devtools/src/reducer.ts
=> feat(StoreDevtools): Add support for jumping to a specific action

modules/store/spec/utils.spec.ts, modules/store/src/reducer_manager.ts, modules/store/src/utils.ts
=> fix(Store): Compose provided meta reducers for a feature reducer

docs/store-devtools/README.md, example-app/app/app.module.ts, modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/src/config.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/instrument.ts
=> feat(StoreDevtools): Add option to configure extension in log-only mode

modules/schematics/src/effect/index.spec.ts, modules/schematics/src/utility/ast-utils.ts
Puts the effect in the appropriate `forRoot` or `forFeature` array based on the blueprint option
=> fix(Schematics): Distinguish between root and feature effect arrays

modules/schematics/src/action/index.spec.ts, modules/schematics/src/action/index.ts, modules/schematics/src/action/schema.d.ts, modules/schematics/src/action/schema.json, modules/schematics/src/effect/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.effects.ts, modules/schematics/src/effect/index.spec.ts, modules/schematics/src/effect/index.ts, modules/schematics/src/effect/schema.d.ts, modules/schematics/src/effect/schema.json, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/index.ts, modules/schematics/src/feature/schema.d.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/reducer/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/reducer/index.ts, modules/schematics/src/reducer/schema.d.ts, modules/schematics/src/reducer/schema.json, modules/schematics/src/strings.ts, modules/schematics/src/utility/ngrx-utils.ts
Adds a `group` option to the feature blueprint that generates each blueprint (action, effect, reducer) within its respective sub-folder (actions, effects, reducers).
Related to #674
=> feat(Schematics): Add option to group feature blueprints in folders

modules/effects/src/index.ts, modules/effects/src/util.ts
BREAKING CHANGE: toPayload function is no longer exported
BEFORE:
import { toPayload } from '@ngrx/effects';
actions$.ofType('SOME_ACTION').map(toPayload);
AFTER:
actions$.ofType('SOME_ACTION').map((action: SomeActionWithPayload) => action.payload)
=> fix(Effects): Remove toPayload utility function

docs/effects/README.md
If you copy/pasted that code it would raise a static error for that missing comma
=> Add missing comma in example in README.md

docs/schematics/container.md, modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/index.ts
Also fixes docs to correct option for providing path to state.
Closes #760
=> fix(Schematics): Add store import to container blueprint

modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts, modules/schematics/src/container/index.spec.ts
This PR continue some works of @dinvlad , include some fix:
- change function return type from boolean to DidMutate
- return correct DidMutate based on update or add
Refs: #550
Closes: #421
=> feat(entity): introduce upsert methods

docs/schematics/effect.md
Based on the description of the command `... in the same folder` there should not have been a `--group` flag on the edited line.
=> updated to fix incorrect --group flag

modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/index.ts
=> fix(Schematics): Remove extra braces from container blueprint

modules/store-devtools/spec/integration.spec.ts, modules/store/src/store_module.ts
Depending on the order if your `NgModule` or `ModuleWithProvider` imports, the `Store` could get initialized after a feature state is loaded, causing the state to be undefined when using the Devtools. This fix creates an explicit instantiation order for `Store` being instantiated first, so the init action is always dispatched first to initialize the state.
Closes #624, #741
=> fix(Devtools): Ensure Store is loaded eagerly

modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/unsorted_state_adapter.ts
I have tried to fix issue #781 and verified the problem is really no longer there by building my application (where I can always reproduce the problem) with a version of `@ngrx/entity` containing these changes.
=> fix(Entity): Do not add Array.prototype properties to store

modules/entity/src/unsorted_state_adapter.ts
It seems that commit f871540f67191195a347297f1208e8f821d511cc introduced again the same problem I have fixed in d537758639016918fe71a70c3b92f06bf10a6dd7. My previous pull request was not rebased on the latest changes and so it caused failing tests after it was merged.
=> fix(Entity): Properly iterate over array in upsert

modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/src/sorted_state_adapter.ts
I have just noticed that the changes in commit f871540f67191195a347297f1208e8f821d511cc introduced to the sorted state adapter the same problem I have already fixed in the unsorted state adapter. So I'm adding the reproducer to those tests as well.
Just one question: Where can we expect these fixes to be released? Is there going to be version `5.0.2` anytime soon?
=> fix(Entity): Avoid for..in iteration in sorted state adapter

modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/config.ts, modules/store-devtools/src/devtools.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/instrument.ts, modules/store-devtools/src/reducer.ts
Continuing the work from #544 and requested by #604, this PR actually adds the sanitization functionality to @ngrx/store-devtools.
Unfortunately, simply passing `actionSanitizer` and `stateSanitizer` to the Redux Devtools Extension does not work, since the `send(action, state)` function exposed by its API does not sanitize anything if the `action` passed in is `null`, which is the current behaviour. As a result, it is necessary to sanitize within ngrx Devtools itself, and then pass that into the extension.
This implementation deliberately avoids mutating the lifted state's `actionsByIds` and `computedStates` properties, but instead creates a sanitized copy of them. This prevents the possibility of a sanitized action from changing the store state if, for example, its sanitized type …
=> feat(StoreDevtools): Add support for ActionSanitizer and StateSanitizer

docs/effects/api.md
A couple of the examples where referencing $action when the member variable was named $actions
=> fixing variable name typos

example-app/app/auth/containers/__snapshots__/login-page.component.spec.ts.snap, example-app/app/books/containers/__snapshots__/find-book-page.spec.ts.snap, package.json, yarn.lock
Organizes the dependencies into their respective `dependencies` and `devDevependencies` so importing into stackblitz will install them correctly. Will follow up with a PR that makes a stackblitz compatible branch.
=> chore(deps): Organize dependencies for better stackblitz support

modules/store-devtools/src/reducer.ts
This fixes the issue with time-traveling to previous states before the reducers were updated. Each state history item will be recomputed with the latest reducer.
=> fix(StoreDevtools): Recompute state history when reducers are updated

example-app/app/auth/reducers/index.ts, example-app/app/books/reducers/index.ts
In the example-app, provide the ActionReducerMap<T> in the books and auth reducer maps for [added type checking](https://github.com/ngrx/platform/blob/master/docs/store/actions.md).  This makes the example-app a better example of best practices.
=> Provide ActionReducerMap<T> with every reducer map in the example-app

example-app/app/books/reducers/books.ts
There is a problem with the order of comment sentence:
`createEntityAdapter creates many an object of helper functions.`
=> chore(Example): Adjust the comment

docs/schematics/README.md
Instead of editing the `.angular-cli.json` manually, you can run `ng set`. This is also used when setting up the `@angular/service-worker`.
=> docs(schematics): add alternative setup command

docs/schematics/README.md
Line no 22 => Replaced entity with schematics.
This is a simple typo by the previous person. I think he copied the README from the @ngrx/entity README. :-).
=> Updated README for a simple Typo

modules/store/spec/store.spec.ts, modules/store/src/reducer_manager.ts, modules/store/src/utils.ts
This assumes the store will only have an `undefined` state on initialization and sets the `initialSate` at that time. If the store state ever becomes `undefined` again in the future it will be reset to the `initialState` again.  This basically means `initialState` is more of a "default state" then "initial", but this at least improves it to be an undefined-check instead of falsey-check.  If we wanted to change this to be more strictly an "initial" state then this change would grow quite a bit.
For example if you add the following diff to the tests weird things occur:
```
@@ -74,8 +74,8 @@ describe('ngRx Store', () => {
store = TestBed.get(Store);
dispatcher = TestBed.get(ActionsSubject);
-      const actionSequence = '--a--b--c--d--e--f--g';
+      const actionSequence = …
```
=> fix(Store): only default to initialValue when store value is undefined

modules/entity/src/create_adapter.ts, modules/entity/src/models.ts
When building tools on top of @ngrx/entity it can be helpful to have access to the resolved `selectId` and `sortComparer` functions.
=> feat(Entity): Add 'selectId' and 'sortComparer' to state adapter

modules/store/spec/utils.spec.ts, modules/store/src/reducer_manager.ts, modules/store/src/utils.ts
I noticed this while doing #886. `createFeatureReducer` was being invoked for each action. In some cases (when `metaReducers` exist) this would invoke `compose` and create a new composed method for each action.
This also changes `createFeatureReducer` to `createFeatureReducerFactory` more like `createReducerFactory`. This could potentially be undone to simplify this PR, but I thought the end result (the two methods being more alike) was better.
However... I think the better solution would be changing the `ActionReducerFactory` `reducerMap` argument from `ActionReducerMap<T, V>` to `ActionReducerMap<T, V> | ActionReducer<T, V>`. Then this `createFeatureReducer` method can be dropped and the reducer vs map of reducers code paths would be combined into one. Things like the `initialValue` …
=> refactor(Store): avoid createFeatureReducer being invoked per-action

build/tasks.ts
Submitting a PR to generate named umd bundles for ngrx.
The motivation is to make ngrx bundles compatible with the Bazel dev server used in the sample here: https://github.com/alexeagle/angular-bazel-example
cc: @alexeagle
=> generate named umd bundles

README.md, example-app/README.md
Fixes #827 
ngrx/platform was incompatible with StackBlitz due to issues building the @ngrx/schematics package.
Reached out to [@ericsimon](https://github.com/EricSimons) who put in a hotfix. ngrx/platform is now compatible: https://stackblitz.com/github/ngrx/platform/
Added links to the StackBlitz in the platform and example-app READMEs.
=> Include Stackblitz in READMEs

.prettierignore, build/tasks.ts, modules/effects/spec/effects_feature_module.spec.ts, modules/effects/src/effect_notification.ts, modules/router-store/spec/integration.spec.ts, modules/schematics/src/utility/ast-utils.ts, modules/schematics/src/utility/change.ts, modules/store/src/reducer_manager.ts, package-lock.json, package.json, prettier.config.js, yarn.lock
This PR enables running prettier before commiting.
Don't feel obligated to accept this PR, I had some time left and thought this would add up to a better dev experience (at least it is for me :smile: )
**Why?**
Because most of the popular IDE's have a plugin to enable prettier on save.
**Changes:**
* created prettier config file (instead of passing the options as argument in `package.json`)
* also prettify `json` and `md` files
* only run prettier on staged files, not the whole codebase.
* ignore package files
* updated prettier version, hence the changes in the lock files
* ran prettier over the whole codebase
=> RFC: Prettier config

modules/schematics/src/action/index.spec.ts, modules/schematics/src/container/index.ts, modules/schematics/src/effect/index.ts, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/index.ts, modules/schematics/src/reducer/index.ts, modules/schematics/src/store/index.ts
Remove unused imports to increase readability and reduce code lines.
=> refactor(Schematics): remove unused imports

docs/schematics/README.md, docs/schematics/ionic.md
Include a section in the `@ngrx/schematics` `README.md` on how to integrate it and use it with Ionic.
---
As Ionic projects normally use the `ionic` CLI instead of `ng`, and several files have a slightly different structure than a normal Angular CLI project, it's not obvious how to use `@ngrx/schematics` in an Ionic project.
The added docs are a simple guide with the steps needed to integrate and use `@ngrx/schematics` in an Ionic project.
=> Add docs in @ngrx/schematics for Ionic integration

example-app/app/auth/actions/auth.ts, example-app/app/auth/containers/login-page.component.spec.ts, example-app/app/auth/containers/login-page.component.ts, example-app/app/auth/reducers/auth.ts, example-app/app/auth/reducers/login-page.ts, example-app/app/auth/services/auth-guard.service.spec.ts, example-app/app/auth/services/auth-guard.service.ts, example-app/app/books/actions/book.ts, example-app/app/books/actions/collection.ts, example-app/app/books/containers/collection-page.spec.ts, example-app/app/books/containers/collection-page.ts, example-app/app/books/containers/find-book-page.spec.ts, example-app/app/books/containers/find-book-page.ts, example-app/app/books/containers/selected-book-page.spec.ts, example-app/app/books/containers/selected-book-page.ts, example-app/app/books/containers/view-book-page.spec.ts, example-app/app/books/containers/view-book-page.ts, example-app/app/books/effects/book.ts, example-app/app/books/effects/collection.spec.ts, example-app/app/books/effects/collection.ts, example-app/app/books/guards/book-exists.ts, example-app/app/books/reducers/books.ts, example-app/app/books/reducers/collection.ts, example-app/app/books/reducers/search.ts, example-app/app/core/actions/layout.ts, example-app/app/core/containers/app.ts, example-app/app/core/reducers/layout.ts
Hi @brandonroberts 
In the example app, there are two forms for the actions import name, one is pascal and another one is lowercase, as show below:
```ts
// app.ts
import * as layout from '../actions/layout';
import * as Auth from '../../auth/actions/auth';
```
If I was a beginner of ngrx, I couldn't figure out which one was the best practices. It was a little confusing for me.
I suggest to unify the form of the import name, meanwhile I don't know which one is better.
In the [Typed Actions](https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions) section of the store document, It used the pascal, as show below:
```ts
import { Store, select } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import * as Counter from './counter.actions';
interface …
```
=> refactor(Example): Unify the form of the actions import name

package.json
`@angular/cli@6.0.0-rc.2` requires `node>=8.9.0`
Updated `package.json` to set minimum node version to `>=8.9.0`
Closes #988
=> fix(deps): Update minimum node version to 8.9.0

docs/store-devtools/README.md
I spent some time trying to debug things until I found https://github.com/ngrx/platform/issues/245 which mentions that the store needs to be injected before the devtools start working! Hopefully the next person that runs into this will be able to find the answer here.
=> docs(devtools): Specify that you need to inject the store for devtools to work

docs/schematics/store.md
As the title says, this should update the docs to the correct command for creating a new store in a module other than the root app module.
=> Fix for Schematics Documentation for Creating Stores

modules/schematics/src/container/schema.json
Container aliases for state and stateInterface removed.
Aliases for `state` and `stateInterface` were removed due to conflicts with component aliases without reasonable alternatives.
=> fix(Schematics): Remove aliases for state and stateInterface options

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/actions.ts, modules/store-devtools/src/devtools.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/reducer.ts
hi!
this is a fix for https://github.com/ngrx/platform/issues/508 (https://github.com/ngrx/platform/issues/966)
solution:
basically i subscribe to the devtools-extension start action and i trigger an action `refresh` to rerender as is the state transformations
=> fix(StoreDevtools): Refresh devtools when extension is started

modules/schematics/src/entity/files/__path__/__name@dasherize@if-flat__/__name@dasherize@group-actions__.actions.ts
Closes #1039 
Changed the payload of the `upsert` actions to have a fully qualified entity, see a0f45ff035726f106f3f34ddf9b5025c54fc63e0 for the change.
I think this is the only change that needs to happen, if not I'll update accordingly.
This is the new (actions) output:
```
import { Update } from '@ngrx/entity';
import { Foo } from '../models/foo.model';
export enum FooActionTypes {
LoadFoos = '[Foo] Load Foos',
AddFoo = '[Foo] Add Foo',
UpsertFoo = '[Foo] Upsert Foo',
AddFoos = '[Foo] Add Foos',
UpsertFoos = '[Foo] Upsert Foos',
UpdateFoo = '[Foo] Update Foo',
UpdateFoos = '[Foo] Update Foos',
DeleteFoo = '[Foo] Delete Foo',
DeleteFoos = '[Foo] Delete Foos',
ClearFoos = '[Foo] Clear Foos'
}
export class LoadFoos implements Action {
readonly type = FooActionTypes.LoadFoos; …
```
=> fix(Schematics): update upsert blueprint

docs/effects/api.md
There was no an example description for why we have to use `{dispatch: false}` .  The main source idea is from here https://medium.com/@tanya/understanding-ngrx-effects-and-the-action-stream-1a74996a0c1c . Here for the documentation I wrote it in my own words.
=> improve documentation for Non-dispatching Effects

modules/schematics/src/action/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.actions.ts, modules/schematics/src/effect/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.effects.ts, modules/schematics/src/reducer/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts
Closes #1040
The action blueprint has been updated to be less generic, with associated reducer and effects updated for the feature blueprint
BEFORE:
export enum UserActionTypes {
UserAction = '[User] Action'
}
export class User implements Action {
readonly type = UserActionTypes.UserAction;
}
export type UserActions = User;
AFTER:
export enum UserActionTypes {
LoadUsers = '[User] Load Users'
}
export class LoadUsers implements Action {
readonly type = UserActionTypes.LoadUsers;
}
export type UserActions = LoadUsers;
=> feat(Schematics): Rename default action type for action blueprint

modules/effects/migrations/BUILD, modules/effects/schematics-core/BUILD, modules/entity/migrations/BUILD, modules/entity/schematics-core/BUILD, modules/router-store/migrations/BUILD, modules/router-store/schematics-core/BUILD, modules/schematics/BUILD, modules/schematics/migrations/BUILD, modules/schematics/schematics-core/BUILD, modules/store-devtools/migrations/BUILD, modules/store-devtools/schematics-core/BUILD, modules/store/migrations/BUILD, modules/store/schematics-core/BUILD, tools/defaults.bzl
Fixes the replacements when building @ngrx/schematics
Moves `@ngrx/store` to first in the `packageGroup`, which enables use of `ng update @ngrx/store` to update all installed @ngrx packages
=> fix(build): Use default build for schematics

docs/schematics/README.md
PR for #1036 
I added information of additional configuration when default collection for schematics changed to `@ngrx/schematics` and example of that.
=> docs(Schematics): add information about schematics settings (#1036)

docs/schematics/README.md
Addresses issue #1060 
1) Edited the introduction and added some links.
2) Changed instances of "blueprints" to "schematics".
=> docs(Schematics): edit README to match ng cli docs

modules/effects/schematics/ng-add/index.spec.ts, modules/effects/schematics/ng-add/index.ts, modules/effects/schematics/ng-add/schema.json, modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts, modules/store/schematics/ng-add/schema.json, modules/store/schematics/ng-add/schema.ts
Allows the package to be added with sane defaults using `ng add @ngrx/store` and `@ngrx/effects`.
Do not squash these commits
=> fix: Added defaults for ng-add schematics

example-app/app/books/components/book-detail.component.ts, example-app/app/books/components/book-preview.component.ts
closes #1106 
add support for showing images in https (i.e, when loaded in stackblitz):
=> [Example App]: Add support for loading images over https

example-app/app/auth/effects/auth.effects.spec.ts
`#` is already an error terminating the observable.
Using `|` is redundant because an Observable cannot complete twice.
=> No need to use | after #

docs/schematics/store.md
https://github.com/ngrx/platform/issues/674
> @crimsonskyfalling this path is implicit. The path you provide for the feature will be the same path provided by the module.
=> Fix command for generate an `Admin` feature state

modules/entity/src/index.ts
When code exports a symbol whose type is inferred (or contains an inferred type), the type must be imported so that a correct name can be generated for it in the resulting .d.ts file.
For example, that means when we create any `selector` we have to import `MemoizedSelector` to the file, and, also not to have the **unused import** linter error, at least one of the selectors has to be fully typed.
Since `MemoizedSelector` is exported through `public_api.ts`, solving this problem is pretty straightforward, however one of the teams has started using `entities` now and has to import `Dictionary` for the exactly same reason, but `Dictionary` is not exported.
e.g. this is the code that they need to use:
```
export const fooEntities: MemoizedSelector<StateWithFoo, Dictionary<Foo>> = …
```
=> expose Dictionary as part of an API

docs/store/api.md
The angular compiler needs statically analyzes code during AOT. As such you can’t call functions like `combineReducers()` when defining metadata in the NgModule. 
Refs #306
=> update(doc): solution for Feature combineReducers and AOT

modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/src/config.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/instrument.ts
`serialize` can be boolean or object. One of the teams needs to provide custom replacer.
Adjusting the `serialize` according to the docs for extension:
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize
=> Allow custom serializer

modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts, modules/schematics/src/action/index.spec.ts
I used `ng generate action` command and found the generated file are invalid.
Please check the result I generated, thank you.
* Result I generated
```
import { Action } from '@ngrx/store';
export enum FooActionTypes {
LoadFoos = '[Foo] Load Foos'
}
export class Foo implements Action {
readonly type = FooActionTypes.LoadFoos;
}
export type FooActions = LoadFoos;
```
* Expected
```
import { Action } from '@ngrx/store';
export enum FooActionTypes {
LoadFoos = '[Foo] Load Foos'
}
export class Foo implements Action {
readonly type = FooActionTypes.LoadFoos;
}
export type FooActions = Foo; // <<< this should be Action class name!
```
=> fix(schematics): correct a type of action class generated

modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts, modules/schematics/src/effect/index.spec.ts
I suppose that we should use ofType operator function instead of Actions#ofType in generated files by schematics.
Please consider this change, thank you!
=> feat(Schematics): use ofType operator function instead of Actions#ofType

docs/entity/adapter.md
Destructuring syntax in this example adds a layer of complexity that may trip up developers who aren't used to using it. Declaring the Entity Adapter selector methods more explicitly should help to keep the example focused on its original intent.
=> #1160 - Update Entity Adapter documentation for clarity

modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects__dot__spec.ts
I think "FooEffects" is more suitable than "FooService" for description of effects spec file.
please review this change, thank you!
=> style(Schematics): revise Effects class name in description of spec file

modules/store-devtools/src/reducer.ts, modules/store/src/store.ts, prettier.config.js
At Google we already switched to 2.9. This PR makes ngrx/platform compatible with 2.9 as well (while still running fine at 2.7.2)
=> Prepare for TS 2.9

tslint.json
Now, tslint fails as described below.
```
$ ng lint
ERROR: /platform/example-app/app/shared/pipes/ellipsis.pipe.spec.ts[42, 6]: " should be '
```
We should use single quotes with escaping.
*ellipsis.pipe.spec.ts#L42
```
// current code
it("should return the string if it's length is less than 250", () => {
// expected
it('should return the string if it\'s length is less than 250', () => {
```
But this file is formatted by prettier as described below.
```
$ yarn run pritter
- it('should return the string if it\'s length is less than 250', () => {
+  it("should return the string if it's length is less than 250", () => {
```
So  I add tslint the "avoid-escape" option.
And ng lint command passes as expected.
```
$ ng lint
All files pass linting.
```
Also, we can use back-quotes instead double …
=> chore(Example): remove tslint configuration conflicting with prettier

modules/effects/src/effects_metadata.ts, modules/effects/src/on_run_effects.ts
Remove leftover of `Reflect`
remove a bunch of `any` types
general cleanup
for https://github.com/ngrx/platform/issues/623
@robwormald @brandonroberts @MikeRyanDev  Any reason in particular why `METADATA_KEY` is added to `sourceProto.constructor` ( aka `instance.constructor`) instead of simply to the `instance`?
This prevents me from removing the remaining `constructor as any` pieces because `constructor` has type of `Function`.
I've experimented with putting it just on `instance` at Firebase and it appears to work just fine, but maybe there is some background that I'm not aware of.
=> cleanup metadata and add types

docs/store/selectors.md, example-app/app/auth/reducers/index.ts, example-app/app/books/reducers/index.ts, example-app/app/reducers/index.ts, modules/store/src/selector.ts
=> feat(Store): add an overload to createFeatureSelector to provide better type checking

docs/effects/api.md
I wanted to reference someone to the `ROOT_EFFECTS_INIT` documentation and noticed this wasn't added to the docs, therefor this PR.
=> docs(effects): add documentation for ROOT_EFFECTS_INIT

docs/store/downgrade.md
Small clarification/fix for @ngrx/store angularJS downgrade instructions.
Change is to specify "Store" instead of "provider" when calling downgradeInjectable.
=> docs(store): fix/clarify angularJS downgrade of Store

modules/entity/spec/utils.spec.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts, modules/entity/src/utils.ts
Closes #1133 
Example of the message:
=> feat(Entity): log a message when selectId returns undefined in dev mode

example-app/app/auth/components/login-form.component.spec.ts
The `../actions/auth` import is throwing an error because the file does not exist.
Removed the imports because there aren't used.
=> style(ExampleApp): remove unused import

modules/store/spec/selector.spec.ts, modules/store/src/index.ts, modules/store/src/selector.ts
Also renamed isEqual to isResultEqual to be clear what is compared
This is the fix for https://github.com/ngrx/platform/issues/1157
=> Change what defaultMemoize compares with isEqual

modules/effects/src/effects_metadata.ts
Prior TS 2.9 keyof T has the type string. Since 2.9 An index type keyof T for some type T is a subtype of string | number | symbol.
2.8 introduced Extract<keyof T, string> that helps to narrow the type down back to string, but ngrx/platform is at 2.7 still, thus this change is needed.
=> Adjust ngrx to be fully compatible with ts27 and ts29 at the same time

modules/store/spec/integration.spec.ts, modules/store/spec/selector.spec.ts, modules/store/src/models.ts, modules/store/src/selector.ts, modules/store/src/store.ts
This allows to provide provide extra properties inside selectors.
```ts
const selector = createSelector(
state => state.count * 10,
(state, props) => state.count + props.value,
(one, two) => one + two
);
const result = selector(
{
count: 10,
},
{ value: 47 }
);
// Result = 157.
```
If we agree on this I can add a commit to enhance the docs.
Closes #1152.
=> feat: allow properties in selectors

modules/store/spec/integration.spec.ts, modules/store/spec/selector.spec.ts, modules/store/src/selector.ts
This is a follow up of #1194.
I was writing the docs and found it a bit awkward I had to create a selector to only pass the props
```ts
const getTodosById = createSelector(
getTodos,
(state: TodoAppSchema, { id }: { id: number }) => id,
(todos, id) => todos.find(todo => todo.id === id)
);
```
Therefor this PR, it also passes the props to the projector function.
Meaning the props will be passed through all the selectors + the projection function.
```ts
const getTodosById = createSelector(
getTodosState,
(todos: Todo[], { id }: { id: number }) =>
todos.find(todo => todo.id === id)
);
```
=> feat(Store): createSelector pass props to projector function

modules/effects/schematics-core/index.ts, modules/effects/schematics-core/utility/ast-utils.ts, modules/effects/schematics-core/utility/project.ts, modules/entity/schematics-core/index.ts, modules/entity/schematics-core/utility/ast-utils.ts, modules/entity/schematics-core/utility/project.ts, modules/router-store/schematics-core/index.ts, modules/router-store/schematics-core/utility/ast-utils.ts, modules/router-store/schematics-core/utility/project.ts, modules/schematics-core/index.ts, modules/schematics-core/testing/create-workspace.ts, modules/schematics-core/utility/ast-utils.ts, modules/schematics-core/utility/project.ts, modules/schematics/schematics-core/index.ts, modules/schematics/schematics-core/utility/ast-utils.ts, modules/schematics/schematics-core/utility/project.ts, modules/schematics/src/store/files/__statePath__/index.ts, modules/schematics/src/store/index.spec.ts, modules/schematics/src/store/index.ts, modules/store-devtools/schematics-core/index.ts, modules/store-devtools/schematics-core/utility/ast-utils.ts, modules/store-devtools/schematics-core/utility/project.ts, modules/store/schematics-core/index.ts, modules/store/schematics-core/utility/ast-utils.ts, modules/store/schematics-core/utility/project.ts
=> fix(schematics): exclude environment imports for libraries

modules/effects/schematics-core/index.ts, modules/effects/schematics-core/utility/ngrx-utils.ts, modules/entity/schematics-core/index.ts, modules/entity/schematics-core/utility/ngrx-utils.ts, modules/router-store/schematics-core/index.ts, modules/router-store/schematics-core/utility/ngrx-utils.ts, modules/schematics-core/index.ts, modules/schematics-core/utility/ngrx-utils.ts, modules/schematics/schematics-core/index.ts, modules/schematics/schematics-core/utility/ngrx-utils.ts, modules/store-devtools/schematics-core/index.ts, modules/store-devtools/schematics-core/utility/ngrx-utils.ts, modules/store/schematics-core/index.ts, modules/store/schematics-core/utility/ngrx-utils.ts
- rename "addReducerToStateInferface" to "addReducerToStateInterface"
- rename "stateInferfaceInsert" to "stateInterfaceInsert"
I ran `yarn copy:schematics` after modifying code in schematics-core directory.
Closes #1209
=> refactor(schematics-core): rename typo function and variable names

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effect_notification.ts
To have a more meaningful error when the effects retrieve an invalid action we could stringify the action. That way the dev would immediately know which action is wrong, this could be helpful for newcomers.
Message before: 
```
ERROR Error: Effect "AuthEffects.login$" dispatched an invalid action: [object Object]
```
Message after: 
```
ERROR Error: Effect "AuthEffects.login$" dispatched an invalid action: [{"payload":{"user":{"name":"User"}},"type":"[Auth] Login Success"}]
```
=> feat(Effects): stringify action on invalid action

modules/schematics/package.json, tools/defaults.bzl
The peer dependencies prevent you from using `ng update` since they are pinned to specific versions. We'll verify the schematics work across versions and rely on the dependencies provided implicitly with the CLI
Closes #1206
=> fix(schematics): Remove peer dependencies on Angular DevKit

modules/effects/src/actions.ts, modules/store/src/store.ts
Adding deprecation notices since we'll be removing these at some point before the next major release.
=> fix: deprecate instance operators in Store and Effects

.circleci/config.yml, modules/schematics-core/utility/ast-utils.ts
```
[ ] Bugfix
[ ] Feature
[ ] angular.io application / infrastructure changes
```
Now, we must run `yarn copy:schematics` after modifying files in the schematics-core folder but we can merge pull request without it.
To prevent it, I add CI a new job.
I newly added ci the `schematics-core-copy` job.
this job checks whether we executed `yarn copy:schematics` script and its changes are committed surely.
I configure this job to run before test job.
CI runs `git diff --name-only --exit-code ./modules` command after `yarn …
=> build: check schematics-core files in CI

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effect_sources.ts
Fixes #1246 
With this change, it is possible to add different instances of the same class to the effects and have them running:
```
class ConfigurableEffect {
@Effect({ dispatch: false })
doSth$ = timer(1000).pipe(
tap(() => console.log(this.message))
);
constructor(private message: string) { }
}
@NgModule({
imports: [BrowserModule, FormsModule, StoreModule.forRoot(() => true), EffectsModule.forRoot([])],
declarations: [AppComponent, HelloComponent],
bootstrap: [AppComponent]
})
export class AppModule {
constructor(effectSources: EffectSources) {
effectSources.addEffects(new ConfigurableEffect("configA"));
effectSources.addEffects(new ConfigurableEffect("configB"));
// -> this did not work before, second effects instance was never run
}
}
```
`EffectSources` still filters out effects …
=> Effects: Add support for effects of different instances of same class

docs/router-store/README.md, docs/router-store/api.md, modules/router-store/spec/integration.spec.ts, modules/router-store/src/router_store_module.ts, projects/example-app/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1241 
```
[x] Yes
[ ] No
```
Closes #1241 
The default state key is changed from routerReducer to router
=> refactor(RouterStore): change default state key to router

docs/router-store/README.md, docs/router-store/api.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This PR updates the router-store docs with information about the new actions and config.
One thing I came across during this is the section "Navigation actions", where it is said "Navigation actions are not provided as part of the router package". To me that seems confusing. Is this just really outdated or what is meant by that exactly?
=> docs(router-store): Document new actions and config

modules/router-store/spec/integration.spec.ts, modules/router-store/src/router_store_module.ts
```
[x] Bugfix
[ ] Feature
```
Fixes #1292, #1293 
- Error during navigation initiated by store is caught and handed to ErrorHandler
- `ROUTER_ERROR` / `ROUTER_CANCEL` action now contain previos router and store state 
```
[ ] Yes
[x] No
```
=> fix(router-store): Handle navigation error, cancel/error action contain real previous state

modules/router-store/src/actions.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1269 
```
[x] Yes
[ ] No
```
Normalize router store actions to be consistent with the other modules
BEFORE:
- ROUTER_REQUEST
- ROUTER_NAVIGATION
- ROUTER_CANCEL
- ROUTER_ERROR
- ROUTER_NAVIGATED
AFTER
- @ngrx/router-store/request
- @ngrx/router-store/navigation
- @ngrx/router-store/cancel
- @ngrx/router-store/error
- @ngrx/router-store/navigated
=> refactor(RouterStore): normalize actions

docs/store/downgrade.md, docs/store/selectors.md, docs/store/setup.md
Updates documentation to no longer reference `store.select`
```
[ ] Bugfix
[ ] Feature
```
The documentation uses `store.select`  
Issue Number: #1313 
The documentation uses `store.pipe(select())`
```
[ ] Yes
[x] No
```
=> docs(store): remove deprecated store.select()

modules/store/src/index.ts
The main purpose is to be able to import `MemoizedSelectorWithProps` and `SelectorWithProps` directly from ngrx/store  module. It helps to define explicit type annotations for selectors with props.
```
[ ] Bugfix
[x] Feature
```
While exporting `MemoizedSelectorWithProps` and `SelectorWithProps` from store `index.ts` file makes it possible to import for type annotations directly from store module instead of `ngrx/store/src/selector` and …
=> Export MemoizedSelectorWithProps and SelectorWithProps from store

modules/effects/src/effects_module.ts, modules/router-store/src/router_store_module.ts, modules/store-devtools/src/instrument.ts, modules/store/src/store_module.ts
```
[ ] Bugfix
[ ] Feature
```
The new compiler (Ivy) gets its metadata exclusively from reading .d.ts files. This means that any type information lost in the TypeScript compilation is not available when compiling downstream packages. We need to preserve the type of the NgModule returned by a ModuleWithProviders, so a generic type parameter is added to …
=>  refactor(effects,router-store,store-devtools,store) add type parameter to ModuleWithProviders for Ivy

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/reducer.ts
state history
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1255 
```
[ ] Yes
[ ] No
```
=> feat(store-devtools): use different action when recomputing state history

modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts
Variables names in Effects should be consistent across whole file.
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1356 
`ng generate @ngrx/schematics:feature customName` generates Effects code correctly.
```
[ ] Yes
[x] No
```
=> fix(schematics): fix effects code generated by schematics:feature

modules/entity/src/models.ts
```
[ ] Bugfix
[ ] Feature
[ x] Refactoring (no functional changes, no api changes)
```
Entities are using `export type` a lot. While they should work similar to `interface`, the latter is a preferred choice.
Moreover, `tsickle` tool has an issue type-annotating abstract classes that implement `type` at the moment: https://github.com/angular/tsickle/issues/912
The behavoir is unchanged, except it's _more …
=> refactor(entity): update types to interfaces

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/index.ts, modules/store-devtools/src/reducer.ts
Recompute action is renamed to @ngrx/devtools/recompute
This action will now also be exported
```
[ ] Bugfix
[ ] Feature
```
This was mentioned in [#1362 (comment)](https://github.com/ngrx/platform/pull/1362/files/1f1d5fe0896679e2eb14ea55a7573792e98ffe70#r226427227)
```
[ ] Yes
[x] No
```
=> refactor(StoreDevtools): rename recompute action

README.md
```
```
Currently, the docs linked to from the platform README are for the master branch / nightly builds. I often come back to the docs ahead of a major angular release (4->5, 5->6, 6->7) and I believe that every time I've looked at them they've reflected an unreleased api. This might be bad luck on my part, but I look at the docs infrequently enough that I always forget that they don't apply to the package version I'm using.
This PR adds a helpful message to the readme reminding folks that it's linking to the master branch version of the docs, and explaining how to find the docs for a specific release.
```
[x] Yes
[ ] No
```
=> docs: clarify that docs are for master branch

modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/models.ts, modules/entity/src/unsorted_state_adapter.ts
This PR allows to remove entities based on a predicate.
See #672
=> feat(Entity): add removeMany by predicate

modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/index.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts
This PR allows to edit entities based on a predicate.
See #672, in the issue it was mentioned to update the entities via multiple predicates - see my comment as why I don't think thats a good idea. If needed I can implement it that way tho.
I do got one question about the implementation of the sorted state adapter. 
Why does this have an own implementation? 
In my head the sorted adapter should call the unsorted adapter and do the sorting afterwards, but I must be missing someting :sweat_smile:
=> feat(Entity): add updateMany by predicate

modules/router-store/spec/serializer.spec.ts, modules/router-store/src/serializer.ts, projects/ngrx.io/content/guide/migration/v7.md
```
[x] Bugfix
[ ] Feature
```
The `routeConfig` isn't being serialized in `DefaultRouterStateSerializer`.
Issue Number: #1363
The `routeConfig` is being serialized in `DefaultRouterStateSerializer`.
Note that not all properies are being serialized:
```ts
{
// was already being serialized
component?: Type<any>;
// added properties to be serialized
path?: string;
pathMatch?: string;   
redirectTo?: string;
outlet?: string;
// not being serialized
matcher?: UrlMatcher; …
```
=> fix(RouterStore): serialize routeConfig inside the default serializer

modules/store/spec/selector.spec.ts, modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1389
This was also being addressed in https://github.com/ngrx/platform/pull/1194#issuecomment-408423739 but was forgotten.
The arguments weren't being memoized when the result of the selector was equal to its previous result.
This fix moves the memoization of the arguments before the check if the results are equal.
```
[ ] Yes
[x] No
```
Closes #1389
=> fix(Store): memoize selector arguments

projects/ngrx.io/content/guide/entity/adapter.md
Including an example of selectId as well as a note stating that it is optional in the case of the PK being id.
- [ X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
Does for entity do not include selectId example
Adding an example as well as noting the case where selectId is optional
```
[ ] Yes
[ X] No
```
=> docs(entity): add example for selectId

docs/store/selectors.md, projects/ngrx.io/content/guide/store/selectors.md
Remove typos in the selectors docs
```
[ ] Bugfix
[ ] Feature
```
Just two small typos in the selectors docs
```
[ ] Yes
[x] No
```
=> docs(store): remove typo in selectors docs

projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
When opening the docs section for ngrx.io the sidenav closes by default.
Closes #
When clicking on the docs link the side nav stays/starts open. This matches the behavior on angular.io as an example.
```
[ ] Yes
[X] No
```
=> docs: open docs sidenav by default

CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
The CHANGELOG currently provides an incorrect example for the breaking change regarding `ofType`
Reference: https://ngrx.io/api/effects/ofType
The example has been fixed.
```
[ ] Yes
[X] No
```
=> docs(changelog): fix `ofType` example

modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/src/extension.ts
```
[ ] Bugfix
[x] Feature
```
Yesterday a new version of the redux devtools was published and was leading to some problems as mentioned in https://github.com/ngrx/platform/issues/1449.
This change wraps the redux devtools execution inside a `try catch` block, so that our applications can continue functioning as usual, but without the devtools.
```
[ ] Yes
[x] No
```
=> feat(StoreDevtools): catch redux devtools errors

docs/effects/api.md, modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/effects_feature_module.spec.ts, modules/effects/spec/integration.spec.ts, modules/effects/src/effect_sources.ts, modules/effects/src/effects_feature_module.ts, modules/effects/src/index.ts, modules/effects/src/lifecycle_hooks.ts
```
[ ] Bugfix
[x] Feature
```
As mentioned in the issue, the solution we have now to dispatch an `INIT` effect action doesn't work in prod builds because the constructor name is mangled.
Closes #1447
This PR adds a new lifecycle hook `OnInitEffects` that dispatches a user-defined action on effect registration. I couldn't find another way to access the effect's name.
Personally, I also find this solution to be cleaner and more flexible than the previous one.
Right now …
=> feat(Effects): add OnInitEffects interface to dispatch an action on initialization

modules/schematics-core/testing/create-workspace.ts, modules/schematics/src/action/index.spec.ts, modules/schematics/src/action/schema.json, modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/schema.json, modules/schematics/src/effect/index.spec.ts, modules/schematics/src/effect/schema.json, modules/schematics/src/entity/index.spec.ts, modules/schematics/src/entity/schema.json, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/reducer/schema.json, modules/schematics/src/store/index.spec.ts, modules/schematics/src/store/schema.json, projects/ngrx.io/content/guide/schematics/action.md, projects/ngrx.io/content/guide/schematics/effect.md, projects/ngrx.io/content/guide/schematics/entity.md, projects/ngrx.io/content/guide/schematics/feature.md, projects/ngrx.io/content/guide/schematics/reducer.md, projects/ngrx.io/content/guide/schematics/store.md
```
[x] Bugfix
[ ] Feature
```
Closes #1455
Now its possible to specify the project when generate actions, effects,
entities, features, reducers and stores.
The new flag is --project and his alias -p
Upgrade the documentation to add the new flag and his alias
```
[ ] Yes
[x] No
```
=> feat(schematics): add project flag support to specify apps or libs

.circleci/config.yml, build/tasks.ts, build/util.ts, projects/ngrx.io/package.json, projects/ngrx.io/scripts/build-404-page.js, projects/ngrx.io/scripts/copy-404-page.js
Branches from ngrx/platform opened as pull requests don't generate previews because the PR_NUMBER field is not provided.
This checks the CIRCLE_PULL_REQUEST environment variable and extracts the PR_NUMBER from it
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> build: use PR URL as fallback for PR number

modules/router-store/package.json, modules/router-store/schematics/BUILD, modules/router-store/schematics/collection.json, modules/router-store/schematics/ng-add/index.spec.ts, modules/router-store/schematics/ng-add/index.ts, modules/router-store/schematics/ng-add/schema.json, modules/router-store/schematics/ng-add/schema.ts
Add ng-add schematics for the router-store
add schema
implement tests
Closes #1479
```
[ ] Bugfix
[x] Feature
```
The user is not able to use Angular CLI to add the NgRX Router Store.
The user is able to use Angular CLI to add the NgRX Router Store.
```
[ ] Yes
[x] No
```
Read the ng-add schematics implementation of the store-devtools and effects modules first. I have done this implementation with their code style in mind.
Is it correct to leave the module attribute …
=> feat(schematics): implement router store ng-add

modules/effects/schematics/ng-add/schema.json, modules/effects/schematics/ng-add/schema.ts, modules/store-devtools/schematics/ng-add/schema.json, modules/store/schematics/ng-add/schema.json
Add missing project keys to schema.json
for store, store-devtools and effects
Line-break remove related to "lint-staged" in "precommit" package.json command
Related to #1487
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor(schematics): add project keys to schema

projects/ngrx.io/content/guide/store/selectors.md
Fixed the typo error in selector.
Mentioned `Books[]` instead of `Book[]`
```
[ ] Bugfix
[ ] Feature
```
Closes #
Fixed the typo error
```
[ ] Yes
[x] No
```
=> docs: fixed the Book typo error

modules/store/spec/fixtures/counter.ts, modules/store/spec/store.spec.ts, modules/store/src/store_module.ts, modules/store/src/tokens.ts
```
[ ] Bugfix
[x ] Feature
```
Closes #1414 
```
[ ] Yes
[ x] No
```
=> feat(store): support meta reducer factory for feature (#1414)

projects/example-app/src/app/app.module.ts, projects/example-app/src/app/auth/components/login-form.component.ts, projects/example-app/src/app/auth/containers/__snapshots__/login-page.component.spec.ts.snap, projects/example-app/src/app/auth/services/auth.service.ts
- allow username 'ngrx' to log in
- prefill username with ngrx
- enable devtools
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
See https://github.com/ngrx/platform/pull/1506
=> feat(Example): make the example app more user friendly

modules/store/spec/modules.spec.ts, modules/store/spec/store.spec.ts, modules/store/src/utils.ts
```
[ x] Bugfix
[ ] Feature
```
`metaReducers` for feature are called without the user's config initial state.
Closes #1464
```
[ ] Yes
[ x] No
```
=> fix(store): call metareducer with the user's config initial state

modules/store/spec/selector.spec.ts, modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
The first commit shows the current behavior, the second commit has the fix.
Closes #1501
```
[ ] Yes
[x] No
```
=> fix(Store): don't call the projector function if there are no selectors and props

modules/router-store/spec/integration.spec.ts, modules/router-store/src/actions.ts, modules/router-store/src/router_store_module.ts
```
[ ] Bugfix
[x] Feature
```
Only the `RouterNavigationAction`, `RouterCancelAction` and `RouterErrorAction` events had the `routerState` property in the payload.
Closes #1509
All of the router events will have the `routerState` property in the payload.
The `routerState` property is added to `RouterRequestAction` and `RouterNavigatedAction`
```
[ ] Yes
[x] No
```
These actions were introduced in https://github.com/ngrx/platform/pull/1267 and I couldn't find why the …
=> feat(RouterStore): add routerState  to action payload

projects/ngrx.io/content/guide/effects/index.md, projects/ngrx.io/content/guide/effects/install.md, projects/ngrx.io/content/guide/entity/index.md, projects/ngrx.io/content/guide/entity/install.md, projects/ngrx.io/content/guide/router-store/index.md, projects/ngrx.io/content/guide/router-store/install.md, projects/ngrx.io/content/guide/schematics/index.md, projects/ngrx.io/content/guide/schematics/install.md, projects/ngrx.io/content/guide/store-devtools/index.md, projects/ngrx.io/content/guide/store-devtools/install.md, projects/ngrx.io/content/guide/store/index.md, projects/ngrx.io/content/guide/store/install.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Missing documentation on use of `ng add`
Added a new section to the [https://ngrx.io/guide/store](Store) that documents how to use the `ng add` commands for NgRx.
```
[ ] Yes
[x] No
```
Cross-reference https://github.com/ngrx/platform/issues/1146
=> docs: reorganize installation instructions into individual pages for each module

modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts, modules/schematics/src/action/index.spec.ts, modules/schematics/src/action/schema.json, modules/schematics/src/action/schema.ts, modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts, modules/schematics/src/effect/index.spec.ts, modules/schematics/src/effect/schema.json, modules/schematics/src/effect/schema.ts, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/index.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/feature/schema.ts, modules/schematics/src/reducer/files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/reducer/schema.json, modules/schematics/src/reducer/schema.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1529 
Should resolve #1524 
The PR enhances the default effect generated for feature.
- Adds 2 new actions: `LoadFeatureSuccess` and `LoadFeatureFailure`
- Enhances feature state interface and initialState with data, loading and error properties the
- Enhances feature reducer adding switch cases for each action type
- `LoadFeature` action sets loading to true
- `LoadFeatureSuccess` action sets loading to false, nulls error …
=> feat(Schematics): add success/failure effects/actions to ng generate feature

modules/store-devtools/spec/integration.spec.ts, modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/reducer.ts, modules/store-devtools/src/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #1522
```
[ ] Yes
[x] No
```
The same error in the issue occured while using the `blacklist` or `whitelist` option.
=> fix(StoreDevTools): out of bounds when actions are filtered

package.json
```
[x] Bugfix
[ ] Feature
```
yarn run watch:tests script does not work on Windows.
```sh
PS C:\VSCode\2019\git-hub-forks\platform> yarn run watch:tests
yarn run v1.13.0
$ chokidar 'modules/**/*.ts' --initial -c 'yarn run test:unit'
Watching "'modules/**/*.ts'", "run", "test:unit'" ..
Terminate batch job (Y/N)? y
```
Closes #
#1559 
```sh
PS C:\VSCode\2019\temp\platform-rex> yarn run watch:tests
yarn run v1.13.0
$ chokidar "modules/**/*.ts" --initial --command "yarn …
```
=> fix(package.json) watch:tests script to work with Windows

modules/effects/src/actions.ts
```
[ ] Bugfix
[ ] Feature
```
Initially, I've meant to fix the typo in "Addtion", but then I thought
it could help if the example was expanded a bit.
NA
```
[ ] Yes
[X] No
```
=> docs(effects): expand ofType docs a bit, fixing typo

projects/ngrx.io/content/guide/entity/index.md
```
[ ] Bugfix
[ ] Feature
```
Added a section to `@ngrx/entity` overview page in the docs which mentions the ([apparently "known" but never described](https://github.com/ngrx/platform/issues/976#issuecomment-383615818)) limitation that the entity state adapter doesn't support es6 classes. Definitely spent a while trying to debug an issue caused by this limitation.
```
[ ] Yes
[x] No
```
=> docs(entity): detail limitation of entity state adapter

modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts, modules/schematics/src/effect/index.spec.ts
Two minor fixes for effects generated by `ng g feature`:
- Make the generated effect for 'ng g feature'  harmless by not dispatching any action
- type the 'Actions' injectable by default in feature effect
Closes #1573
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(schematics): type actions and avoid endless loop in effect

projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
There is no guide for `provideMockStore` API.
Added
```
[ ] Yes
[x] No
```
maybe relates to https://github.com/ngrx/platform/issues/1383
=> docs(store): add guide for provideMockStore

modules/router-store/spec/integration.spec.ts, modules/store/spec/meta-reducers/action_serialization_reducer.spec.ts, modules/store/spec/meta-reducers/immutability_reducer.spec.ts, modules/store/spec/meta-reducers/state_serialization_reducer.spec.ts, modules/store/spec/meta-reducers/utils.spec.ts, modules/store/spec/runtime_checks.spec.ts, modules/store/src/index.ts, modules/store/src/meta-reducers/action_serialization_reducer.ts, modules/store/src/meta-reducers/immutability_reducer.ts, modules/store/src/meta-reducers/index.ts, modules/store/src/meta-reducers/state_serialization_reducer.ts, modules/store/src/meta-reducers/utils.ts, modules/store/src/models.ts, modules/store/src/runtime_checks.ts, modules/store/src/state.ts, modules/store/src/store_module.ts, modules/store/src/tokens.ts, tests.js
```
[ ] Bugfix
[x] Feature
```
Closes #857
```
[x] Yes
[ ] No
```
The META_REDUCERS token has been renamed to USER_PROVIDED_META_REDUCERS
The META_REDUCERS token has become a multi token and can be used by
library authors
Based of [feat/serialization-and-mutation-checks](https://github.com/ngrx/platform/tree/feat/serialization-and-mutation-checks)
This PR also affects #1539
=> feat(Store): runtime checks

modules/effects/spec/actions.spec.ts, modules/effects/src/actions.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
Allows to filter Actions with `ofType(actionCreator)` as well as maintains previous behavior `ofType(actionCreator.type)`.
```
[ ] Yes
[x] No
```
=> feat(effects): allow ofType to handle ActionCreator

modules/effects/spec/create_effect.spec.ts, modules/effects/spec/effect_decorator.spec.ts, modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/effects_feature_module.spec.ts, modules/effects/spec/effects_metadata.spec.ts, modules/effects/spec/utils.spec.ts, modules/effects/src/effect_creator.ts, modules/effects/src/effect_decorator.ts, modules/effects/src/effect_sources.ts, modules/effects/src/effects_metadata.ts, modules/effects/src/effects_resolver.ts, modules/effects/src/index.ts, modules/effects/src/models.ts, modules/effects/src/utils.ts, projects/example-app/src/app/auth/effects/auth.effects.ts, projects/example-app/src/app/books/effects/book.effects.spec.ts, projects/example-app/src/app/books/effects/book.effects.ts, projects/example-app/src/app/books/effects/collection.effects.spec.ts, projects/example-app/src/app/books/effects/collection.effects.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1368 
```
[ ] Yes
[x] No
```
=> feat(Effects, Example): add createEffect

modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/spec/integration.spec.ts, modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/config.ts, modules/store-devtools/src/devtools.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/reducer.ts, modules/store-devtools/src/utils.ts, projects/ngrx.io/content/guide/store-devtools/config.md
```
[x] Bugfix
[ ] Feature
```
Closes #1557
```
[x] Yes
[ ] No
```
`actionsWhitelist` is renamed to `actionsSafelist`
`actionsBlacklist` is renamed to `actionsBlocklist`
BEFORE:
```ts
StoreDevtoolsModule.instrument({
actionsWhitelist: ['...'],
actionsBlacklist: ['...']
})
```
AFTER:
```ts
StoreDevtoolsModule.instrument({
actionsSafelist: ['...'],
actionsBlocklist: ['...']
})
```
=> fix(StoreDevTools): rename action list filters

modules/store/migrations/8_0_0/index.spec.ts, modules/store/migrations/8_0_0/index.ts, modules/store/migrations/BUILD, modules/store/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Users can provide meta reducers with `META_REDUCERS`
Closes #
Users can provide meta reducers with `USER_PROVIDED_META_REDUCERS`
```
[ ] Yes
[x] No
```
This migration will replace all `META_REDUCERS` occurrences to `USER_PROVIDED_META_REDUCERS` on `ng update` - this breaking change was introduced in #1613.
=> feat(Store): add META_REDUCERS replacement migration

.circleci/config.yml
Applitools has become flaky with no obvious changes. Will diagnose failures and re-enable.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> ci: temporarily disable example e2e tests

projects/example-app/src/app/app.module.ts, projects/example-app/src/app/auth/containers/login-page.component.spec.ts, projects/example-app/src/app/auth/reducers/index.ts, projects/example-app/src/app/books/containers/collection-page.component.spec.ts, projects/example-app/src/app/books/containers/find-book-page.component.spec.ts, projects/example-app/src/app/books/containers/selected-book-page.component.spec.ts
add runtimeChecks to store root module
add runtimeChecks to tests, removes warning
set ActionReducerMap action type to any inline with rest of example to remove type issue
```
[ ] Bugfix
[ ] Feature
```
Closes #1683 
```
[ ] Yes
[x] No
```
=> refactor(example): enable immutability checks

modules/schematics/src/store/index.spec.ts, modules/schematics/src/store/index.ts
fix(schematics): avoid lastIndexOf error while creating store schematics (#1659)
```
[x] Bugfix
[ ] Feature
```
Closes #1659
Now its possible to create a store schematic without a name if its called with the "--root" flag, otherwise a name is necessary.
```
[ ] Yes
[x] No
```
=> fix(schematics): avoid lastIndexOf error while creating store schematics (#1659)

projects/ngrx.io/src/app/custom-elements/events/event-list.component.spec.ts, projects/ngrx.io/src/app/custom-elements/events/event-list.component.ts, projects/ngrx.io/src/app/custom-elements/events/event-list.module.ts, projects/ngrx.io/src/app/custom-elements/events/event-order-by.pipe.spec.ts, projects/ngrx.io/src/app/custom-elements/events/event-order-by.pipe.ts
```
[ ] Bugfix
[x] Feature
```
Follow up to #1617 
- Upcoming events are in soonest to latest order (JSON ordering, not enforced)
- Past events are in least recent to most recent order (JSON ordering, not enforced)
Enforces ordering on the events page:
- Upcoming events are in soonest to latest order (enforced)
- Past events are in most recent to least recent order (enforced)
```
[ ] Yes
[x] No
```
=> docs: order past events in descending order

projects/example-app/src/app/auth/effects/auth.effects.ts, projects/example-app/src/app/books/effects/book.effects.ts, projects/example-app/src/app/books/effects/collection.effects.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1687 
Updates example application to match new action creator functionality of PR #1676 
```
[ ] Yes
[x] No
```
=> feat(example): update ofType in effects per #1676

modules/entity/spec/BUILD, modules/entity/spec/state_selectors.spec.ts, modules/entity/src/models.ts
Index signatures always return value and never return `undefined` 🤯
```ts
export class Dictionary {
[id: string]: number;
}
const dict = new Dictionary();
dict[100] // <--- type is number
```
https://github.com/Microsoft/TypeScript/issues/13778
Typescript is telling me that I don't need to check because it's of type `number`. In reality it's actually `number | undefined`, and I should check for the `undefined`.
Suggestion in the bug from TS team is to add " `| undefined` at their definition sites".
```
[ ] Bugfix
[x] Feature
[ ] …
```
=> feat(entity): add undefined to Dictionary's index signature

projects/example-app/src/app/books/reducers/index.ts
Adjust the example to handle the updated `Dictionary`, which now types as `T | undefined`.
```
[x] Bugfix
[ ] Feature
```
Closes #
https://github.com/ngrx/platform/issues/1735
```
[ ] Yes
[x] No
```
=> fix(example): handle possible undefined results from Dictionary

modules/store/spec/reducer_creator.spec.ts, modules/store/src/index.ts, modules/store/src/models.ts, modules/store/src/reducer_creator.ts, projects/example-app/src/app/app.module.ts, projects/example-app/src/app/auth/actions/auth-api.actions.ts, projects/example-app/src/app/auth/actions/auth.actions.ts, projects/example-app/src/app/auth/actions/login-page.actions.ts, projects/example-app/src/app/auth/reducers/auth.reducer.ts, projects/example-app/src/app/auth/reducers/index.ts, projects/example-app/src/app/auth/reducers/login-page.reducer.ts, projects/example-app/src/app/books/actions/book.actions.ts, projects/example-app/src/app/books/actions/books-api.actions.ts, projects/example-app/src/app/books/actions/collection-api.actions.ts, projects/example-app/src/app/books/actions/collection-page.actions.ts, projects/example-app/src/app/books/actions/find-book-page.actions.ts, projects/example-app/src/app/books/actions/selected-book-page.actions.ts, projects/example-app/src/app/books/actions/view-book-page.actions.ts, projects/example-app/src/app/books/reducers/books.reducer.ts, projects/example-app/src/app/books/reducers/collection.reducer.ts, projects/example-app/src/app/books/reducers/index.ts, projects/example-app/src/app/books/reducers/search.reducer.ts, projects/example-app/src/app/core/actions/layout.actions.ts, projects/example-app/src/app/core/reducers/layout.reducer.ts, projects/example-app/src/app/reducers/index.ts
Introduces `createReducer` function, that has the same functionality as `reducer` from `ts-actions` (created by @cartant).
It helps remove Action unions and dramatically reduce the code needed for reducers. Compare:
However, there are a few caveats that are caused by https://github.com/Microsoft/TypeScript/issues/3755 and https://github.com/Microsoft/TypeScript/issues/7547#issuecomment-218017839 with the latter acknowledging current TS limitation. 
``` ts
export interface State {
showSidenav: boolean;
}
const initialState: State = {
showSidenav: false,
};
export const reducer = createReducer<State>(
[
// Explicit 'State' return type for the 'on' functions is needed because
// otherwise …
```
=> feat(store): add createReducer function

projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Code sample for the `scan` operator is missing a comma in the arguments.
Closes #
Adds a missing comma in the scan operator code sample for the selectLastStateTransitions selector.
```
[ ] Yes
[x] No
```
=> docs(selectors): add missing comma in code sample

projects/ngrx.io/content/guide/migration/v8.md
```
[ ] Bugfix
[ ] Feature
```
Follow up to #1757 (coming from #1701)
```
[ ] Yes
[x] No
```
=> docs: add features and migrations

projects/ngrx.io/content/guide/schematics/install.md
Fixes #1739
```
[ ] Bugfix
[ ] Feature
```
Closes #1739
```
[ ] Yes
[X] No
```
=> Docs: Add instructions for using ng add

modules/schematics/src/entity/creator-files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template, modules/schematics/src/reducer/creator-files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template, modules/schematics/src/reducer/index.spec.ts, modules/store/spec/reducer_creator.spec.ts, modules/store/src/reducer_creator.ts, projects/example-app/src/app/auth/reducers/auth.reducer.ts, projects/example-app/src/app/auth/reducers/login-page.reducer.ts, projects/example-app/src/app/books/reducers/books.reducer.ts, projects/example-app/src/app/books/reducers/collection.reducer.ts, projects/example-app/src/app/books/reducers/search.reducer.ts, projects/example-app/src/app/core/reducers/layout.reducer.ts
As mentioned in https://github.com/ngrx/platform/pull/1746#issuecomment-485826209 this changes the order of `createReducer` function parameters and puts `initialState` first. That allows the function to properly infer the type and drop the generic that was otherwise needed.
In general, it is considered to be an anti-pattern if the function requires the generic to be specified - something is wrong with implementation or TS has some limitations. In this case the limitation was how TS was inferring the `State` type.
It also flattens the `ons`, which is a good benefit as well.
```
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional …
```
=> feat(store): change createReducer to avoid generic

projects/ngrx.io/content/guide/data/install.md
```
[ ] Bugfix
[ ] Feature
```
I think this is the last step in order to close #1554
```
[ ] Yes
[x] No
```
=> docs(data): add ng add installation

modules/store/spec/reducer_creator.spec.ts, modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1758
```
[ ] Yes
[x] No
```
=> feat(store): warn when same action is registered

modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[X] Feature
```
Current type signature only supports type inference for up to three action creators
This expands the type signature to support up to ten action creators. Highest I have internally is 7 so 10 felt like a good ceiling for now.
```
[ ] Yes
[X] No
```
=> feat(store): Expand createReducer type signature to support up to ten action creators

modules/data/schematics/ng-add/index.spec.ts, modules/data/schematics/ng-add/index.ts, modules/data/schematics/ng-add/schema.json, projects/ngrx.io/content/guide/data/install.md, projects/ngrx.io/content/guide/migration/v8.md
```
[x] Bugfix
[ ] Feature
```
Closes #1802
```
[ ] Yes
[ ] No
```
=> fix(data): the correct package name is ngrx-data

build/tasks.ts
```
[ ] Bugfix
[ ] Feature
```
Right now whenever we run the `schematics:copy` command, it will also copy the `BUILD.bazel` file.
Closes #
```
[ ] Yes
[x] No
```
=> chore: don't copy build files on copySchematicsCore

projects/ngrx.io/content/guide/data/index.md
`close` method is not declared in HeroComponent but it is used in the getHeroes method. So i removed the `close` method in this PR
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ x] No
```
=> docs: removed close method

WORKSPACE, modules/data/schematics/ng-add/index.spec.ts, modules/data/spec/utils/default-pluralizer.spec.ts, modules/effects/schematics/ng-add/index.spec.ts, modules/entity/schematics/ng-add/index.spec.ts, modules/router-store/schematics/ng-add/index.spec.ts, modules/schematics-core/BUILD.bazel, modules/schematics-core/testing/create-workspace.ts, modules/schematics/src/action/index.spec.ts, modules/schematics/src/cli.spec.ts, modules/schematics/src/container/index.spec.ts, modules/schematics/src/effect/index.spec.ts, modules/schematics/src/entity/index.spec.ts, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/ng-add/index.spec.ts, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/store/index.spec.ts, modules/store-devtools/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.spec.ts, package.json, projects/ngrx.io/content/guide/migration/v8.md, projects/ngrx.io/package.json, projects/ngrx.io/tools/examples/shared/package.json, projects/ngrx.io/tools/examples/shared/yarn.lock, projects/ngrx.io/yarn.lock, tools/defaults.bzl, tools/package.json, yarn.lock
```
[ ] Bugfix
[x] Feature
```
Closes #1788
```
[ ] Yes
[x] No
```
=> Build  update typescript to 3.4.x and rx js to 6.5.x

projects/ngrx.io/content/guide/effects/index.md
Add missing imports for `catchError` and `MoviesService` in `projects/ngrx.io/content/guide/effects/index.md`
Fixes #1861 
```
[ ] Bugfix
[ ] Feature
```
Closes #1861
```
[ ] Yes
[x] No
```
=> docs(effects): update example in Effects Module

modules/store/spec/runtime_checks.spec.ts, modules/store/spec/state.spec.ts, modules/store/src/state.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1865
```
[ ] Yes
[x] No
```
This commit partially reverts commit 60633b770e27f6d984abc91a802df5ea9902d80a
These changes were made in context to test runtime checks. @alex-okrushko pointed out that this change broke some of the google tests. This PR reverts the store subscription and rewrites the runtime checks.
cc @alex-okrushko
=> revert(Store): store should fail synchronously

modules/store/spec/BUILD, modules/store/spec/fixtures/BUILD, modules/store/spec/store.spec.ts, modules/store/testing/spec/BUILD, modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/mock_store.ts
- [c] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
```
[x] Bugfix
[ ] Feature
```
Mock store doesn't handle selectors with props
Closes # https://github.com/ngrx/platform/issues/1864
Fixed it
```
[ ] Yes
[x] No
```
Refactored Mock Store tests out of store/spec
Added Bazel for it
Moved store/spec/fixtures into its own Bazel module
Added a number of tests for Mock Store
Added clean-up logic for Mock Store …
=> fix(store): adjust mock store to handle selectors with props

modules/store/src/selector.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1849
```
[x] Yes
[ ] No
```
The return type of the createSelectorFactory function is now a MemoizedSelector instead of a Selector
=> fix: createSelectorFactory should return a MemoizedSelector

modules/effects/spec/effect_creator.spec.ts, modules/effects/spec/effect_decorator.spec.ts, modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/effects_metadata.spec.ts, modules/effects/src/effect_creator.ts, modules/effects/src/effect_decorator.ts, modules/effects/src/effect_notification.ts, modules/effects/src/effect_sources.ts, modules/effects/src/effects_metadata.ts, modules/effects/src/effects_resolver.ts, modules/effects/src/models.ts, projects/ngrx.io/content/guide/effects/lifecycle.md, projects/ngrx.io/content/guide/effects/testing.md, projects/ngrx.io/content/guide/migration/v8.md
```
[ ] Bugfix
[x] Feature
```
When Errors happen in the main Actions stream that error is reported and the stream is closed
Closes # https://github.com/ngrx/platform/issues/1851
For `{dispatch: true}`, which is the default Effect option, if the error occurs in the main actions stream, the effect will be resubscribed. This could result in unusual behavior (in cases where operators like `startWith` are used).
Resubscriptions can be turned off by setting …
=> feat(effects): resubscribe to effects on error

modules/store/src/selector.ts
- supply a default projector type to MemoizedSelector
```
[ ] Bugfix
[ ] Feature
```
Currently selectors projector functions are typed as 'any'
Closes #
#1908 
`MemoizedSelector` extended to have a third parameter that has a default projector function that utilizes `Result` as type.
```
[ ] Yes
[x] No
```
=> refactor(selectors): Capture the type of a selectors projector

modules/store/spec/action_creator.spec.ts, modules/store/src/action_creator.ts, modules/store/src/models.ts
```
[ ] Bugfix
[x] Feature
```
actions creators could use `type` property, even thought it would be overridden.
```ts
export const a = createAction('my action', props<{type: string}>());
```
Closes https://github.com/ngrx/platform/issues/1917
Such usage will produce the error:
- with creator function
```
Type '{ type: string; }' is not assignable to type '"type property is not allowed in action creators"
```
- with `props`
```
Argument of type '"type property is not …
```
=> feat(store): add protection from type property use

projects/ngrx.io/content/guide/entity/adapter.md, projects/ngrx.io/content/guide/entity/recipes/additional-state-properties.md, projects/ngrx.io/content/guide/store/reducers.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #1762 
```
[ ] Yes
[x] No
```
=> docs: add exported reducer function to createReducer examples

modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
Generating an effect with the old template lead to TSLint warnings due to unnecessary whitespace
```
[x] Bugfix
[ ] Feature
```
Generated effects TS files have two whitespaces after the constructor brackets with `--creators`. This makes TSLint trigger the `no-trailing-whitespace` rule.
Removed the whitespace
```
[ ] Yes
[x] No
```
=> style(schematics): remove whitespace from effects template

projects/ngrx.io/content/guide/entity/adapter.md, projects/ngrx.io/content/guide/entity/recipes/additional-state-properties.md, projects/ngrx.io/content/guide/store/reducers.md
```
[ ] Bugfix
[ ] Feature
```
The current exported reducer function documentation has a typo. It uses a colon to separate the `state` and `action` arguments instead of a comma.
Typo has been fixed.
```
[ ] Yes
[x] No
```
=> docs: fix typo in exported reducer function examples

projects/ngrx.io/content/guide/data/entity-metadata.md
- [ X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ X] Documentation has been added / updated (for bug fixes / features)
only doc
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
Closes #1930
```
[ ] Yes
[X ] No
```
=> docs: fix module import (#1930)

projects/ngrx.io/content/guide/data/entity-metadata.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Add documentation about how to customize a EntityCollection level property. Such as in my use case, I want to add `paging information` in `EntityCollection level`, but current `document` can only add an additional property in `initialization`, there is no document about who to get the property from backend.
=> docs(data): add document about how customize a entityCollection level property of ngrx-data

projects/ngrx.io/src/index.html, projects/ngrx.io/src/styles/0-base/_typography.scss, projects/ngrx.io/src/styles/_constants.scss
added 
```
[ ] Bugfix
[ ] Feature
```
markdown `**` bold feature generates into `<strong></strong>` element, which set the font weights of the content between to "500".
currently, the docs are missing roboto's 500 weight so the bold content doesn't look bold.
content wrapped by `**` looks bolder.
=> docs: add roboto font weights to support md's bold

modules/store/src/meta-reducers/immutability_reducer.ts
IE errors when attempting to access the `caller` property of a function,
so rearrange the freeze function to check for this first.
Fixes #1991
This shouldn't change the logic, so I think it should be covered by the existing tests?
```
[x] Bugfix
```
If a store state object contains a function, the immutability check's freeze function will fail in IE. This is a known issue that [also affected ngrx-store-freeze for a while](https://github.com/brandonroberts/ngrx-store-freeze/issues/7) and necessitated switching to [deep-freeze-strict](https://www.npmjs.com/package/deep-freeze-strict) 
It looks like whoever wrote the freeze function referenced deep-freeze-strict's code but perhaps didn't realise why the check for certain properties …
=> fix(store): immutability check IE compatibility

modules/effects/src/effect_creator.ts, modules/effects/src/index.ts, modules/effects/src/models.ts, modules/store/src/action_creator.ts, modules/store/src/models.ts, modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1977, #1956
- Creates basic API documentation for Creator Functions.
- Does not attempt to provide the level of context that the main documentation provides.
- Provides simple usage examples.
- Provides implementation details.
```
[ ] Yes
[x] No
```
=> docs: API level documentation for Creator Functions

modules/data/src/actions/entity-cache-change-set.ts
```
[x] Bugfix
[ ] Feature
```
`ChangeSetItemFactory.update` only allows for entities with `string` type IDs
Closes #1988 
`ChangeSetItemFactory.update` allows for entities with `string` or `number` type IDs, to match with `Update<T>`
```
[ ] Yes
[x] No
```
=> fix(data): allow ChangeSetItemFactory to update entities with number ids

projects/ngrx.io/content/guide/store/recipes/injecting.md
Current documentation for store/recipes/injecting.md for META_REDUCERS injection token is incomplete. While attempting to add a meta reducer from a library I am implementing, the question arose about whether the use of `multi: true` was appropriate when using the META_REDUCERS token. 
Current documentation, as well as current third party library implementations, do NOT make use of `multi` at all. Lack of use of `multi: true` presents a problem when multiple third-party @ngrx libraries are used simultaneously, as it would most likely be "last in wins" for whichever META_REDUCER was actually added to the set of meta reducers applied during runtime. 
After verification with Wes Grimes and …
=> docs: update store recipes to clarify proper use of META_REDUCER token in libs

modules/store/src/index.ts
These were missing from `modules/store/src/index.ts`.
Closes ngrx/platform#2007
```
[x] Bugfix
[ ] Feature
```
`@ngrx/store` does not export the `StoreConfig` and `RootStoreConfig` interfaces from `modules/store/src.index.ts`, which it should per the NgRx guide.
Closes #2007
`@ngrx/store` now exports the `StoreConfig` and `RootStoreConfig` modules per [Using Dependency Injection -> Injecting Feature Config](https://ngrx.io/guide/store/recipes/injecting#injecting-feature …
=> fix(store): add missing StoreConfig and RootStoreConfig exports

modules/store/spec/runtime_checks.spec.ts, modules/store/src/index.ts, modules/store/src/runtime_checks.ts, modules/store/src/tokens.ts
```
[ ] Bugfix
[x] Feature
```
Only way to provide runtime checks is via `store.forRoot()`
Closes #1973 
Make it possible to define runtime checks via an injection token:
```
providers: [
{
provide: USER_RUNTIME_CHECKS,
useValue: {
strictStateImmutability: true,
strictActionImmutability: true,
strictStateSerializability: true,
strictActionSerializability: true,
},
},
],
```
```
[ ] Yes
[x] No
```
=> feat(store): add USER_RUNTIME_CHECKS public token

projects/ngrx.io/content/guide/effects/index.md, projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Part of #1383
```
[ ] Yes
[x] No
```
=> docs(effects): rewrite testing

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/models.ts, modules/router-store/src/router_selectors.ts, projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[x] Feature
```
NgRx 8 gave us frequently used router selectors, `selectQueryParams` and `selectRouteParams` were two of these. Often a specific param is needed instead of all the params provided, and this selector has to be created manually:
```
export const selectRouteId = createSelector(
selectRouteParams,
params => params && params['id']
);
``` 
Closes #
This PR adds `selectQueryParam` and `selectRouteParam`, to create a selector to retrieve a …
=> feat(router-store): add selectQueryParam and selectRouteParam

modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Currently, createReducer requires that entities be of the Action type, but we have a use case that requires custom action types.
This just makes createReducer generic, allowing for other types to be passed in.
```
[ ] Yes
[X] No
```
=> refactor(store): give createReducer generic action

projects/ngrx.io/src/app/app.component.html, projects/ngrx.io/src/app/app.component.spec.ts, projects/ngrx.io/src/app/layout/top-menu/top-menu.component.ts, projects/ngrx.io/src/styles/1-layouts/_top-menu.scss
```
[ ] Bugfix
[x] Feature
```
Closes #1860
Re-enable search box on website
```
[ ] Yes
[x] No
```
=> feat(docs): enable search functionality

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effects_resolver.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2023
The effects will resubscribe every time an error occurs in the stream.
```
[ ] Yes
[x] No
```
=> fix(effects): resubscribe every time and error occurs (#2023)

modules/schematics/BUILD, modules/schematics/src/container/files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/index.ts, modules/schematics/src/container/integration-files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, modules/schematics/src/container/schema.json, modules/schematics/src/container/schema.ts, projects/ngrx.io/content/guide/schematics/container.md
```
[ ] Bugfix
[x] Feature
```
- Container schematic uses StoreModule for unit tests
Closes #2028
- Container schematic uses MockStore for unit tests
- `testDepth` option to use StoreModule for integration tests instead.
```
[ ] Yes
[x] No
```
=> Schematics: Use MockStore in container generated tests

modules/data/src/dataservices/default-data-service-config.ts, projects/ngrx.io/content/guide/data/entity-dataservice.md
add more details for the DefaultDataServiceConfig api docs and Entity Dataservice
doc page.  specifically, added details and examples for providing a remote api to
the DefaultDataServiceConfig root parameter.  Current docs do not include this
information, and it this makes it clear how one would use a remote api, which is
a very common use case.
Closes #2071
```
[ ] Bugfix
[ ] Feature
```
No indication in the docs on how to set a remote API url.  The way the root …
=> docs(data): improve DefaultDataServiceConfig root parameter docs

modules/store/migrations/8_0_0-beta/index.spec.ts, modules/store/migrations/8_0_0-beta/index.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2093
```
[ ] Yes
[x] No
```
=> fix(store): should not run schematics when not using named imports

projects/ngrx.io/content/guide/store/recipes/injecting.md
docs(store): factory function has to return a reducer instead of an array
Closes #2094
```
[ ] Bugfix
[ ] Feature
```
Closes #2094
```
[ ] Yes
[x] No
```
=> docs(store): factory function has to return a reducer

modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.spec.ts.template, modules/schematics/src/action/index.spec.ts
- [N/A] Documentation has been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
when you use the action schematic to generate an action unit test without creators, you get a failing unit test because of the wrong imports.
Closes #2082
Modified the spec template to properly import the actions and also uses the correct class template inside the test suites
```
[ ] Yes
[x] No
```
=> fix(schematics): fixed the schematics/action spec template

projects/ngrx.io/content/guide/store/selectors.md
The selectLastStateTransitions example should use the count parameter.
closes #2102
```
[ ] Bugfix
[ ] Feature
```
The advanced selector example doesn't use the count parameter as explained in #2102 
Closes #2102 
```
[ ] Yes
[x] No
```
=> docs(store): update advanced selector example

projects/ngrx.io/content/examples/testing-store/src/app/auth-guard.service.spec.ts, projects/ngrx.io/content/guide/store/testing.md
- [n/a] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #2044
Show a workaround to prevent cross-test state bleeding using `afterAll` + `resetSelectors`.
```
[ ] Yes
[x] No
```
=> docs(store): add note to use resetSelectors to prevent cross-test state bleeding

projects/ngrx.io/content/guide/data/entity-metadata.md
the string "guide/data" was prefixed to the entities parameter contained within the example code likely due to a search and replace in the documentation.
```
[ ] Bugfix
[ ] Feature
```
irrelvant/misleading text within code example  
Closes #
corrrection of function parameter in example
```
[ ] Yes
[ x] No
```
=> docs: cleanup code sample

projects/ngrx.io/content/examples/testing-store/src/app/auth-guard.service.spec.ts, projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Follow up to #2115 
```
[ ] Yes
[x] No
```
=> docs(store): change alert to mention auto cleanup

modules/store/spec/reducer_creator.spec.ts, modules/store/src/reducer_creator.ts
createReducer should allow ons to take actions of same type and excute all ons to match the action dispatched
```
[x] Bugfix
[ ] Feature
```
If the following is configured and initial state is 0, if `increase` action is dispatched, the next state is 2, because the the second `on` has same action type as the first `on`, and the first `on` is overwritten.
```
const increase = createAction('[COUNTER] INCREASE');
createReducer(0, on(increase, state = state + 1), …
```
=> fix/feat(store): createReducer: on should not be overwritten

modules/store/testing/spec/BUILD, modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/mock_store.ts, modules/store/testing/src/testing.ts
The MockStore.refreshState() method emits a clone of the existing
state on the state observable, that will cause the selectors to recompute.
This enables multiple calls of setResult for mocked selectors during testing.
Also fixes a bug with store.select not refreshing mocked selectors
Closes #2121
```
[x] Bugfix
[x] Feature
```
Closes #2121 
```
[ ] Yes
[x] No
```
=> feat(store): add refreshState method to mock store

modules/data/spec/entity-data.module.spec.ts, modules/data/src/effects/entity-cache-effects.ts, modules/data/src/effects/entity-effects.ts, modules/data/src/entity-data.module.ts
```
[ ] Bugfix
[ ] Feature
```
Using `createEffect` instead of `@Effect` in the source code of `@ngrx/data`.
```
[ ] Yes
[x] No
```
=> refactor(data): use createEffect function instead of decorator

modules/data/schematics-core/utility/ast-utils.ts, modules/data/schematics-core/utility/change.ts, modules/effects/schematics-core/utility/ast-utils.ts, modules/effects/schematics-core/utility/change.ts, modules/entity/schematics-core/utility/ast-utils.ts, modules/entity/schematics-core/utility/change.ts, modules/router-store/schematics-core/utility/ast-utils.ts, modules/router-store/schematics-core/utility/change.ts, modules/schematics-core/utility/ast-utils.ts, modules/schematics-core/utility/change.ts, modules/schematics/BUILD, modules/schematics/collection.json, modules/schematics/schematics-core/utility/ast-utils.ts, modules/schematics/schematics-core/utility/change.ts, modules/schematics/src/create-effect-migration/index.spec.ts, modules/schematics/src/create-effect-migration/index.ts, modules/schematics/src/create-effect-migration/schema.json, modules/schematics/src/create-effect-migration/schema.ts, modules/store-devtools/schematics-core/utility/ast-utils.ts, modules/store-devtools/schematics-core/utility/change.ts, modules/store/schematics-core/utility/ast-utils.ts, modules/store/schematics-core/utility/change.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
This PR adds a new schematic `create-effect-migration` to migrate from the `@Effect()` decorator to the `createEffect()` function.
```
[ ] Yes
[x] No
```
=> feat(schematics): add createEffect migration

docs/schematics/effect.md, projects/ngrx.io/content/guide/schematics/effect.md
Correct typo reported by @timdeschryver
Issue #2161
```
[ ] Bugfix
[ ] Feature
```
Docs say 'Generate a spec file alongside the action file.'
Closes #
#2161 
Docs say 'Generate a spec file alongside the effect file.'
```
[ ] Yes
[x] No
```
=> docs(schematics): typo, action should be effect

modules/store/spec/action_creator.spec.ts, modules/store/src/action_creator.ts, modules/store/src/models.ts
I think it is debatable whether this is a bugfix or a feature.
```
[-] Bugfix
[-] Feature
```
I noticed that the new `createAction()` function has a clever type definition which prevents it from being used with a props object shaped like this `{ type: any }`.  Since an array is also an object in JavaScript it can still be used like this:
```typescript
const myAction = createAction('MY_ACTION_TYPE', (x: string) => [ x ]);
const myOtherAction = …
```
=> Fix disallow arrays in action creators

modules/effects/spec/effect_sources.spec.ts, modules/effects/src/effects_resolver.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Seems like with the original PR we forgot to modify the spec for the usage with `createEffect`. This PR uses the same implementation as the original PR.
History:
- #2026 - original PR with the fix
- #2037  - revert caused by inconsistant CI
=> fix(effects): resubscribe every time an error occurs

modules/data/spec/selectors/entity-selectors$.spec.ts, modules/router-store/src/router_store_module.ts, modules/store/spec/action_creator.spec.ts, modules/store/spec/reducer_creator.spec.ts, modules/store/spec/types/action_creator.spec.ts, modules/store/spec/types/reducer_creator.spec.ts, modules/store/spec/types/select.spec.ts, modules/store/spec/types/utils.ts, modules/store/src/store.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
The string selectors don't have the correct types:
- Does not infer correctly, it will always(?) infer to `any`
```
books = this.store.select('books')
```
- Are not type safe
```
books = this.store.select('books', 'notExistingState')
```
The new behavior will  infer correctly and will throw errors if the state property is missing.
```
[ ] Yes
[x] No
```
Similar PRs:
- https://github.com/ngrx/platform/pull/2170
- …
=> fix(store): improve types for string selectors

modules/effects/spec/effect_creator.spec.ts, modules/effects/spec/types/effect_creator.spec.ts, modules/effects/spec/types/of_type.spec.ts, modules/effects/spec/types/utils.ts, modules/effects/src/actions.ts
```
[ ] Bugfix
[x] Feature
```
Today, I had the case where I needed to support more than 5 actions inside an effect, but the types only allow up to 5 actions.
I'm proposing a change where we could support an unrestricted amount of actions.
```
[ ] Yes
[x] No
```
/cc @alex-okrushko
=> feat(effects): improve types for ofType with action creators

modules/store/spec/utils.spec.ts, package.json
- Bump up the node version
- refactor the test that was funky (dealing with floating point calculations) and was failing with new node. Switch to test the compose fn instead of how JS deals with floating points.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build: push node version up and refactor test

modules/data/schematics/ng-add/files/entity-metadata.ts.template, modules/data/schematics/ng-add/index.spec.ts, modules/data/schematics/ng-add/index.ts, modules/data/schematics/ng-add/schema.json, modules/data/schematics/ng-add/schema.ts, projects/ngrx.io/content/guide/data/install.md
```
[ ] Bugfix
[x] Feature
```
On ng-add @ngrx/data we do not create the entity-config file
Closes #
Create and declare entity-config file to AppModule.
```
[ ] Yes
[x] No
```
=> feat(data): add entity config in App module declaration

modules/effects/src/effect_creator.ts, modules/effects/src/effect_decorator.ts, modules/effects/src/effect_notification.ts, modules/effects/src/effects_metadata.ts, modules/effects/src/models.ts
TS 3.5 becomes stricter with type, and generic `T` doesn't have `constructor` or `hasOwnProperty` methods.
for example, see https://github.com/microsoft/TypeScript/issues/31380
```
[ ] Bugfix
[ ] Feature
```
Closes #
Fix issues that would come up with TS 3.5 upgrade
```
[ ] Yes
[x] No
```
=> refactor(effects): prepare for TS 3.5

modules/effects/spec/effect_creator.spec.ts, modules/effects/src/effect_creator.ts, modules/effects/src/effect_decorator.ts, modules/effects/src/models.ts
PR is based off https://github.com/ngrx/platform/pull/2190
- Cleanup types within effects (remove `any`)
- expose `[CREATE_EFFECT_METADATA_KEY]` key on the `createEffect` and clean up the tests.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor(effects): Refactor types in effects, expose metadata key

modules/schematics/src/action/schema.json, modules/schematics/src/container/schema.json, modules/schematics/src/effect/schema.json, modules/schematics/src/entity/schema.json, modules/schematics/src/feature/schema.json, modules/schematics/src/reducer/schema.json, modules/schematics/src/store/schema.json
```
[ ] Bugfix
[x] Feature
```
Devs need to remember the command or look in the docs to know how to use the schematics.
This PR adds an `x-prompt` for the required fields, or for the fields that I think can benefit from having an `x-prompt`
```
[ ] Yes
[x] No
```
To be honest, I always forget the flags I have to pass to use the schematics.
I'm open for suggestions, if the message should be modified, or if a message needs to be added or removed.
We could also do the …
=> feat(schematics): add x-prompt messages

modules/store/spec/fixtures/todos.ts, modules/store/spec/integration.spec.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2184
```
[ ] Yes
[x] No
```
=> test(store): fix flaky integration test

modules/effects/spec/types/effect_creator.spec.ts, modules/effects/src/effect_creator.ts, modules/effects/src/models.ts
based of https://github.com/ngrx/platform/pull/2194
`createEffect` with `{dispatch: false}` now returns whatever Observable type is actually returned (instead of `unknown`).
```
[ ] Bugfix
[x] Feature
```
`createEffect` with `{dispatch: false}` returns  `Observable<unknown>`.
`createEffect` with `{dispatch: false}` returns  `Observable<SpecificType>`.
```
[x] Yes
[ ] No
```
Somewhat. If anyone was relying that `Observable<unknown>` is returned. However, …
=> feat(effects): createEffect returns specific type for dispatch false

modules/effects/src/effect_sources.ts, modules/effects/src/lifecycle_hooks.ts
```
[ ] Bugfix
[ ] Feature
```
JetBrains WebStorm can not recognize that `ngrxOnRunEffects` is implements `OnRunEffects`
JetBrains WebStorm can recognize that `ngrxOnRunEffects` is implements `OnRunEffects`
```
[ ] Yes
[x] No
```
=> refactor(effects): inline ngrxOnRunEffects type

projects/ngrx.io/content/guide/store/reducers.md
Code change related to this issue: https://github.com/ngrx/platform/issues/2233
```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngrx/platform/issues/2233
import { createAction } from '@ngrx/store';
Closes #2233
import { createAction, props } from '@ngrx/store';
```
[ ] Yes
[x] No
```
=> Fixed example in reducers.md

modules/store/testing/src/mock_reducer_manager.ts
```
[x] Bugfix
[ ] Feature
```
It is currently not possible to use _provideMockStore_ if the component has a dependency to a module which uses forFeature imports.
```
StoreModule.forFeature('feature', FeatureReducer),
EffectsModule.forFeature([FeatureEffects]),
```
Currently crashes with:
`
TypeError: reducerManager.addFeatures is not a function
`
Closes #2263
Added noop for _addFeature_.
```
[ ] Yes
[x] No
```
=> fix(store): added noop for addFeature in MockReducerManager

tools/defaults.bzl
Previously UMD globals Ids were incorrect example
`@ngrx/store` should be `ngrx.store`
Before
```js
(function (global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('tslib'), require('@angular/core'), require('rxjs'), require('@ngrx/store')) :
typeof define === 'function' && define.amd ? define('@ngrx/store/testing', ['exports', 'tslib', '@angular/core', 'rxjs', '@ngrx/store'], factory) :
(global = global || self, factory((global.ngrx = global.ngrx || {}, global.ngrx.store = global.ngrx.store || {}, global.ngrx.store.testing = {}), global.tslib, global.ng.core, global.rxjs, global['@ngrx/store']));
```
After
```js
(function (global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, …
```
=> build: fix ngrx global ids

modules/data/src/actions/merge-strategy.ts, modules/data/src/dispatchers/entity-commands.ts, modules/data/src/entity-services/entity-collection-service-base.ts, projects/ngrx.io/content/guide/data/architecture-overview.md, projects/ngrx.io/content/guide/data/entity-actions.md, projects/ngrx.io/content/guide/data/entity-change-tracker.md, projects/ngrx.io/content/guide/data/extension-points.md
closes issue #2288
Also
- fix similar documentation error for optimistic/pessimistic
- add/correct code comments in EntityCommands and EntityCollectionServiceBase
- extends `EntityCollectionService` methods to accept optional EntityActionOptions and pass through to dispatch methods (omission was oversight)
```
[x] Bugfix (trivial)
[ ] Feature
```
See #2288 
Closes #2288
Mostly documentation.
Appropriate command methods of `EntityCollectionServiceBase` accept optional …
=> docs(data): correct doc for disabling change tracking (2288)

modules/store/spec/types/store.spec.ts, modules/store/src/models.ts, modules/store/src/store.ts
During the recent merge of NgRx to Google I discovered a number of dispatch calls of new action creators without actual calls, e.g. `store.dispatch(fooAction)` instead of `store.dispatch(fooAction())`.
In NgRx we already added the runtime check, but I think we can do even better and catch it at compile time (IDEs will catch this too).
```
[ ] Bugfix
[x] Feature
```
Errors (warnings) at runtime
Type Error: Functions are not allowed to be dispatched. Did you forget to …
=> feature(store): catch action creators being passed to dispatch without () even sooner

modules/store/src/action_creator.ts, modules/store/src/models.ts
`createAction` returns incorrect type as neither `Creator` not it's return type contains `type`.
The proper return type is `ActionCreator` with the inner typed creator
Closes https://github.com/meeroslav/ng-helpers/issues/2
Could contribute to https://github.com/ngrx/platform/issues/2192 as well.
```
[X] Bugfix
[ ] Feature
```
Using type `ActionCreator` as the input parameter is causing type errors due to the `Creator` type being insufficient. ActionCreator is a …
=> fix(store): replace Creator with ActionCreator on createAction

modules/schematics/src/action/index.spec.ts, modules/schematics/src/action/schema.json, modules/schematics/src/effect/schema.json, modules/schematics/src/entity/schema.json, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/reducer/schema.json, projects/ngrx.io/content/guide/schematics/action.md, projects/ngrx.io/content/guide/schematics/effect.md, projects/ngrx.io/content/guide/schematics/entity.md, projects/ngrx.io/content/guide/schematics/feature.md, projects/ngrx.io/content/guide/schematics/reducer.md
```
[ ] Bugfix
[x] Feature
```
Closes #2210 
```
[x] Yes
[ ] No
```
BEFORE:
The create functions weren't the default to create actions, reducers and effects
AFTER:
The create functions are the default to create actions (`createAction`, reducers (`createReducer`) and effects (`createEffect`)
To fallback to the previous generators, use
```sh
ng generate reducer ReducerName --creators=false
```
=> feat(schematics): update creators to the default

modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts, modules/store/spec/runtime_checks.spec.ts, modules/store/src/runtime_checks.ts
Closes #2217
Store runtime immutability checks are being enabled by default with this change
```
[ ] Bugfix
[x] Feature
```
Currently immutability checks are opt in.
Closes #2217
If state or action is mutated then there will be a run time exception thrown by default now. In order to opt out user will need to pass immutability checks set to false.
```
[x] Yes
[] No
```
BREAKING CHANGE
Before
Immutability checks are opt-in.
After
Immutability checks are enabled by …
=> feat(store): enable immutability checks by default

angular.json, modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/schema.json, modules/schematics/src/container/schema.ts, projects/ngrx.io/angular.json, projects/ngrx.io/content/guide/schematics/container.md, projects/ngrx.io/content/guide/schematics/index.md
Migration from `styleext` to `style`
```
[ ] Bugfix
[ ] Feature
```
When setting the `style` you can do this by `ng set default.styleext`.
Closes #2248 
With these changes, we are inline with the Angular CLI and you need the following command for setting the style `ng set default.style`
```
[ ] Yes
[ ] No
```
=> refactor(schematics): migrate from styleext to style

modules/data/schematics-core/index.ts, modules/data/schematics-core/utility/ast-utils.ts, modules/data/schematics-core/utility/visitors.ts, modules/effects/schematics-core/index.ts, modules/effects/schematics-core/utility/ast-utils.ts, modules/effects/schematics-core/utility/visitors.ts, modules/entity/schematics-core/index.ts, modules/entity/schematics-core/utility/ast-utils.ts, modules/entity/schematics-core/utility/visitors.ts, modules/router-store/migrations/9_0_0/index.spec.ts, modules/router-store/migrations/9_0_0/index.ts, modules/router-store/migrations/migration.json, modules/router-store/schematics-core/index.ts, modules/router-store/schematics-core/utility/ast-utils.ts, modules/router-store/schematics-core/utility/queries.ts, modules/router-store/schematics-core/utility/visitors.ts, modules/schematics-core/index.ts, modules/schematics-core/utility/ast-utils.ts, modules/schematics-core/utility/visitors.ts, modules/schematics/schematics-core/index.ts, modules/schematics/schematics-core/utility/ast-utils.ts, modules/schematics/schematics-core/utility/visitors.ts, modules/store-devtools/schematics-core/index.ts, modules/store-devtools/schematics-core/utility/ast-utils.ts, modules/store-devtools/schematics-core/utility/visitors.ts, modules/store/schematics-core/index.ts, modules/store/schematics-core/utility/ast-utils.ts, modules/store/schematics-core/utility/visitors.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
This migration will add the default router serializer during the `ng update` migration if it isn't explicitly set already.
```
[ ] Yes
[x] No
```
This PR also adds a two utility functions (`visitNgModuleImports` and `containsProperty`)schematics-core.
=> feat(router-store): migration to add the default serializer

modules/store/src/selector.ts, modules/store/testing/src/mock_store.ts
```
[ ] Bugfix
[x] Feature
```
Calling `mockSelector.setValue(undefined)`, does a reset the mocked selector. 
Closes #2244
Calling `mockSelector.setValue(undefined)`, sets the result to `undefined`.
To reset a mock selector, use `mockSelector.clearResult()`. 
```
[x] Yes
[ ] No
```
```
BEFORE:
Using `mockSelector.setResult(undefined)` resulted in clearing the
return value.
AFTER:
Using `mockSelector.setResult(undefined)` will set the return value of …
```
=> feat(store): add clearResult to reset a mock selector

modules/store/spec/action_creator.spec.ts, modules/store/src/action_creator.ts, modules/store/src/models.ts
Instead of modifying the type of the `Creator`, it appears to be better to add intersection `& NotAllowedCheck` where it used.
```
[x] Bugfix
[ ] Feature
```
```typescript
interface A {
sameProp: 'A';
}
interface B {
sameProp: 'B';
extraProp: string;
}
type U = A | B;
const foo = createAction('FOO', props<U>()); // <--- Error
```
Closes #2300 
Allows to take `props<U>()` where `U = A | B`.
```
[ ] Yes
[x] No
```
=> fix(store): allow union of types in props

modules/store/spec/types/action_creator.spec.ts, modules/store/spec/types/utils.ts, modules/store/src/action_creator.ts
```
[x] Bugfix
[ ] Feature
```
The last commit broke the build, this PR fixes the build.
```
[ ] Yes
[x] No
```
=> fix(store): add not allowed check to action creator config

projects/ngrx.io/content/examples/testing-store/src/app/user-greeting.component.spec.ts, projects/ngrx.io/content/guide/effects/testing.md, projects/ngrx.io/content/guide/migration/v4.md, projects/ngrx.io/content/guide/store/testing.md
angular 9 compatibillity changes for TestBed
Closes #2240
```
[ ] Bugfix
[ ] Feature
[x] Testing compatibility changes for angular 9
```
Closes #
```
[ ] Yes
[ ] No
```
=> test(component): update usage of TestBed.get to TestBed.inject

modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/integration.spec.ts, modules/effects/src/effect_sources.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2106
See the breaking change section below
```
[x] Yes
[ ] No
```
BREAKING CHANGE
Before
When the effect class was registered, the init action would be dispatched.
If the effect was provided in multiple lazy loaded modules, the init action would be dispatched for every module.
After
The init action is only dispatched once
The init action is now dispatched based on the identifier of the effect (via ngrxOnIdentifyEffects)
=> fix(effects): dispatch init action once

projects/ngrx.io/content/guide/data/entity-reducer.md
This change of the function name `EntityCollectionReducerRegistry.registerReducer()` to `EntityCollectionReducerRegistry.registerReducers(reducerMap)` in the documentation would be in line with the correct function name in the `EntityCollectionReducerRegistry` class responsible for registering several custom reducers.
```
[ ] Bugfix
[ ] Feature
```
Currently the documentation reads as follows, "You can register several custom reducers at the same time by calling …
=> docs(data): change registerReducer to registerReducers

projects/example-app/src/app/auth/reducers/index.ts, projects/example-app/src/app/books/reducers/index.ts, projects/example-app/src/app/reducers/index.ts
Consistently use feature keys exported from reducer file, e.g. where selectors for underlying state are being created.
```
[ ] Bugfix
[ ] Feature
```
Both feature keys and hard-corded values are used.
Declared feature keys are being used in all places where they should be referenced which scope potential name changes to one place.
```
[ ] Yes
[x] No
```
=> refactor(example): use featureKey for layout selector

modules/data/src/selectors/entity-selectors$.ts
#2324 Allowing random selectors so selectors created based on entity metadata's additionalCollectionState can be accessed without casting to `any`.
=> fix(data): allow additional selectors in entitySelectors$

modules/effects/migrations/9_0_0/index.spec.ts, modules/effects/migrations/9_0_0/index.ts, modules/effects/migrations/BUILD, modules/effects/migrations/migration.json
<strike>- [ ] Documentation has been added / updated (for bug fixes / features)</strike>
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Migration schematic to migrate breaking change introduced in effects.
```
https://github.com/ngrx/platform/pull/2295 introduces a breaking change, this PR adds a migration to ease the transition to ngrx@9 for developers.
Closes #
On upgrade to ngrx 9 developers can run the migration to automatically fix the renamed configuration variable
```
[ ] Yes
[x] …
```
=> Schematic for customisable error handling migration

modules/router-store/spec/router_store_module.spec.ts, modules/router-store/src/router_store_module.ts, projects/example-app/src/app/app.module.ts, projects/ngrx.io/content/guide/router-store/configuration.md, projects/ngrx.io/content/guide/router-store/index.md
```
[ ] Bugfix
[x] Feature
```
If no router state serializer is provided through the configuration of router store, the DefaultRouterStateSerializer is used.
Closes #2225
If no router state serializer is provided through the configuration of router store, the MinimalRouterStateSerializer is used.
```
[x] Yes
[ ] No
```
The default option for `rooterState` in `StoreRouterConnectingModule` is changing. If still need to support `DefaultRouterStateSerializer` will need to …
=> feat(router): enabling MinimalRouterStateSerializer by default

modules/store/src/store.ts, modules/store/testing/src/mock_store.ts, projects/ngrx.io/content/guide/store/selectors.md
A common pattern has emerged in NgRx usage where types are no longer being provided to the Store injection point, and as such, most code is just getting an empty object `{}` for the generic. The type safety is nominal as we are already using Selectors and suggesting that selectors are the preferred way to select information from the store. Selectors themselves have types, so it is nice to be able to use the Store without providing redundant, and often unused typing.
Adding a default to the `Store` and `MockStore` class generics, so that `Store` and `MockStore` can be injected without the need for providing a type. 
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local …
```
=> feat(store): add default generic type to Store and MockStore

docs/entity/adapter.md, modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/state_selectors.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts, modules/schematics/src/entity/creator-files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template, modules/schematics/src/entity/files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template
```
[ ] Bugfix
[x] Feature
```
Currently `addAll` removes all existing entities and then add all, which is very confusing and bug-prone.
Closes #2330
Deprecated `addAll` and added an identical `setAll`
```
[ ] Yes
[x] No
```
=> feat(Entity) Deprecate addAll and rename it to setAll

.bazelrc
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Must have happened during the Bazel upgrade, but the 0.0.0-PLACEHOLDER was no longer being replaced correctly.
=> build: fix version stamping after Bazel build

projects/ngrx.io/content/guide/effects/lifecycle.md
<strike>- [ ] Tests for the changes have been added (for bug fixes / features)</strike>
<strike>- [ ] Documentation has been added / updated (for bug fixes / features)</strike>
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
It might be worth considering automating the embedding of code samples so this kind of thing is automatically caught in future.
One option I'd recommend <sup>Disclaimer I maintain this</sup> is [embedme](https://github.com/zakhenry/embedme) …
=> docs(effects): tidy examples in effects lifecycle guide

modules/data/spec/reducers/entity-change-tracker-base.spec.ts, modules/data/src/reducers/entity-change-tracker-base.ts
Fixes #2346
- [ x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ x ] Bugfix
[ ] Feature
```
UNDO_ONE and UNDO_MANY actions reverts one/many entities back to their original state but changeState keeps the tracking the entity/entities.
Closes #2346
UNDO_ONE and UNDO_MANY actions remove the entity/entities from changeState as …
=> fix(data): make undoMany remove tracking changes in changeState (#2346)

modules/store/spec/meta-reducers/inNgZoneAssert_reducer.spec.ts, modules/store/spec/meta-reducers/serialization_reducer.spec.ts, modules/store/spec/runtime_checks.spec.ts, modules/store/src/meta-reducers/inNgZoneAssert_reducer.ts, modules/store/src/meta-reducers/index.ts, modules/store/src/meta-reducers/serialization_reducer.ts, modules/store/src/meta-reducers/utils.ts, modules/store/src/models.ts, modules/store/src/runtime_checks.ts, projects/example-app/src/app/app.module.ts, projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
```
[ ] Bugfix
[X] Feature
```
Currently there is no alert if an Action is running outside of NgZone which can lead to stale views as change detection will not be triggered. Would help prevent issues like 
https://github.com/ngrx/platform/issues/476.
Add a runtime check that asserts dispatched actions are running within NgZone. Will be off by default and activated by the strictActionWithinNgZone flag.
Closes https://github.com/ngrx/platform/issues/2339
An error will be …
=> feat(store): add strictActionWithinNgZone runtime check

modules/effects/spec/effects_error_handler.spec.ts, modules/effects/src/effects_error_handler.ts, modules/effects/src/index.ts, projects/ngrx.io/content/guide/effects/lifecycle.md
Limit the number of retries to 10 by default
Removes infinite loop if the effect is producing errors on every retry
```
[ ] Bugfix
[x] Feature
```
Closes #2303
```
[ ] Yes
[x] No
```
=> feat(effects): limit retries to 10 by default

modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/mock_store.ts
- Add tests that would consistently catch `resetSelectors` in `afterEach`
- Make `selectors` private, instead of static
- cleanup constructor
- remove function overloads for `overrideSelector` - can we typed all at once
```
[ ] Bugfix
[ ] Feature
```
Closes #
`MockStore.selectors` is not longer static or visible. I don't think that's the API that we meant to support to begin with.
```
[x] Yes
[ ] No
```
=> feat(store): testing - clean up mock store a bit

modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/integration.spec.ts, modules/effects/src/effect_sources.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2373
```
[ ] Yes
[x] No
```
The problem wasn't Ivy, but that the action was dispatched before the registration of the effect sources. The action was dispatched, but the effects didn't catch this action because it was dispatched too early.
=> fix(effects): dispatch OnInitEffects action after registration

modules/data/spec/reducers/entity-change-tracker-base.spec.ts, modules/data/src/reducers/entity-change-tracker-base.ts
- [ x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ x ] Bugfix
[ ] Feature
```
Runtime error thrown if performing a QUERY action (with the default preserve changes strategy) after an UPSERT action due to mutably changing state.
```
can't define property "originalValue": Object is not extensible
```
Closes #2374 …
=> fix(data): make mergeServerUpserts change state immutably (#2374)

projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
The link for "You might not need NgRx by Mike Ryan at AngularConnect 2018" is a duplicate of the link to the "NgRx at ng-conf 2018" playlist.
Fix link to point at the correct video
```
[ ] Yes
[x] No
```
=> docs(marketing): Fix duplicated link

projects/ngrx.io/content/guide/data/extension-points.md
```
[ ] Bugfix
[ ] Feature
```
I used the code referenced in the docs which resulted in:
```
ERROR in projects/ngrx-playground/src/app/app.module.ts:68:48 - error NG2005: The class 'PluralHttpUrlGenerator' cannot be created via dependency injection, as it does not have an Angular decorator. This will result in an error at runtime.
Either add the @Injectable() decorator to 'PluralHttpUrlGenerator', or configure a different provider (such as a provider with 'useFactory').
68         { provide: HttpUrlGenerator, useClass: …
```
=> docs(data): add @Injectable to PluralHttpUrlGenerator

modules/data/spec/actions/entity-action-guard.spec.ts
- [ x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe: 
→ added tests
```
Closes #
```
[ ] Yes
[ x ] No
```
=> test(data): add entity action guard tests

projects/example-app/src/app/core/containers/app.component.ts, projects/example-app/src/app/reducers/index.ts
Fix an example-app's typo by replacing selecthowSidenav by selectShowSidenav
It fixes a typo.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: typo for an example-app's selector
```
```
[ ] Yes
[x] No
```
=> fix(example): fix an example-app's typo in app reducers - showSidenav selector

projects/ngrx.io/content/guide/data/entity-services.md
closes #2280
DOCS ONLY
```
[ ] Bugfix
[ ] Feature
```
The incorrect code example referred to NgRx Data as it _used to be a long time ago_. This PR brings the example up to date.
Closes #2280
```
[ ] Yes
[x] No
```
=> docs(ngrx/data): correct AppEntityServices example in ngrx data doc page

modules/effects/src/index.ts
Exposes EffectsRunner in the public API to address #2426
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(effects): expose EffectsRunner in public api

projects/example-app/src/app/books/reducers/collection.reducer.ts
```
[x ] Bugfix
[ ] Feature
```
Closes #2417
Example app optimistically adds/removes book from collection
```
[ ] Yes
[ x ] No
```
=> fix(example): optimistically add/remove book from collection

projects/ngrx.io/content/guide/entity/adapter.md
- [x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
`user.actions.ts`
- Differentiate the `updateOne` and `updateMany` which use the `Update<T>` interface by using props update/updates over user/users
Closes #2431
Add section **Entity Updates** clarifying how entities update under various adapter methods.
Many issues have been raised with regards to this #1604, #2061,  #2369
```
[ ] Yes
[x ] No
```
=> docs(entity): clarify how entities update

projects/ngrx.io/content/guide/component/index.md, projects/ngrx.io/content/guide/component/let.md, projects/ngrx.io/content/guide/component/push.md, projects/ngrx.io/content/marketing/docs.md
Added link to docs intro page. Created content for the components index pag and linked let and push docs.
related to #2441 closes #2442
=> fix(component): add docs overview

projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
When I copied and pasted the documentation sample for router selectors, I noticed some imports were missing. I also believe the `fromRouter.getSelectors` selectors such as `selectRouteParams` should be exported.
Copying and pasting the example now includes the right imports (aside from `selectCarEntities`, which isn't defined in the file). Selectors provided by `fromRouter.getSelectors` are now exported.
```
[ ] Yes
[x] No
```
=> docs(router-store): add missing imports and export route selectors

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
Each PR pulls the bazel cache based on the latest SHA from the master branch on this repo. This should reduce the time for Bazel to build packages in CI that haven't changed, as it will reuse that cache. Each time a PR is merged, a new immutable cache is built based on that SHA.
```
[ ] Yes
[x] No
```
=> ci: use hash of master branch for Bazel cache key

projects/ngrx.io/content/guide/data/extension-points.md
The example code for "Replace the HttpUrlGenerator" has two errors:
1. `pluralizer` is misspelled as `pluralizzer` once
2. `pluralizer` needs to be something else to avoid conflicting with the private `pluralizer` property in the parent.
```
[ ] Bugfix
[ ] Feature
```
Compilation errors in a documentation example
Closes #
Pasting the code into a …
=> docs(data): fix compilation errors in example

docs/entity/adapter.md, projects/ngrx.io/content/guide/entity/adapter.md
It is indicated in the documentation that `addAll` has been deprecated in favor of `setAll`. In the reducer switch/case example, `addAll` was still being used instead of `setAll`.
```
[ ] Bugfix
[ ] Feature
```
Closes #
No behavioral changes as this fix only affects documentation. 
```
[ ] Yes
[x] No
```
=> docs(entity): Call setAll instead of deprecated addAll

modules/effects/schematics/ng-add/files/__name@dasherize@if-flat__/__name@dasherize__.effects.spec.ts.template, modules/effects/schematics/ng-add/index.spec.ts, modules/schematics/src/container/files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, modules/schematics/src/container/index.spec.ts, modules/schematics/src/container/integration-files/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.spec.ts.template, modules/schematics/src/effect/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
The deprecated `TestBed.get` method is used in generated test suites.
Closes #2498
The strongly typed `TestBed.inject` method is used in generated test suites.
```
[ ] Yes
[x] No
```
Cc @timdeschryver
=> refactor(schematics): replace deprecated `TestBed.get`

modules/schematics/src/container/index.ts, modules/schematics/src/container/schema.json, projects/ngrx.io/content/guide/schematics/index.md
```
[x] Bugfix
[ ] Feature
```
Closes [#1036(comment)](https://github.com/ngrx/platform/issues/1036#issuecomment-621728838)
```
[ ] Yes
[x] No
```
By removing the default values in the schema, we can remove the undefined values before we pass them to the Angular component schematic. By doing this, Angular will replace the undefined values with the defaults set in `angular.json`. If no default value is provided in the `angular.json` file, it will use the defaults from …
=> fix(schematics): use Angular default properties when not defined

modules/store/spec/flags.spec.ts, modules/store/spec/selector.spec.ts, modules/store/src/flags.ts, modules/store/src/index.ts, modules/store/src/selector.ts, modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/testing.ts
This code adds an internal setting and a setter for mock store environment.
When set it suppresses the logs about the state which does not exist.
```
[ ] Bugfix
[x] Feature
```
Console warn logs numerous logs for mocked store which should not happen
Closes #2363
Logs will be suppressed
```
[ ] Yes
[x] No
```
This is a copy of https://github.com/ngrx/platform/pull/2420
=> No logs about empty state for tests with mocked store

modules/component-store/spec/BUILD, modules/component-store/spec/component-store.spec.ts, modules/component-store/spec/placeholder.spec.ts, modules/component-store/src/component-store.ts, modules/component-store/src/index.ts, modules/component-store/src/placeholder.ts, package.json, projects/ngrx.io/content/guide/component-store/index.md, yarn.lock
Initial implementation of ComponentStore - adding the initialization and state updates via `setState` and `updater`.
Detailed overview of this PR can be watched here: https://www.youtube.com/watch?v=-hp72aA0wBw
😁
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(component-store): initialization + updater/setState

modules/data/schematics-core/index.ts, modules/data/schematics-core/utility/visitors.ts, modules/effects/schematics-core/index.ts, modules/effects/schematics-core/utility/visitors.ts, modules/entity/schematics-core/index.ts, modules/entity/schematics-core/utility/visitors.ts, modules/router-store/schematics-core/index.ts, modules/router-store/schematics-core/utility/visitors.ts, modules/schematics-core/index.ts, modules/schematics-core/utility/visitors.ts, modules/schematics/collection.json, modules/schematics/schematics-core/index.ts, modules/schematics/schematics-core/utility/visitors.ts, modules/schematics/src/ngrx-push-migration/index.spec.ts, modules/schematics/src/ngrx-push-migration/index.ts, modules/schematics/src/ngrx-push-migration/schema.json, modules/schematics/src/ngrx-push-migration/schema.ts, modules/store-devtools/schematics-core/index.ts, modules/store-devtools/schematics-core/utility/visitors.ts, modules/store/schematics-core/index.ts, modules/store/schematics-core/utility/visitors.ts
```
[ ] Bugfix
[x] Feature
```
Closes the first todo of #2450
This PR adds a `visitTemplates` method to schematics-core to find all templates (inline and as a file).
For the migration, it creates a  new  `ngrx-push-migration` schematic.
```
[ ] Yes
[x] No
```
Implementation is inspired by angular material.
=> feat(components): add ngrxPush migration

modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/effects_error_handler.spec.ts, modules/effects/spec/types/effect_creator.spec.ts, modules/effects/src/effect_creator.ts, modules/store/spec/types/store.spec.ts, modules/store/src/store.ts
In https://github.com/ngrx/platform/pull/2306 we are catching actionCreators that are not called in `store.dispatch(actionCreatorNotCalled)` at compile time, however it was still possible to map to `ActionCreator` in the effects by accident: https://twitter.com/DeborahKurata/status/1263612553067819008
```
[ ] Bugfix
[x] Feature
```
We are catching at runtime, which is nice, but we can do better.
Closes #
Catch `ActionCreators` that are not called at compile time:
```
[ …
```
=> feat(effect): catch action creators being returned in effect without ()

modules/effects/spec/types/utils.ts, modules/router-store/spec/types/utils.ts, modules/store/spec/runtime_checks.spec.ts, modules/store/spec/types/utils.ts, modules/store/src/action_creator.ts, modules/store/src/globals.ts, modules/store/src/models.ts, modules/store/src/runtime_checks.ts, modules/store/src/store_module.ts, modules/store/src/tokens.ts, projects/example-app/src/app/app.module.ts, projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
```
[ ] Bugfix
[x] Feature
```
Currently there is no way to warn devs when there are multiple actions with the same action type.
I've seen that this might lead to some confusion and some debugging time to spot the cause of a bug. 
The most recent one, https://twitter.com/FabianGosebrink/status/1259043401724542978
The ngrx-tslint-rules has a TSLint rule to spot these, but not many people know that this exists.
What if we create a runtime check for it?
In the PR, you see …
=> feat(store): add runtime check for action type uniqueness

LICENSE, modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts, modules/component-store/src/debounceSync.ts
Adding `selector` for `ComponentStore`. Includes `debounceSync` operator from `rxjs-etc` package, which requires a separate LICENSE adjustement.
Video overview of this PR is here: 
https://youtu.be/n2fxNhY8KDQ
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> feat(component-store): selectors

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
Final part of the ComponentStore - effect.
Video review is here: https://youtu.be/phw_QQY5Gd8
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> feat(component-store): add effect

modules/component-store/src/component-store.ts
Export `EffectReturnFn` as well, otherwise we get an error:
```sh
error TS4029: Public property 'effectName' of exported class has or is using name 'EffectReturnFn' from external module "path/to/ngrx/modules/component-store/src/component-store" but cannot be named
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(component-store): export EffectReturnFn interface

modules/data/spec/reducers/entity-cache-reducer.spec.ts, modules/data/src/reducers/entity-cache-reducer.ts
- [ x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Documentation has been added / updated (for bug fixes / features)
```
[ x ] Bugfix
[ ] Feature
```
`mergeQuerySet` accessible via `EntityCacheDispatcher` does not implement the `mergeStrategy` parameter which governs how queried data and changes tracked via `changeState` …
=> fix(data): mergeQuerySet uses mergeStrategy

modules/store/src/state.ts
```
[ ] Bugfix
[ ] Feature
```
Value of type `T|undefined` is passed as the next value of `ScannedActionsSubject`.
Value is asserted to type `T`. See "other information" section for context.
```
[ ] Yes
[x] No
```
In RxJS v7, the type of `Subject.next()` will change from `next(value?: T)` to `next(value: T)` ([change](https://github.com/ReactiveX/rxjs/commit/33561526d2c893fdb2a7c5552a3c86806cb0e9a9#diff-54b18fdea0a03178c258be326d16f566L61)). No runtime behavior is …
=> refactor: assert value for RxJS v7 compatibility

modules/component-store/spec/integration.spec.ts, modules/component-store/src/component-store.ts
Making ComponentStore compatible with ViewEngine. This unfortunately means that we are no longer platform-agnostic.
Also adding integration tests for all kinds of usages that I expect from ComponentStore.
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> feat(component-store): make CS compatible with ViewEngine

projects/ngrx.io/content/guide/component-store/index.md
```
[ ] Bugfix
[ ] Feature
```
No changes in the behaviour, just a tiny doc change. The assignment of the `movie$` observable was made as a type definition `movie$: this.store....`, but should be `movie$ = this.store...`.
The assignment is made as `movie$ = this.store...`
```
[ ] Yes
[x] No
```
=> docs(component-store): fix movies$ observable assignment

modules/data/spec/entity-metadata/entity-definition.spec.ts, modules/entity/src/models.ts
The compare function is used in two places, neither of which expect it to be able to return a string:
The [first caller](https://github.com/ngrx/platform/blob/master/modules/entity/src/sorted_state_adapter.ts#L174) is the [Array prototype sort function](https://www.w3schools.com/js/js_array_sort.asp), and there it "should return a negative, zero, or positive value, depending on the arguments".
The [second caller](https://github.com/ngrx/platform/blob/master/modules/entity/src/sorted_state_adapter.ts#L187) does a numerical comparison with the result.
Even though an id can be a string, the result of a comparison shouldn't be.
This might be a breaking change.
- [x ] The commit message follows our guidelines: …
=> fix(entity): remove ComparerStr

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
When PRs run in CI, the build-affected job is not building direct dependencies of the package. For example, changes to `@ngrx/router-store` should trigger `@ngrx/store` to be built also.  
Closes #
```
[ ] Yes
[x] No
```
=> ci: include all package dependencies when running affected builds

modules/effects/schematics/ng-add/index.ts, modules/effects/schematics/ng-add/schema.json, modules/effects/schematics/ng-add/schema.ts, modules/schematics/src/action/index.ts, modules/schematics/src/action/schema.json, modules/schematics/src/action/schema.ts, modules/schematics/src/container/index.ts, modules/schematics/src/container/schema.json, modules/schematics/src/container/schema.ts, modules/schematics/src/data/index.ts, modules/schematics/src/data/schema.json, modules/schematics/src/data/schema.ts, modules/schematics/src/effect/index.ts, modules/schematics/src/effect/schema.json, modules/schematics/src/effect/schema.ts, modules/schematics/src/entity/index.ts, modules/schematics/src/entity/schema.json, modules/schematics/src/entity/schema.ts, modules/schematics/src/feature/index.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/feature/schema.ts, modules/schematics/src/reducer/index.ts, modules/schematics/src/reducer/schema.json, modules/schematics/src/reducer/schema.ts, modules/schematics/src/selector/index.ts, modules/schematics/src/selector/schema.json, modules/schematics/src/selector/schema.ts, modules/schematics/src/store/schema.json, modules/schematics/src/store/schema.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #2561
```
[x] Yes
[ ] No
```
The skipTest option has been renamed to skipTests
BEFORE:
ng generate container UsersPage --skipTest
AFTER:
ng generate container UsersPage --skipTests
=> schematics: remove skipTest option

modules/component-store/spec/component-store.spec.ts, modules/component-store/spec/integration.spec.ts, modules/component-store/src/component-store.ts
~By removing `debounceSync` from a single-value selector, the selector value now becomes available immediately after the updates.~
~Longer versions:~
- ~updates/setState were always sync~
- ~selectors now fall into two buckets:~
- ~state selectors like `selector(state => state.foo)` are back to being sync~
- ~selectors that combine other selectors and/or Observables are still async, scheduled to run into the microtask.~
Introduce `SelectConfig` configuration for selector. Currently it allows to "debounce" selector values until the state is "settled".
By default it will be set to `debounce: false`, as it makes it more predictable (same behaviour as global store) and allows instant reads …
=> feat(component-store): add config for debounce selectors

modules/component-store/spec/component-store.spec.ts, modules/component-store/spec/integration.spec.ts, modules/component-store/src/component-store.ts
Add ability to read from `ComponentStore` imperatively.
It is set as `protected` to encourage its usage to be limited within a `*Store` that extends `ComponentStore` - and would contain all the business logic needed. Moreover, it's recommended to use `get` only within `effects`.
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> feat(component-store): add imperative reads

.circleci/config.yml, modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/index.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts, projects/ngrx.io/angular.json, projects/ngrx.io/content/guide/entity/adapter.md
PR Checklist
```
[ ] Bugfix
[x] Feature
```
Closes #2538
```
[ ] Yes
[x] No
```
If we agree on the API, I can update the docs.
=> feat(entity): add mapOne

projects/ngrx.io/content/guide/effects/testing.md
defer which is being called under the hood is being upgraded by rxjs and it only emits of the function passed to it returns something. So in order for this to work properly in tests the actions$ observable actually needs to be initialized. Updated documentation to reflect this.
```
[ ] Bugfix
[ ] Feature
```
After [this commit](https://github.com/ReactiveX/rxjs/commit/1ae937a8e594aef96b93313bb3c68ea910e6f528) the behavior of defer is corrected and it no longer allows …
=> docs (Testing): Update usage for provideMockActions

modules/component-store/spec/component-store.spec.ts, modules/component-store/spec/types/component-store.types.spec.ts, modules/component-store/spec/types/utils.ts, modules/component-store/src/component-store.ts
remove `EffectReturnFn` and make the effect type stricter and more predictable.
For example, previously if effect was `const e = effect((o: Observable<string>) => ....)` it was still possible to call `e()` without passing any `string`s.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[x] Yes
[ ] No
```
Some tests needed to be adjusted because we are stricter with types and actually enforce the argument requirement (or enforce not passing one).
=> refactor(component-store): fine-tune effect types

modules/component-store/package.json
I've added the entry point for the schematics in the `package.json` as requested.
```
[x] Bugfix
[ ] Feature
```
When running `ng add @ngrx/component-store` you will see a the error
Closes #2682 
Because we've added the entrypoint we should not see the rror any more.
```
[ ] Yes
[X] No
```
=> fix(component-store): add entry point for schematic

projects/ngrx.io/src/app/custom-elements/api/api-list.component.html, projects/ngrx.io/src/app/layout/footer/footer.component.html, projects/ngrx.io/src/app/layout/nav-item/nav-item.component.html, projects/ngrx.io/src/styles/0-base/_typography.scss, projects/ngrx.io/src/styles/1-layouts/_api-pages.scss, projects/ngrx.io/src/styles/1-layouts/_footer.scss, projects/ngrx.io/src/styles/1-layouts/_homepage.scss, projects/ngrx.io/src/styles/1-layouts/_sidenav.scss, projects/ngrx.io/src/styles/2-modules/_alert.scss, projects/ngrx.io/src/styles/2-modules/_api-list.scss, projects/ngrx.io/src/styles/2-modules/_api-pages.scss, projects/ngrx.io/src/styles/2-modules/_buttons.scss, projects/ngrx.io/src/styles/2-modules/_callout.scss, projects/ngrx.io/src/styles/2-modules/_card.scss, projects/ngrx.io/src/styles/2-modules/_code.scss, projects/ngrx.io/src/styles/2-modules/_details.scss, projects/ngrx.io/src/styles/2-modules/_edit-page-cta.scss, projects/ngrx.io/src/styles/2-modules/_features.scss, projects/ngrx.io/src/styles/2-modules/_label.scss, projects/ngrx.io/src/styles/2-modules/_notification.scss, projects/ngrx.io/src/styles/2-modules/_search-results.scss, projects/ngrx.io/src/styles/2-modules/_select-menu.scss, projects/ngrx.io/src/styles/2-modules/_table.scss, projects/ngrx.io/src/styles/_mixins.scss, projects/ngrx.io/src/styles/_ngrx.scss, projects/ngrx.io/src/styles/main.scss
- increate the default font size from 14 to 16px
- ensure that we have the appropriate `line-height` that accompanies the corresponding `font-size` through mixins
- switch the nav-bar to use flexbox instead of %-based and pixel-adjusted alignments.
```
[ ] Bugfix
[ ] Feature
```
On the LEFT is a new look, on the RIGHT is the current look.
* Home page looks **the same** (except for the footer):
* left Nav items are now **bigger** (the right side mini nav stays the same) …
=> docs: font size, line-height, nav-rework

modules/store/spec/types/action_creator.spec.ts, modules/store/src/models.ts
```
[x] Bugfix
[ ] Feature
```
```typescript
// Case 1
const foo = createAction('foo', props<{}>()); // no error
foo(1); // no error
foo('1'); // no error
// Case 2
const foo = createAction('foo', props<{ bar?: string }>()); // ok
foo({}); // ok
```
```typescript
// Case 1
const foo = createAction('foo', props<{}>()); // error
foo(1); // error
foo('1'); // error
// Case 2
const foo = createAction('foo', props<{ bar?: string }>()); // ok
foo({}); // ok
```
```
[ ] Yes …
```
=> fix(store): prevent unexpected behavior of {} as a props type

modules/schematics/src/ng-add/index.ts
```
[x] Bugfix
[ ] Feature
```
When ng-add is exectuted it removes other workspace cli options and includes only { defaultCollection: '@ngrx/schematics' } on it.
This fix adds { defaultCollection: '@ngrx/schematics' } to options and doesn't remove the current ones (other options may be ex: analytics).
```
[ ] Yes
[x] No
```
=> fix(schematics): ng-add removes other workspace cli options

projects/ngrx.io/content/guide/router-store/selectors.md
Following up on discussion in https://github.com/ngrx/platform/issues/2062, I propose this draft for addition to the doc.
```
[ ] Bugfix
[ ] Feature
```
Closes #2062 
```
[ ] Yes
[x] No
```
=> docs: add snippet for nested param extraction

modules/component-store/src/component-store.ts, modules/data/src/effects/entity-effects-scheduler.ts, modules/data/src/entity-metadata/entity-metadata.ts, modules/data/src/reducers/constants.ts, modules/data/src/selectors/entity-cache-selector.ts, modules/data/src/utils/interfaces.ts, modules/effects/src/tokens.ts, modules/store-devtools/src/config.ts, modules/store-devtools/src/extension.ts, modules/store-devtools/src/instrument.ts
```
[ ] Bugfix
[ ] Feature
```
Name/description of injection tokens is inconsistent.
**@ngrx/component-store**
```typescript
export const initialStateToken = new InjectionToken('ComponentStore InitState');
```
**@ngrx/data**
```typescript
export const ENTITY_EFFECTS_SCHEDULER = new InjectionToken<SchedulerLike>(
'EntityEffects Scheduler'
);
export const ENTITY_METADATA_TOKEN = new InjectionToken<EntityMetadataMap>(
'@ngrx/data/entity-metadata'
);
```
**@ngrx/effects** …
=> refactor: consistent naming of injection tokens

modules/component-store/spec/types/component-store.types.spec.ts, modules/component-store/src/component-store.ts
Adjust updater typings.
New type would work properly with `Partial<Obj>` interfaces, as well as with simple `unknown` if that's what the developer wants to pass to the `updater`.
It would still return `() => void` if the second argument is not specified.
```
[x] Bugfix
[ ] Feature
```
Closes #2754 
```
[ ] Yes
[x] No
```
=> fix(component-store): adjust updater to accept partials

modules/router-store/spec/router_store_module.spec.ts, modules/router-store/spec/utils.ts, modules/router-store/src/router_store_module.ts
Even if the developer is using `RouterState.Minimal` we should be providing the `urlAfterRedirects` property, that exists on `NavigationEnd` Router even.
Is got broken when the default implementation was switched from `Full` to `Minimal`, however our `Minimal` should still cover this case.
Also, fix the router tests - with just `async () =>` they were not testing the assertions within `subscribe(...)` 😳 
Discovered that, because I first try to fail the test, before making sure that new code passes.
```
[ ] Bugfix
[x] Feature
[ ] …
```
=> feat(router-store): Add urlAfterRedirects to Minimal

modules/store/testing/src/mock_reducer_manager.ts
```
[x] Bugfix
[ ] Feature
```
It is currently not possible to use provideMockStore if the component has a dependency to a module which uses the following imports:
- removeFeature
- removeFeatures
- addReducer
- addReducers
- removeReducer
- removeReducers
Currently crashes with something like
`TypeError: reducerManager.addReducer is not a function`
Closes https://github.com/ngrx/platform/issues/2776
Add `noop` for `removeFeature`, `removeFeatures`, `addReducer`, …
=> fix(store): added noop for all methods in MockReducerManager

modules/effects/spec/integration.spec.ts, modules/effects/src/effects_module.ts
Allow multiple empty `EffectModule.forRoot()`.
Within Google we have a number of cases with empty `EffectModule.forRoot()` have to be added for tests to be able to find this module - ngc has a hard time generating a summary for EffectsModule.forRoot otherwise.
Up until now, the solution was to just remove the guard altogether when merging NgRx locally, but that's not a sustainable approach and requires "un-doing" it with every merge.
```
[ ] Bugfix
[x] Feature
```
``` …
```
=> feat(effects): allow multiple empty EffectModule.forRoot()

modules/effects/testing/spec/mock_actions.spec.ts, modules/effects/testing/src/testing.ts
```
[ ] Bugfix
[x] Feature
```
`provideMockActions` can be used with `TestBed.configureTestingModule`
`provideMockActions` can be used with `TestBed.configureTestingModule` and `Injector.create`
```
[ ] Yes
[x] No
```
This feature is similar to: https://github.com/ngrx/platform/pull/2759
=> feat(effects): use provideMockActions outside of the TestBed

modules/store/src/utils.ts
Document the `combineReducers` function as it is not only used internally but can also be useful for
splitting reducers into multiple feature reducers.
```
[ ] Bugfix
[ ] Feature
```
The `combineReducers` function is undocumented.
Closes #1179 
Added doc-comments to the `combineReducers` function, along with an example.
```
[ ] Yes
[x] No
```
=> docs(store): Add documentation for combineReducers

modules/data/spec/reducers/entity-collection-reducer.spec.ts, modules/data/src/reducers/entity-collection-reducer-methods.ts, modules/entity/spec/sorted_state_adapter.spec.ts, modules/entity/spec/unsorted_state_adapter.spec.ts, modules/entity/src/models.ts, modules/entity/src/sorted_state_adapter.ts, modules/entity/src/unsorted_state_adapter.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[x] Yes
[ ] No
```
To overwrite the entities, we previously used the `addAll` method but the method name was confusing.
BEFORE:
```ts
adapter.addAll(action.entities, state);
```
AFTER:
The new method name `setAll` describes the intention better.
```ts
adapter.setAll(action.entities, state);
```
=> feat(entity): remove addAll

modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/testing.ts
```
[ ] Bugfix
[x] Feature
```
`provideMockStore` can only be used with `TestBed.configureTestingModule`.
Closes #2745
`provideMockStore` can be used with `TestBed.configureTestingModule` and `Injector.create`.
```
[ ] Yes
[x] No
```
=> feat(store): use provideMockStore outside of the TestBed

modules/schematics/package.json
```
[x] Bugfix
[ ] Feature
```
Currently, when you run `ng add @ngrx/schematics` the package will be added to `dependencies`.
This change, adds the `@ngrx/schematics` package to the  `devDependencies`.
```
[ ] Yes
[ ] No
```
[Schematics docs](https://angular.io/guide/schematics-for-libraries#define-dependency-type)
=> fix(schematics): add schematics to devDependencies

projects/ngrx.io/content/guide/store/index.md
Remove `Store` from `my-counter.component.ts` example at step 6 as the tutorial introduces it only at step 8.
```
[ ] Bugfix
[ ] Feature
```
The example in step 6 of the tutorial is inconsistent with the description.
The `Store` is introduced to the example only at step 8 as the description suggests.
```
[ ] Yes
[x] No
```
=> docs(store): improve example in store tutorial

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[ ] Bugfix
[x] Feature
```
```typescript
// case 1
this.moviesStore.setState(state => ({
...state,
movies,
}));
// case 2
this.moviesStore.setState(state => ({
...state,
movies: [...state.movies, movie],
}));
```
Closes #2786
```typescript
// case 1
this.moviesStore.patchState({ movies });
// case 2
this.moviesStore.patchState(state => ({
movies: [...state.movies, movie],
}));
```
```
[ ] Yes
[x] No
```
=> feat(component-store): add patchState method

modules/effects/src/act.ts, modules/effects/src/effect_sources.ts, modules/effects/src/effects_resolver.ts
```
[ ] Bugfix
[ ] Feature
```
RxJS v7 changes the type signatures for `materialize`/`dematerialize`, and v7 is currently being merged for testing into Google. NgRx code breaks with these changes.
This PR introduces changes that would work with both RxJS v6 and v7.
More info here: https://github.com/ReactiveX/rxjs/issues/5706#issuecomment-739549306
```
[ ] Yes
[x] No
```
=> refactor(effects): dematerialize with RxJS v7

modules/effects/spec/effects_metadata.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Additional test cases for effects factory syntax
```
Adding a few cases to cover the `createEffect` factory syntax.
Closes #2817
```
[ ] Yes
[x] No
```
=> test(effects): add test cases for effect factory

modules/store/spec/modules.spec.ts, modules/store/src/index.ts, modules/store/src/store_module.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2809 
Adding a new overload for `StoreModule.forFeature()`;
```ts
static forFeature<T, V extends Action = Action>(
slice: FeatureSlice<T, V>,
config?: StoreConfig<T, V> | InjectionToken<StoreConfig<T, V>>
): ModuleWithProviders<StoreFeatureModule>;
```
```
[ ] Yes
[x] No
```
I think my code is not elegant because added overload has a very different shape. I'd like to be commented on codes.
=> feat(store): add object-style StoreModule.forFeature overload

projects/ngrx.io/content/guide/component/let.md
The removed line, which was outside of the code bloc of examples, is not really useful compared to those explained in the code bloc.
=> docs(component/let.md): remove not really useful example

modules/router-store/spec/integration.spec.ts, modules/router-store/src/router_store_module.ts
Ignore trailing slash (`/`) when comparing URLs in the `navigateIfNeed` method of the `router-store`.
```
[x] Bugfix
[ ] Feature
```
proceeds with re-navigation, which can lead to infinite loop if there's a guard on `/` or `` path (root).
Closes #2829 
Doesn't navigate if the changes in Store lead to the URL being the same as the current one (previously only the exact match would've prevented it).
```
[ ] Yes
[x] No
```
=> fix(router-store): ignore trailing slash when comparing routes

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/models.ts, modules/router-store/src/router_selectors.ts, projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #2758 
`selectParamFromRouterState` selector is added to router selectors.
```
[ ] Yes
[x] No
```
=> feat(router-store): add selectParamFromRouterState selector

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/models.ts, modules/router-store/src/router_selectors.ts, projects/ngrx.io/content/guide/router-store/selectors.md
Reverts ngrx/platform#2771
After some discussion with @alex-okrushko, we will revert this new behavior in favor of a different selector named `selectAllRouteParams` that will gather all route params from the route tree. It will use a "last one wins" strategy, in that if two route parameters have the same name, such as `:id`, the value will be the last occurrence of that parameter name's value. This behavior is different from the Angular Router where a route parameter can have the same name through the hierarchy of defined routes, but as this should be used a more global selector we will document this expected behavior.
cc: @markostanimirovic
=> revert "feat(router-store): add selectParamFromRouterState selector"

projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(store): add 'Testing without TestBed' example

modules/component-store/src/component-store.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2840
Component Store's `select` method now uses variadic tuples types to allow an N number of inputs.
```
[ ] Yes
[x] No
```
=> feat(component-store): allow more than 4 selects

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/router_selectors.ts, projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Performance improvement
```
`selectQueryParams` - returns query params from the last router state node
`selectQueryParam` - returns a query param from the last router state node
`selectFragment` - returns the fragment from the last router state node
Optional chaining is introduced for all selectors.
`selectQueryParams` - returns query params from `routerState.root`
`selectQueryParam` - returns a query param from `routerState.root` …
=> perf(router-store): optimize selectQueryParams, selectQueryParam and selectFragment selectors

projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[ ] Feature
```
```typescript
const customerPageLoaded = createAction('[Customer Page] Loaded', props<{}>());
```
should not be changed to:
```typescript
const customerPageLoaded = createAction('[Customer Page] Loaded');
```
but to:
```typescript
const customerPageLoaded = createAction('[Customer Page] Loaded', props<Record<string, unknown>>());
```
```
[ ] Yes
[x] No
```
=> docs: fix 'empty object as a props type' migration guide

projects/ngrx.io/content/marketing/resources.json
The link to the ultimatecourses NgRX course was broken.
```
[ ] Bugfix
[ ] Feature
```
The link to the ultimatecourses NgRX course is broken.
Closes #2860.
The link is fixed, pointing to https://ultimatecourses.com/learn/ngrx-store-effects.
```
[ ] Yes
[x] No
```
=> docs(ngrx.io): fix ultimatecourses link

modules/data/src/entity-services/entity-services-base.ts, modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Currently the wrong tag `@example` is used in the **entity-services-base.ts** and **reducer_creator.ts** doc comments. No code blocks are used for the code.
Relates to #2854, [comment, part 1](https://github.com/ngrx/platform/issues/2854#issuecomment-756303506)
Changed the tag to `@usageNotes` and added typescript code blocks around the code in doc comments.
```
[ ] Yes
[x] No
```
=> docs(ngrx.io): replace @example tag with @usageNotes and add ts code block

projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
no info about the lib https://github.com/satanTime/ngrx-entity-relationship
a section with the info about the lib https://github.com/satanTime/ngrx-entity-relationship
```
[ ] Yes
[x] No
```
Hi guys, thanks for NGRX, it's awesome.
There is the known problem about selecting relational data. I always tried to approach it in different ways, and, looks like, finally, I found a solution that might work not only for me, but also for other devs. …
=> docs(resources): ngrx-entity-relationship

modules/component/src/let/let.directive.ts
```
[x] Bugfix
[ ] Feature
```
Following code:
```typescript
@Component({
selector: 'my-app',
template: `
<p *ngrxLet="foo$; let f">Hello foo$ '{{ f.bar }}'</p>
`,
})
export class AppComponent {
foo$ = of({ bar: 'baz' });
}
```
will throw this error in strict mode:
```
ERROR in src/app/app.component.ts:7:48 - error TS2532: Object is possibly 'undefined'.
7     <p *ngrxLet="foo$; let f">Hello foo$ '{{ f.bar }}'</p>
~~~
```
Closes #2755 
'Possibily `undefined`' error no …
=> fix(component): remove ? from LetViewContext props to prevent 'possiblly undefined' error in strict mode

modules/schematics/src/create-effect-migration/index.spec.ts, modules/schematics/src/create-effect-migration/index.ts
```
[ ] Bugfix
[ ] Feature
```
All TS files were visited, included where the files inside `node_modules`
Exclude `node_modules` from being visited
```
[ ] Yes
[x] No
```
It took the previous version  1 minute to run in our application.
The refactored version took a few seconds.
=> perf(schematics): speed up create effect migration

modules/store-devtools/src/extension.ts
The deprecated function 'empty()' is replaced with 'EMPTY' object.
Closes #2891
```
[ ] Bugfix
[ ] Feature
```
Closes #2891 
```
[ ] Yes
[x] No
```
=> refactor(store-devtools): replace deprecated empty() function

modules/data/src/entity-services/entity-collection-service-base.ts
- Make the entity: T parameter for the NgRx Data .add command partial when isOptimistic: false since in some cases the PK will be created on the server
Closes #2870
```
[x] Bugfix
[ ] Feature
```
Currently NgRx Data allows the primary key to not be passed into the .add() function for an entity but the typings do not allow for that as they expect `T`
Closes #2870
Change `T` to be `Partial<T>` so that functionality is represented in the types. The full object may not be …
=> fix(data): make entity param partial when is not optimistic

modules/data/src/entity-services/entity-collection-service-base.ts
TypeScript only recognizes the overloads as method signatures when being overloaded not the actual implementation, added overload for the case where isOptimistic is true or undefined (default for entity).
This will allow for the following:
`.add(entityWithoutId, { isOptimistic: false })`
`.add(entityWithId, { isOptimistic: true })`
`.add(entityWithId, { // any other options with whatever settings and no explicit value for isOptimistic })`
`.add(entityWithId)`
```
[x] Bugfix
[ ] Feature
[ ] Other... …
```
=> fix(data): type overloaded add for is optimistic true | undefined

modules/component/src/push/push.pipe.ts
ngrxPush typing considers `undefined` when the input type is an observable
Closes #2888
```
[x] Bugfix
[ ] Feature
```
Closes #2888 
```
[x] Yes
[ ] No
```
Applications that have strict null checks might need to handle `undefined`.
=> fix(push): fix return typing for observables to include undefined

modules/effects/spec/concat_latest_from.spec.ts, modules/effects/src/concat_latest_from.ts, modules/effects/src/index.ts, projects/example-app/src/app/core/effects/router.effects.ts, projects/ngrx.io/content/guide/effects/index.md, projects/ngrx.io/content/guide/effects/operators.md
```
[ ] Bugfix
[x] Feature
```
The NgRx Effects docs tell us:
> Note: For performance reasons, use a flattening operator in combination with withLatestFrom to prevent the selector from firing until the correct action is dispatched.
An operator which does this for consumers of NgRx is nice to have, but does not currently exist.
Closes #2222 
- Calls to `store.select` (or any arbitrary function that produces an observable) are delayed until the function provided to …
=> feat(effects): concatLatestFrom operator

projects/ngrx.io/content/guide/component-store/write.md
The argument type of `addMovie` method in `movies.store.ts` is Movie | Observable<Movie>.
But calls it with string in `movies-page.component.ts`
```
[ ] Bugfix
[ ] Feature
```
The argument type of `addMovie` method in `movies.store.ts` is `Movie | Observable<Movie>` ().
But calls it with string in `movies-page.component.ts`
calls `addMovie` method with interface `Movie`.
`Interface Movie` is not is not explicitly defined, but from …
=> docs(component-store): fix to call `addMovie()` with not string but interface Movie

modules/schematics/src/data/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts.template
```
[ ] Bugfix
[ ] Feature
```
Data schematics are creating specs with deprecated `TestBed.get` method.
Data schematics are creating specs with `TestBed.inject` method.
```
[ ] Yes
[x] No
```
=> refactor(schematics): replace deprecated TestBed.get method

projects/ngrx.io/content/guide/store/testing.md
Trivial fix to documentation only. 
```
[ ] Bugfix
[ ] Feature
```
Two unit test files on the [NgRx store testing guide](https://ngrx.io/guide/store/testing#testing-without-testbed) page are labelled as `books.component.ts`.
Closes #
Labels on the relevant files are updated to `books.component.spec.ts`, reflective of the file content.
```
[ ] Yes
[x] No
```
=> docs: fix filename on spec files

modules/store/spec/types/action_creator.spec.ts, modules/store/src/action_creator.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2948
```
[ ] Yes
[x] No
```
=> fix(store): allow default parameters in function action

modules/store/spec/reducer_creator.spec.ts, modules/store/spec/types/action_creator.spec.ts, modules/store/spec/types/reducer_creator.spec.ts, modules/store/spec/types/utils.ts, modules/store/src/reducer_creator.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2966
```
[ ] Yes
[x] No
```
=> fix(store): allow primitive types

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[ ] Bugfix
[x] Feature
```
`patchState` accepts partial state value or partial updater function.
Closes #2852
`patchState` accepts partial state value or Observable or partial updater function.
```
[ ] Yes
[x] No
```
=> feat(component-store): add ability for patchState to accept Observable

modules/effects/spec/effect_creator.spec.ts, modules/effects/src/effect_creator.ts
```
[x] Bugfix
[ ] Feature
```
Right now `mergeEffects` fails with an error when a `Proxy` object is injected in an `Effect`s class.
Closes #2975 
With this extra condition `Proxy` will be filtered out.
```
[ ] Yes
[x] No
```
I don't fully understand how the commit message should be formed and if there should be any documentation changes. I hope you can help with that.
=> fix(effects): add support for Proxy objects in Effects

modules/component-store/tsconfig-build.json, modules/data/tsconfig-build.json, modules/effects/testing/tsconfig-build.json, modules/effects/tsconfig-build.json, modules/entity/tsconfig-build.json, modules/router-store/tsconfig-build.json, modules/store-devtools/tsconfig-build.json, modules/store/testing/tsconfig-build.json, modules/store/tsconfig-build.json
At the moment, redundant files are being included in the packages libraries ex: https://unpkg.com/browse/@ngrx/store@11.1.0/esm2015/testing/
This change updates the `tsconfig.json` of the all modules to enable `skipTemplateCodegen` with the recommended setting for libraries.
With this option enabled, ngfactories and ngsummaries which are not needed for libraries are not generated and hence the libraries size footprint in the node_modules directory is also smaller.
This is also the default value for the option when generating a library using Angular CLI https://github.com/angular/angular-cli/blob/e607d4482e761c3e556ccc6f4b870af350a5c86a/packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/tsconfig.lib.json#L15
More info about this option can be found here: …
=> build: don't include un-needed files in the distributed packages

projects/example-app/src/app/auth/containers/login-page.component.ts, projects/example-app/src/app/auth/reducers/index.ts, projects/example-app/src/app/auth/services/auth-guard.service.ts, projects/example-app/src/app/books/containers/collection-page.component.ts, projects/example-app/src/app/books/containers/find-book-page.component.ts, projects/example-app/src/app/books/containers/selected-book-page.component.ts, projects/example-app/src/app/books/containers/view-book-page.component.ts, projects/example-app/src/app/books/guards/book-exists.guard.ts, projects/example-app/src/app/books/reducers/index.ts, projects/example-app/src/app/core/containers/app.component.ts, projects/example-app/src/app/core/effects/router.effects.ts, projects/example-app/src/app/reducers/index.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
This PR removes the generic interface for Store.
Because of this change, I also had to change the `createFeatureSelector` method, otherwise it was giving compile erros that state doesn't match the interface.
=> refactor(example-app): remove store generic

modules/store/spec/types/reducer_creator.spec.ts, modules/store/src/reducer_creator.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2982
```
[ ] Yes
[x] No
```
While this works, I can't explain why ...😅
=> fix(store): allow a generic reducer

modules/component-store/src/component-store.ts
Despite its name, a ComponentStore is not necessarily tied to the lifecycle of a component. Let the description of `ComponentStore#effect` reflect this.
```
[ ] Bugfix
[ ] Feature
```
The description of `ComponentStore#effect` states that an effect is tied to the lifecycle of a component.
The description of `ComponentStore#effect` states that an effect is tied to the lifecycle of the component store.
```
[ ] Yes
[x] No
```
=> docs(component-store): clarify effect description

modules/store/src/models.ts, modules/store/src/selector.ts, modules/store/src/store.ts, projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2980
```
[ ] Yes
[x] No
```
=> feat(store): deprecate selectors with props

projects/ngrx.io/content/examples/store/src/app/my-counter/my-counter.component.ts
```
[ ] Bugfix
[ ] Feature
```
The final step in the State walkthrough contains a CSS file in the `@Component` decorator that has no styles and did not originally appear anywhere in the walkthrough.
Closes #2989 
The CSS file was deleted and removed from the `@Component` decorator.
```
[ ] Yes
[x] No
```
=> docs: remove unused css file from counter component

modules/component-store/ng-package.json, modules/component/ng-package.json, modules/data/ng-package.json, modules/effects/ng-package.json, modules/entity/ng-package.json, modules/router-store/ng-package.json, modules/store-devtools/ng-package.json, modules/store/ng-package.json
```
[x ] Bugfix
[ ] Feature
[x ] Build related changes
```
Closes #2998
```
[ ] Yes
[x] No
```
Originally when running `ng-add @ngrx/store --minimal false` or `ng-add @ngrx/effects --minimal false`, the package will run the `ng-add` schematics, but it would not generate newly created files that are defined in the `files/` folder. This was because after building the package, the …
=> build: fix module builds to include schematics files for ng-add

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
It seems like our CI has problem to run the linter in parallel. 
Locally, all linters are OK if I run them one by one.
```
> nx run data:lint 
Nx could not find process's output. Run the command without --parallel.
> nx run schematics:lint 
Nx could not find process's output. Run the command without --parallel.
```
=> ci: dont lint in parallel

projects/ngrx.io/content/guide/migration/v12.md
- / Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> docs(store): add selector deprecation in v12 migration

projects/ngrx.io/content/guide/entity/adapter.md, projects/ngrx.io/content/guide/entity/interfaces.md, projects/ngrx.io/content/guide/entity/recipes/additional-state-properties.md
```
[ ] Bugfix
[ ] Feature
```
In `@ngrx/entity` examples, interface `User` has `id` property which is of type `string`, but `selectedUserId` has type `number` or `number | null` instead of `string | null`.
```
[ ] Yes
[x] No
```
=> docs(entity): fix selectedUserId type

modules/data/src/entity-services/entity-collection-service-base.ts
Additional overload for `.add()` on NgRx Data Service causes issue when passing in `boolean` to `isOptimistic`. Remove overload as it should not be needed. Resolves #2928
```
[x] Bugfix
[ ] Feature
```
Cannot add a pass through function with a parameter of `EntityActionOptions` as `boolean` is not assignable to `false`
Closes #2928
Looser typing allows passing `EntityActionOptions` through
```
[ ] Yes
[x] No
```
=> fix(data): remove strict typing for optimistic false

modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3031 
```
[ ] Yes
[x] No
```
This change adds the ESLint Plugin configuration to the typescript overrides, instead of to the global configuration. This keeps our schematic more alligned with the Angular ESLint plugin.
=> fix(store): add ESLint plugin to TS overrides when possible

modules/store/spec/feature_creator.spec.ts, modules/store/spec/helpers.spec.ts, modules/store/spec/types/feature_creator.spec.ts, modules/store/src/feature_creator.ts, modules/store/src/helpers.ts, modules/store/src/index.ts, modules/store/src/models.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2974
**Example 1:**
```ts
// products.reducer.ts
interface State {
products: Product[];
activeProductId: number | null;
filter: string;
}
const initialState: State = {
products: [],
activeProductId: null,
filter: '',
};
export const productsFeature = createFeature({
name: 'products',
reducer: createReducer(
initialState,
on(ProductsPageActions.enter, /* ... */),
on(ProductsApiActions.loadSuccess, /* ... */),
),
});
// …
```
=> feat(store): add `createFeature`

modules/component/src/let/let.directive.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2890
Let `ViewContainerRef` destroy the view
```
[ ] Yes
[x] No
```
cc @BioPhoton @Kamshak @4javier
=> fix(component): avoid early destruction of view in ngrxLet which interfered with animations (#2890)

projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
The current example that we're using in "Testing Effects without using TestBed" does not work if the effect uses the `store.select` method (`select` doesn't exist on the Observable created with `of`). This PR updates the example to use `provideMockStore`.
=> docs(effects): update test without TestBed example

modules/component-store/src/tap-response.ts, projects/ngrx.io/content/guide/component-store/effect.md
```
[ ] Bugfix
[x] Feature
```
The input argument of `tapResponse` error callback cannot be typed directly.
Closes #3051
The input argument of `tapResponse` error callback can be typed directly:
```ts
tapResponse(
() => {},
(error: { message: string }) => console.error(error.message),
),
```
If not passed, the type of error will be `unknown`, just like the current `tapResponse` implementation.
```
[ ] Yes
[x] No
```
=> feat(component-store): accept error type in `tapResponse`

modules/store/spec/reducer_manager.spec.ts, modules/store/src/reducer_manager.ts
```
[ ] Bugfix
[x] Feature
```
The `ActionReducerMap` of `ReduceManager` is internal.
It is hard to enhance `ActionReducerMap` dynamically.
Closes #3049
The `ActionReducerMap` of `ReduceManager` can be accessed via getter (READ-ONLY).
This allows to get to know which features are registered in the store, at run-time.
```
[ ] Yes
[x] No
```
=> feat(store): make reducers accessible from ReducerManager

projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2780
Added doc explaining usage of `createFeatureSelector` with `Store`
```
[ ] Yes
[x] No
```
=> docs(store): add note about using createFeatureSelector with no generic supplied to Store

modules/component-store/spec/tap-response.spec.ts, modules/component-store/spec/types/tap-response.types.spec.ts, modules/component-store/src/tap-response.ts
```
[x] Bugfix
[ ] Feature
```
`tapResponse` cannot accept error type when `noStrictGenericChecks` is `false`.
This bug is reported [here](https://github.com/ngrx/platform/pull/3056#issuecomment-877183920).
`tapResponse` accepts error type when `noStrictGenericChecks` is `false`.
```
[ ] Yes
[x] No
```
Added unit and type tests for `tapResponse` operator.
=> fix(component-store): accept error type in tapResponse with strict generic checks

modules/effects/src/act.ts, modules/effects/src/actions.ts, modules/effects/src/concat_latest_from.ts, modules/effects/testing/src/testing.ts, modules/store-devtools/src/config.ts, projects/ngrx.io/src/app/custom-elements/api/api-list.component.ts
```
[ ] Bugfix
[ ] Feature
```
There are function, classes, that have JSDoc currently in code (for example [act](https://ngrx.io/api/effects/act), [ofType](https://ngrx.io/api/effects/ofType) - misplaced JSDoc, [StoreDevtoolsConfig](https://ngrx.io/api/store-devtools/StoreDevtoolsConfig) - add property JSDoc with link to the original redux devtool website for explanation) but it is currently not visible in the docs.
All the written is JSDoc are now visible when looking …
=> docs: update JSDocs to show up in the online documentation

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/index.ts, modules/router-store/src/router_selectors.ts, projects/example-app/src/app/reducers/index.ts, projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
This is an RFC to make it easier to select the router state when the default router config is used.
Because the router store module is opinionated and uses `router` as the default feature name, I was thinking about adding a bit of default behavior to the current router selectors. This aims to make it easier to get started with using the router store.
When the default config is used, I think we can:
- export …
=> feat(router-store): add createRouterSelector to select router data for default config

projects/ngrx.io/tools/transforms/angular-api-package/index.js, projects/ngrx.io/tools/transforms/angular-base-package/index.js, projects/ngrx.io/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js, projects/ngrx.io/tools/transforms/templates/disambiguator.template.html
```
[x] Bugfix
[ ] Feature
```
Serving the docs fails due to files with same name but different casing. Manually cherry-picked changes from https://github.com/angular/angular/pull/41788
Closes #
```
[ ] Yes
[x] No
```
=> docs: fix error with serving files with ambiguous casing

projects/ngrx.io/content/guide/store/reducers.md
Rephrase the explanation of the whether the exported reducer function is necessary, in light of the fact that the Ivy compiler is now enabled by default. Most new users will not require the separate exported reducer function, so it makes sense to lead with that.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(store): clarify necessity of exported reducer function

projects/ngrx.io/content/guide/component-store/read.md
```
[ ] Bugfix
[ ] Feature
```
The previous documentation example uses the `this.effect` API in a way that is inconsistent with the rest of the docs (actually not even sure if it is valid syntax).
The revised example in the docs now uses code patterns consistent with the `effects` doc section
```
[ ] Yes
[x] No
```
=> docs: Slightly altering the debounced selector and effects example

modules/store-devtools/src/config.ts
The JsDoc comments of the StoreDevtoolsConfig class and DevToolsFeatureOptions interface lead to a site that is now NSFW.
This commit replaces the single link by two links: one for the Firefox extension documentation, and one for the Chrome extension documentation.
```
[ ] Bugfix
[ ] Feature
```
JsDoc leads to a porn site (remotedev.extensions.io)
Closes #3143 
The link now leads to real docs
```
[ ] Yes
[x] Hell No, it's just a damn link!
```
=> StoreDevtoolsConfig: Remove links to NFSW website

modules/entity/src/unsorted_state_adapter.ts
```
[x] Bugfix
[ ] Feature
```
Input argument types for `removeOneMutably` and `removeManyMutably` methods are incorrect.
```
[ ] Yes
[x] No
```
=> fix(entity): set correct input argument types for removeMutably methods

modules/schematics/schematics-core/index.ts, modules/schematics/schematics-core/utility/ngrx-utils.ts, modules/schematics/src/action/index.ts, modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template, modules/schematics/src/effect/index.spec.ts, modules/schematics/src/effect/index.ts, modules/schematics/src/effect/schema.json, modules/schematics/src/effect/schema.ts, modules/schematics/src/feature/index.spec.ts, modules/schematics/src/feature/index.ts, modules/schematics/src/feature/schema.json, modules/schematics/src/feature/schema.ts, modules/schematics/src/reducer/creator-files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template, modules/schematics/src/reducer/files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template, modules/schematics/src/reducer/index.spec.ts, modules/schematics/src/reducer/index.ts, modules/schematics/src/reducer/schema.json, modules/schematics/src/reducer/schema.ts
```
[x] Bugfix
[x] Feature
```
Closes #3116
When using the `feature` schematic with `--prefix` option, `effects` and `reducers` will use the supplied prefix. `action` already uses the supplied prefix.
```
[ ] Yes
[x] No
```
=> fix(schematics): Use prefix option in feature schematic

modules/store/spec/types/feature_creator.spec.ts, modules/store/src/store.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
This change should help for cases as https://github.com/ngrx/platform/issues/2780#issuecomment-931443027.
This change doesn't fix the cases where `createFeatureSelector` is used with 2 generics.
To resolve those cases, we could assert the generic `T` as `any`, or remove the `<State, FeatureState>` overload from `createFeatureSelector` in the next version.
```ts
export const selectBooksState = …
```
=> refactor(store): use Record as Store generic

modules/store/spec/types/action_creator.spec.ts, modules/store/src/action_creator.ts, modules/store/src/feature_creator_models.ts, modules/store/src/models.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2892
```
[x] Yes - usage of `props` outside of an action creator now breaks for invalid types
[ ] No
```
Thanks to the advice from [Nadia Chibrikova on StackOverflow](https://stackoverflow.com/a/68080083/11087018), `props` can have its generic argument asserted to pass `NotAllowedCheck`:
This provides a more precise error than the current one which is hidden within TS outputting multiple errors for a mismatch for each overload of …
=> feat(store): provide better TS errors for action creator props

modules/component/spec/push/push.pipe.spec.ts, modules/component/src/push/push.pipe.ts
```
[x] Bugfix
[ ] Feature
```
`PushPipe` doesn't work properly with `strictTemplates` set to `true`.
Closes #3114
`PushPipe` works with `strictTemplates` set to `true`.
```
[x] Yes
[ ] No
```
```
PushPipe no longer has a class-level generic type parameter.
This change will affect the use of PushPipe outside of component templates.
```
=> fix(component): remove class-level generic from PushPipe

modules/store/spec/types/store_module.spec.ts, modules/store/src/store_module.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3007
```
[x] Yes
[ ] No
```
This will probably be a breaking change because we're more strict.
```
`initialState` needs to match the interface of the store.
```
=> fix(store): infer initial store state properly with metareducers

modules/store/migrations/13_0_0-beta/index.spec.ts, modules/store/migrations/13_0_0-beta/index.ts, modules/store/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Adds a migration to update the deprecated `createFeatureSelector` syntax:
```ts
// BEFORE:
import {createFeatureSelector} from '@ngrx/store'
const featureSelector1 = createFeatureSelector('feature1');
const featureSelector2 = createFeatureSelector<Feature>(feature2);
const featureSelector3 = createFeatureSelector<State, Feature>('feature3');
const featureSelector4 = …
```
=> feat(store): add createFeatureSelector migration

modules/store/spec/modules.spec.ts, modules/store/spec/types/store_module.spec.ts, modules/store/src/store_module.ts
```
[x] Bugfix
[ ] Feature
```
The `StoreModule.forFeature` signature with `FeatureSlice` has `StoreConfig` as the second input argument, but the configuration isn't registered if passed.
Closes #3216
The `StoreModule.forFeature` signature with `FeatureSlice` no longer has `StoreConfig` as the second input argument.
```
[x] Yes
[ ] No
The `StoreConfig` argument is removed from the `StoreModule.forFeature` signature with `FeatureSlice`.
BEFORE:
The …
```
=> fix(store): remove store config from forFeature signature with slice

modules/data/spec/reducers/entity-collection-reducer.spec.ts, modules/data/src/reducers/entity-collection-reducer-methods.ts
```
[x] Bugfix
[ ] Feature
```
The `getWithQuery` method has not set the loaded property to true as opposed to the getAll method. 
Closes #3165 
Now they both `getWithQuery` and `getAll` methods are consistent and do set `loaded` property to _true_ on dispatching their success actions respectively.
```
[x] Yes
[ ] No
```
Now `getWithQuery` method really does "load data collection". So far it has been necessary to call `setLoaded(true)` if a developer has wanted to fetch the list using `getWithQuery`.
=> fix(data): set loaded to true on queryManySuccess

modules/effects/testing/package.json, modules/store/testing/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #3248 
```
[ ] Yes
[x] No
```
This PR changes the package.json from the testing (store and effects) packages.
Instead of setting the paths manually, the ng-packagr can do it for us - [docs](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md#example-folder-layout-for-secondary-entry-points)
After this change the output files look like this:
Store:
Before:
```json
{
"name": "@ngrx/store/testing", …
```
=> fix: set correct dist paths for testing packages

.circleci/config.yml, .eslintrc.json, angular.json, nx.json, package.json, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
While testing #3245, some tests of the example app weren't working anymore.
With this update, all tests are back to green.
To upgrade, I used the `nx migrate` commands.
```
nx migrate latest
nx migrate --run-migrations
```
=> build: update NX

modules/component/spec/let/let.directive.spec.ts, modules/component/src/let/let.directive.ts
Handles edge case where rendering causes the observable to emit which causes
`ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]`
Change the logic to set `embeddedViewCreated` before calling `createEmbeddedView`, so if `ensureEmbeddedViewCreated` is called recursively it won't call `createEmbeddedView` a 2nd time. Also, we're calling `ensureEmbeddedViewCreated` after we setup the view context because if it gets called recursively the previous call stack will override the later value.
```
[x] Bugfix
[ ] Feature
[ ] CI …
```
=> fix(component): fixes recursive rendering

projects/ngrx.io/tools/transforms/templates/api/lib/memberHelpers.html
Hi everyone,
```
[x] Bugfix
[ ] Feature
```
I managed to find the similar issue that both Angular and RxJS documentation apps had. Basically, the docs app does not render what [EntityCollectionServiceBase](https://ngrx.io/api/data/EntityCollectionServiceBase) implements. While the docs app says this:
`class EntityCollectionServiceBase<...> implements EntityCollectionService`,
[it actually implements this](https://github.com/ngrx/platform/blob/d3aa7d0bde6c0e4de4b3e91a99f …
=> docs: fix heritage links

projects/ngrx.io/tools/transforms/angular-base-package/post-processors/auto-link-code.js
Hi everyone,
```
[x] Bugfix
[ ] Feature
```
Currently, [auto-link-code](https://github.com/ngrx/platform/blob/875adb3a99/projects/ngrx.io/tools/transforms/angular-base-package/post-processors/auto-link-code.js#L23) tool adds links to `<code>` tags automatically by parsing the entire node and doing lookup for existing words (objects/functions/classes). It misses words that contain `$`. Thus, docs pages like [`EntityCollectionServiceBase`](https://ngrx.io/api/data/EntityC …
=> docs: fix links missing objects with a dollar sign

projects/ngrx.io/content/guide/entity/adapter.md
Removed mentions of partial updates for upsertOne and upsertMany as they are not longer support them
```
[ ] Bugfix
[ ] Feature
```
[
](https://github.com/ngrx/platform/issues/3282)
Closes #3282
Correct documentation for upsertOne and upsertMany method. Now documentation explicitly state that upsertOne and upsertMany do not support partial updates.
```
[ ] Yes
[x] No
```
=> docs(entity): remove partial update notes for upsert methods

modules/entity/src/create_adapter.ts
```
[x] Bugfix
[ ] Feature
```
```ts
const {
selectId, // selectId is undefined instead of the default id selector
sortComparer, // sortComparer is undefined instead of false
} = createEntityAdapter<Entity>({
selectId: undefined,
sortComparer: undefined,
});
``` 
```ts
const {
selectId, // selectId is equal to default id selector
sortComparer, // sortComparer is false
} = createEntityAdapter<Entity>({
selectId: undefined,
sortComparer: undefined,
});
``` 
```
[ ] Yes …
```
=> fix(entity): add default options to entity adapter when undefined is passed

projects/ngrx.io/content/guide/migration/v12.md
```
[ ] Bugfix
[ ] Feature
```
Documentation for migrating to v12 does not include version number in command used to update the framework.
Closes #
Version number is added to command used to migrate the framework to v12 in order to avoid confusion to the reader. Without this, the update version will be the latest version. 
```
[ ] Yes
[ x] No
```
=> docs(store): include version in command for v12 update

MIGRATION.md, build/update-version-numbers.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
In the past there were some issues when people upgraded the NgRx dependencies because they wanted to update to a specific version, and not the the latest version. That's why I'm proposing that we
explicitly set the version number to the `ng upgraded` command in the migration guide. An alternative would be that we update the previous migration guide.
This PR also updates the version number in `MIGRATION.md`, …
=> chore: include version number to ng add command in migration guide

projects/ngrx.io/src/styles/2-modules/_api-list.scss, projects/ngrx.io/src/styles/2-modules/_api-pages.scss, projects/ngrx.io/tools/transforms/templates/api/lib/memberHelpers.html
```
[ ] Bugfix
[x] Feature
```
None.
This PR adds styling to the deprecated items. Since there are no much deprecated items, here's what it looks like on the only deprecated item that exists in the repository:
To show other example, I locally faked another deprecation and here's the result:
I also faked `name?` property 🙂 
```
[ ] Yes
[x] No
```
Similar to ReactiveX/rxjs#6379 and ReactiveX/rxjs#6886
=> docs: add styling for deprecated items

projects/ngrx.io/tools/transforms/templates/api/lib/memberHelpers.html, projects/ngrx.io/tools/transforms/templates/api/lib/paramList.html
```
[ ] Bugfix
[x] Feature
```
This PR includes rendering parameters in the function documents. It also fixes an issue related to anchor tag ID. Let me [show an example](https://ngrx.io/api/effects/act):
This PR fixes this so that parameters of the function from the image are properly rendered:
This PR also fixes an issue with `a` tag having an empty ID. Having proper id will make it possible to write docs in such way so that it produces a link that leads to the …
=> docs: turn on rendering parameter types

projects/ngrx.io/content/guide/store/reducers.md
The name of the reducer exported from the scorebord.reducer.ts is scoreboardReducer.
In the app.module.ts, we should import the reducer with the same name.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> docs(store): fix reducer import in reducer guide

modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3268
```
[ ] Yes
[x] No
```
I only added explicit overloads for `createSelector` with variadic "slice" arguments, because only that signature failed due to the problems identified in #3268. The signature that uses an array for the "slices" [does not fail](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQDRQDUA+KAXigAoBnYAQ2AgC4psBKMkggbgFgAoUJCgBZCAFtUASwBeEACZxEKDDnzEysBMjRY8hIrz785yeLXTQAZgFcAdikmpbUJBfoR …
=> bug(store) add explicit overloads for createSelector

modules/data/spec/dataservices/default-data.service.spec.ts, modules/data/src/dataservices/default-data-service-config.ts, modules/data/src/dataservices/default-data.service.ts, modules/data/src/dataservices/http-url-generator.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[ x] No
```
=> feat(data): add ability to configure trailing slashes

modules/component/src/push/push.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
There are two typos.
Closes #3374 
The typos have been fixed. It was changed from "render_creator" to "render" on lines 30 and 39.
```
[ ] Yes
[x] No
```
=> docs(component): fix typo in PushPipe docs

modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/integration.spec.ts, modules/router-store/spec/integration.spec.ts, projects/example-app/src/app/core/effects/user.effects.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
`mapTo` variations are deprecated, this PR replaces them with the `map` equivalents.
=> refactor: replace mapTo deprecations

modules/component/.eslintrc.json, modules/component/spec/fixtures/fixtures.ts, modules/component/spec/let/let.directive.spec.ts, modules/component/src/let/let.directive.ts, projects/ngrx.io/content/guide/component/let.md
```
[ ] Bugfix
[x] Feature
```
Closes #3340
Added ability to pass the suspense template to `LetDirective`:
```html
<p *ngrxLet="obs$ as o; suspenseTpl: loading">
{{ o }}
</p>
<ng-template #loading>Loading...</ng-template>
```
A suspense template will be displayed when passed observable is in a suspense state. If the suspense template is not passed, the behavior will remain the same:
- The main template will be rendered only when the first observable emits …
=> feat(component): add suspense template input to LetDirective

modules/component/spec/let/let.directive.spec.ts, modules/component/src/let/let.directive.ts, projects/ngrx.io/content/guide/component/let.md
```
[ ] Bugfix
[x] Feature
```
The `$error` property from `LetDirective`'s view context will be `true` or `false`.
Closes #3343 
The `$error` property from `LetDirective`'s view context will be thrown error or `undefined`.
```
[x] Yes
[ ] No
The `$error` property from `LetDirective`'s view context is a thrown error or `undefined` instead of `true`/`false`.
BEFORE:
<p *ngrxLet="obs$; $error as e">{{ e }}</p>
- `e` will be `true` when `obs$` emits error …
```
=> feat(component): add error as value to LetDirective's context

modules/effects/src/act.ts, modules/effects/src/effect_notification.ts, modules/effects/src/effect_sources.ts, modules/effects/src/utils.ts
```
[ ] Bugfix
[ ] Feature
```
when using RxJS 8 and importing from "@ngrx/effects":
` Error: export 'Notification' (imported as 'Notification') was not found in 'rxjs' `
Working code
https://github.com/ngrx/platform/discussions/3365
```
[ ] Yes
[x] No
```
=> refactor(effects): use ObservableNotification instead of Notification, to support RxJS 8

modules/component/spec/core/render-scheduler.spec.ts, modules/component/spec/fixtures/fixtures.ts, modules/component/src/core/render-scheduler.ts, modules/component/src/push/push.pipe.ts, projects/ngrx.io/content/guide/component/let.md, projects/ngrx.io/content/guide/component/push.md
```
[ ] Bugfix
[x] Feature
```
Closes #3342 
`@ngrx/component` uses a global rendering strategy in zone-less mode.
```
[x] Yes
[ ] No
The native local rendering strategy is replaced by global in zone-less mode for better performance.
BEFORE:
The change detection is triggered via `changeDetectorRef.detectChanges` in zone-less mode.
AFTER:
The change detection is triggered via `ɵmarkDirty` in zone-less mode.
```
=> feat(component): use global render strategy in zone-less mode

modules/store/spec/types/action_group_creator.spec.ts, modules/store/src/action_group_creator_models.ts
```
[x] Bugfix
[ ] Feature
```
Template literals are subsets of string literal types. The `createActionGroup` function requires to use string literals for source/event names, but the error message is 'source/event name must be a **template** literal type'.
Displaying correct error message when the type of source/event name is not a string literal.
```
[ ] Yes
[x] No
```
=> fix(store): rename template literal to string literal for createActionGroup

modules/component/spec/core/potential-observable.spec.ts, modules/component/spec/helpers.ts, modules/component/spec/let/let.directive.spec.ts, modules/component/spec/push/push.pipe.spec.ts, modules/component/spec/types/let.directive.types.spec.ts, modules/component/spec/types/push.pipe.types.spec.ts, modules/component/spec/types/utils.ts, modules/component/src/core/potential-observable.ts, modules/component/src/core/render-event/manager.ts, modules/component/src/core/render-event/models.ts, modules/component/src/let/let.directive.ts, modules/component/src/push/push.pipe.ts, projects/ngrx.io/content/guide/component/index.md, projects/ngrx.io/content/guide/component/let.md
```
[x] Bugfix
[x] Feature
```
Closes #3344, #3345
1. Added the ability to pass "non-observable" values to `LetDirective`/`PushPipe`. With this feature, we can create readable templates by using aliases for deeply nested properties:
```html
<ng-container *ngrxLet="userForm.controls.email as email">
<input type="text" [formControl]="email" />
<ng-container *ngIf="email.errors && (email.touched || email.dirty)">
<p *ngIf="email.errors.required">This field is …
```
=> feat(component): add ability to pass non-observable values & fix types

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts, modules/component-store/src/index.ts, modules/component-store/src/lifecycle_hooks.ts, projects/ngrx.io/content/guide/component-store/lifecycle.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
Adds a check and warning if lifecycle hooks are defined on the ComponentStore and its not provided using the `provideComponentStore()` function.
Adds documentation for lifecycle hooks and explanation for `provideComponentStore()` function.
```
[ ] Yes
[x] No
```
=> refactor(component-store): add docs and warning for hooks without provideComponentStore

projects/ngrx.io/content/guide/component-store/install.md, projects/ngrx.io/content/guide/component/install.md, projects/ngrx.io/content/guide/data/install.md, projects/ngrx.io/content/guide/effects/install.md, projects/ngrx.io/content/guide/entity/install.md, projects/ngrx.io/content/guide/eslint-plugin/install.md, projects/ngrx.io/content/guide/router-store/install.md, projects/ngrx.io/content/guide/schematics/install.md, projects/ngrx.io/content/guide/store-devtools/install.md, projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[ ] Feature
```
- The `ng add` command, which automatically makes useful changes to files related to the lib installation, is being shown after the `npm install` and `yarn install` commands.
- The optional flags are displayed as a list.
Closes #3434
- The `ng add` command is the first option in the installation guides.
- The optional flags are displayed in a markdown datatable.
```
[ ] Yes
[x] No
```
=> docs: prioritize ng add in installation guides

modules/schematics/src/ng-add/index.spec.ts, modules/schematics/src/ng-add/index.ts, modules/schematics/src/ng-add/schema.json, modules/schematics/src/ng-add/schema.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3383
Throw an exception if schematicCollections is not defined because the user may not have upgraded Angular to v14.
```
[ ] Yes
[x] No
```
=> feat(schematics): use schematicCollections instead of defaultCollection

modules/eslint-plugin/schematics/ng-add/schema.json, modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
Improvements after I tried to install the beta version of NgRx ESLint:
- Only install the plugin if an ESLint config exists
- Rephrased the prompt to select the configuration to make it explicit that it's about the ESLint config
=> feat(eslint-plugin): improve install flow

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/spec/serializers.spec.ts, modules/router-store/spec/types/selectors.spec.ts, modules/router-store/src/models.ts, modules/router-store/src/router_selectors.ts, modules/router-store/src/serializers/full_serializer.ts, modules/router-store/src/serializers/minimal_serializer.ts, projects/ngrx.io/content/examples/router-store-selectors/src/app/router.selectors.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3336
```
[ ] Yes
[ ] No
```
=> feat(router-store) add selector to get title

modules/component/spec/let/let.module.spec.ts, modules/component/spec/push/push.module.spec.ts, modules/component/spec/reactive-component.module.spec.ts, modules/component/src/index.ts, modules/component/src/let/let.directive.ts, modules/component/src/let/let.module.ts, modules/component/src/push/push.module.ts, modules/component/src/push/push.pipe.ts, modules/component/src/reactive-component.module.ts, projects/ngrx.io/content/guide/component/let.md, projects/ngrx.io/content/guide/component/push.md
```
[ ] Bugfix
[x] Feature
```
`LetDirective` and `PushPipe` are exported via `ReactiveComponentModule`.
Closes #3341
1. `LetDirective` is exported via `LetModule`.
2. `PushPipe` is exported via `PushModule`.
3. `ReactiveComponentModule` re-exports declarations from `PushModule` and `LetModule`.
```
[ ] Yes
[x] No
```
=> feat(component): add separate modules for PushPipe and LetDirective

modules/component/src/let/let.directive.ts
```
[x] Bugfix
[ ] Feature
```
If we pass the property that contains falsy types to the `LetDirective` as follows:
```ts
@Component({
selector: 'app-foo',
template: `
<div *ngrxLet="prop as alias">
{{ prop }}
{{ alias }}
</div>
`,
})
export class FooComponent {
prop: Observable<string> | null | false = of('marko');
}
```
The type of `prop` within the embedded template will be `Observable<string>` (falsy types are excluded).
Fortunately, the type of the `alias` variable …
=> fix(component): do not exclude falsy types from LetDirective's input type

modules/schematics/src/ng-add/index.spec.ts, modules/schematics/src/ng-add/index.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3468
```
[ ] Yes
[x] No
```
=> fix(schematics): create schematicCollections if not exists

modules/component-store/spec/types/component-store.types.spec.ts, modules/component-store/src/component-store.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3462
```
[ ] Yes
[x] No
```
=> fix(component-store): allow void callbacks in effect

modules/data/schematics/ng-add/schema.json, modules/effects/schematics/ng-add/schema.json, modules/router-store/schematics/ng-add/schema.json, modules/schematics/src/action/schema.json, modules/schematics/src/component-store/schema.json, modules/schematics/src/container/schema.json, modules/schematics/src/data/schema.json, modules/schematics/src/effect/schema.json, modules/schematics/src/entity/schema.json, modules/schematics/src/feature/schema.json, modules/schematics/src/reducer/schema.json, modules/schematics/src/selector/schema.json, modules/schematics/src/store/schema.json, modules/store-devtools/schematics/ng-add/schema.json, modules/store/schematics/ng-add/schema.json, projects/example-app-e2e/src/integration/round-trip.spec.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3469
```
[ ] Yes
[x] No
```
Old:
```
 npx ng add ngrx-store-14.0.0-local
ℹ Using package manager: npm
✔ Package information loaded.
The package ngrx-store-14.0.0-local will be installed and
executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
The 'path' option in 'C:\Users\timde\dev\playgrounds\ng-fourteen\node_modules\@ngrx\store\schematics\ng-add\schema.json' is using deprecated …
```
=> fix(schematics): add workingDirectory to schemas

projects/ngrx.io/content/examples/testing-store/src/app/state/books.reducer.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> docs(store): fix reducer test result example

modules/component/src/core/render-event/manager.ts
```
[x] Bugfix
[ ] Feature
```
Related to #3464 & #3465
Import RxJS operators from `rxjs/operators` instead of `rxjs`. Otherwise the build fails with latest rxjs v6.
```
[ ] Yes
[x] No
```
=> fix(component): import operators from rxjs/operators

projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
The resources page of ngrx.io doesn't have ngrx-traits on the list of libraries
Closes #
Did not create any issue for this, I will imagine is not needed for this case but I can if requested
In the resources page of ngrx.io add to the libraries section ngrx-traits lib ( see …
=> docs: add ngrx-traits to the list of libraries in resources

modules/component/spec/core/render-event/handlers.spec.ts, modules/component/spec/core/render-event/manager.spec.ts, modules/component/src/core/render-event/manager.ts, modules/component/src/core/render-event/models.ts, modules/component/src/let/let.directive.ts, modules/component/src/push/push.pipe.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Performance improvements
```
The render scheduler unnecessarily schedules render/marks a component as dirty when synchronous events are emitted.
For instance, in the following example:
```ts
@Component({
template: `
<p>{{ obs$ | ngrxPush }}</p>
`
})
export class TestComponent {
obs$ = of(1, 2, 3);
}
```
The PushPipe will mark `TestComponent` as dirty (and schedule tick in zone-less mode) 4 times (3 next, and 1 complete event) which is not …
=> perf(component): do not schedule render for synchronous events

modules/component/spec/core/render-scheduler.spec.ts, modules/component/spec/core/tick-scheduler.spec.ts, modules/component/spec/core/zone-helpers.spec.ts, modules/component/spec/fixtures/fixtures.ts, modules/component/src/core/render-scheduler.ts, modules/component/src/core/tick-scheduler.ts, modules/component/src/core/zone-helpers.ts, modules/component/src/let/let.directive.ts, modules/component/src/push/push.pipe.ts
```
[ ] Bugfix
[x] Feature
```
The `@ngrx/component` package uses the `markDirty` function from the `@angular/core` package to mark a component as dirty and schedule tick in zone-less mode. However, [this function will be removed soon](https://github.com/angular/angular/pull/46806).
The `markDirty` function is replaced with a custom `TickScheduler`.
```
[ ] Yes
[x] No
```
https://github.com/angular/angular/pull/46806
=> feat(component): replace markDirty with custom TickScheduler

modules/component/spec/core/render-scheduler.spec.ts, modules/component/spec/types/push.pipe.types.spec.ts, modules/component/src/core/render-scheduler.ts, modules/component/src/let/let.directive.ts, modules/component/src/push/push.pipe.ts
This PR converts `RenderScheduler` to a service, so it could be also used in the following way:
```ts
import { RenderScheduler } from '@ngrx/component';
@Component({
providers: [RenderScheduler],
})
export class TestComponent {
constructor(private readonly renderScheduler: RenderScheduler) {}
doSomething(): void {
// ...
this.renderScheduler.schedule();
}
}
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This PR currently depends on #3488
=> refactor(component): use RenderScheduler as a service

CONTRIBUTING.md, modules/eslint-plugin/src/utils/helper-functions/docs.ts
```
[x] Bugfix
[ ] Feature
```
When I click on the docs url on VSCode, the user is navigated to a `PAGE NOT FOUND` page for all the rules.
https://user-images.githubusercontent.com/6942946/183309538-9e016d8a-de6a-4f92-8e53-b53c5a6157ca.mov
Closes #
```
[ ] Yes
[x] No
```
=> fix(eslint-plugin): Remove the md suffix from the docsUrl path

projects/example-app/src/app/auth/auth.module.ts
```
[ ] Bugfix
[ ] Feature
```
The `entryComponents` property is still being used in the `auth.module` inside the example app.
Closes https://github.com/ngrx/platform/issues/3523
The `entryComponents` property is now removed.
```
[ ] Yes
[x] No
```
=> refactor(example-app): remove occurrence of deprecated entryComponents

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3266 
All synchronous errors are now catchable. Also, error handling is changed - an error will not be emitted to the `stateSubject$` anymore, it will be thrown instead.
```
[ ] Yes
[x] No
```
As we discussed at the last team meeting, this should not be considered a breaking change.
=> fix(component-store): make synchronous updater errors catchable

modules/component-store/spec/tap-response.spec.ts, modules/component-store/src/tap-response.ts
```
[ ] Bugfix
[x] Feature
```
When anything is thrown from the first argument of `tapResponse` fn( aka `next` callback) it is not handled.
Closes # https://github.com/ngrx/platform/issues/3431
When anything is thrown from the first argument of `tapResponse` fn( aka `next` callback) is now handled by the same error handler as the second argument (aka `error` callback).
```
[ ] Yes
[x] No
```
=> feat(component-store): handle errors in next callback

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2991
There is no initialization error when ComponentStore initialization and state update are scheduled via `queueScheduler`.
```
[ ] Yes
[x] No
```
=> fix(component-store): move isInitialized check to queueScheduler context on state update

modules/eslint-plugin/spec/rules/avoid-mapping-selectors.spec.ts, modules/eslint-plugin/src/rules/store/avoid-mapping-selectors.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3511
```
[ ] Yes
[x] No
```
This scans if `this` is used in an operator.
If it finds a `this`, then the `avoid-mapping-selectors` rule is disabled.
The reasoning behind this, is that the selector is used in combination with something from the component (which can't be moved into the selector) to do something.
=> fix(eslint-plugin): avoid-mapping-selectors don't report on ThisExpression

modules/eslint-plugin/spec/rules/avoid-combining-selectors.spec.ts, modules/eslint-plugin/src/rules/store/avoid-combining-selectors.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3565
The problem was that only `combineLatest(foo$, bar$, baz$)` was analyzed, and not the overload that takes the selectors as an array `combineLatest([foo$, bar$, baz$])`.
```
[ ] Yes
[x] No
```
=> fix(eslint-plugin): avoid-combining-selectors with arrays should warn

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
Switch from asyncScheduler to asapScheduler to prevent the "1 periodic timer(s) still in the queue" error.
there are existing tests for this that still pass
```
[x] Bugfix
[ ] Feature
```
Closes #3573
```
[ ] Yes
[x] No
```
=> fix(component-store): use asapScheduler to schedule lifecycle hooks check

modules/store/spec/types/reducer_creator.spec.ts, modules/store/src/reducer_creator.ts
- Fix for https://github.com/ngrx/platform/issues/3576
- Address the comment inside on Fn, since https://github.com/microsoft/TypeScript/pull/41544 has been merged
```
[x] Bugfix
[ ] Feature
```
Closes https://github.com/ngrx/platform/issues/3576 
```
[ ] Yes
[x] No
```
=> fix(store): fix typing of on fn

projects/ngrx.io/content/guide/store/walkthrough.md
Removes app.state.ts from Walkthrough because it is not used.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[X] No
```
=> docs(router-store): remove app.state.ts

modules/component/src/core/tick-scheduler.ts
```
[x] Bugfix
[ ] Feature
```
`animationFrameScheduler` can stop working unexpectedly. See https://github.com/ReactiveX/rxjs/issues/7018 for more info.
Closes #3591 
`animationFrameScheduler` is replaced with the native `requestAnimationFrame` API to solve potential bugs caused by the issue with `animationFrameScheduler`.
```
[ ] Yes
[x] No
```
=> fix(component): replace animationFrameScheduler with requestAnimationFrame

modules/router-store/src/serializers/minimal_serializer.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3495 
`MinimalRouterStateSerializer` sets `undefined` for unserializable route title.
```
[ ] Yes
[x] No
```
This is a temporary fix to avoid runtime errors when the `@ngrx/router-store` package is used with a custom title resolver in Angular 14. I'll create another PR that completely resolves this issue when we move to Angular 15 (that includes this fix https://github.com/angular/angular/issues/47459).
=> fix(router-store): set undefined for unserializable route title

.devcontainer/devcontainer.json, modules/effects/migrations/15_0_0-beta/index.spec.ts, modules/effects/migrations/15_0_0-beta/index.ts, modules/effects/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Adds a migration for #3587
```
[ ] Yes
[x] No
```
=> feat(effects): migration for provideEffects argument

modules/component/spec/core/potential-observable.spec.ts, modules/component/spec/core/render-event/manager.spec.ts, modules/component/spec/let/let.directive.spec.ts, modules/component/spec/push/push.pipe.spec.ts, modules/component/spec/types/let.directive.types.spec.ts, modules/component/spec/types/push.pipe.types.spec.ts, modules/component/spec/types/utils.ts, modules/component/src/core/potential-observable.ts, modules/component/src/core/render-event/manager.ts, modules/component/src/let/let.directive.ts, modules/component/src/push/push.pipe.ts, projects/ngrx.io/content/guide/component/index.md, projects/ngrx.io/content/guide/component/let.md, projects/ngrx.io/content/guide/component/push.md
```
[ ] Bugfix
[x] Feature
```
`*ngrxLet` directive and `ngrxPush` pipe treat observable dictionaries as static values.
Closes #3545 
`*ngrxLet` directive and `ngrxPush` pipe are able to handle observable dictionaries.
```
[ ] Yes
[x] No
```
=> feat(component): handle observable dictionaries

modules/store/src/provide_store.ts, modules/store/src/store_module.ts
```
[ ] Bugfix
[x] Feature
```
Importing `StoreModule.forRoot` without initial reducers is done in the following way:
```ts
imports: [
StoreModule.forRoot({}),
]
```
Importing `StoreModule.forRoot` without initial reducers can be also done as follows:
```ts
imports: [
StoreModule.forRoot(),
]
```
```
[ ] Yes
[x] No
```
=> feat(store): make reducers arg of StoreModule.forRoot optional

modules/router-store/spec/types/selectors.spec.ts, modules/store/spec/selector.spec.ts, modules/store/spec/types/selector.spec.ts, modules/store/src/selector.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3571 
The `projector` is strict by default, but can be bypassed with an `any` generic parameter.
```
[x] Yes
[ ] No
```
A migration will be included to include `<any>` for every existing projector.
=> feat(store): strict projectors

projects/ngrx.io/content/guide/store/why.md
```
[ ] Bugfix
[ ] Feature
```
There's a link in the doc for component-store that actually points to component
The link correctly points to component-store
```
[ ] Yes
[X] No
```
=> docs(store): fix link to component-store

modules/store/spec/selector.spec.ts, modules/store/spec/types/selector.spec.ts, modules/store/src/selector.ts
```
[ ] Bugfix
[x] Feature
```
Closes: #3571
```
[x] Yes
[ ] No
```
The projector method has become strict
BEFORE:
You could pass any arguments to the projector method
```ts
const selector = createSelector(
selectString, // returning a string
selectNumber, // returning a number
(s, n, prefix: string) => {
return prefix + s.repeat(n);
}
)
// you could pass any argument
selector.projector(1, 'a', true);
```
AFTER:
```ts
const selector = createSelector( …
```
=> feat(store): strict projector for selectors with props

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/src/router_selectors.ts, modules/router-store/src/serializers/minimal_serializer.ts
```
[ ] Bugfix
[x] Feature
```
The `selectTitle` selector returns only a static title. When custom title resolver is used, the `selectTitle` result is `undefined`.
Closes #3622
The `selectTitle` selector returns resolved route title when a custom title resolver is used.
```
[x] Yes
[ ] No
```
```
Property `title: string | undefined` is added to the `MinimalActivatedRouteSnapshot` interface.
BEFORE:
The `MinimalActivatedRouteSnapshot` interface doesn't …
```
=> feat(router-store): return resolved title via selectTitle

modules/effects/migrations/15_0_0-beta/index.spec.ts, modules/schematics-core/testing/create-reducers.ts, modules/schematics/src/store/files/__statePath__/index.ts.template, modules/schematics/src/store/index.spec.ts, modules/schematics/src/store/index.ts, modules/store-devtools/schematics/ng-add/index.spec.ts, modules/store-devtools/schematics/ng-add/index.ts, modules/store-devtools/src/provide-store-devtools.ts, modules/store/schematics/ng-add/files/__statePath__/index.ts.template, modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts, projects/ngrx.io/content/guide/store-devtools/index.md, projects/ngrx.io/content/guide/store-devtools/install.md, projects/standalone-app/src/main.ts
As of Angular 15.0.0 there will be no auto-generated environment files anymore. Instead, we use `isDevMode()` to detect development mode. Angular's schematics for `ServiceWorkerModule` utilize the same function.
- schematics/reducer
- schematics/store
- store/ng-add
- store-devtools/ng-add
My first attempt to create a PR – let me know about what I missed 😄 
```
[x] Bugfix
[x] Feature
```
Closes #3618
`ng-add` schematics set `!isDevMode()` for the `logOnly` option of …
=> feat(schematics): do not rely on environments to detect dev mode

projects/ngrx.io/content/guide/migration/v15.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3615
```
[ ] Yes
[X] No
```
Added titles 
Added some extra info
Reworded a few things
=> docs: few tweaks to the migration guide

modules/data/src/entity-data-without-effects.module.ts, modules/data/src/entity-data.module.ts, modules/data/src/index.ts, modules/data/src/provide-entity-data.ts
```
[ ] Bugfix
[x] Feature
```
There are two standalone functions for `@ngrx/data` package: `provideEntityData` and `provideEntityDataWithoutEffects`.
There is only one standalone function for `@ngrx/data` package - `provideEntityData`.
When it's used in the following way:
```ts
provideEntityData({ entityMetadata });
```
It provides entity data with entity configuration without effects.
When it's used with `withEffects` feature as follows:
```ts
provideEntityData({ …
```
=> feat(data): add withEffects feature for provideEntityData

modules/component/spec/let/let.directive.spec.ts, modules/component/src/let/let.directive.ts, projects/ngrx.io/content/guide/component/let.md, projects/ngrx.io/content/guide/migration/v15.md
```
[ ] Bugfix
[x] Feature
```
`LetViewContext` property names contain the `$` prefix. (`$error`, `$complete`, `$suspense`)
`LetViewContext` property names don't contain the `$` prefix. (`error`, `complete`, `suspense`)
```
[x] Yes
[ ] No
```
```
The `$` prefix is removed from `LetViewContext` property names.
BEFORE:
<ng-container *ngrxLet="obs$; $error as e; $complete as c">
...
</ng-container>
AFTER:
<ng-container *ngrxLet="obs$; error as e; …
```
=> feat(component): remove $ prefix from LetViewContext property names

modules/component/spec/let/let.directive.spec.ts, modules/component/src/let/let.directive.ts, projects/ngrx.io/content/guide/migration/v15.md
```
[ ] Bugfix
[x] Feature
```
The `LetDirective` view will not be cleared when the replaced observable is in a suspense state and the suspense template is not passed.
The `LetDirective` view will be cleared when the replaced observable is in a suspense state and the suspense template is not passed.
```
[x] Yes
[ ] No
```
The `LetDirective` view will be cleared when the replaced observable is in a suspense state. Also, the `suspense` property is …
=> feat(component): clear `LetDirective` view when replaced observable is in suspense state

projects/ngrx.io/content/guide/store/selectors.md
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #
The stated examples are inconsistend. Sometimes selectors are prefixed with `select` and sometimes with `get`
```
[ ] Yes
[x ] No
```
Alternativly one could mention that …
=> docs(store): unify selector-naming in selectors-guide

modules/data/src/dataservices/default-data-service-config.ts
explain that trailingSlashEndpoints also removes leading slahses.
Closes #3689
```
[ ] Bugfix
[ ] Feature
```
Closes #3689
```
[ ] Yes
[X] No
```
=> docs(data): improve DefaultDataServiceConfig.trailingSlashEndpoints

angular.json
```
[x] Bugfix
[ ] Feature
```
Closes #3691
The `package.json` for `@ngrx/schematics` is not updated
```
[ ] Yes
[ ] No
```
=> fix(schematics): disable package json peer dep updates during build

modules/store/spec/selector.spec.ts, modules/store/spec/types/selector.spec.ts, modules/store/src/selector.ts, projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #3677 
We're able to use the `createSelector` function with a dictionary of selectors:
```ts
export const selectUsersPageViewModel = createSelector({
users: selectUsers,
activeUser: selectActiveUser,
query: selectQuery,
isLoading: selectIsLoading,
});
```
```
[ ] Yes
[x] No
```
=> feat(store): use `createSelector` with selectors dictionary

modules/store/spec/types/action_group_creator.spec.ts, modules/store/src/action_group_creator_models.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3712
We are able to use the `createActionGroup` function with props typed as unions:
```ts
const booksApiActions = createActionGroup({
source: 'Books API',
events: {
'Load Books Success': props<{ books: string[]; status: 'success' } | { books: Book[] }>(),
},
});
// works as intended
booksApiActions.loadBooksSuccess({ books: [''], status: 'success' });
booksApiActions.loadBooksSuccess({ books: [{ id: 1, title: '' }] });
```
```
[ …
```
=> fix(store): support using `createActionGroup` with props typed as unions

angular.json, modules/eslint-plugin/package.json
```
[x] Bugfix
[ ] Feature
```
When isntallint the eslint-plugin the old v14 version of `@angular-devkit/schematics` will be installed
Closes #3709
With this fix the latest v15 version of `@angular-devkit/schematics` will be installed
```
[ ] Yes
[x] No
```
=> fix(eslint-plugin): remove @angular-devkit/schematics dependency

modules/component-store/src/component-store.ts, modules/data/src/dataservices/default-data.service.ts, modules/data/src/dataservices/entity-cache-data.service.ts, modules/data/src/dispatchers/entity-cache-dispatcher.ts, modules/data/src/dispatchers/entity-dispatcher-base.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3702 
`component-store` and `data` packages are compatible with RxJS 6.
```
[ ] Yes
[x] No
```
=> fix: revert throwError usages with factory for RxJS 6 compatibility

modules/store/src/selector.ts
The documentation comments for createSelectorFactory had a minor typo.
closes #3705 
```
[ ] Bugfix
[ ] Feature
```
Closes #3705 
Addresses a typo in the createSelectorFactory comments
```
[ ] Yes
[x] No
```
=> docs(store): fix typo for createSelectorFactory docs

modules/component-store/src/component-store.ts, modules/data/src/dataservices/default-data.service.ts, modules/data/src/dataservices/entity-cache-data.service.ts, modules/data/src/dispatchers/entity-cache-dispatcher.ts, modules/data/src/dispatchers/entity-dispatcher-base.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3702 
Packages are compatible with RxJs version 6 again.
```
[ ] Yes
[x] No
```
=> revert: replace deprecated throwError usage

projects/ngrx.io/content/guide/component-store/effect.md
effects without parameters is a common use case, but it's not trivial to find our to do with component store The added documentation will show this use case
```
[ ] Bugfix
[ ] Feature
```
Closes #3384 
```
[ ] Yes
[x] No
```
=> docs(component-store): add example for effect without parameters

modules/router-store/spec/router_selectors.spec.ts, modules/router-store/spec/types/selectors.spec.ts, modules/router-store/src/index.ts, modules/router-store/src/router_selectors.ts, projects/example-app/src/app/reducers/index.ts, projects/ngrx.io/content/examples/router-store-selectors/src/app/router.selectors.ts, projects/ngrx.io/content/guide/migration/v15.md, projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #3738 
The `getSelectors` function renamed to `getRouterSelectors`. The `getSelectors` alias is still available but is deprecated.
```
[ ] Yes
[x] No
```
=> feat(router-store): rename getSelectors to getRouterSelectors

modules/store/spec/feature_creator.spec.ts, modules/store/spec/types/feature_creator.spec.ts, modules/store/src/feature_creator.ts, modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3719 
We can add extra selectors to the feature object by using the extra selectors factory:
```ts
interface State extends EntityState<Book> {
callState: CallState;
}
export const booksFeature = createFeature({
name: 'books',
reducer: createReducer(initialState, /* case reducers */),
extraSelectors: ({ selectBooksState, selectCallState }) => ({
...adapter.getSelectors(selectBooksState),
...getCallStateSelectors(selectCallState), …
```
=> feat(store): add ability to create extra selectors with createFeature

modules/effects/spec/effect_creator.spec.ts, modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/effects_feature_module.spec.ts, modules/effects/spec/effects_metadata.spec.ts, modules/effects/spec/integration.spec.ts, modules/effects/spec/provide_effects.spec.ts, modules/effects/spec/types/effect_creator.spec.ts, modules/effects/spec/types/effects_module.spec.ts, modules/effects/spec/types/provide_effects.spec.ts, modules/effects/spec/utils.spec.ts, modules/effects/src/effect_creator.ts, modules/effects/src/effect_sources.ts, modules/effects/src/effects_feature_module.ts, modules/effects/src/effects_module.ts, modules/effects/src/effects_root_module.ts, modules/effects/src/index.ts, modules/effects/src/models.ts, modules/effects/src/provide_effects.ts, modules/effects/src/tokens.ts, modules/effects/src/utils.ts
```
[ ] Bugfix
[x] Feature
```
We are not able to create effects outside the effects classes.
Closes #3668 
We are able to create effects outside the effects class by adding `functional: true` flag within the effect config.
Examples:
```ts
// (file: users.effects.ts)
// mapping to a different action
export const loadUsers = createEffect(
(actions$ = inject(Actions), usersService = inject(UsersService)) => {
return actions$.pipe(
ofType(UsersPageActions.opened), …
```
=> feat(effects): add ability to create functional effects

projects/ngrx.io/content/guide/component-store/effect.md
Fix the verb omission in the effect example comment encouraging users to *use* a specific source stream name.
- [n/a] Tests for the changes have been added (for bug fixes / features)
- [n/a] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
The comment in the effect example for component-store has a typo of a missing word, it reads
```
We encourage to choose one of these and them consistently in your codebase.
```
Closes # …
=> docs(component-store): typo fix in effect example

modules/store/spec/feature_creator.spec.ts, modules/store/spec/types/feature_creator.spec.ts, modules/store/src/feature_creator.ts
```
[x] Bugfix
[ ] Feature
```
We can return factory selectors as `createFeature.extraSelectors` result:
```ts
export const usersFeature = createFeature({
name: 'users',
reducers: createReducer(initialState),
extraSelectors: ({ selectUsers }) => ({
selectUserById: (id: number) => createSelector(
selectUsers,
(users) => users.find((user) => user.id === id)
),
}),
});
```
```
[ ] Yes
[x] No
```
=> fix(store): support using factory selectors as extra selectors

projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Updates the mergeMap operator to exhaustMap within the effects docs to make a more realistic example with best practices.
Closes #3770
=> docs(effects): use `exhaustMap` for `loadMovies$` example

modules/store/testing/spec/mock_store.spec.ts, modules/store/testing/src/testing.ts, projects/ngrx.io/content/guide/effects/testing.md, projects/ngrx.io/content/guide/migration/v15.md, projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[x] Feature
```
Closes #3781
The `getMockStore` function renamed to `createMockStore`. The `getMockStore` alias is still available but is deprecated.
```
[ ] Yes
[x] No
```
=> feat(store): rename getMockStore to createMockStore

modules/eslint-plugin/spec/rules/prefix-selectors-with-select.spec.ts, modules/eslint-plugin/src/rules/store/prefix-selectors-with-select.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3786
```
[ ] Yes
[x] No
```
In a version for v16 this rule should also lint `extraSelectors`.
I didn't choose to address that in this PR because it could result in errors for existing applications.
=> fix(eslint-plugin): ignore select name within createFeature

modules/data/spec/dataservices/default-data.service.spec.ts, modules/data/src/dataservices/default-data.service.ts
```
[x] Bugfix
[ ] Feature
```
Http Options are incorrectly merged when users extend the DefaultDataService and override a method, adding http options to the execute call.
Closes #3794 
Http Options are correctly merged
```
[ ] Yes
[x] No
```
=> fix(data): correctly handle HttpOptions when provided

projects/ngrx.io/content/guide/component-store/initialization.md
accessing the store directly may confuse users because they might get weird behaviors when using observables like this in the state (like infinite loops), I think we should probably discourage examples that access the store directly without the select method to avoid confusion.
```
[ ] Bugfix
[ ] Feature
```
confusing example (accessing state directly) that may lead to wrong implementation if people don't read full docs
Closes #
use select method to get the state
```
[ …
```
=> docs: use select method instead of state pipe

modules/store/spec/types/feature_creator.spec.ts, modules/store/src/feature_creator_models.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3740
Projector function arguments of selectors generated by createFeature are strongly typed.
```
[x] Yes
[ ] No
```
Projectors of selectors generated by createFeature are strongly typed.
BEFORE:
Projector function arguments of selectors generated by createFeature are not strongly typed:
```ts
const counterFeature = createFeature({
name: 'counter',
reducer: createReducer({ count: 0 }),
}); …
```
=> feat(store): use strict projectors for createFeature selectors

modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts.template, modules/schematics/src/action/index.spec.ts, modules/schematics/src/data/files/__name@dasherize@if-flat__/__name@dasherize__.ts.template, modules/schematics/src/data/index.spec.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[x] Yes
[ ] No
```
BEFORE:
Schematics used the `any` type to declare some types.
AFTER:
Schematics use the `unknown` type to declare some types.
=> feat(schematics): replace `any` type with `unknown` type

modules/router-store/src/index.ts, modules/router-store/src/router_selectors.ts
Removes deprecated getSelectors method from router-store
Closes #3813
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: removes deprecated method
```
Closes #3815
The deprecated method getSelectors is removed from router-store
```
[x] Yes
[ ] No
```
Migration script for the renaming of the method is already in place.
=> feat(router-store): remove deprecated getSelectors method

modules/store/spec/types/action_group_creator.spec.ts, modules/store/src/action_group_creator_models.ts
```
[x] Bugfix
[ ] Feature
```
The action group type won't be correctly inferred when events are defined as an empty object:
```ts
const fooActions = createActionGroup({
source: 'Foo',
events: {},
});
// there is no compilation error
fooActions.x();
fooActions.y();
```
The action group type will be correctly inferred when events are defined as an empty object, so in the example above, the compilation error will be thrown.
```
[ ] Yes
[x] No
```
=> fix(store): correctly infer action group events defined as empty object

modules/effects/spec/integration.spec.ts, modules/effects/spec/utils.spec.ts, modules/effects/src/effects_module.ts, modules/effects/src/tokens.ts, modules/effects/src/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3848
We can define `USER_PROVIDED_EFFECTS` as an injection token.
```
[ ] Yes
[x] No
```
=> fix(effects): run user provided effects defined as injection token

modules/store-devtools/spec/config.spec.ts, modules/store-devtools/src/config.ts, projects/example-app/src/app/app.module.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3636
```
[ ] Yes
[ ] No
```
While testing this in a react app the behavior was identical.
Setting the `import` feature to `true` resulted in the same error.
=> fix(store-devtools): correctly import state when feature is set to true

modules/entity/spec/types/entity_selectors.types.spec.ts, modules/entity/spec/types/utils.ts, modules/entity/src/models.ts, modules/entity/src/state_selectors.ts, modules/router-store/spec/types/router_selectors.types.spec.ts, modules/router-store/src/models.ts
```
[ ] Bugfix
[x] Feature
```
Interfaces `EntitySelectors` and `RouterStateSelectors` are not compatible with `Record<string, Selector>` which is expected as `createSelector.extraSelectors` result. For example, we cannot add entity selectors to a specific feature in the following way:
```ts
export const productsFeature = createFeature({
name: 'products',
reducer: createReducer(initialState),
extraSelectors: ({ selectProductsState }) => …
```
=> feat: convert entity and router selectors interfaces to types

modules/store/spec/action_group_creator.spec.ts, modules/store/spec/helpers.spec.ts, modules/store/spec/types/action_group_creator.spec.ts, modules/store/src/action_group_creator.ts, modules/store/src/action_group_creator_models.ts, modules/store/src/helpers.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3693
All letters of the event name will be lowercase, except for the initial letters of words starting from the second word, which will be uppercase.
The initial letter of the first word of the event name will be lowercase, and the initial letters of the other words will be uppercase. The case of other letters in the event name will remain the same.
```
[x] Yes
[ ] No
```
The event name case is preserved when …
=> feat(store): preserve the event name case with createActionGroup

modules/store/spec/types/action_group_creator.spec.ts, modules/store/src/action_group_creator_models.ts, projects/ngrx.io/content/guide/store/action-groups.md
```
[ ] Bugfix
[x] Feature
```
There will be a compilation error if we try to define actions whose names contain only empty spaces or forbidden characters:
```ts
const myActionGroup = createActionGroup({
source: 'My Actions',
events: {
'': emptyProps(),
'+-*': emptyProps(),
}
});
```
There is no compilation error in the example above. The `myActionGroup` object will contain the following action creators:
```ts
store.dispatch(myActionGroup['']()); …
```
=> feat(store): remove forbidden chars and empty str checks from createActionGroup

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[ ] Bugfix
[x] Feature
```
A new signature of the `selectSignal` function is added. It creates a new signal by combining provided signals:
```ts
@Injectable()
class UsersStore extends ComponentStore<State> {
readonly users = this.selectSignal((s) => s.users);
readonly query = this.selectSignal((s) => s.query);
readonly filteredUsers = this.selectSignal(
this.users,
this.query,
(users, query) => users.filter((user) => user.name.includes(query))
);
}
```
```
[ ] Yes …
```
=> feat(component-store): add selectSignal signature that combines provided signals

modules/data/spec/dispatchers/entity-dispatcher.spec.ts, modules/data/src/dispatchers/entity-commands.ts
Mirror the type definition of EntityCollectionServiceBase.add on EntityServerCommands.add.
Closes EntityServerCommands.add does not allow optional id #3847
```
[x] Bugfix
[ ] Feature
```
`EntityServerCommands.add()` allows only full entities.
Closes #3847
`EntityServerCommands.add()` allows partial entities if non-optimistic, just like `EntityCollectionServiceBase.add()`.
```
[ ] Yes
[x] No
```
=> fix(data): make non-optimistic add command entity partial

modules/data/spec/selectors/entity-selectors$.spec.ts, modules/store/spec/store_pipes.spec.ts, modules/store/src/state.ts, modules/store/src/store.ts, modules/store/testing/src/mock_state.ts, modules/store/testing/src/mock_store.ts, projects/standalone-app/src/app/app.component.spec.ts, projects/standalone-app/src/app/app.component.ts, projects/standalone-app/src/app/test.pipe.ts
```
[x] Bugfix
[ ] Feature
```
Store.select throws an error about writing to a signal from a computed when used in a pipe. This happens when the `Store.lift` method is called when the observable flows through operators, creating a new instance of the Store. Moving the signal to the `State` service only creates only subscribes to the StateObservable once for the signal integration.
Closes #3869 
Store.select works correctly when used inside a pipe.
```
[ ] Yes
[x] No …
```
=> fix(store): move Angular Signal interop into State service

modules/store/spec/integration_signals.spec.ts, modules/store/src/store.ts
```
[x] Bugfix
[ ] Feature
```
All selectors created with `store.selectSignal()` fire on every global state change, even if the related state received no update.
Closes #3882 
If `selector(this.state())` returns the same object reference the computed Signal does not trigger a value update anymore.
```
[ ] Yes
[x] No
```
=> fix(store): add Signal equal function for immutable object comparison

modules/component-store/schematics-core/utility/standalone.ts, modules/component/schematics-core/utility/standalone.ts, modules/data/schematics-core/utility/standalone.ts, modules/effects/schematics-core/utility/standalone.ts, modules/effects/schematics/ng-add/index.spec.ts, modules/effects/schematics/ng-add/index.ts, modules/effects/schematics/ng-add/schema.json, modules/effects/schematics/ng-add/schema.ts, modules/entity/schematics-core/utility/standalone.ts, modules/router-store/schematics-core/utility/standalone.ts, modules/router-store/schematics/ng-add/index.spec.ts, modules/router-store/schematics/ng-add/index.ts, modules/router-store/schematics/ng-add/schema.json, modules/router-store/schematics/ng-add/schema.ts, modules/schematics-core/utility/standalone.ts, modules/schematics/schematics-core/utility/standalone.ts, modules/store-devtools/schematics-core/utility/standalone.ts, modules/store-devtools/schematics/ng-add/index.spec.ts, modules/store-devtools/schematics/ng-add/index.ts, modules/store-devtools/schematics/ng-add/schema.json, modules/store-devtools/schematics/ng-add/schema.ts, modules/store/schematics-core/utility/standalone.ts, modules/store/schematics/ng-add/index.spec.ts, modules/store/schematics/ng-add/index.ts, modules/store/schematics/ng-add/schema.json, modules/store/schematics/ng-add/schema.ts, projects/ngrx.io/content/guide/effects/install.md, projects/ngrx.io/content/guide/router-store/install.md, projects/ngrx.io/content/guide/store-devtools/install.md, projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
When running ng add commands
```sh
ng add @ngrx/store
ng add @ngrx/effects
ng add @ngrx/store-devtools
ng add @ngrx/router-store
```
The schematic detects where the application is using `bootstrapApplication` and applies the appropriate provider functions to the application config. Module-based setups remain the same.
```
[ ] Yes
[x] No
```
Reference code: https://github.com/angular/angular-cli/blob/c109fb6a1630983d9f775e29a9ca729 …
=> refactor: detect standalone application when using ng add

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts
```
[x] Bugfix
[ ] Feature
```
Related to #3882 
```
[ ] Yes
[x] No
```
=> fix(component-store): use default equality function for selectSignal

modules/store-devtools/spec/store.spec.ts, modules/store-devtools/src/devtools.ts, modules/store-devtools/src/instrument.ts
```
[x] Bugfix
[ ] Feature
```
`Store.selectSignal` method is not working when `store-devtools` package is used because it replaces `StateObservable` with a custom one that doesn't contain the `state` signal.
```
[ ] Yes
[x] No
```
=> fix(store-devtools): add state signal to StateObservable

modules/component/spec/push/push.pipe.spec.ts, modules/component/src/core/render-event/manager.ts
NgrxPush pipe has the same issue as async pipe: https://github.com/angular/angular/issues/50382
Can be fixed same as: https://github.com/angular/angular/pull/50522
Also added the same test that fails without the fix.
Repro: https://stackblitz.com/edit/stackblitz-starters-tapet4?file=src%2Fmain.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> fix(component): untrack subscription in ngrxPush pipe

projects/ngrx.io/src/styles/1-layouts/_sidenav.scss
```
[x] Bugfix
[ ] Feature
```
Sidenav width is increased after adding the "Entity Adapter with Feature Creator" item:
```
[ ] Yes
[x] No
```
=> fix(ngrx.io): preserve sidenav width for larger menu items

modules/component-store/spec/component-store.spec.ts, modules/component-store/src/component-store.ts, projects/ngrx.io/content/guide/component-store/read.md
```
[ ] Bugfix
[x] Feature
```
`select` uses `distinctUntilChanged` but there was no way to provide a custom equality fn.
Closes #3931
Added `equal` option to provide a custom equality function for `distinctUntilChanged` in `select` method.
```
[ ] Yes
[x] No
```
=> feat(component-store): added custom equal option in select

modules/eslint-plugin/spec/rules/no-store-subscription.spec.ts, modules/eslint-plugin/src/utils/helper-functions/utils.ts
```
[x] Bugfix
[ ] Feature
```
Currently, the eslint plugin does not detect the store, if it is injected via the new ``inject`` method
Closes #3834
Updated store detection logic to also check for stores injected via ``inject`` method from the ``@angular/core`` package
```
[ ] Yes
[x] No
```
I only updated a single spec file for now, so check if the implementation approach is okay. I'll add more test files later.
Also maybe other rules are affected as well, since for …
=> fix(eslint): fix inject function based injection not detecting store (#3834)

projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md, projects/ngrx.io/content/guide/eslint-plugin/rules/select-style.md, projects/ngrx.io/content/guide/eslint-plugin/rules/use-consistent-global-store-name.md
since this is the new official eslint-plugin for ngrx we need to add @ in front of the rule name
- [ X ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ X ] Documentation content changes
```
Closes #
```
[ ] Yes
[ X ] No
```
=> docs: update lint rule imports 

modules/store-devtools/src/devtools.ts
This commit updates the implementation of the `StoreDevtools` and adds the `ngOnDestroy` hook, which ensures the teardown of internal subscriptions. Previously, this caused an excessive memory leak because subscription callbacks created closures that captured `this`, preventing `this` from being garbage collected.
=> fix(store-devtools): resolve memory leak when devtools are destroyed

projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md, projects/ngrx.io/content/guide/eslint-plugin/rules/select-style.md, projects/ngrx.io/content/guide/eslint-plugin/rules/use-consistent-global-store-name.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
@markostanimirovic noticed that https://github.com/ngrx/platform/pull/3938 didn't make the `main` branch, but was pushed to `master` and thus never released.
This PR is the cherry pick of that commit.
We verified and the `master` branch is currently read-only to prevent this in the future.
=> docs: update lint rule imports  (#3938)

.github/ISSUE_TEMPLATE/bug-report.yml
This commit changes a text label in the file "platform\.github\ISSUE_TEMPLATE\bug-report.yml" from "Minimal reproduction of the bug/regression with instructions" to "Expected behavior".
Closes #3977
=> docs: set correct label in the bug report template

modules/store/spec/types/feature_creator.spec.ts, modules/store/src/feature_creator.ts
```
[ ] Bugfix
[ ] Feature
```
After removing deprecated `createFeature` signature with `AppState` in [this PR](https://github.com/ngrx/platform/pull/3825), the `AppState` generic is not needed anymore and can be removed from the codebase.
```
[ ] Yes
[x] No
```
=> refactor(store): remove AppState generic from Feature Creator

modules/eslint-plugin/spec/rules/use-consistent-global-store-name.spec.ts, modules/eslint-plugin/src/rules/store/use-consistent-global-store-name.ts
```
[x] Bugfix
[ ] Feature
```
Currently, use-consistent-global-store-name rule throws the following error when the rule is violated using inject
```
An unhandled exception occurred: Cannot read properties of undefined (reading 'typeAnnotation')
```
Added handling of cases where typeAnnotation does not exist.
```
[ ] Yes
[x] No
```
=> fix(eslint-plugin): support inject for use-consistent-global-store-name rule

modules/effects/spec/effect_sources.spec.ts, modules/effects/spec/utils.spec.ts, modules/effects/src/effect_notification.ts, modules/effects/src/effects_resolver.ts, modules/effects/src/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3972
It's possible to import functional effects that grouped via named imports from buildable libraries.
```
[ ] Yes
[x] No
```
=> fix(effects): register functional effects from object without prototype

modules/data/src/dataservices/data-service-error.ts
I was kind of surprised when `DataServiceError instanceof Error` returned `false` but then I saw the note in the source code (4 years ago) about how `dse instanceof DataServiceError` didn't work in unit tests when extending from `Error`.  As long as `super()` is called in the child class constructor when extending from `Error`, then `instanceof` should work fine.  I made the change, then ran the unit tests and they all passed so it seems it's ok.
This is not a big deal but it's usually good form to have `Error` in the inheritance chain of custom errors. I don't believe this is a breaking change.
=> fix(data): make DataServiceError extend from Error

build/publish-latest.ts, build/publish-next.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
No longer relies on the `angular.json` to determine which packages are published
```
[ ] Yes
[x] No
```
=> build: update packages for npm publishing

modules/eslint-plugin/spec/rules/prefer-selector-in-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> test(eslint-plugin): add inject tests for prefer-selector-in-select rule

modules/signals/spec/helpers.ts, modules/signals/spec/index.spec.ts, modules/signals/spec/select-signal.spec.ts, modules/signals/spec/signal-state.spec.ts, modules/signals/src/deep-signal.ts, modules/signals/src/index.ts, modules/signals/src/select-signal.ts, modules/signals/src/signal-state-models.ts, modules/signals/src/signal-state.ts, modules/signals/tsconfig.build.json
```
[ ] Bugfix
[x] Feature
```
Closes #3993 
```
[ ] Yes
[x] No
```
=> feat(signals): add signalState and selectSignal APIs

modules/eslint-plugin/spec/rules/updater-explicit-return-type.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> test(eslint-plugin): add inject tests for updater-explicit-return-type rule

modules/eslint-plugin/spec/rules/avoid-cyclic-effects.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test
```
Closes #3943 (this is the last rule to test)
```
[ ] Yes
[ ] No
```
=> test(eslint-plugin): add tests using inject

modules/signals/spec/helpers.ts, modules/signals/spec/patch-state.spec.ts, modules/signals/spec/signal-state.spec.ts, modules/signals/spec/signal-store-feature.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/with-hooks.spec.ts, modules/signals/spec/with-methods.spec.ts, modules/signals/spec/with-signals.spec.ts, modules/signals/spec/with-state.spec.ts, modules/signals/src/helpers.ts, modules/signals/src/index.ts, modules/signals/src/patch-state.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store-feature.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-signals.ts, modules/signals/src/with-state.ts
```
[ ] Bugfix
[x] Feature
```
Closes #4000
`signalStore` and `signalStoreFeature` functions are added to the `@ngrx/signals` package.
```
[ ] Yes
[x] No
```
=> feat(signals): add signalStore and signalStoreFeature

modules/signals/spec/signal-state.spec.ts, modules/signals/src/deep-signal.ts
```
[x] Bugfix
[ ] Feature
```
The `toDeepSignal` function accidentally creates nested signals for the `STATE_SIGNAL` property that is part of the `signalState` instance. This caused a runtime error when the `signalState` instance was used with `patchState`:
Thanks to @manfredsteyer for reporting this bug!
The `toDeepSignal` function does not create nested signals for the `STATE_SIGNAL` or any other property that is not part of the state object.
```
[ ] Yes
[x] No
```
=> fix(signals): do not create nested signals for STATE_SIGNAL property

modules/signals/spec/types/helpers.ts, modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/src/deep-signal.ts, modules/signals/src/patch-state.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store-feature.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/ts-helpers.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-signals.ts, modules/signals/src/with-state.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4065
1. `DeepSignal` result is not prettified:
```ts
const state = signalState({ user: { firstName: 'Marko' } });
const user = state.user; // type: DeepSignal<{ firstName: string }>
const firstName = user.firstName; // type: DeepSignal<string>
```
2. The state can contain function properties (`name`, `bind`, `call`, `apply`, etc.) which will throw a runtime error because signal function properties cannot be overridden.
3. Deep …
=> fix(signals): improve state type and add type tests

modules/entity/src/models.ts, modules/entity/src/state_selectors.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2751, #3172
```
[x] Yes
[ ] No
```
```
Selectors returned by the `adapter.getSelectors` signature that accepts a parent selector are strongly typed.
BEFORE:
const {
selectIds, // type: (state: object) => string[] | number[]
selectEntities, // type: (state: object) => Dictionary<Book>
selectAll, // type: (state: object) => Book[]
selectTotal, // type: (state: object) => number
} = …
```
=> fix(entity): set correct return type for getSelectors signature with parent selector

modules/store/src/store.ts
```
[ ] Bugfix
[ ] Feature
```
In v17, Angular introduced a default equality check for reference types so it's not needed to pass it anymore explicitly.
```
[ ] Yes
[x] No
```
=> refactor(store): remove default equality function

modules/component-store/src/component-store.ts
```
[ ] Bugfix
[ ] Feature
```
In v17, Angular introduced a default equality check for reference types so it's not needed to pass it anymore explicitly.
```
[ ] Yes
[x] No
```
=> refactor(component-store): remove default equality function

projects/ngrx.io/src/styles/2-modules/code/_code-theme.scss
```
[ ] Bugfix
[x] Feature
```
I have bring back the orange color for code snippets at light mode
=> docs: bring back orange color for code snippets

modules/signals/spec/get-state.spec.ts, modules/signals/src/get-state.ts, modules/signals/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Currently, it's not possible to obtain the state object as a whole, via a single signal.
Closes #4116
Using the `getState` function will return the whole state object,  via the state signal under the hood.
```ts
import { getState, signalState } from '@ngrx/signals';
const itemsState = signalState({
loading: false,
items: [] as Item[]
});
getState(itemsState);  // returns the state object
```
```
[ ] Yes
[x] No
```
=> feat(signals): add `getState` function

modules/signals/entities/src/with-entities.ts, modules/signals/spec/signal-state.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/src/deep-signal.ts, modules/signals/src/signal-state.ts, modules/signals/src/ts-helpers.ts, modules/signals/src/with-state.ts
```
[x] Bugfix
[ ] Feature
```
After some research, we realized that compilation errors that prevent creating deep signals with keys `name` or `length` (overriding Signal/Function properties) can be hard to debug, especially when migrating existing stores to the SignalStore.
```ts
// compilation error - it's not allowed to override `name` which is a property of `state` Signal
const state = signalState({ name: 'Marko' });
```
We're able to override Signal/Function …
=> fix(signals): remove state checks for better DX

modules/signals/entities/src/with-entities.ts, modules/signals/spec/get-state.spec.ts, modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/src/deep-signal.ts, modules/signals/src/get-state.ts, modules/signals/src/patch-state.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/ts-helpers.ts, modules/signals/src/with-state.ts
```
[ ] Bugfix
[x] Feature
```
Closes #4117 
We can use interfaces as state/nested slice types:
```ts
interface User {
id: number;
name: string;
}
interface State {
user: User;
}
const state = signalState<State>({
user: { id: 1, name: 'Marko' },
});
state.user // type: DeepSignal<User>
state.user.name // type: Signal<string>
```
```
[ ] Yes
[x] No
```
=> feat(signals): provide ability to use interface as state type

modules/signals/src/deep-signal.ts
```
[x] Bugfix
[ ] Feature
```
The runtime error is thrown for deep signals:
Tricky, because it's thrown in the browser, while tests pass.
There is no runtime error when accessing deep signals anymore.
```
[ ] Yes
[x] No
```
=> fix(signals): define deep signals as configurable properties

modules/signals/spec/patch-state.spec.ts, modules/signals/spec/signal-state.spec.ts, modules/signals/spec/signal-store-feature.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/spec/with-state.spec.ts, modules/signals/src/deep-signal.ts, modules/signals/src/get-state.ts, modules/signals/src/patch-state.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/state-signal.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-state.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4151 
`signalStore` and `signalState` can be used/exported in projects that have `tsconfig` with `"declaration": true`.
```
[ ] Yes
[x] No
```
This is a workaround for the following TS bug: https://github.com/microsoft/TypeScript/issues/37888
=> fix(signals): allow using signalStore and signalState in TS libs

.devcontainer/devcontainer.json, .devcontainer/ngrx.io/devcontainer.json
Changes the Microsoft image used to build the codespaces container from `typescript-node:0-16-bullseye` --> `typescript-node:0-18-bullseye`
Closes #4172
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
[X] Other... Please describe:
```
☝️ Other or build. Unsure what best fits this kind of change?
When checking out the repo via Codespaces, it crashes producing the following error:
`The engine "node" is incompatible with this module. Expected version ">=18.13.0". Got "16.20.0"`
Closes #4172
The container successfully …
=> build(codespaces): update dev-container to use node 18 image

modules/store/src/selector.ts
Principle of least surprise.
- [x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
People stumble on this notice and they have to read a long issue, rather than the actual solution
Closes #
```
[ ] Yes
[X] No
```
This issue on selector …
=> docs: Add link to migration path for selector props deprecation notice

modules/signals/spec/signal-store.spec.ts, modules/signals/src/signal-store.ts
The Signal Store saves the injection context upon instantiation and re-uses it in the `onDestroy` hook.
If the Store is provided in root, any test with an `onDestroy` hook fails with the error message: NG0205: Injector has already been destroyed.
This PR runs `onDestroy` outside of the injection context.
Since this will break any code which depends on the injection context in `onDestroy`, there will be follow-up (breaking change) feature which will provide the injection context before the hook is executed.
Discussed in: https://github.com/ngrx/platform/pull/4196
```
[x] Bugfix
[ ] Feature
[ ] CI …
```
=> fix(signals): run `onDestroy` outside of injection context

modules/signals/rxjs-interop/src/rx-method.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Performance improvements
```
`rxMethod` converts signals and static inputs into observables.
`rxMethod` does not convert signals and static inputs into observables which reduces more than 1kB.
```
[ ] Yes
[x] No
```
=> perf(signals): avoid unecessary observable conversions in rxMethod

modules/store-devtools/spec/extension.spec.ts, modules/store-devtools/src/extension.ts
From my perspective, this removes the unnecessary `eval` method to get an action's payload.
If somebody knows why the `eval` was there in the first place (no test is failing), we could provide a safer, alternative version of `unwrapAction`.
```
[x] Bugfix
[ ] Feature
```
Closes #4213
The `payload` is directly used.
```
[ ] Yes
[x] No
```
=> fix(store-devtools): replace direct with indirect `eval`

modules/signals/src/helpers.ts
Make the `excludeKeys` create only one object as it's enough for the function to work correctly. Currently the `excludeKeys` helper function creates a new object on every iteration of the non-removed keys. It's unnecessary as - before the function returns the result outside, nothing can have the reference to the newly created object. It's safe to mutate the temporarily created result.
no breaking changes, fixes #4238
```
[ ] Bugfix
[ ] Feature
```
Closes #4238
```
[ ] …
```
=> perf(signals): avoid creating unnecessary objects in excludeKeys

modules/signals/src/index.ts
expose `StateSignal` store type in order to make it easier for 3rd party extensions to wrap signal store APIs, e.g. patchState with immer immutability - generic `StateSignal<State>` is difficult to obtain via `ReturnType<typeof signalStore>` or any other way.
no breaking changes
```
```
```
[ ] Yes
[X] No
```
=> fix(signals): add `StateSignal` to the public API

modules/signals/spec/types/patch-state.types.spec.ts, modules/signals/src/patch-state.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4279
Verified with both - TS 5.3 and 5.4.
```
[ ] Yes
[x] No
```
=> fix(signals): make patchState work with TS 5.4

modules/effects/spec/types/effect_creator.spec.ts, modules/effects/spec/types/of_type.spec.ts, modules/store/spec/types/action_group_creator.spec.ts, modules/store/spec/types/feature_creator.spec.ts, modules/store/spec/types/reducer_creator.spec.ts, modules/store/src/action_creator.ts, modules/store/src/action_group_creator.ts, modules/store/src/models.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #4136
Closes #4183
```
[x] Yes
[ ] No
```
```
The Action and TypedAction interfaces are merged into one interface.
BEFORE:
There was a separation between the Action and TypedAction interfaces.
AFTER:
The Action interface accepts a generic type parameter that represents the payload type (defaults to string).
The TypedAction interface is removed.
```
=> feat(store): merge Action and TypedAction intefaces

modules/component-store/migrations/18_0_0-beta/index.spec.ts, modules/component-store/migrations/18_0_0-beta/index.ts, modules/component-store/migrations/migration.json
Migrates any `import` of `tapResponse` from `@ngrx/component-store` to `@ngrx/operators`.
I have done this in the same way as the migrator of `concatLatestFrom` in #4311. So, in the end, it is a better copy & paste.
I could also come up with a generic function that we could reuse for other potential, similar migrations.
Fixes #4261
```
[ ] Bugfix
[x] Feature
```
Closes #4261
```
[ ] Yes
[x] No
```
=> feat(component-store): add migrator for `tapResponse`

modules/operators/spec/map-response.spec.ts, modules/operators/src/index.ts, modules/operators/src/map-response.ts, projects/ngrx.io/content/guide/operators/operators.md
```
[ ] Bugfix
[x] Feature
```
```ts
export const loadAllUsers = createEffect((
actions$ = inject(Actions),
usersService = inject(UsersService)
) => {
return actions$.pipe(
ofType(UsersPageActions.opened),
exhaustMap(() => {
return usersService.getAll().pipe(
map((users) => UsersApiActions.usersLoadedSuccess({ users })),
catchError((error) =>
of(UsersApiActions.usersLoadedFailure({ error }))
)
);
})
);
});
```
Closes #4230 
```ts
import { mapResponse } from '@ngrx/operators';
export const loadAllUsers = createEffect((
actions$ = …
```
=> feat(operators): add `mapResponse`

modules/operators/src/map-response.ts
Adds JSDoc for `mapResponse`
```
[ ] Bugfix
[ ] Feature
```
Closes #4336
```
[ ] Yes
[x] No
```
=> docs(operators): add JSDoc for `mapResponse`

projects/ngrx.io/content/guide/signals/signal-state.md, projects/ngrx.io/content/guide/signals/signal-store/index.md
Clarify that the state's type must be an object literal. See referenced issue below.
Closes #4316
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(signals): clarify that signal type can only be an object literal.

modules/component-store/src/index.ts, modules/operators/spec/types/tap-response.types.spec.ts, modules/operators/spec/types/utils.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
The `tapResponse` operator has been removed from `@ngrx/component-store` in favor of the `@ngrx/operators` package.
BEFORE:
import { tapResponse } from '@ngrx/component-store';
AFTER:
import { tapResponse } from '@ngrx/operators';
=> feat(component-store): remove tapResponse operator

modules/effects/spec/provide_effects.spec.ts, modules/effects/src/index.ts, projects/example-app/src/app/core/effects/router.effects.ts, projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
The `concatLatestFrom` operator has been removed from `@ngrx/effects` in favor of the `@ngrx/operators` package.
BEFORE:
import { concatLatestFrom } from '@ngrx/effects';
AFTER:
import { concatLatestFrom } from '@ngrx/operators';
=> feat(effects): remove concatLatestFrom operator

modules/router-store/spec/types/router_selectors.types.spec.ts, modules/router-store/src/models.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4286 
```
[x] Yes
[ ] No
```
```
BEFORE:
The return type of `selectQueryParam` is `MemoizedSelector<V, string | undefined>`.
AFTER:
The return type of `selectQueryParam` now includes `string[]`, making the return type `MemoizedSelector<V, string | string[] | undefined>`.
```
=> fix(router-store): include string[] as return type for selectQueryParam

modules/signals/src/index.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4372
```
[ ] Yes
[x] No
```
=> fix(signals): export DeepSignal

modules/effects/migrations/18_0_0-beta/index.spec.ts, modules/effects/migrations/18_0_0-beta/index.ts
ChangeLog:
- Update 17.6: Remove `os.EOL`.
This commit fixes one major bug and some edge cases in the migration script.
- Reset the changes array with every file.
- Fix an issue when a file has multiple import declarations to `@ngrx/effects`.
- Print out a warning if `concatLatestFrom` is imported multiple times.
The same problem exists for the component store's migration script. I will provide a PR for that as well.
I'm afraid a new patch release is necessary. Apologies, I'm very sorry!
```
[x] Bugfix
[ ] Feature
[ ] Documentation …
```
=> fix(effects): fix bugs in migration script to v18

modules/signals/entities/src/models.ts, modules/signals/entities/src/with-entities.ts, modules/signals/spec/signal-store-feature.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/spec/with-computed.spec.ts, modules/signals/spec/with-methods.spec.ts, modules/signals/spec/with-state.spec.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/with-computed.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-state.ts, projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
```
[ ] Bugfix
[x] Feature
```
To define computed input, the `signals` property name is used:
```ts
function withN() {
return signalStoreFeature(
{ signals: type<{ l: Signal<number>; m: Signal<number> }>() },
withComputed(({ l, m }) => ({
n: computed(() => l() + m()),
}))
);
}
```
Closes #4391
To define computed input, the `computed` property name is used:
```ts
function withN() {
return signalStoreFeature(
{ computed: type<{ l: Signal<number>; m: Signal<number> }>() …
```
=> feat(signals): rename signals to computed when defining custom features with input

modules/signals/entities/spec/helpers.ts, modules/signals/entities/spec/updaters/add-entities.spec.ts, modules/signals/entities/spec/updaters/add-entity.spec.ts, modules/signals/entities/spec/updaters/remove-all-entities.spec.ts, modules/signals/entities/spec/updaters/remove-entities.spec.ts, modules/signals/entities/spec/updaters/remove-entity.spec.ts, modules/signals/entities/spec/updaters/set-all-entities.spec.ts, modules/signals/entities/spec/updaters/set-entities.spec.ts, modules/signals/entities/spec/updaters/set-entity.spec.ts, modules/signals/entities/spec/updaters/update-all-entities.spec.ts, modules/signals/entities/spec/updaters/update-entities.spec.ts, modules/signals/entities/spec/updaters/update-entity.spec.ts, modules/signals/entities/spec/with-entities.spec.ts, modules/signals/entities/src/helpers.ts, modules/signals/entities/src/index.ts, modules/signals/entities/src/models.ts, modules/signals/entities/src/updaters/add-entities.ts, modules/signals/entities/src/updaters/add-entity.ts, modules/signals/entities/src/updaters/set-all-entities.ts, modules/signals/entities/src/updaters/set-entities.ts, modules/signals/entities/src/updaters/set-entity.ts, projects/ngrx.io/content/guide/signals/signal-store/entity-management.md
```
[ ] Bugfix
[x] Feature
```
The custom entity id is defined using the `idKey` property:
```ts
const TodosStore = signalStore(
withEntities<Todo>(),
withMethods((store) => ({
addTodo(todo: Todo): void {
patchState(store, addEntity(todo, { idKey: '_id' }));
},
})
);
```
Closes #4217, #4392
The custom entity id is defined using the `selectId` function:
```ts
const selectId: SelectEntityId<Todo> = (todo) => todo._id;
const TodosStore = signalStore(
withEntities<Todo>(), …
```
=> feat(signals): replace `idKey` with `selectId` when defining custom entity ID

modules/component-store/migrations/18_0_0-beta/index.spec.ts, modules/component-store/migrations/18_0_0-beta/index.ts
ChangeLog
- 17.5.2024: Remove `os.EOL`
Fixes the migration script for `tapResponse` in v18. It is exactly the same as in #4402:
- Reset the `changes` array for each file.
- Correct handling of files with multiple import declarations to `@ngrx/component-store`.
- Add a warning when `tapResponse` is imported multiple times.
```
[x] Bugfix
[ ] Feature
```
Closes: No Issues have been reported yet
```
[ ] Yes
[x] No
```
=> fix(component-store): resolve issues in migration script to v18

modules/eslint-plugin/spec/rules/effects/no-multiple-actions-in-effects.spec.ts, modules/eslint-plugin/src/rules/effects/no-multiple-actions-in-effects.ts, modules/eslint-plugin/src/utils/helper-functions/guards.ts, modules/eslint-plugin/src/utils/selectors/index.ts
…ultiple-actions-in-effects
```
[x] Bugfix
[ ] Feature
```
Closes #4409
```
[ ] Yes
[x] No
```
=> fix(eslint-plugin): only take return statement into account with no-multiple-actions-in-effects

modules/signals/entities/spec/types/entity-config.types.spec.ts, modules/signals/entities/spec/types/helpers.ts, modules/signals/entities/spec/updaters/add-entities.spec.ts, modules/signals/entities/spec/updaters/add-entity.spec.ts, modules/signals/entities/spec/updaters/remove-entities.spec.ts, modules/signals/entities/spec/updaters/remove-entity.spec.ts, modules/signals/entities/spec/updaters/set-all-entities.spec.ts, modules/signals/entities/spec/updaters/set-entities.spec.ts, modules/signals/entities/spec/updaters/set-entity.spec.ts, modules/signals/entities/spec/updaters/update-entities.spec.ts, modules/signals/entities/spec/updaters/update-entity.spec.ts, modules/signals/entities/spec/with-entities.spec.ts, modules/signals/entities/src/entity-config.ts, modules/signals/entities/src/index.ts, projects/ngrx.io/content/guide/signals/signal-store/entity-management.md
```
[ ] Bugfix
[x] Feature
```
```ts
const selectId: SelectEntityId<Todo> = (todo) => todo.key;
const Store = signalStore(
withEntities({ entity: type<Todo>(), collection: 'todo' }),
withEntities({ entity: type<User>(), collection: 'user' }),
withMethods((store) => ({
addTodo(todo: Todo): void {
patchState(store, addEntity(todo, { collection: 'todo', selectId }));
},
addUser(user: User): void {
patchState(store, addEntity(user, { collection: 'user' }));
},
}))
);
``` …
=> feat(signals): add entityConfig function

modules/signals/entities/spec/updaters/update-all-entities.spec.ts, modules/signals/entities/spec/updaters/update-entities.spec.ts, modules/signals/entities/spec/updaters/update-entity.spec.ts, modules/signals/entities/src/helpers.ts, modules/signals/entities/src/updaters/update-all-entities.ts, modules/signals/entities/src/updaters/update-entities.ts, modules/signals/entities/src/updaters/update-entity.ts, projects/ngrx.io/content/guide/signals/signal-store/entity-management.md
```
[x] Bugfix
[ ] Feature
```
It's not possible to modify entity ID via `update*` functions. Instead, it's necessary to remove the existing one and add a new entity with an updated ID:
```ts
const myEntity = { ...entityMap()['tmp_id'], id: 'real_id' };
patchState(store, removeEntity('tmp_id'), addEntity(myEntity));
```
Closes #4235 
The `update*` updaters can be used to modify entity ID:
```ts
patchState(store, updateEntity({ id: 'tmp_id', changes: { id: 'real_id' } …
```
=> fix(signals): allow modifying entity id on update

modules/eslint-plugin/spec/rules/effects/no-multiple-actions-in-effects.spec.ts, modules/eslint-plugin/src/rules/effects/no-multiple-actions-in-effects.ts
…tions-in-effects
```
[x] Bugfix
[ ] Feature
```
Eslint rules incorrectly reports an error for the rule no-multiple-actions-in-effects for the following code:
```typescript
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { createAction, props } from '@ngrx/store';
import { of, switchMap } from 'rxjs';
const foo = createAction('foo', props<{ payload: string }>());
const bar = createAction('bar');
const baz = createAction('baz');
@Injectable() …
```
=> fix(eslint-plugin): do not report non-array returns in no-multiple-actions-in-effects

modules/signals/entities/spec/updaters/add-entities.spec.ts, modules/signals/entities/spec/updaters/add-entity.spec.ts, modules/signals/entities/spec/updaters/remove-all-entities.spec.ts, modules/signals/entities/spec/updaters/remove-entities.spec.ts, modules/signals/entities/spec/updaters/remove-entity.spec.ts, modules/signals/entities/spec/updaters/set-all-entities.spec.ts, modules/signals/entities/spec/updaters/set-entities.spec.ts, modules/signals/entities/spec/updaters/set-entity.spec.ts, modules/signals/entities/spec/updaters/update-all-entities.spec.ts, modules/signals/entities/spec/updaters/update-entities.spec.ts, modules/signals/entities/spec/updaters/update-entity.spec.ts, modules/signals/entities/spec/with-entities.spec.ts, modules/signals/spec/signal-state.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/state-source.spec.ts, modules/signals/spec/types/patch-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/src/index.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/state-source.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-methods.ts, projects/ngrx.io/content/guide/signals/faq.md, projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[x] Feature
```
SignalStore's state can be updated from the outside by default:
```ts
export const CounterStore = signalStore(
withState({ count: 0 }),
withMethods((store) => ({
setCount(count: number): void {
patchState(store, { count }); // ✅
},
}))
);
const store = inject(CounterStore);
patchState(store, { count: 10 }); // ✅
```
Closes #4405
SignalStore's state cannot be updated from the outside by default:
```ts
export const CounterStore = …
```
=> feat(signals): limit external SignalStore state updates

modules/signals/rxjs-interop/src/rx-method.ts
```
[ ] Bugfix
[x] Feature
```
In the following example:
```ts
const logNumber = rxMethod<number>(tap(console.log));
```
The `logNumber` input type is `RxMethodInput<number>`.
The `logNumber` input type is `number | Signal<number> | Observable<number>`.
```
[ ] Yes
[x] No
```
=> feat(signals): remove RxMethodInput for better readability

modules/signals/spec/state-source.spec.ts, modules/signals/src/index.ts, modules/signals/src/state-source.ts, projects/ngrx.io/content/guide/signals/signal-store/index.md, projects/ngrx.io/content/guide/signals/signal-store/state-tracking.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[x] Feature
```
There is no way to synchronously track SignalState/SignalStore's state changes.
Closes #4416
The `watchState` function is provided to synchronously track state changes:
```ts
const state = signalState({ count: 0 });
watchState(state, console.log);
// logs: { count: 0 }, { count: 1 }, { count: 2 }
patchState(state, { count: 1 });
patchState(state, { count: 2 });
```
```
[ ] Yes
[x] No
```
=> feat(signals): add watchState function

modules/store-devtools/package.json
Please check if your PR fulfils the following requirements:
```
[ ] Bugfix
[ ] Feature
```
When installing using pnpm which isolates the dependencies per default. The application will fail to start because there is no @angular/core (./rxjs-interop) available to import. 
Error:
`✘ [ERROR] Missing "./rxjs-interop" specifier in "@angular/core" package [plugin vite:dep-pre-bundle]`
and
`7 │ import { toSignal } from '@angular/core/rxjs-interop';`
Closes #4479 
Adding a peer dependency should make @angular/core available within the …
=> fix(store-devtools): add @angular/core as peer dependency

.github/workflows/ci.yml, .github/workflows/main.yml, projects/ngrx.io/src/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
First step of #4507
```
[ ] Yes
[x] No
```
First step to make sure everything is set up properly :)
This will run CircleCI and GitHub Actions side by side.
Some stats:
- Circle CI affect build (PR) 12m 28s - https://app.circleci.com/pipelines/github/ngrx/platform/3713/workflows/55e21343-4028-4ae5-8df5-34c3b6ab4ce0
- GitHub affected build (PR) 16m 18s - https://github.com/ngrx/platform/actions/runs/10742124526
- GitHub affected build (PR) …
=> ci: setup GitHub actions

projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-protected-state.md, projects/ngrx.io/content/guide/eslint-plugin/rules/signal-store-feature-should-use-generic-type.md
…eric-type
```
[ ] Bugfix
[ ] Feature
```
Closes #4502
```
[ ] Yes
[x] No
```
This PR continues the work from #4515, which was disbanded.
=> docs(eslint-plugin): add docs for signal-store-feature-should-use-generic-type

projects/ngrx.io/content/guide/signals/signal-store/testing.md, projects/ngrx.io/content/navigation.json
The formatted version is available at: https://github.com/rainerhahnekamp/ngrx/blob/docs/signals/testing/projects/ngrx.io/content/guide/signals/signal-store/testing.md.
```
[ ] Bugfix
[ ] Feature
```
Closes #4206 
```
[ ] Yes
[x] No
```
=> docs(signals): add testing guide

modules/signals/spec/signal-store.spec.ts, modules/signals/src/signal-store.ts, modules/signals/src/state-source.ts
```
[x] Bugfix
[ ] Feature
```
- The `SIGNAL` symbol is imported from the `@angular/core/primitives/signals` package. This is a private import from Angular. This causes issues syncing the NgRx Signals library into G3.
- Removes `readonly` from internal signal as this is checked at the type level
Closes #
The `SIGNAL` symbol is no longer imported from the `@angular/core/primitives/signals` package.
```
[ ] Yes
[x] No
```
=> fix(signals): remove usage of SIGNAL from @angular/core/primitives/signals package

modules/effects/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #4524
```
[ ] Yes
[x] No
```
=> fix(effects): remove @ngrx/operators from dependencies

modules/signals/spec/deep-computed.spec.ts, modules/signals/src/deep-computed.ts, modules/signals/src/index.ts, projects/ngrx.io/content/guide/signals/deep-computed.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[x] Feature
```
Closes #4202
```
[ ] Yes
[x] No
```
=> feat(signals): add deepComputed function

modules/router-store/src/router_store_config.ts
Using a const enum here triggers "Cannot access ambient const enums when 'isolatedModules' is enabled." error when "isolatedModules" is `true` in tsconfig.json.
"isolatedModules" is set to `true` by default in new Angular CLI applications.
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
=> fix(router-store): use non-const enum to allow isolatedModules tsconfig option

modules/data/src/index.ts
```
[x] Bugfix
[ ] Feature
```
Any custom implementations of `EntityCollectionDataService`, particularly those extending `DefaultDataService` have to import related interfaces with a deep import (e.g. `import { HttpOptions } from '@ngrx/data/src/dataservices/interfaces';`. Some Typescript compiler option configurations have issues with this, since it is not possible to import from specific files not mentioned in the package.json exports.
Export HttpOptions under …
=> fix(data): export HttpOptions

modules/schematics/src/container/schema.json
"feat(schematics): change standalone default to true for components"
- [ ✓] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
```
[ ] Bugfix
[✓ ] Feature
```
The default setting for generating components using schematics does not use standalone components.
Closes #4563
By default, component schematics will now generate standalone components, setting "standalone": true in schema.json.
```
[ ] Yes
[✓ ] No
```
N/A
=> feat(schematics): change standalone default to true for components

projects/ngrx.io/content/guide/signals/rxjs-integration.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(signals): add section about calling rx method in different injection ctx

projects/ngrx.io/content/guide/store-devtools/config.md, projects/ngrx.io/content/guide/store-devtools/index.md, projects/ngrx.io/content/guide/store-devtools/install.md, projects/ngrx.io/content/guide/store-devtools/recipes/exclude.md
```
[ ] Bugfix
[ ] Feature
```
`@ngrx/store-devtools` documentation is using Modules and Standalone API is stable since v16.
Closes #4470 
Updated the `@ngrx/store-devtools` documentation  to use standalone 
```
[ ] Yes
[x] No
```
=> docs: update @ngrx/store-devtools examples to standalone

modules/signals/rxjs-interop/spec/rx-method.spec.ts, modules/signals/rxjs-interop/src/rx-method.ts, projects/ngrx.io/content/guide/signals/rxjs-integration.md
```
[ ] Bugfix
[x] Feature
```
The `unsubscribe` method from `rxMethod` is renamed to `destroy`.
```
[x] Yes
[ ] No
```
```
The `unsubscribe` method from `rxMethod` is renamed to `destroy`.
BEFORE:
const logNumber = rxMethod<number>(tap(console.log));
const num1Ref = logNumber(interval(1_000));
const num2Ref = logNumber(interval(2_000));
// destroy `num1Ref` after 2 seconds
setTimeout(() => num1Ref.unsubscribe(), 2_000);
// destroy all reactive method …
```
=> feat(signals): rename `rxMethod.unsubscribe` to `destroy`

modules/signals/spec/deep-freeze.spec.ts, modules/signals/src/deep-freeze.ts, modules/signals/src/signal-state.ts, modules/signals/src/state-source.ts, modules/signals/src/with-state.ts
Alternative version to protected the state from mutable changes via `Object.freeze`.
```
[ ] Bugfix
[x] Feature
```
Mutable changes in `patchState` don't trigger any kind of warning
Closes #4030
In development mode (`ngDevMode`), `Object.freeze` is applied to the state, causing a runtime error on a mutable change.
```
[x] Yes
[ ] No
```
```
The `patchState` function applies a deep freeze on the state in dev mode.
BEFORE:
const userState = …
```
=> feat(signals): throw error in dev mode on state mutation

projects/ngrx.io/content/guide/signals/signal-state.md, projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4451
```
[ ] Yes
[x] No
```
=> docs(signals): add info about throwing error on state mutation in dev mode

modules/store/spec/store.spec.ts, modules/store/spec/types/store.spec.ts, modules/store/src/helpers.ts, modules/store/src/models.ts, modules/store/src/store.ts, projects/ngrx.io/content/guide/store/actions.md
A type of Signal<Action> can be passed to dispatch:
```typescript
class BookComponent {
bookId = input.required<number>();
bookAction = computed(() => loadBook({id: this.bookId()}));
store = inject(Store);
constructor() {
this.store.dispatch(this.bookAction);
}
}
```
The benefit is that users no longer need to use an effect to track the Signal. The Store handles this internally.
If `dispatch` receives a `Signal` it returns an `EffectRef`, allowing manual destruction.
By default, the injection context of the caller is used. If the call happens outside an injection context, the Store will use its own injection context, which is usually the root injector.
It is also possible to provide a custom injector as the second parameter:
```typescript
this.store.dispatch(this.bookAction, {injector: …
```
=> feat(store): enable dispatching actions on signal changes

modules/signals/entities/src/index.ts, modules/signals/entities/src/models.ts, modules/signals/entities/src/with-entities.ts, modules/signals/spec/signal-store-feature.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/spec/with-computed.spec.ts, modules/signals/spec/with-props.spec.ts, modules/signals/src/index.ts, modules/signals/src/signal-store-assertions.ts, modules/signals/src/signal-store-feature.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/with-computed.ts, modules/signals/src/with-hooks.ts, modules/signals/src/with-props.ts, modules/signals/src/with-state.ts, projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md, projects/ngrx.io/content/guide/signals/signal-store/custom-store-properties.md, projects/ngrx.io/content/guide/signals/signal-store/index.md, projects/ngrx.io/content/guide/signals/signal-store/private-store-members.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[x] Feature
```
Closes #4504
- The `computed` property in `SignalStoreFeatureResult` type is renamed to `props`.
- The `EntityComputed` and `NamedEntityComputed` types in the `entities` plugin are renamed to `EntityProps` and `NamedEntityProps`.
```
[x] Yes
[ ] No
```
```
- The `computed` property in `SignalStoreFeatureResult` type is renamed to `props`.
- The `EntityComputed` and `NamedEntityComputed` types in the `entities` plugin are …
```
=> feat(signals): add `withProps` base feature

modules/signals/spec/signal-method.spec.ts, modules/signals/src/index.ts, modules/signals/src/signal-method.ts, projects/ngrx.io/content/guide/signals/signal-method.md, projects/ngrx.io/content/navigation.json
`signalMethod` is a factory function to process side effects on Signals or static values.
It is similar to `rxMethod` but does not support RxJS.
`signalMethod` follows Angular's pattern of RxJS-less utilities for Signals, like `resource` and `rxResource`.
`signalMethod` expects a type and processor function:
```typescript
const doubleLogger = signalMethod<number>(value => console.log(value * 2))
const value = signal(1);
doubleLogger(value); // tracks value and executes initially and on every change
```
It also supports static values, e.g., `doubleLogger(1)`.
This PR also contains the documentation and tests.
```
[ ] Bugfix
[x] Feature …
```
=> feat(signals): add `signalMethod`

projects/ngrx.io/content/guide/migration/v19.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4591
```
[ ] Yes
[x] No
```
=> docs: add breaking changes to v19 migration

projects/ngrx.io/content/guide/component-store/comparison.md, projects/ngrx.io/content/guide/component-store/effect.md, projects/ngrx.io/content/guide/component-store/index.md, projects/ngrx.io/content/guide/component-store/initialization.md, projects/ngrx.io/content/guide/component-store/install.md, projects/ngrx.io/content/guide/component-store/lifecycle.md, projects/ngrx.io/content/guide/component-store/read.md, projects/ngrx.io/content/guide/component-store/usage.md, projects/ngrx.io/content/guide/component-store/write.md, projects/ngrx.io/content/marketing/docs.md, projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(component-store): add alert about NgRx Signals

projects/ngrx.io/content/guide/store/index.md, projects/ngrx.io/content/guide/store/why.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(store): recommend using NgRx Signals instead of ComponentStore

modules/signals/rxjs-interop/spec/rx-method.spec.ts
Refactor the tests for `rxMethod` to avoid component navigation when testing the behavior of switching injection contexts.
Rename the `signalMethod` method in the testing service to `trackSignal` for better readability.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor(signals): improve `rxMethod` tests by using child injectors

modules/store-devtools/src/instrument.ts, modules/store-devtools/src/provide-store-devtools.ts
This change resolves the cyclical import dependency `store-devtools/src/{provide-store-devtools <-> instrument}.ts` by moving `createStateObservable` to `provide-store-devtools.ts`, its only user.
```
[ ] Bugfix
[ ] Feature
```
The import cycle breaks TS language tools/environments (e.g. Google's TS build) that don't support cyclical imports. 
Support TS language tools/environments that don't support cyclical imports.
```
[ ] Yes
[x] No
```
=> refactor(store-devtools): resolve import cycle to improve tool compatibility

modules/signals/spec/deep-freeze.spec.ts, modules/signals/spec/signal-store.spec.ts, modules/signals/spec/state-source.spec.ts, modules/signals/spec/with-computed.spec.ts, modules/signals/spec/with-methods.spec.ts, modules/signals/spec/with-props.spec.ts, modules/signals/spec/with-state.spec.ts, modules/signals/src/deep-freeze.ts, modules/signals/src/signal-store-assertions.ts, modules/signals/src/signal-store-models.ts, modules/signals/src/signal-store.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-props.ts, modules/signals/src/with-state.ts
Resolve an issue in `signalStore` that prevented Symbols from being added as property keys when merging
different features.
```
[x] Bugfix
[ ] Feature
```
The value is just undefined.
Closes #4655
```
[ ] Yes
[x] No
```
=> fix(signals): enable `withProps` to handle Symbols

modules/component-store/package.json, modules/component/package.json, modules/data/package.json, modules/effects/package.json, modules/entity/package.json, modules/eslint-plugin/package.json, modules/operators/package.json, modules/router-store/package.json, modules/schematics/package.json, modules/signals/package.json, modules/store-devtools/package.json, modules/store/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #4682
```
[ ] Yes
[ ] No
```
According to the docs this should fix it, https://github.com/angular/angular-cli/blob/main/docs/specifications/update.md#migration . I don't know a way to test this though without releasing a new version.
=> build: set explicit packageGroupName's

.github/workflows/main.yml, build/deploy-build.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #4507
```
[ ] Yes
[x] No
```
This PR pushes the dist folders to the nightly build repositories using the `deploy` step.
The additional changes in the commit is because I switched the `build` and the `schematics-core-check` in order, to keep the deploy close to the build step.
I did not test this, I assume `webfactory/ssh-agent@v0.9.0` does the same as setting the fingerprint with CicleCi.
=> ci: deploy nightly builds

modules/signals/entities/src/helpers.ts, modules/signals/src/signal-store-assertions.ts
```
[x] Bugfix
[ ] Feature
```
Error is thrown when the `ngDevMode` global variable is not defined.
Closes #4699
SignalStore assertions are skipped when the `ngDevMode` global variable is not defined.
```
[ ] Yes
[x] No
```
=> fix(signals): skip assertions when ngDevMode is not defined

modules/signals/spec/with-feature.spec.ts, modules/signals/src/index.ts, modules/signals/src/with-feature.ts, projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
`withFeature` adds the possibility to pass on signals, methods, or properties from a store to a custom feature.
```
[ ] Bugfix
[x] Feature
```
Closes #4678
```
[ ] Yes
[x] No
```
=> feat(signals): add `withFeature`

modules/eslint-plugin/project.json, modules/eslint-plugin/schematics/ng-add/index.ts, modules/eslint-plugin/spec/rules/component-store/require-super-ondestroy.spec.ts, modules/eslint-plugin/spec/schematics/ng-add.spec.ts, modules/eslint-plugin/src/rules/component-store/require-super-ondestroy.ts, modules/eslint-plugin/test-setup.ts, modules/eslint-plugin/tsconfig.spec.json, modules/eslint-plugin/vite.config.mts
```
[ ] Bugfix
[ ] Feature
```
Unit tests for eslint-plugin are run with Jest.
Closes #
Unit tests for eslint-plugin are run with Vitest.
```
[ ] Yes
[x] No
```
=> test(eslint-plugin): migrate from Jest to Vitest

modules/eslint-plugin/schematics/ng-add/index.ts, modules/eslint-plugin/spec/schematics/ng-add.spec.ts
```
[ ] Bugfix
[x] Feature
```
The current schematic only supports the "old" ESLint configuration, which exists in a JSON file.
Closes #4643
This PR adds support to add the NgRx plugin to the flat config (Eslint v9.
It supports the following formats:
- eslint.config.js
- eslint.config.mjs
- eslint.config.cjs
```
[ ] Yes
[x] No
```
=> feat(eslint-plugin): add schematic support for flat configs

modules/signals/spec/signal-method.spec.ts
Small improvements in signal method tests:
- Test "does not cause issues if destroyed signalMethodFn contains destroyed effectRefs" - summand2 should be set with different value so the effect is triggered for summand2 and it is not triggered for summand1, which uses the detroyed Injector. Otherwise it causes confusion that may be also the second summand is not "observed" from the effect. It is, but the set is called with the same value.
- Test "uses the provided injector (source injector) on creation" - one small additional same expect to show that after the destroy of Injector, the signal is not tracked in the effect.
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```
=> test(signals): improve signalMethod injector tests

modules/signals/spec/with-computed.spec.ts, modules/signals/spec/with-methods.spec.ts, modules/signals/spec/with-props.spec.ts, modules/signals/spec/with-state.spec.ts
Small improvements in tests - after migration from jest to vitest, there are still calls to mockImplementation without corresponding param, which is required. It should have respective param, otherwise IDEs (mine is VS Code) shows errors. The tests run successfully also without this fix, but the code base would be cleaner.
```
[ ] Bugfix
[ ] Feature
[ x] Refactoring (no functional changes, no api changes)
```
Tests run successfully, but IDEs show errors.
Closes #
Tests run successfully and no error in IDEs.
```
[ ] Yes
[x ] …
```
=> test(signals): improve tests with mockImplementation without param

modules/signals/spec/types/with-computed.types.spec.ts, modules/signals/spec/with-computed.spec.ts, modules/signals/src/with-computed.ts, projects/ngrx.io/content/guide/signals/signal-store/index.md
Example:
```ts
const CounterStore = signalStore(
withState({ count: 0 }),
withComputed(({ count }) => ({
doubleCount: () => count() * 2,
})),
);
```
- Updated withComputed to automatically wrap functions in computed signals.
- Added tests to verify automatic computation and mixing user-defined computeds.
- Improved documentation to clarify the factory function's return type.
```
[ ] Bugfix
[x] Feature
```
Closes #4782
```
[ ] Yes
[x] No
```
=> feat(signals): enhance `withComputed` to accept computation functions

modules/entity/spec/types/entity_state.types.spec.ts, modules/entity/src/entity_state.ts, modules/entity/src/models.ts, modules/store/src/selector.ts, nx.json
```
[ ] Bugfix
[x] Feature
```
Closes #4422
When initializing an EntityAdapter<T> and subsequently setting the initialState using ...adapter.getInitialState({ <additional state here>}), it is possible, given the current interface, to introduce unknown variables that do not conform to the user's specified state. This could result in bugs related to mistyped variable names, resulting in confusing user error scenarios.
This small change modifies the interface to require …
=> feat(entity): strengthen typing of getInitialState

modules/signals/spec/types/with-computed.types.spec.ts, modules/signals/spec/with-computed.spec.ts, modules/signals/src/with-computed.ts, projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[x] Feature
```
`withComputed` doesn't have access to `methods`
Closes #4846
```
[ ] Yes
[x] No
```
=> feat(signals): allow access to methods in `withComputed`

modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/src/deep-signal.ts
```
[x] Bugfix
[ ] Feature
```
The NgRx Signals package utilizes the internal `Signal` type, which extends the Angular `Signal` type, to enable deep signals with properties `name` and `length`.
Internal `Signal` type is not necessary anymore. The type of deep signals with properties `name` and `length` is correctly inferred in the latest TypeScript and Angular versions.
```
[ ] Yes
[x] No
```
=> fix(signals): remove internal Signal type

modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/src/ts-helpers.ts
```
[x] Bugfix
[ ] Feature
```
`DeepSignal` is created for empty objects and unknown records with symbol keys.
`Signal` is created for empty objects and unknown records with symbol keys.
```
[ ] Yes
[x] No
```
=> fix(signals): do not create deep signals for empty objects and unknown records with symbol keys

modules/signals/spec/signal-store.spec.ts, modules/signals/spec/state-source.spec.ts, modules/signals/spec/types/signal-state.types.spec.ts, modules/signals/spec/types/signal-store.types.spec.ts, modules/signals/spec/types/with-linked-state.types.spec.ts, modules/signals/spec/with-linked-state.spec.ts, modules/signals/spec/with-state.spec.ts, modules/signals/src/signal-state.ts, modules/signals/src/signal-store.ts, modules/signals/src/state-source.ts, modules/signals/src/with-linked-state.ts, modules/signals/src/with-state.ts, projects/ngrx.io/content/guide/migration/v20.md, projects/ngrx.io/content/guide/signals/signal-state.md, projects/ngrx.io/content/guide/signals/signal-store/index.md, projects/ngrx.io/content/guide/signals/signal-store/linked-state.md, projects/www/src/app/pages/guide/migration/v20.md
```
[ ] Bugfix
[x] Feature
```
Closes #4863
```
[x] Yes
[ ] No
```
```
User-defined `WritableSignal`s are not allowed in `withState` and `signalState` anymore.
BEFORE:
// signalState:
const state = signalState({ ngrx: signal('rocks') });
state.ngrx // type: Signal<string>
// withState:
const Store = signalStore(withState({ ngrx: signal('rocks') })); const store = new Store();
store.ngrx // type: Signal<string>
AFTER:
// signalState:
const state = …
```
=> feat(signals): disallow user-defined signals in withState and signalState

modules/component/spec/core/tick-scheduler.spec.ts, modules/component/src/core/tick-scheduler.ts
…stead of requestAnimationFrame
```
[X] Bugfix
[ ] Feature
```
When using either ngrxLet or ngrxPush in ssr and zoneless, the server calls `requestAnimationFrame` which does not exist in a node environment. 
Closes #4902
Within a node environment ( ssr ) and zoneless we use setTimeout instead of requestAnimationFrame.
```
[ ] Yes
[X] No
```
I did some more testing on angular v20, when using ssr + zoneless and using a `NoopTickScheduler` it does trigger changes. I opted …
=> fix(component): use setTimeout instead of requestAnimationFrame in SSR mode

projects/www/src/app/components/footer.component.ts, projects/www/src/app/components/menu.component.ts, projects/www/src/app/pages/(home).page.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
I noticed we don't have a sponsor link on the new website.
This replaces the (not implemented) support link to a sponsor link.
```
[ ] Yes
[x] No
```
=> docs(www): replace support link with sponsor link

modules/signals/src/signal-store-assertions.ts, modules/signals/src/with-linked-state.ts, modules/signals/src/with-methods.ts, modules/signals/src/with-props.ts, modules/signals/src/with-state.ts
The `assertUniqueStoreMembers` method previously used an early-return guard:
```js
if (!ngDevMode) return;
// dev-only code ...
```
In production builds, `ngDevMode` is replaced with `false`, so the guard compiles to `return;`. However, bundlers like ESBuild still keep the remaining statements after the return as unreachable code instead of removing them. This leaves behind unnecessary dead code in the output.
Technically, the body is unreachable. But to prove that, the bundler must be 100% certain that:
- `return` cannot be removed by some transform
- there's no later transformation that changes control flow
As thus, it's always conservative.
This commit updates the method to instead wrap the full function:
```js
if (ngDevMode) {
// assertUniqueStoreMembers ...
}
```
=> fix(signals): drop `assertUniqueStoreMembers` in production

modules/signals/events/src/inject-dispatch.ts, modules/signals/rxjs-interop/src/rx-method.ts, modules/signals/src/signal-method.ts, modules/signals/src/state-source.ts
Angular itself wraps `assertInInjectionContext()` (and similar helpers) in `ngDevMode` so that:
- In dev builds → the assertion runs, catches mistakes early, and gives clear errors.
- In prod builds → the code gets tree-shaken away, leaving no overhead.
=> fix(signals): drop `assertInInjectionContext` in production

modules/eslint-plugin/spec/rules/store/prefix-selectors-with-select.spec.ts, modules/eslint-plugin/src/rules/store/prefix-selectors-with-select.ts
```
[ ] Bugfix
[X] Feature
```
Closes #4845 
ESLint will now complain when destructuring is used with incorrect names.  The rule will likely not work with nested destructuring or other advanced / edge cases.
```
[ ] Yes
[X] No
```
=> feat(eslint-plugin): enhance prefix-selectors-with-select to handle destructuring  

modules/signals/src/with-feature.ts
Minor refactor to use dot-notation instead of brackets for accessing the properties of the `store` object
=> refactor(signals): use dot-notation to access properties in withFeature
