ngrx/platform

- angular.json
```
[ ] Bugfix
[ ] Feature
```
The `CNAME` file was not being included in the build, causing next.ngrx.io to not be displayed after nightly builds are run.
Closes #
```
[ ] Yes
[x] No
```
> build: add missing files to build for next.ngrx.io

- modules/store/spec/runtime_checks.spec.ts
- modules/store/spec/runtime_checks_meta_reducers.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> test(store): enable USER_RUNTIME_CHECKS Token tests

- projects/ngrx.io/content/guide/store/configuration/runtime-checks.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: changed the number of runtime checks from 5 to 6

- modules/store/src/reducer_creator.ts
docs(store): update createReducer docs to make its usage more clear WRT View Engine AOT
fixes 2241
```
[ ] Bugfix
[ ] Feature
```
Closes #2241 (even though the issue has been closed, the docs have not been updated properly)
```
[ ] Yes
[x] No
```
> docs(store): update createReducer docs to make its usage more clear

- modules/component-store/src/debounce-sync.ts
Adjust the error callback. Since it shouldn't be returning the value, wrap it in the function body.
Linter within G was complaining about it.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(component-store): adjust error callback

- nx.json
- package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #
Discussed with the team to add distributed caching with Nx Cloud.
```
[ ] Yes
[ ] No
```
> build: add distributed caching with Nx Cloud

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> build: skip cache for package builds

- projects/ngrx.io/content/navigation.json
Closes #2564
```
[ ] Bugfix
[ ] Feature
```
Closes #2564 
```
[ ] Yes
[X] No
```
> docs: reorganize sidenav into 3 groups

- build/update-version-numbers.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #2601
```
[ ] Yes
[ ] No
```
> build: update peer dependencies

- projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: update install instructions for ng add

- projects/ngrx.io/content/guide/data/install.md
- projects/ngrx.io/content/guide/effects/install.md
- projects/ngrx.io/content/guide/entity/install.md
- projects/ngrx.io/content/guide/router-store/install.md
- projects/ngrx.io/content/guide/schematics/install.md
- projects/ngrx.io/content/guide/store-devtools/install.md
- projects/ngrx.io/content/guide/store/install.md
```
[ ] Bugfix
[ ] Feature
```
Follow-up PR to #2612
```
[ ] Yes
[x] No
```
> docs: update ng add latest

- modules/component-store/schematics-core/utility/visitors.ts
- modules/component/schematics-core/utility/visitors.ts
- modules/data/schematics-core/utility/visitors.ts
- modules/effects/schematics-core/utility/visitors.ts
- modules/entity/schematics-core/utility/visitors.ts
- modules/router-store/schematics-core/utility/visitors.ts
- modules/schematics-core/utility/visitors.ts
- modules/schematics/schematics-core/utility/visitors.ts
- modules/store-devtools/schematics-core/utility/visitors.ts
- modules/store/schematics-core/utility/visitors.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2631
```
[ ] Yes
[x] No
```
> fix(schematics): add safety check to decorator visitor 

- projects/ngrx.io/.firebaserc
```
[ ] Bugfix
[ ] Feature
```
Closes #2557 
Just sets the archive site for the version 9 release
```
[ ] Yes
[x] No
```
> chore: add v9 archive release to firebase config

- modules/component-store/schematics/ng-add/index.spec.ts
- modules/component/schematics/ng-add/index.spec.ts
- modules/data/schematics/ng-add/index.spec.ts
- modules/effects/migrations/6_0_0/index.spec.ts
- modules/effects/migrations/9_0_0/index.spec.ts
- modules/effects/schematics/ng-add/index.spec.ts
- modules/entity/migrations/6_0_0/index.spec.ts
- modules/entity/schematics/ng-add/index.spec.ts
- modules/router-store/migrations/6_0_0/index.spec.ts
- modules/router-store/migrations/8_0_0/index.spec.ts
- modules/router-store/migrations/9_0_0/index.spec.ts
- modules/router-store/schematics/ng-add/index.spec.ts
- modules/schematics/migrations/6_0_0/index.spec.ts
- modules/schematics/src/action/index.spec.ts
- modules/schematics/src/data/index.spec.ts
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/entity/index.spec.ts
- modules/schematics/src/feature/index.spec.ts
- modules/schematics/src/ng-add/index.spec.ts
- modules/schematics/src/reducer/index.spec.ts
- modules/schematics/src/selector/index.spec.ts
- modules/schematics/src/store/index.spec.ts
- modules/store-devtools/migrations/6_0_0/index.spec.ts
- modules/store-devtools/schematics/ng-add/index.spec.ts
- modules/store/migrations/6_0_0/index.spec.ts
- modules/store/migrations/8_0_0-beta/index.spec.ts
- modules/store/migrations/8_0_0-rc/index.spec.ts
- modules/store/schematics/ng-add/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> chore: update schematics tests to use async await with async schematic test runner

- projects/ngrx.io/content/guide/migration/v10.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #2559
```
[ ] Yes
[ ] No
```
> docs: add v10 migration guide

- modules/data/schematics/ng-add/index.spec.ts
- modules/effects/schematics/ng-add/index.spec.ts
- modules/router-store/schematics/ng-add/index.spec.ts
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/store/index.spec.ts
- modules/store-devtools/schematics/ng-add/index.spec.ts
- modules/store/migrations/8_0_0-rc/index.spec.ts
- modules/store/schematics/ng-add/index.spec.ts
- modules/store/src/globals.ts
Mutable exports can create hard to understand and debug code, in particular with re-exports across multiple modules. `export let` is strongly discouraged (and not allowed within g3).
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(store): export variables should be const

- projects/ngrx.io/content/guide/component-store/index.md
- projects/ngrx.io/content/guide/component-store/initialization.md
- projects/ngrx.io/content/guide/component-store/install.md
- projects/ngrx.io/content/guide/component-store/read.md
- projects/ngrx.io/content/guide/component-store/write.md
- projects/ngrx.io/content/navigation.json
Sections for initializing, reading and updating ComponentStore.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): init, read, write sections

- .circleci/config.yml
- build/publish-next.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
- Switches over from Bazel to a more vanilla command to publish the packages to NPM.
- Fixes the CircleCI config to allow auto-deployment
```
[x] Yes
[] No
```
> build: update deployment script for publishing to next on NPM

- projects/ngrx.io/content/guide/component-store/effect.md
- projects/ngrx.io/content/guide/component-store/initialization.md
- projects/ngrx.io/content/guide/component-store/read.md
- projects/ngrx.io/content/guide/component-store/write.md
Adds docs for `effect` and `setState` methods.
Corrects some issues with code examples
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): add docs for effect

- projects/ngrx.io/content/guide/component-store/effect.md
- projects/ngrx.io/content/guide/component-store/initialization.md
- projects/ngrx.io/content/guide/component-store/install.md
- projects/ngrx.io/content/guide/component-store/read.md
- projects/ngrx.io/content/guide/component-store/write.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(component-store): grammar and style changes

- .circleci/config.yml
- build/publish-next.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> build: fix deployment script for next

- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/component/spec/core/cd-aware/render_creator.spec.ts
- modules/component/spec/core/utils/has-zone.spec.ts
- modules/component/spec/let/let.directive.spec.ts
- modules/component/spec/push/push.pipe.spec.ts
- modules/component/src/core/cd-aware/creator_render.ts
- modules/component/src/core/cd-aware/index.ts
- modules/component/src/core/index.ts
- modules/component/src/core/utils/index.ts
- modules/component/src/index.ts
- modules/component/src/let/index.ts
- modules/component/src/let/let.directive.ts
- modules/component/src/push/index.ts
- modules/component/src/push/push.pipe.ts
- modules/component/src/reactive-component.module.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2643 
Public API are explicitly exported instead of using barrels.
```
[ ] Yes
[x] No
```
> refactor(component): remove barrels from exporting to the public API

- projects/ngrx.io/package.json
- projects/ngrx.io/tools/transforms/angular-api-package/index.js
- projects/ngrx.io/tools/transforms/authors-package/api-package.js
- projects/ngrx.io/yarn.lock
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Update the deps for docs API generations and add "ComponentStore" for API generations (thanks @LayZeeDK !)
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): generate API for CS, update docs deps

- projects/ngrx.io/content/guide/component-store/comparison.md
- projects/ngrx.io/content/guide/component-store/install.md
- projects/ngrx.io/content/guide/component/index.md
- projects/ngrx.io/content/guide/component/install.md
- projects/ngrx.io/content/guide/component/let.md
- projects/ngrx.io/content/guide/component/push.md
- projects/ngrx.io/content/guide/migration/v10.md
- projects/ngrx.io/content/guide/nightlies.md
- projects/ngrx.io/content/guide/store/index.md
- projects/ngrx.io/content/guide/store/why.md
- projects/ngrx.io/content/marketing/docs.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
- Cleans up various docs pages
- Restructures intro page to talk more generally about NgRx vs just NgRx Store
- Moves intro content to `Why use Store?` page
```
[ ] Yes
[x] No
```
> docs: cleaned up docs pages and restructured intro page

- projects/ngrx.io/content/guide/component/install.md
- projects/ngrx.io/content/guide/entity/install.md
- projects/ngrx.io/content/guide/migration/v10.md
- projects/ngrx.io/content/guide/store/why.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: grammar

- projects/ngrx.io/content/guide/component/install.md
```
[ ] Bugfix
[ ] Feature
```
just correct installation cmd line
> docs(component): install @ngrx/component

- projects/ngrx.io/content/guide/component-store/write.md
I thought the example was a bit confusing, and most likely just a mistake. This small change just updates the example code to what I think the intention was.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(component-store): update setState updater example code

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: fix typo in resources.json

- projects/ngrx.io/content/guide/component/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
a small PR containing correction of a sentence, which I found while going through the "@ngrx/component" docs
> docs: sentence correction for @ngrx/component

- projects/ngrx.io/content/guide/component-store/read.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Change `readonly movies$:<Movie[]> Observable = this.select(state => state.movies);` to `readonly movies$: Observable<Movie[]> = this.select(state => state.movies);`
> docs(component-store): fix syntax error of sample code

- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add links to the NgRx discord server and swag store

- projects/ngrx.io/content/guide/component-store/comparison.md
Minor change to the sentence structure which did not make sense. 
changed from: 'Would the be changing frequently?'
changed to: 'Would it be frequently changing?'
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> unclear sentence.

- modules/component/package.json
Added the entry point for the schematic so that the error is resolved.
- [ X The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
```
[X ] Bugfix
[ ] Feature
```
When running ng add @ngrx/component you will see an error
Closes #2683 
Because we've added the entrypoint we should not see the error any more.
```
[ ] Yes
[x ] No
```
> fix(component): add entry point for schematic

- projects/ngrx.io/content/guide/component-store/read.md
```
[ ] Bugfix
[ ] Feature
```
Code snippet in `Debounce selectors` [part of Component Store docs](https://ngrx.io/guide/component-store/read#debounce-selectors) contains duplicated method names. Presumably, it's a typo and the second method name should be changed.
Closes #
The typo is fixed
```
[ ] Yes
[x] No
```
> docs(component-store): fix typo in component store docs

- projects/ngrx.io/content/guide/component/let.md
```
[ ] Bugfix
[ ] Feature
```
Tiny typo in ngrxLet usage guide
Closes #
Typo is fixed ✅
```
[ ] Yes
[x] No
```
> docs(component): fix typo in ngrxLet usage guide

- README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
Adds a discord badge to the README
```
[ ] Yes
[x] No
```
> docs: add discord server to README

- projects/ngrx.io/content/guide/store/index.md
The tutorial doesn't explicitly match the live example. Adding some clarity for newbies like myself. Thank you.
- [x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x ] No
```
> docs(example): live example doesn't match tutorial

- projects/ngrx.io/content/marketing/contributing.md
- Add instructions to run `prettier` on live examples
- Add a note about potential Design Doc and smaller PRs
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: contributing guide - prettier - small PRs

- CONTRIBUTING.md
Documentation change only for contributing
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(contributing): add commands to run specific unit tests

- projects/ngrx.io/content/guide/store/selectors.md
…t link
- [ X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
RxJS pipeable operators link select doc give 404
Closes #
RxJS pipeable operators link is working now
```
[ ] Yes
[ X] No
```
> docs: fix pipeable operators link

- .prettierignore
Followup to https://github.com/ngrx/platform/pull/2697#issuecomment-685861779
Add prettier auto-formatting to the live examples from docs.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: adjust prettier not to ignore examples

- projects/example-app/src/app/auth/containers/login-page.component.ts
- projects/example-app/src/app/auth/services/auth-guard.service.ts
- projects/example-app/src/app/books/containers/collection-page.component.ts
- projects/example-app/src/app/books/containers/find-book-page.component.ts
- projects/example-app/src/app/books/containers/selected-book-page.component.ts
- projects/example-app/src/app/books/guards/book-exists.guard.ts
- projects/example-app/src/app/core/containers/app.component.ts
- projects/ngrx.io/content/examples/store/src/app/my-counter/my-counter.component.ts
- projects/ngrx.io/content/examples/testing-store/src/app/user-greeting.component.ts
- projects/ngrx.io/content/guide/data/entity-collection-service.md
- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/store/index.md
- projects/ngrx.io/content/guide/store/recipes/downgrade.md
- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2710
```
[ ] Yes
[x] No
```
> docs: remove usage of select operator in favor of store.select

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: fix small typos in effects

- projects/ngrx.io/content/guide/store/why.md
```
[ ] Bugfix
[ ] Feature
```
Closes # N/A
Fixed grammar and sentence structure to further clarify concepts on the page.
```
[ ] Yes
[x] No
```
> docs: Grammar/sentence structure fixes

- projects/ngrx.io/src/404-body.html
- projects/ngrx.io/src/app/layout/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Saw a missed opportunity 😋
> docs: update footer year to 2020

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Library is not referenced on resource page
Library is referenced on resource page
```
[ ] Yes
[x] No
```
> docs: add ngrx-handlers to resources

- projects/ngrx.io/content/guide/component-store/effect.md
- projects/ngrx.io/content/guide/component-store/read.md
- projects/ngrx.io/content/guide/component-store/write.md
```
[ ] Bugfix
[ ] Feature
```
Button is not visible in following code snippet:
Fixed button visibility. Other changes are in accordance with formatting style in other code snippets of component-store (trailing comma and semicolon).
```
[ ] Yes
[x] No
```
> docs(component-store): fix code formatting

- projects/ngrx.io/content/guide/effects/install.md
```
[ ] Bugfix
[ ] Feature
```
Updating docs to actual behavior.
Behavior is described in docs.
```
[ ] Yes
[x] No
```
> docs(effects): update steps

- build/publish-latest.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
Updates publish script to deploy using NPM CLI instead of Bazel
```
[ ] Yes
[x] No
```
> chore: update script for publishing to latest

- CONTRIBUTING.md
- projects/ngrx.io/content/guide/data/entity-actions.md
- projects/ngrx.io/content/guide/data/entity-change-tracker.md
- projects/ngrx.io/content/guide/data/index.md
- projects/ngrx.io/content/marketing/docs.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: fix small typos in intro pages

- .circleci/config.yml
- nx.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> ci: build all projects in parallel on CircleCI changes and builds on master

- modules/store/src/selector.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Current types
https://github.com/ngrx/platform/blob/01ad2cd569dab97b6656ff786777e75e4f4cddbe/modules/store/src/selector.ts#L532-L539
Current usage
https://github.com/ngrx/platform/blob/01ad2cd569dab97b6656ff786777e75e4f4cddbe/modules/store/src/selector.ts#L581-L588
https://github.com/ngrx/platform/blob/01ad2cd569dab97b6656ff786777e75e4f4cddbe/modules/store/src/selector.ts#L515-L520
> fix(store): Correct types for SelectorFactoryConfig

- modules/store/testing/spec/mock_store.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Re-inclusion of excluded tests
```
Tests from mock_store.spec.ts were excluded because they failed.
Closes #
Tests from mock_store.spec.ts are included.
```
[ ] Yes
[x] No
```
> chore: re-include mock_store tests

- modules/store/src/index.ts
When wrapping `createAction` with some additional functionality, it's beneficial to access `Props` and `NotAllowedCheck`, so that the underlying `createAction` won't need force-casting some of the types.
Discovered during the g3 sync.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(store): open models needed for creating a custom createAction

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
Builds all dependencies for affected projects, to cover packages that depend on `store`, which is currently copied into the `node_modules` folder after being built. Removing the `--parallel` flag, which shouldn't cause an increase in build times with Nx Cloud caching.
```
[ ] Yes
[x] No
```
> ci: build dependencies for affected projects

- projects/ngrx.io/content/guide/component-store/read.md
Fixing as per #2769
```
[ ] Bugfix
[ ] Feature
```
Closes #2769
```
[ ] Yes
[x] No
```
> docs(component-store): Fix "Combining Selectors"

- projects/example-app/src/app/core/effects/router.effects.spec.ts
- projects/example-app/src/app/core/effects/router.effects.ts
- projects/example-app/src/app/reducers/index.ts
```
[ ] Bugfix
[ ] Feature
```
Route data is extracted manually from `ActivatedRoute` in `updateTitle$` effect.
`updateTitle$` effect uses `selectRouteData` selector.
```
[ ] Yes
[x] No
```
> refactor(example-app): use router store in RouterEffects

- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Removed duplicated and legacy scripts from package.json
```
```
[ ] Yes
[x] No
```
> chore: remove redundant/legacy scripts

- modules/data/ng-package.json
- modules/effects/ng-package.json
- modules/entity/ng-package.json
- modules/router-store/ng-package.json
- modules/store-devtools/ng-package.json
```
[ ] Bugfix
[ ] Feature
```
Correct UMD module ids are added for dependent ngrx packages and the warning is gone.
```
[ ] Yes
[x] No
```
> build: fix warning during UMD bundling

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
Book is not referenced in resources.
Book is referenced in resources.
```
[ ] Yes
[x] No
```
> docs(resources): add book to resources

- projects/ngrx.io/content/guide/component-store/write.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): `this` was missing to access moviesStore

- projects/ngrx.io/content/guide/component-store/write.md
```
[ ] Bugfix
[ ] Feature
```
`patchState` misses in the documentation.
Added `patchState` description and example.
```
[ ] Yes
[x] No
```
> docs(component-store): add patchState description with example

- modules/component/spec/let/let.directive.spec.ts
- modules/component/spec/push/push.pipe.spec.ts
```
[ ] Bugfix
[ ] Feature
```
`async` function from `@angular/core/testing` package is deprecated since v10.1.0
```
[ ] Yes
[x] No
```
> refactor(component): replace deprecated async with waitForAsync

- modules/store/spec/reducer_creator.spec.ts
- modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
Not that I know of 
```
[ ] Yes
[x] No
```
> refactor(store): variadic tuple types for on

- projects/ngrx.io/content/guide/component-store/effect.md
Closes #2811
```
[ ] Bugfix
[ ] Feature
```
Closes #2811
```
[ ] Yes
[X ] No
```
> docs(component-store): add documentation for tapResponse operator

- projects/ngrx.io/content/guide/component/push.md
> docs(push.md): fix typo

- modules/store/src/selector.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1825
```
[ ] Yes
[x] No
```
Draft of blog on this topics available: https://dev.to/zackderose/using-custom-selector-factories-in-ngrx-50oc-temp-slug-1909450?preview=a589b297153ff68d78bf96af9f1662b8a63a64033b1fddc3116b27402a48f31c1be43690501e538866de7adcc04d9425c7953853745a3bb2c55d0184 would be interested in adding link to this article if that is deemed acceptable to the team!!
> docs: usage notes for createSelectorFactory()

- modules/component-store/package.json
- modules/component/package.json
- modules/data/package.json
- modules/effects/package.json
- modules/entity/package.json
- modules/router-store/package.json
- modules/store/package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #2842 
```
[x] Yes
[] No
```
> chore: update Angular peer dependencies to version 11

- build/update-version-numbers.ts
```
[x] Bugfix
[ ] Feature
```
The update script updates the version of NgRx dependencies, but does nothing with the Angular peer dependency version.
While preparing the NgRx v11 version, I forgot to update the Angular peer dependencies and this was recently fixed in #2843.
The changes made within this PR, also updates the peer dependencies from `@angular` to the new version.
```
[ ] Yes
[ ] No
```
> chore(build): upgrade Angular peer dependency version

- projects/ngrx.io/content/guide/entity/adapter.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(entity): add missing mapOne method

- modules/store/spec/modules.spec.ts
- modules/store/src/index.ts
- modules/store/src/store_module.ts
Reverts ngrx/platform#2821 due to issues with merging in Google G3. A new PR will be opened with a fix
> Revert "feat(store): add object-style StoreModule.forFeature overload"

- modules/effects/src/effect_decorator.ts
- projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> feat(Effects): deprecate @Effect decorator

- modules/store/spec/integration.spec.ts
- projects/ngrx.io/content/guide/data/limitations.md
- projects/ngrx.io/src/app/app.component.ts
- projects/ngrx.io/src/app/custom-elements/api/api-list.component.ts
- projects/ngrx.io/src/app/custom-elements/toc/toc.component.ts
- projects/ngrx.io/src/app/navigation/navigation.service.ts
Closes #2861
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> refactor(ngrx.io): fix combineLatest usage in deprecated way

- modules/store-devtools/src/reducer.ts
```
[ ] Bugfix
[x] Feature
```
Closes #2824
```
[ ] Yes
[x] No
```
> feat(store-devtools): pass entire error object to the error handler

- modules/store/spec/integration.spec.ts
```
[x] Bugfix
[ ] Feature
```
Fixes a bug (in the tests) introduced in #2864.
```
[ ] Yes
[x] No
```
> test(store): fix failing tests

- projects/ngrx.io/content/guide/data/entity-dataservice.md
Adds return types for the DataService methods as well as an explanation of what the server should be returning for each.
resolves #1939
```
[ ] Bugfix
[ ] Feature
```
Closes #1939
```
[ ] Yes
[x] No
```
> docs(data): add api response explanations

- projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Adds a migration note for #2853
> docs(store-devtools): add breaking change to migration

- modules/store/spec/modules.spec.ts
- modules/store/src/index.ts
- modules/store/src/store_module.ts
- projects/example-app/src/app/auth/auth.module.ts
```
[ ] Bugfix
[ ] Feature
```
Builds on top of the original PR by @lacolaco to add interop with Redux Toolkit style of `{ name, reducer }`, with additional fixes for AOT  compliance. Also added usage to the example app. In order to preserve original commit author, the PR will be rebased and merged if it lands.
Closes #2809 
```
[ ] Yes
[x] No
```
> feat(store): add object-style StoreModule.forFeature overload w/fixes

- .github/labeler.yml
- .github/workflows/labeler.yml
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Add support for the labeler. It's improve readability of the scopes affected by the PR.
```
Closes #2576
```
[ ] Yes
[X] No
```
> docs: add labeler

- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/component/spec/let/let.directive.spec.ts
- modules/component/spec/push/push.pipe.spec.ts
- modules/component/src/core/cd-aware/cd-aware_creator.ts
```
[X] Bugfix
[ ] Feature
```
Push Pipe breaks if input is a Promise, which means it's not a drop in replacement for async pipe at the moment
Closes #
If the input is a Promise it is converted to an Observable
```
[ ] Yes
[X] No
```
Fixes tests for #2874
> Fix push pipe

- projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2638
```
[ ] Yes
[ ] No
```
> docs(router-store): show working usage for router-store selectors

- modules/store/spec/types/action_creator.spec.ts
- modules/store/src/action_creator.ts
- modules/store/src/index.ts
- modules/store/src/models.ts
- modules/store/src/reducer_creator.ts
- projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[x] Feature
```
Closes #2808
Closes #2854
```
[x] Yes
[ ] No
```
- the interface `Props` is renamed to `ActionCreatorProps`
- the interface `On<T>` is renamed to `ReducerTypes<T>`
Naming things is hard 😅 , feel free to suggest a better name for one of the interfaces.
> Interface renames

- modules/router-store/src/reducer.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2882
```
[ ] Yes
[x] No
```
> fix(router-store): cast return type as RouterReducerState

- projects/ngrx.io/content/guide/component-store/read.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: add missing this

- projects/ngrx.io/src/app/layout/footer/footer.component.html
Minor update to the ngrx.io site footer to reflect the current year.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> Updated Copyright year to 2021

- modules/store/src/store_module.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2919
```
[ ] Yes
[x] No
```
The local build of this PR, works on the [reprodution repo](https://github.com/bbortt/ngrx-store-module-reproducible)
> fix(store): forFeature using instanceof instead of typeof

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #2926
```
[ ] Yes
[x] No
```
> docs(effects): add missing concatLatestFrom operator import

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: New sample to the ressources page
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add TodoMVC app to the ressources page

- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
The examples may lead users to write tests that silently fail, as noted in https://github.com/ngrx/platform/issues/2449.
Maybe closes #2449 
Updated examples
```
[ ] Yes
[x] No
```
> docs(effects): update documentation to help avoid asynchronous testing mistakes

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
The URL for the in-depth platform is broken
Tried to change this broken URL to the search URL for NgRX articles on the in-depth platform
Closes #
https://indepth.dev/search?query=ngrx 
instead of 
https://indepth.dev/ngrx
```
[ ] Yes
[X] No
```
> docs(resources): update break url for indepth

- projects/ngrx.io/src/styles/1-layouts/_sidenav.scss
```
[ ] Bugfix
[ ] Feature
```
It was hard to see the active tree and active tabs 
I tested this result on another person to make sure it's a useful edit and making the docs easier to navigate
Closes #
instead of 
```
[ ] Yes
[X] No
```
> docs(sidebar): add weight for selected menu item

- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/data/spec/dataservices/default-data.service.spec.ts
- modules/data/spec/entity-data.module.spec.ts
- modules/effects/spec/actions.spec.ts
- modules/store/spec/integration.spec.ts
- modules/store/spec/modules.spec.ts
- modules/store/spec/store.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: tests fix
```
```
[ ] Yes
[x] No
```
`expect()` inside of `subscribe()` without `done()` will always pass.
> test: fix async tests across packages

- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/data/spec/dataservices/default-data.service.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Test related changes
```
Several tests failed when my PR #2946 was merged: https://app.circleci.com/pipelines/github/ngrx/platform/959/workflows/c172c998-fd15-4191-8d05-9924c3e55f1f/jobs/32582 🤦‍♂️
```
[ ] Yes
[x] No
```
> test(component/data): fix failed tests

- projects/example-app/src/app/core/reducers/layout.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(layout.reducer): typo "thought" in comment

- modules/data/spec/dataservices/entity-data.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
These tests were failing locally after pulling the latest version and making a change to `store` 😅
```
[ ] Yes
[ ] No
```
> test(data): fix tests

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add ngrx-child-selectors to resources

- projects/ngrx.io/content/guide/data/entity-change-tracker.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: fix typo

- projects/ngrx.io/content/guide/component-store/write.md
complete documentation because of https://github.com/ngrx/platform/pull/2937
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore: complete documentation for patchState

- modules/store/src/index.ts
```
[ ] Bugfix
[X] Feature
```
The only way to reference `FunctionWithParametersType` currently is to do a deep import of `@ngrx/store/src/models`. 
Closes #2983 
This PR would expose `FunctionWithParametersType` without the need for a deep import. ie: `@ngrx/store`
```
[ ] Yes
[X ] No
```
Can we patch this change with other versions (8+) as well?
> feat: expose FunctionWithParametersType

- modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/feature/index.spec.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2931
```
[ ] Yes
[x] No
```
> fix(schematics): assert empty as action observable

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
There are obsolete imports in an example.
Removed obsolete imports
```
[ ] Yes
[x] No
```
> docs(effects): cleanup module imports in example

- modules/store/schematics/ng-add/index.spec.ts
- modules/store/schematics/ng-add/index.ts
- modules/store/schematics/ng-add/schema.json
- modules/store/schematics/ng-add/schema.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> feat(store): register eslint-plugin-ngrx with ng add

- modules/schematics/src/action/creator-files/__name@dasherize@if-flat__/__name@dasherize__.actions.spec.ts.template
- modules/schematics/src/action/creator-files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts.template
- modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.spec.ts.template
- modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts.template
- modules/schematics/src/action/index.spec.ts
- modules/schematics/src/action/index.ts
- modules/schematics/src/action/schema.json
- modules/schematics/src/action/schema.ts
- projects/ngrx.io/content/guide/schematics/action.md
```
[ ] Bugfix
[x] Feature
```
The actions are created only with the prefix Load.
Closes #3012 
The actions are created with a specified prefix.
```
[ ] Yes
[x] No
```
> feat(schematics): add the ability to create actions with the prefix

- modules/component-store/schematics/ng-add/schema.json
- modules/component/schematics/ng-add/schema.json
- modules/data/schematics/ng-add/schema.json
- modules/effects/schematics/ng-add/schema.json
- modules/entity/schematics/ng-add/schema.json
- modules/router-store/schematics/ng-add/schema.json
- modules/schematics/src/action/schema.json
- modules/schematics/src/component-store/schema.json
- modules/schematics/src/container/schema.json
- modules/schematics/src/create-effect-migration/schema.json
- modules/schematics/src/data/schema.json
- modules/schematics/src/effect/schema.json
- modules/schematics/src/entity/schema.json
- modules/schematics/src/feature/schema.json
- modules/schematics/src/ng-add/schema.json
- modules/schematics/src/ngrx-push-migration/schema.json
- modules/schematics/src/reducer/schema.json
- modules/schematics/src/selector/schema.json
- modules/schematics/src/store/schema.json
- modules/store-devtools/schematics/ng-add/schema.json
- modules/store/schematics/ng-add/schema.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: schematics id property was deprecated in favour of $id
```
Closes #
No warning message anymore.
```
[ ] Yes
[x] No
```
> chore(schematics): replace schemas id with $id

- angular.json
```
[ ] Bugfix
[ ] Feature
```
Closes #3054 
```
[ ] Yes
[x] No
```
> build: clean node modules on build

- modules/data/src/entity-services/entity-collection-service-base.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3041
```
[ ] Yes
[x] No
```
> fix(data): make options optional on add with partial

- modules/store/src/feature_creator.ts
- modules/store/src/feature_creator_models.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(store): add `createFeature` docs

- projects/ngrx.io/content/guide/migration/v11.md
Without explicit version, ng update would try installing the newest version.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: add pinned version for update guide v11

- modules/data/spec/reducers/entity-change-tracker-base.spec.ts
- modules/data/src/reducers/entity-change-tracker-base.ts
- modules/store/spec/runtime_checks.spec.ts
```
[x] Bugfix
[ ] Feature
```
Closes #2553
No state mutation on delete and ngrx/data actions are exempt from strictActionImmutability runtime checks.
```
[ ] Yes
[x] No
```
> fix(data): immutably delete an entity

- projects/ngrx.io/content/guide/component-store/usage.md
```
[ ] Bugfix
[ ] Feature
```
in ngrx/component-store Usage doc, proposal for being more specific as to why we are adding the stopEventPropagation side-effect (which seems unnecessary at the first glance
> docs: more details on why using stopPropagation

- modules/effects/spec/types/of_type.spec.ts
- modules/store/spec/types/feature_creator.spec.ts
- modules/store/spec/types/select.spec.ts
- package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: package update and related fixes
```
ts-snippet has been updated with new features like outputting the actual error produced when using `toFail`.
ts-snippet is updated to v5.0.2.
```
[ ] Yes
[x] No
```
`toInfer` now implies `toSucceed`, and some of the tests using `toInfer` actually had failures in them.
> chore: update ts-snippet to 5.0.2

- modules/store/src/reducer_creator.ts
Type definition fix.
```
[X] Bugfix
[ ] Feature
```
Closes #3050 
The PR makes type definitions consistent
```
[ ] Yes
[X] No
```
> fix(store): make readonly usage consistent (#3050)

- projects/ngrx.io/content/guide/migration/v12.md
```
[ ] Bugfix
[ ] Feature
```
A typo
A better documentation :-)
```
[ ] Yes
[x] No
```
> docs: fix for V12 Update Guide

- modules/data/src/actions/entity-cache-action.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3065
```
[ ] Yes
[x] No
```
> fix(data): SAVE_ENTITIES_CANCELED type in SaveEntitiesCanceled

- .gitignore
- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/component/src/core/cd-aware/cd-aware_creator.ts
- modules/component/src/let/let.directive.ts
- modules/component/src/push/push.pipe.ts
```
[x] Bugfix
[ ] Feature
```
Closes https://github.com/ngrx/platform/issues/3100
Report errors to the global error handler (instead of throwing it directly which would be a breaking change)
```
[ ] Yes
[x] No
```
> fix(component): capture errors from observable when using `ngrxPush` pipe and `ngrxLet` directive

- projects/ngrx.io/content/guide/component-store/comparison.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add missing word to ComponentStore comparison

- projects/ngrx.io/content/guide/migration/v12.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(store): fix migration guide for selector with props

- projects/ngrx.io/content/guide/store/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(store): fix outdated hint

- projects/ngrx.io/content/marketing/contributors.json
- projects/ngrx.io/src/app/custom-elements/contributor/contributor-list.component.spec.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor-list.component.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor-list.module.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor.component.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor.service.spec.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor.service.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributors.model.ts
- projects/ngrx.io/src/polyfills.ts
Closes #1608
```
[ ] Bugfix
[ ] Feature
```
Closes #
All contributors are listed on the About page
To view:
- Click on preview
- Go to footer at bottom of the page
- Click the About link
- Click the Community tab
```
[ ] Yes
[x] No
```
> docs: add community contributors section to about page

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add new plugins to resources

- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.component.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/state/books.actions.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/state/books.reducer.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/state/collection.reducer.ts
- projects/ngrx.io/content/guide/store/walkthrough.md
Fix books reducer and action in store-walkthrough example
```
[ ] Bugfix
[ ] Feature
```
Sample code does not compile because `Book` is wrongly called instead of an array of books in books action and reducer.
Closes #
Sample code compiles and works.
```
[ ] Yes
[x] No
```
> docs(store-walkthrough): fix books reducer and action

- modules/component-store/spec/component-store.spec.ts
- modules/component/spec/fixtures/mock-event-emitter.ts
- modules/effects/src/actions.ts
- modules/store/src/actions_subject.ts
- modules/store/src/store.ts
- modules/store/testing/src/mock_store.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: add noImplicitOverride compiler option

- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.component.ts
Refactored walkthrough page from store.pipe(select(...)) to store.select(...)
```
[ ] Bugfix
[ ] Feature
```
Closes https://github.com/ngrx/platform/issues/3122
```
[ ] Yes
[x] No
```
> docs(store-walkthrough): refactor from store.pipe(select(...)) to store.select(...)

- modules/schematics/schematics-core/index.ts
- modules/schematics/schematics-core/utility/ngrx-utils.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
Not all schematics files are up to date, making the build fail.
This PR runs the `copy:schematics` command to get it resolved.
> chore: update schematic files

- modules/component-store/schematics-core/index.ts
- modules/component-store/schematics-core/utility/ngrx-utils.ts
- modules/component/schematics-core/index.ts
- modules/component/schematics-core/utility/ngrx-utils.ts
- modules/data/schematics-core/index.ts
- modules/data/schematics-core/utility/ngrx-utils.ts
- modules/effects/schematics-core/index.ts
- modules/effects/schematics-core/utility/ngrx-utils.ts
- modules/entity/schematics-core/index.ts
- modules/entity/schematics-core/utility/ngrx-utils.ts
- modules/router-store/schematics-core/index.ts
- modules/router-store/schematics-core/utility/ngrx-utils.ts
- modules/schematics-core/index.ts
- modules/schematics-core/utility/ngrx-utils.ts
- modules/schematics/schematics-core/index.ts
- modules/schematics/schematics-core/utility/ngrx-utils.ts
- modules/store-devtools/schematics-core/index.ts
- modules/store-devtools/schematics-core/utility/ngrx-utils.ts
- modules/store/schematics-core/index.ts
- modules/store/schematics-core/utility/ngrx-utils.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
🤦‍♂️ seems like the removed method in #3156 was needed.
> fix(schematics): add missing method

- projects/ngrx.io/content/guide/entity/adapter.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3125 
Docs for [selectCurrentUser](https://ngrx.io/guide/entity/adapter#entity-selectors) selector is updated.
```
[ ] Yes
[x] No
```
> docs(entity): fix code snippet for selectCurrentUser selector

- projects/ngrx.io/content/examples/store-walkthrough/src/app/book-collection/book-collection.component.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/book-list/book-list.component.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/state/books.selectors.ts
```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngrx/platform/issues/3209
Walkthrough code sample not working with
Angilar 12 + strict templates + typescript 4.3.5 + strict mode.
@ngrx/store ~12.4.0 or 12.5.1 (both of them)
Walkthrough code sample working with Angilar 12 + strict templates + typescript 4.3.5 + strict mode.
@ngrx/store ~12.4.0 or 12.5.1 (both of them)
```
[ ] Yes
[x] No
```
> docs(store): improve types in walkthrough example

- projects/ngrx.io/content/guide/eslint-plugin.md
- projects/ngrx.io/content/guide/store/recipes/eslint-plugin.md
- projects/ngrx.io/content/navigation.json
add a documenation page detailing eslint plugin and how to use it
```
[ ] Bugfix
[ ] Feature
```
Closes #3178
```
[ ] Yes
[x] No
```
> docs: add a documentation page detailing ESLint NgRx plugin and how to use it

- modules/effects/migrations/13_0_0/index.spec.ts
- modules/effects/migrations/13_0_0/index.ts
- modules/effects/migrations/migration.json
- modules/schematics/collection.json
- modules/schematics/src/create-effect-migration/schema.json
- modules/schematics/src/create-effect-migration/schema.ts
- projects/ngrx.io/content/guide/migration/v11.md
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[x] Yes
[ ] No
```
```
The create-effect-migration migration is removed
```
> feat(effects): move createEffect migration to ng-update migration

- projects/ngrx.io/content/guide/store/feature-creators.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #3183
```
[ ] Yes
[x] No
```
> docs(store): add feature creator guide

- modules/store/src/feature_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #3220
```
[ ] Yes
[x] No
```
> docs: fix typo on createFeature page

- projects/ngrx.io/content/guide/entity/adapter.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3225
```
[ ] Yes
[x] No
```
> docs: remove wrong link entity adapter

- projects/ngrx.io/content/guide/migration/v13.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3187
```
[ ] Yes
[x] No
```
> docs: add v13 migration

- modules/schematics/schematics-core/utility/config.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
The builds are failing because there's a change made to a schematics core folder.
This PR runs  the `copy:schematics` command to keep the content the same in those folders.
> chore: update schematics core

- projects/ngrx.io/content/guide/migration/v13.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3253 
```
[ ] Yes
[x] No
```
> docs(migration): RxJs dependency version in v13

- modules/store/schematics/ng-add/index.spec.ts
- modules/store/schematics/ng-add/index.ts
- projects/ngrx.io/content/guide/eslint-plugin.md
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
This PR updates the installation and the docs of the NgRx ESLint plugin.
An overview of the changes:
- install v2 of the plugin, this is required for projects that use the latest version of the typescript plugin (installed with the Angular ESLint plugin)
- the plugin has better configuration files, meaning that we can simply extend it now instead of configuring it manually
- updated the config to make it …
> fix(store): update installation of the NgRx ESLint Plugin

- projects/ngrx.io/content/guide/component-store/usage.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): remove usage placeholders

- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/app/layout/footer/footer.component.html
- x ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Closes #
Adds links for Code of Conduct and Netlify to footer as part of the agreement for the Open Source Plan Policy. https://www.netlify.com/legal/open-source-policy
```
[ ] Yes
[x] No
```
> docs: add links for Code of Conduct and Netlify

- projects/example-app/src/app/auth/containers/login-page.component.ts
- projects/example-app/src/app/books/components/book-search.component.ts
- projects/example-app/src/app/books/containers/collection-page.component.ts
- projects/example-app/src/app/books/containers/find-book-page.component.ts
- projects/example-app/src/app/books/containers/selected-book-page.component.ts
- projects/example-app/src/app/core/containers/app.component.ts
- projects/example-app/tsconfig.app.json
```
[ ] Bugfix
[x] Feature
```
Closes #3222
```
[ ] Yes
[x] No
```
> feat(example): turn on strict Angular compiler flags

- projects/ngrx.io/src/app/layout/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
Closes #3288 
```
[ ] Yes
[x] No
```
> docs: update footer year to 2022

- projects/ngrx.io/tools/stackblitz-builder/builder.js
```
[ ] Bugfix
[ ] Feature
```
StackBlitz examples are displaying a TypeScript error about initialization.
Closes #3295 
tsconfig.json is included in the generated StackBlitz examples
```
[ ] Yes
[x] No
```
> docs: include tsconfig.json in Angular v13 StackBlitz examples

- projects/ngrx.io/content/guide/migration/v13.md
see #3264
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(store): add breaking change with mock store teardown for jasmine tests

- projects/ngrx.io/content/guide/migration/v13.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(store): include version in command for v13 update

- modules/data/spec/effects/entity-cache-effects.spec.ts
- modules/data/spec/entity-data.module.spec.ts
- modules/data/spec/entity-services/entity-collection-service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #3313 
```
[ ] Yes
[X] No
```
> refactor(data): replace deprecated subscribe usages

- projects/ngrx.io/package.json
- projects/ngrx.io/src/app/custom-elements/api/api.service.ts
- projects/ngrx.io/src/app/custom-elements/contributor/contributor-list.component.ts
- projects/ngrx.io/src/app/custom-elements/toc/toc.component.spec.ts
- projects/ngrx.io/src/app/custom-elements/toc/toc.component.ts
- projects/ngrx.io/src/app/layout/notification/notification.component.ts
- projects/ngrx.io/src/app/shared/scroll-spy.service.ts
- projects/ngrx.io/tools/examples/shared/boilerplate/cli/package.json
- projects/ngrx.io/tools/examples/shared/package.json
- projects/ngrx.io/yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Closes #3296
`RxJS` and `jasmine-marbles` package versions are bumped up to `~7.4.0` and `^0.9.1` in the examples.
```
[ ] Yes
[x] No
```
> build(example): update example rxjs to 7 and jasmine-marbles to 0.9.1

- modules/component-store/spec/tap-response.spec.ts
- modules/component-store/src/component-store.ts
- modules/component/spec/core/cd-aware/cd-aware_creator.spec.ts
- modules/component/spec/let/let.directive.spec.ts
- modules/data/spec/effects/entity-effects.spec.ts
- modules/data/spec/entity-services/entity-collection-service.spec.ts
- modules/data/src/dataservices/default-data.service.ts
- modules/data/src/dataservices/entity-cache-data.service.ts
- modules/data/src/dispatchers/entity-cache-dispatcher.ts
- modules/data/src/dispatchers/entity-dispatcher-base.ts
- modules/effects/spec/act.spec.ts
- modules/effects/spec/effect_sources.spec.ts
- modules/effects/spec/effects_error_handler.spec.ts
- projects/data-example-app/src/fake-backend-interceptor.service.ts
- projects/example-app/src/app/auth/services/auth.service.ts
- projects/example-app/src/app/core/services/book-storage.service.ts
- projects/ngrx.io/content/guide/effects/lifecycle.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: replace deprecated throwError usages

- modules/data/spec/effects/entity-cache-effects.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test changes
```
```
[ ] Yes
[x] No
```
> test(data): fix EntityCacheEffects tests

- modules/data/spec/effects/entity-cache-effects.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test-related changes
```
checked locally with `--skip-nx-cache` 👀 
```
[ ] Yes
[x] No
```
> test(data): include skipped tests

- projects/example-app/src/app/app.module.ts
- projects/example-app/src/app/auth/components/login-form.component.ts
- projects/example-app/src/app/auth/effects/auth.effects.ts
- projects/example-app/src/app/auth/services/auth.service.ts
- projects/example-app/src/app/books/containers/collection-page.component.spec.ts
- projects/example-app/src/app/books/containers/selected-book-page.component.spec.ts
- projects/example-app/src/app/books/containers/view-book-page.component.spec.ts
- projects/example-app/src/app/books/containers/view-book-page.component.ts
- projects/example-app/src/app/books/reducers/books.reducer.spec.ts
- projects/example-app/src/app/books/reducers/collection.reducer.ts
- projects/example-app/src/app/core/reducers/layout.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> style(example-app): fix lint warning

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Only run tests for affected projects in CI
Closes #
Run all tests for all projects in CI. We've run into an issue a few times where tests are skipped and break the `master` branch when we run all tests.
```
[ ] Yes
[x] No
```
> ci: run all tests in CI instead of only affected projects

- projects/ngrx.io/src/app/custom-elements/ngrx/mff.component.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore: update donation to support efforts in Ukraine

- projects/ngrx.io/content/examples/router-store-selectors/e2e/src/app.e2e-spec.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/app.component.css
- projects/ngrx.io/content/examples/router-store-selectors/src/app/app.component.html
- projects/ngrx.io/content/examples/router-store-selectors/src/app/app.component.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/app.module.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.actions.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.component.css
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.component.html
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.component.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.reducer.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/car/car.selectors.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/app/router.selectors.ts
- projects/ngrx.io/content/examples/router-store-selectors/src/index.html
- projects/ngrx.io/content/examples/router-store-selectors/src/main.ts
- projects/ngrx.io/content/examples/router-store-selectors/stackblitz.json
- projects/ngrx.io/content/guide/router-store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
router store selectors StackBlitz example has direct link to StackBlitz
Closes #
router store selectors StackBlitz example use StackBlitz api
```
[ ] Yes
[x] No
```
> docs: move router store selector StackBlitz example

- modules/store-devtools/src/index.ts
```
[ ] Bugfix
[x] Feature
```
REDUX_DEVTOOLS_EXTENSION is private and we're unable to provide a custom interface implementation in platforms where window is not defined.
We export `REDUX_DEVTOOLS_EXTENSION` as `ɵREDUX_DEVTOOLS_EXTENSION` allowing for custom implementations of the extension interface
```
[ ] Yes
[x] No
```
This change is needed to be able to debug ngrx using remote devtools under a `@nativescript/angular` application.
> feat(store-devtools): export private Redux Devtools Extension injection token

- angular.json
```
[ ] Bugfix
[ ] Feature
```
Example apps are served in production mode.
Example apps will be served in development mode by default.
```
[ ] Yes
[x] No
```
> chore: serve example apps in dev mode

- projects/ngrx.io/content/examples/store/src/app/counter.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #3352 
The reducer wrapper function is removed from the store example.
```
[ ] Yes
[x] No
```
> docs(store): remove reducer wrapper function

- modules/effects/src/concat_latest_from.ts
small change to the sample code in documentation
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(effects): add as in import all statement

- projects/ngrx.io/content/guide/data/extension-points.md
```
[ ] Bugfix
[ ] Feature
```
The sample is using selectEntities to get the entity to be joined in the owner property. This selector will return an array of owners that is not indexed by the owner's id.
Now we use selectEntityMap to get the dictionary and the right entity to be joined.
```
[ ] Yes
[X] No
```
> docs(data): fix custom selector example

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
[ngrx-lite](https://github.com/gernsdorfer/ngrx-lite) Library is not referenced on resource page
Closes #
[ngrx-lite](https://github.com/gernsdorfer/ngrx-lite) Library is referenced on resource page
```
[ ] Yes
[x] No
```
> docs: add ngrx-lite to resources

- modules/eslint-plugin/schematics/ng-add/schema.json
- modules/store/schematics/ng-add/index.spec.ts
- modules/store/schematics/ng-add/index.ts
```
[x] Bugfix
[x] Feature
```
Partially https://github.com/ngrx/platform/issues/3372
```
[ ] Yes
[x] No
```
Instead of adding the plugin manually, this PR appends the @ngrx/eslint-plugin to the ng-add tasks.
> feat(store): install and configure the @ngrx/eslint-plugin on ng-add

- projects/ngrx.io/content/guide/data/entity-reducer.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(Entity Reducers): minor typo fixed

- modules/store/src/helpers.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(store): google upstream changes

- projects/ngrx.io/content/marketing/index.html
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore: remove Nrwl logo from homepage

- modules/component/spec/push/push.pipe.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Test related changes
```
```
[ ] Yes
[x] No
```
> test(component): mock ErrorHandler in PushPipe tests

- projects/ngrx.io/content/guide/effects/index.md
(#3387)
```
[ ] Bugfix
[ ] Feature
```
Closes #3387 
```
[ ] Yes
[x] No
```
> docs(effects): add an example of effects without actions

- modules/component/src/push/push.pipe.ts
- projects/ngrx.io/content/guide/component/index.md
- projects/ngrx.io/content/guide/component/let.md
- projects/ngrx.io/content/guide/component/push.md
- projects/ngrx.io/content/marketing/docs.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(component): improve PushPipe & Overview pages

- projects/ngrx.io/content/guide/store/reducers.md
- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(store): Added references to Feature Creators in Reducers and Selectors pages

- projects/ngrx.io/content/guide/component-store/read.md
Adding movieService in the constructor
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs(component-store): add movie service to the constructor 

- projects/ngrx.io/content/guide/store-devtools/index.md
```
[ ] Bugfix
[ ] Feature
```
The link to DevTools repo is old.
Update Redux DevTools extension URL.
```
[ ] Yes
[x] No
```
> docs(store-devtools): update DevTools url

- projects/ngrx.io/content/guide/migration/v14.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3418
```
[ ] Yes
[x] No
```
> docs: add v14 migration

- projects/ngrx.io/content/guide/data/extension-points.md
- projects/ngrx.io/content/guide/entity/recipes/additional-state-properties.md
- projects/ngrx.io/content/guide/eslint-plugin/rules/no-effects-in-providers.md
- projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md
- projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-selector-in-select.md
- projects/ngrx.io/content/guide/eslint-plugin/rules/use-effects-lifecycle-interface.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: replace absolute links to prevent hard reload

- MIGRATION.md
- build/update-version-numbers.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix migration guide link

- projects/data-example-app/src/board/board.component.html
- projects/data-example-app/src/board/ui/board-ui.component.ts
- projects/data-example-app/tsconfig.app.json
```
[ ] Bugfix
[ ] Feature
```
The `data-example-app` does not have strict mode configurations implemented. Also, there is a compilation error in the `board` component as the `stories` parameter is not accepting `null` as an input type.
Closes #3445
- `data-example-app` project has strict mode configuration implemented.
- The `stories` parameter can receive the `null` type.
```
[ ] Yes
[x] No
```
> refactor(example): add strict mode options to data-example-app

- modules/component-store/src/lifecycle_hooks.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3464
```
[ ] Yes
[x] No
```
> fix(component-store): import operators from rxjs/operators

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
The circleci images are deprecated
- Use the "new" cimg images
- Use browser-tools to install browsers for our docs tests (karma)
```
[ ] Yes
[x] No
```
> ci: update docker image

- modules/component/spec/core/render-event/handlers.spec.ts
- modules/component/spec/core/render-event/manager.spec.ts
- modules/component/src/core/render-event/handlers.ts
- modules/component/src/core/render-event/manager.ts
- modules/component/src/core/render-event/models.ts
- modules/component/src/let/let.directive.ts
- modules/component/src/push/push.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
The name "SuspenseRenderEvent" is more accurate for this type of render event because events of this type are emitted when an observable is in a suspense state.
```
[ ] Yes
[x] No
```
> refactor(component): rename ResetRenderEvent to SuspenseRenderEvent

- modules/component-store/spec/types/regression.spec.ts
- modules/component-store/src/component-store.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3482
```
[ ] Yes
[x] No
```
> fix(component-store): effect handles generics that extend upon a type

- modules/data/src/dispatchers/entity-dispatcher-factory.ts
- modules/data/src/selectors/entity-selectors$.ts
```
[x] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> fix(data): add TSDoc annotations

- modules/store/spec/types/action_group_creator.spec.ts
- modules/store/src/action_group_creator_models.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(store): improve error for forbidden characters in createActionGroup

- projects/ngrx.io/content/guide/store/recipes/injecting.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3509
```
[ ] Yes
[x] No
```
> docs(ngrx.io): add missing imports in the injecting.md file

- modules/component/src/core/render-scheduler.ts
- modules/component/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(component): add RenderScheduler to the public API

- projects/ngrx.io/content/guide/component/let.md
- projects/ngrx.io/content/guide/component/push.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(component): remove "markDirty" from docs

- projects/ngrx.io/content/guide/store/install.md
see https://stackoverflow.com/questions/73017961/error-when-i-tried-ng-add-ngrx-storelatest-minimal-false
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
doc's shows an install command which isn't working
doc's shows an …
> docs(store): update ng add command for full install

- modules/store-devtools/spec/store.spec.ts
- modules/store-devtools/src/index.ts
- modules/store-devtools/src/instrument.ts
- modules/store-devtools/src/provide-store-devtools.ts
```
[ ] Bugfix
[x] Feature
```
store devtools does not have a provider function and can only be configured via a static instrument function on the module.
Closes #3527
refactor store devtools to export a provider function to go moduleless
```
[ ] Yes
[x] No
```
> feat(store-devtools): add provideStoreDevtools function

- modules/effects/spec/effects_root_module.spec.ts
- modules/effects/spec/provide_effects.spec.ts
- modules/effects/src/actions.ts
- modules/effects/src/effect_sources.ts
- modules/effects/src/effects_actions.ts
- modules/effects/src/effects_module.ts
- modules/effects/src/effects_root_module.ts
- modules/effects/src/effects_runner.ts
- modules/effects/src/index.ts
- modules/effects/src/provide_effects.ts
- modules/effects/src/tokens.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3522 
```
[ ] Yes
[x] No
```
> feat(effects): add provideEffects function

- projects/ngrx.io/content/guide/store/action-groups.md
- projects/ngrx.io/content/navigation.json
This PR adds a new page for createActionGroup API
```
[ ] Bugfix
[ ] Feature
```
Closes #3514
```
[ ] Yes
[x] No
```
> docs(store): add docs for createActionGroup api

- modules/router-store/src/provide_router_store.ts
- modules/store-devtools/src/provide-store-devtools.ts
- modules/store/src/provide_store.ts
```
[ ] Bugfix
[ ] Feature
```
- API docs for `provideStoreDevtools` are missing
- API docs for `provideStore` and `provideState` are not visible
- API docs for `provideStoreDevtools` are added
- API docs for `provideStore` and `provideState` are visible
```
[ ] Yes
[x] No
```
> docs: improve docs for standalone APIs

- projects/standalone-app/src/app/app.effects.ts
- projects/standalone-app/src/main.ts
```
[ ] Bugfix
[ ] Feature
```
The standalone example app doesn't include all the provide methods. 
The example app uses the new provide methods.
```
[ ] Yes
[x] No
```
> docs: add provide methods to example

- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: remove non-strict check for generics

- projects/ngrx.io/content/marketing/contributors.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add Marko to core contributor group

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: add "affected packages" dropdown to issue templates

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/ngrx.io/Dockerfile
- .devcontainer/ngrx.io/devcontainer.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
Adds a devcontainer with some default configuration.
I also tried to add a specific container for `ngrx.io` but I don't see it anywhere, maybe if it's pushed to master that it becomes visible 🙃
> chore: add GitHub Codespace containers

- modules/router-store/src/provide_router_store.ts
- projects/standalone-app/src/main.ts
```
[ ] Bugfix
[ ] Feature
```
`routerReducer` is missing in the `provideRouterStore` examples.
`routerReducer` is added to the `provideRouterStore` examples.
```
[ ] Yes
[x] No
```
> docs(router-store): add routerReducer to provideRouterStore examples

- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.module.ts
HttpClientModule is missing in the Docs.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[X] No
```
> docs(store-walkthrought): Add HttpClientModule to Doc Imports

- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.module.1.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.module.ts
- projects/ngrx.io/content/guide/store/walkthrough.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3542 , as stated in the issue, the current store walkthrough instructions result in a non-working app due to missing imports and import statements.
- updating walkthrough w/ instructions to import BookList, BookCollection components
- update code example to include above import statements
- update walkthrough w/ instruction to import CommonModule
- remove HttpClient from import statement in app.module as it's not needed
```
[ ] …
```
> docs(store): add missing imports to store walkthrough

- CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: add changes from v14.3.2 to changelog

- projects/ngrx.io/content/marketing/enterprise-support.md
- projects/ngrx.io/src/app/custom-elements/contact-form/contact-form.component.ts
- Adds 4-th offering - Architecture and code review.
- adjust `to` to include Mike and `replyTo` to the email templates.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: Add code review info and replyTo

- modules/effects/testing/src/testing.ts
```
[ ] Bugfix
[ ] Feature
```
Same behavior of [pull request 2607](https://github.com/ngrx/platform/pull/2607):
After [this commit](https://github.com/ReactiveX/rxjs/commit/1ae937a8e594aef96b93313bb3c68ea910e6f528) the behavior of defer is corrected and it no longer allows factories to return void or undefined. In this case it will not emit. So the previous documentation for usage of provideMockActions will not work correctly. Tests will fail because no observable is …
> docs(testing): update usage example of provideMockActions

- modules/effects/src/effects_module.ts
- modules/effects/src/provide_effects.ts
- modules/store/src/provide_store.ts
- modules/store/src/store_config.ts
- modules/store/src/store_module.ts
```
[ ] Bugfix
[ ] Feature
```
- Replaced deprecated `inject` usages.
- Removed single overload signatures and improved typing of `Store/EffectsModule.forRoot/Feature` and `provideStore/State` implementation signatures and their helper functions.
- Replaced `Injector.get` with `inject`.
```
[ ] Yes
[x] No
```
> refactor: improve typing & replace deprecated inject usages

- modules/store/src/reducer_creator.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[X] No
```
> chore: Removed View Engine AOT comments

- modules/effects/spec/types/effects_module.spec.ts
- modules/effects/spec/types/provide_effects.spec.ts
- modules/effects/src/effects_module.ts
- modules/effects/src/provide_effects.ts
- projects/example-app/src/app/app.module.ts
- projects/example-app/src/app/auth/auth.module.ts
- projects/example-app/src/app/books/books.module.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
Update the signature of `EffectsModule.forRoot` and `EffectsModule.forFeature` to also accept spreaded arrays.
The second commit updates the `provideEffects` method to have the same signature as `EffectsModule`.
```
[ ] Yes
[x] No
```
> feat(effects): forRoot and forFeature accept spreaded array

- modules/store/src/selector.ts
```
[ ] Bugfix
[ ] Feature
```
Closes: /
```
[ ] Yes
[x] No
```
The types of the strict projector introduced in #3581 and #3640 can be improved.
Thanks for the tip @alex-okrushko !
> refactor(store): simplify projector type

- modules/schematics/src/container/index.spec.ts
- modules/schematics/src/container/schema.json
- modules/schematics/src/container/schema.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3662
```
[ ] Yes
[x] No
```
> feat(schematics): update container schematics for standalone components 

- projects/ngrx.io/content/guide/component/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
- Weekly downloads have increased by ~5k since v14
- Only one reported bug since v14 (that was external actually, caused by animationFrameScheduler)
> docs(component): mark component package as stable

- modules/effects/src/provide_effects.ts
- [ X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
Closes #3637 
```
[ ] Yes
[ ] No
```
> docs(effects): fix `provideEffects` example

- projects/ngrx.io/content/guide/store-devtools/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3682
```
[ ] Yes
[ ] No
```
> docs(store-devtools): remove useless environment import

- projects/ngrx.io/content/guide/data/index.md
- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/router-store/configuration.md
- projects/ngrx.io/content/guide/router-store/index.md
- projects/ngrx.io/content/guide/store-devtools/index.md
- projects/ngrx.io/content/guide/store/feature-creators.md
- projects/ngrx.io/content/guide/store/reducers.md
Adds documentation of standalone APIs for each page that needs them.
```
[ ] Bugfix
[ ] Feature
```
Closes #3612
```
[ ] Yes
[x] No
```
> docs: add usage of standalone APIs to packages

- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3724 
createFeatureSelector section contained a deprecated signature.
createFeatureSelector section has been updated to use supported signature.
```
[ ] Yes
[x] No
```
> docs(store): update createFeatureSelector to non-deprecated signature

- projects/ngrx.io/content/guide/component-store/read.md
add explanation about the new signature of select to accept a dictionnary of obs to create a view model
```
[ ] Bugfix
[ ] Feature
```
Closes #3704 
```
[ ] Yes
[x] No
```
> docs(component-store): update docs to add dictionnary of obs inside select

- modules/store/src/models.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(store): remove unused models

- projects/ngrx.io/content/guide/component-store/lifecycle.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(component-store): fix typo in lifecycle guide

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
The `test` job in CI doesn't fail on checkout due to existing files being installed from the browser tools
```
[ ] Yes
[x] No
```
> ci: checkout code before next steps during test job

- modules/store/src/feature_creator.ts
- projects/ngrx.io/content/guide/migration/v15.md
```
[ ] Bugfix
[x] Feature
```
Closes #3737
```
[ ] Yes
[x] No
```
> feat(store): deprecate createFeature signature with root state

- modules/store/migrations/15_2_0/index.spec.ts
- modules/store/migrations/15_2_0/index.ts
- modules/store/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Adds a migration for #3756
```
[ ] Yes
[x] No
```
> feat(store): add createFeature migration

- projects/ngrx.io/content/guide/schematics/index.md
- projects/ngrx.io/content/guide/schematics/install.md
```
[ ] Bugfix
[ ] Feature
```
Adds docs for #3760
```
[ ] Yes
[x] No
```
> docs(schematics): replace defaultCollection with schematicCollections

- projects/ngrx.io/content/guide/router-store/configuration.md
- projects/ngrx.io/content/guide/router-store/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3762
```
[ ] Yes
[x] No
```
> docs(router-store): fix example for standalone api setup

- LICENSE
- projects/ngrx.io/src/app/layout/footer/footer.component.html
This is a documentation change - updated year
```
[ ] Bugfix
[ ] Feature
```
Closes #3771 
```
[ ] Yes
[x] No
```
> docs: update year to 2023

- projects/ngrx.io/content/guide/schematics/index.md
```
[ ] Bugfix
[ ] Feature
```
Clarify #3760
```
[ ] Yes
[x] No
```
> docs(schematics): clarify schematics collection

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/lifecycle.md
- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3798 
```
[ ] Yes
[x] No
```
> docs(effects): add guide for functional effects

- modules/store/src/feature_creator.ts
```
[ ] Bugfix
[ ] Feature
```
[createFeature](https://ngrx.io/api/store/createFeature) doc page has a typo on the Creating Feature with Extra Selectors example: 
`...adapter.getSelectors(selectBooksState)` should instead be `...adapter.getSelectors(selectProductsState)`
Closes store/createFeature #3817
`...adapter.getSelectors(selectBooksState)` has been updated to `...adapter.getSelectors(selectProductsState)`
```
[ ] Yes
[X] No
```
> docs(store): fix create feature docs

- projects/ngrx.io/content/guide/migration/v15.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: update v15.md

- modules/data/spec/actions/entity-action-guard.spec.ts
- modules/data/src/actions/entity-action-guard.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3828
```
[ ] Yes
[ ] No
```
> fix(data): allow 0 to be a valid key

- modules/store/testing/src/testing.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3802
```
[x] Yes
[ ] No
```
BEFORE:
```ts
import { getMockStore } from '@ngrx/store/testing';
const mockStore = getMockStore();
```
AFTER:
```ts
import { createMockStore } from '@ngrx/store/testing';
const mockStore = createMockStore();
```
> feat(store): remove getMockStore in favor of createMockStore

- projects/example-app/src/app/core/components/nav-item.component.ts
- projects/example-app/src/app/core/components/sidenav.component.ts
- projects/example-app/src/app/core/components/toolbar.component.ts
```
[ ] Bugfix
[ ] Feature
```
Output event emitters that emit no value, for additional type safety, should have the type `void` .
Closes #
Additional type safety
```
[ ] Yes
[x] No
```
> refactor(example-app): use strong types for event emitters

- modules/store/migrations/16_0_0-beta/index.spec.ts
- modules/store/migrations/16_0_0-beta/index.ts
- modules/store/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> feat(store): add createMockStore migration

- projects/ngrx.io/content/guide/effects/testing.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(effects): remove 'we can' redundancy

- projects/example-app/src/app/app-routing.module.ts
- projects/example-app/src/app/auth/services/auth-guard.service.spec.ts
- projects/example-app/src/app/auth/services/auth-guard.service.ts
- projects/example-app/src/app/books/books-routing.module.ts
- projects/example-app/src/app/books/guards/book-exists.guard.ts
```
[ ] Bugfix
[ ] Feature
```
Currently route guards are class based, which is deprecated in Angular v15
Route guards are function based
```
[ ] Yes
[x] No
```
> refactor(example-app): use functional route guards

- modules/schematics/src/action/files/__name@dasherize@if-flat__/__name@dasherize__.actions.ts.template
- modules/schematics/src/action/index.spec.ts
- modules/schematics/src/effect/files/__name@dasherize@if-flat__/__name@dasherize__.effects.ts.template
- modules/schematics/src/effect/index.spec.ts
- modules/schematics/src/entity/files/__name@dasherize@if-flat__/__name@dasherize@group-actions__.actions.ts.template
- modules/schematics/src/entity/files/__name@dasherize@if-flat__/__name@dasherize@group-reducers__.reducer.ts.template
- modules/schematics/src/entity/index.spec.ts
- modules/schematics/src/feature/index.spec.ts
- modules/schematics/src/reducer/files/__name@dasherize@if-flat__/__name@dasherize__.reducer.ts.template
- modules/schematics/src/reducer/index.spec.ts
```
[ ] Bugfix
[x] Feature
```
It generates the actions with `createAction`
Closes #3543 
It generates the actions with `createActionGroup`
```
[ ] Yes
[x] No
```
> feat(schematics): Use createActionGroup in schematics

- modules/store/src/store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(store): fix selectSignal API docs

- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/store/reducers.md
For those working in module-based angular apps who want to leverage standalone components going forward, it's a bit confusing when you register feature state in your standalone components and receive a Null Injector error for the root store. This adds guides for registering root store and root effects for use in standalone components in module-based Angular applications. 
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add guides for standalone APIs in module-based apps

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3866 
```
[ ] Yes
[x] No
```
> docs(effects): add missing import to the functional effects example 

- modules/component-store/spec/component-store.spec.ts
- modules/component-store/src/component-store.ts
- modules/store/spec/types/select_signal.spec.ts
- modules/store/src/models.ts
- modules/store/src/store.ts
```
[ ] Bugfix
[x] Feature
```
Closes #
This PR adds the `ValueEqualityFn` configuration to the `selectSignal` API in `@ngrx/store` and `@ngrx/component-store`.
```
[ ] Yes
[x] No
```
> feat: selectSignal config

- modules/component/migrations/16_0_0/index.spec.ts
- modules/component/migrations/16_0_0/index.ts
- modules/component/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(component): add migration for LetModule and PushModule

- modules/component-store/src/component-store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(component-store): use stateSubject$ for converting to state signal

- projects/ngrx.io/content/marketing/contributing.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: make contributing video responsive

- projects/ngrx.io/content/guide/schematics/action.md
Closes ngrx#3873
```
[ ] Bugfix
[ ] Feature
```
Closes #3873 
```
[ ] Yes
[x] No
```
> docs(schematics): update action schematic documentation

- modules/component-store/schematics-core/tsconfig.spec.json
- modules/component/schematics-core/tsconfig.spec.json
- modules/data/schematics-core/tsconfig.spec.json
- modules/effects/schematics-core/tsconfig.spec.json
- modules/entity/schematics-core/tsconfig.spec.json
- modules/router-store/schematics-core/tsconfig.spec.json
- modules/schematics/schematics-core/tsconfig.spec.json
- modules/store-devtools/schematics-core/tsconfig.spec.json
- modules/store/schematics-core/tsconfig.spec.json
- modules/store/spec/store_pipes.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
Fixing a last error after the merge causing the build to fail.
> lint(store): fix lint error after merge

- modules/schematics/src/action/__snapshots__/index.spec.ts.snap
- modules/schematics/src/action/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): refactor action specs to snapshots

- angular.json
```
[ ] Bugfix
[ ] Feature
```
Closes #3900
```
[ ] Yes
[ ] No
```
> build: include LICENSE in npm package

- modules/schematics/src/container/__snapshots__/index.spec.ts.snap
- modules/schematics/src/container/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to container

- modules/schematics/src/data/__snapshots__/index.spec.ts.snap
- modules/schematics/src/data/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to data

- modules/schematics/src/entity/__snapshots__/index.spec.ts.snap
- modules/schematics/src/entity/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to entity

- projects/ngrx.io/content/guide/store/reducers.md
docs(store): update to reducer documentation
update to example code for registering root and feature state using `provideState()`.
- [/ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [/ ] Documentation has been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[/ ] Documentation content changes
```
Closes #3913 
```
[ ] Yes
[/ ] No
```
> docs(store): fix example of feature reducer registration

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- build/tasks.ts
- modules/component-store/CHANGELOG.md
- modules/component/CHANGELOG.md
- modules/data/CHANGELOG.md
- modules/effects/CHANGELOG.md
- modules/entity/CHANGELOG.md
- modules/eslint-plugin/CHANGELOG.md
- modules/eslint-plugin/scripts/generate-overview.ts
- modules/router-store/CHANGELOG.md
- modules/schematics/CHANGELOG.md
- modules/store-devtools/CHANGELOG.md
- modules/store/CHANGELOG.md
- nx.json
- projects/ngrx.io/content/guide/data/entity-dataservice.md
- projects/ngrx.io/content/guide/data/entity-metadata.md
- projects/ngrx.io/content/guide/eslint-plugin/index.md
- projects/ngrx.io/content/guide/nightlies.md
- projects/ngrx.io/content/guide/schematics/index.md
- projects/ngrx.io/content/marketing/contributing.md
- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/scripts/deploy-to-firebase.sh
- projects/ngrx.io/scripts/deploy-to-firebase.test.sh
- projects/ngrx.io/tools/transforms/templates/lib/githubLinks.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: replace master branch with main

- .circleci/config.yml
- .gitignore
```
[ ] Bugfix
[ ] Feature
```
No cache hits
Closes #
Cache hits
```
[ ] Yes
[x] No
```
> ci: update Nx Cloud environment variable

- modules/eslint-plugin/spec/rules/updater-explicit-return-type.spec.ts
- modules/eslint-plugin/src/rules/component-store/updater-explicit-return-type.ts
- modules/eslint-plugin/src/utils/helper-functions/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3868
```
[ ] Yes
[ ] No
```
> fix(eslint): updater-explicit-return-type not applied when inheritance

- modules/schematics/src/effect/__snapshots__/index.spec.ts.snap
- modules/schematics/src/effect/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of https://github.com/ngrx/platform/issues/3865
```
[ ] Yes
[x] No
```
> test(schematics): add snapshot tests to effects

- modules/schematics/src/reducer/__snapshots__/index.spec.ts.snap
- modules/schematics/src/reducer/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to reducer

- modules/schematics/src/selector/__snapshots__/index.spec.ts.snap
- modules/schematics/src/selector/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to selector

- modules/schematics/src/store/__snapshots__/index.spec.ts.snap
- modules/schematics/src/store/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to store

- modules/schematics/src/feature/__snapshots__/index.spec.ts.snap
- modules/schematics/src/feature/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Part of #3865
```
[ ] Yes
[ ] No
```
> test(schematics): add snapshot tests to feature

- modules/eslint-plugin/spec/rules/prefer-concat-latest-from.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, the eslint plugin does not detect the actions, if it is injected via the new inject method
Related to #3943 
Closes #3943 
Updated actions detection logic to also check for actions injected via inject method from the @angular/core package
```
[ ] Yes
[x] No
```
> fix(eslint-plugin): fix prefer-contact-latest-from rule to detect inject

- modules/eslint-plugin/src/rule-creator.ts
```
[ ] Bugfix
[x] Feature
```
Closes #3942 
URL to docs is included within the message.
```
[ ] Yes
[x] No
```
> feat(eslint-plugin): include docs URL in lint message

- modules/eslint-plugin/spec/rules/no-typed-global-store.spec.ts
- modules/eslint-plugin/src/rules/store/no-typed-global-store.ts
- modules/eslint-plugin/src/utils/helper-functions/guards.ts
- modules/eslint-plugin/src/utils/helper-functions/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #3950
```
[ ] Yes
[x] No
```
> fix(eslint-plugin): support inject for no-typed-global-store rule

- projects/ngrx.io/content/guide/store/feature-creators.md
```
[ ] Bugfix
[ ] Feature
```
There is no video guide on how to use `createFeature` function.
Added a video guide on how to use the `createFeature` function.
```
[ ] Yes
[x] No
```
> docs(store): add video guide to feature creators page

- modules/eslint-plugin/spec/rules/avoid-dispatching-multiple-actions-sequentially.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, the eslint plugin does not detect the actions and state, if it is injected via the new inject method
Related to #3948
Updated actions detection logic to also check for actions injected via inject method from the @angular/core package
```
[ ] Yes
[X] No
```
> test(eslint-plugin): add inject tests for avoid-dispatching-multiple-actions-sequentially

- modules/eslint-plugin/spec/rules/avoid-combining-selectors.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, the eslint plugin does not detect the actions and state, if it is injected via the new inject method
Related to #3942 
Updated actions detection logic to also check for actions injected via inject method from the @angular/core package
```
[ ] Yes
[x] No
```
> test(eslint-plugin): add inject tests for avoid-combining-selector

- modules/eslint-plugin/spec/rules/prefix-selectors-with-select.spec.ts
- modules/eslint-plugin/src/rules/store/prefix-selectors-with-select.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #3956
```
[ ] Yes
[x] No
```
> fix(eslint-plugin): prefix-selectors-with-select suggestion

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
CI uses updated node images and browser tools for running tests
```
[ ] Yes
[x] No
```
> ci: update node images and browser tools

- projects/example-app/src/app/app.module.ts
- projects/example-app/src/app/core/components/layout.component.ts
- projects/example-app/src/app/reducers/index.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
Refactors the example app not to use an injection token, which was needed before.
> refactor(example-app): remove root reducer injection token

- modules/eslint-plugin/spec/rules/select-style.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(eslint-plugin): add inject tests for select-style rule

- projects/ngrx.io/content/guide/effects/index.md
- [ ✓] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
```
[✓ ] Bugfix
[ ] Feature
```
Closes #3985 
```
[ ] Yes
[✓ ] No
```
> docs(effects): removed unneeded critical div (#3985)

- modules/eslint-plugin/spec/rules/prefer-action-creator-in-dispatch.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(eslint-plugin): add inject tests for prefer-action-creator-in-dispatch rule

- projects/ngrx.io/content/guide/component-store/lifecycle.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4010 
```
[ ] Yes
[x] No
```
> docs(component-store): fix typo on the lifecycle page

- modules/eslint-plugin/spec/rules/no-dispatch-in-effects.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, the eslint plugin does not detect the actions and state, if it is injected via the new inject method
Related to #3943 
Updated actions detection logic to also check for actions injected via inject method from the @angular/core package
```
[ ] Yes
[x] No
```
> test(eslint-plugin): add inject tests for no-dispatch-in-effects

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> ci: update node images

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
Updates the contributing file because the module projects within the angular.json file are moved to the module folders.
```
[ ] Yes
[x] No
```
> docs: update contributing test script

- modules/eslint-plugin/spec/rules/avoid-combining-component-store-selectors.spec.ts
- modules/eslint-plugin/spec/rules/avoid-combining-selectors.spec.ts
- modules/eslint-plugin/src/configs/all-requiring-type-checking.ts
- modules/eslint-plugin/src/configs/all.ts
- modules/eslint-plugin/src/configs/component-store-strict.ts
- modules/eslint-plugin/src/configs/component-store.ts
- modules/eslint-plugin/src/configs/recommended-requiring-type-checking.ts
- modules/eslint-plugin/src/configs/recommended.ts
- modules/eslint-plugin/src/configs/strict-requiring-type-checking.ts
- modules/eslint-plugin/src/configs/strict.ts
- modules/eslint-plugin/src/rules/component-store/avoid-combining-component-store-selectors.ts
- projects/ngrx.io/content/guide/eslint-plugin/index.md
- projects/ngrx.io/content/guide/eslint-plugin/rules/avoid-combining-component-store-selectors.md
```
[ ] Bugfix
[x] Feature
```
Closes #3939
```
[ ] Yes
[ ] No
```
> feat(eslint-plugin): add avoid-combining-component-store-selectors rule

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/labeler.yml
- CONTRIBUTING.md
- add signals as new scope
- sort scope list alphabetically
**IMPORTANT: I didn't add schematics-core. Please let me know if I should update my PR**
```
[ ] Bugfix
[ ] Feature
```
CONTRIBUTING.md reflects the current scopes.
```
[ ] Yes
[x] No
```
> docs: add signals package to the list of supported scopes

- modules/data/schematics/ng-add/__snapshots__/index.spec.ts.snap
- modules/data/schematics/ng-add/index.spec.ts
- modules/data/schematics/ng-add/index.ts
```
[ ] Bugfix
[x] Feature
```
Currently ng add do not have standalone for @ngrx/data package
Closes #3935 
Add standalone configuration support for ng add command for @ngrx/data package
```
[ ] Yes
[x] No
```
> feat(data): standalone support for ng add @ngrx/data

- projects/ngrx.io/content/guide/store-devtools/config.md
- projects/ngrx.io/content/guide/store-devtools/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4008 
```
[ ] Yes
[x] No
```
> docs(store-devtools): add docs for `connectOutsideZone` option

- modules/effects/src/act.ts
```
[ ] Bugfix
[x] Feature
[x] Other... Please describe: Deprecation
```
Closes #4072 
```
[ ] Yes
[x] No
```
> feat(effects): deprecate act operator

- projects/ngrx.io/content/guide/data/architecture-overview.md
- projects/ngrx.io/content/guide/data/entity-actions.md
- projects/ngrx.io/content/guide/data/entity-change-tracker.md
- projects/ngrx.io/content/guide/data/entity-collection-service.md
- projects/ngrx.io/content/guide/data/entity-collection.md
- projects/ngrx.io/content/guide/data/entity-dataservice.md
- projects/ngrx.io/content/guide/data/entity-effects.md
- projects/ngrx.io/content/guide/data/entity-metadata.md
- projects/ngrx.io/content/guide/data/entity-reducer.md
- projects/ngrx.io/content/guide/data/entity-services.md
- projects/ngrx.io/content/guide/data/extension-points.md
- projects/ngrx.io/content/guide/data/faq.md
- projects/ngrx.io/content/guide/data/index.md
- projects/ngrx.io/content/guide/data/install.md
- projects/ngrx.io/content/guide/data/limitations.md
- projects/ngrx.io/content/guide/data/save-entities.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4011
```
[ ] Yes
[x] No
```
> docs(data): add warning about maintenance mode

- modules/signals/rxjs-interop/spec/rx-method.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Added missing tests
```
```
[ ] Yes
[x] No
```
> test(signals): add missing tests for `rxMethod`

- projects/ngrx.io/src/styles/2-modules/select-menu/_select-menu-theme.scss
- projects/ngrx.io/src/styles/_constants.scss
```
[x] Bugfix
[ ] Feature
```
Closes #4089 
```
[ ] Yes
[x] No
```
> docs(theme): fix dropdowns background in dark mode

- projects/ngrx.io/src/app/custom-elements/contact-form/contact-form.module.ts
- projects/ngrx.io/src/styles/2-modules/contributor/_contributor-theme.scss
```
[x] Bugfix
[ ] Feature
```
Closes #4085
> docs(theme): fix contributor card in dark mode

- projects/ngrx.io/src/styles/custom-themes/dark-theme.scss
- projects/ngrx.io/src/styles/custom-themes/light-theme.scss
- projects/ngrx.io/src/styles/main.scss
Closes: #4086
```
[x] Bugfix
[ ] Feature
```
Closes #4086 
```
[ ] Yes
[x] No
```
> docs: fix floating labels on forms. Adjust styles setup

- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> docs: remove resources, events, and gitter links

- modules/store-devtools/spec/config.spec.ts
- modules/store-devtools/spec/extension.spec.ts
- modules/store-devtools/src/config.ts
- modules/store-devtools/src/devtools.ts
- modules/store-devtools/src/extension.ts
- modules/store-devtools/src/zone-config.ts
- projects/ngrx.io/content/guide/store-devtools/config.md
- projects/ngrx.io/content/guide/store-devtools/index.md
```
[ ] Bugfix
[x] Feature
```
Closes #4093 
```
[x] Yes
[] No
```
> feat(store-devtools): change connectOutsideZone to be 'true' by default

- modules/store-devtools/migrations/17_0_0-beta/index.spec.ts
- modules/store-devtools/migrations/17_0_0-beta/index.ts
- modules/store-devtools/migrations/migration.json
```
[ ] Bugfix
[x] Feature
```
Adds a migration for #4093
```
[ ] Yes
[x] No
```
Uses `connectInZone` as discussed in https://github.com/ngrx/platform/pull/4103
> feat(store-devtools): add migration for connectInZone

- projects/ngrx.io/content/guide/migration/v17.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #4099
```
[ ] Yes
[x] No
```
> docs: add v17 migration guide

- projects/ngrx.io/package.json
- projects/ngrx.io/src/app/app.module.ts
- projects/ngrx.io/yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Add [https://getpolaris.ai](Polaris) to docs website for runtime performance incident detection.
```
[ ] Yes
[x] No
```
> docs: add polaris integration

- projects/ngrx.io/content/guide/operators/index.md
- projects/ngrx.io/content/guide/operators/install.md
- projects/ngrx.io/content/guide/operators/operators.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
Initial docs for overview, installation, and operators are added for the`@ngrx/operators` package.
```
[ ] Yes
[x] No
```
> docs: add initial docs for @ngrx/operators

- projects/ngrx.io/content/guide/store/selectors.md
```
[ ] Bugfix
[ ] Feature
```
Closes #3968 
@markostanimirovic I have tried to convert the article into documentation. I you fell that there should be something specific there let me know.
> docs(store): add selectSignal documentation

- projects/ngrx.io/content/marketing/events.json
- projects/ngrx.io/content/marketing/workshops.md
- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/app/custom-elements/contact-form/contact-form.component.ts
- projects/ngrx.io/src/styles/1-layouts/top-menu/_top-menu-theme.scss
- projects/ngrx.io/src/styles/1-layouts/top-menu/_top-menu.scss
Replace Enterprise Support with NgRx workshops offering.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add ngrx workshops

- projects/ngrx.io/content/marketing/resources.json
```
[ ] Bugfix
[ ] Feature
```
⚠️ Currently, the development of further features for ngrx-ducks is not planned. We also think about freezing this project due to new features Angular received (e.g. Signals).
🤗 Please reach out, you rely on this project, so we can take your needs into account. 🙏🏻 Thank you!
Closes #
```
[ ] Yes
[x] No
```
> docs(ngrx-ducks): remove library from resources

- projects/ngrx.io/src/app/custom-elements/code/code.component.spec.ts
- projects/ngrx.io/src/app/custom-elements/code/code.component.ts
- projects/ngrx.io/src/styles/1-layouts/sidenav/_sidenav-theme.scss
- projects/ngrx.io/src/styles/2-modules/code/_code-theme.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
A few colors that are used within our dark theme are a bit "off" in my opinion.
This PR updates those colors to match the theme that the angular.io website uses.
> docs: update dark theme colors

- modules/eslint-plugin/spec/rules/component-store/avoid-combining-component-store-selectors.spec.ts
- modules/eslint-plugin/spec/rules/effects/avoid-cyclic-effects.spec.ts
- modules/eslint-plugin/src/rules/effects/avoid-cyclic-effects.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4168
```
[ ] Yes
[x] No
```
> fix(eslint-plugin): only report main pipe violations

- projects/ngrx.io/content/guide/signals/rxjs-integration.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(signals): remove extra semi-colon

- projects/ngrx.io/content/guide/signals/signal-store/entity-management.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): fix typo in Entity Management guide

- projects/ngrx.io/content/guide/signals/index.md
- projects/ngrx.io/src/styles/2-modules/alert/_alert-theme.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): add note about developer preview

- projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4156
```
[ ] Yes
[x] No
```
> docs(signals): add guide for custom SignalStore features

- projects/ngrx.io/content/guide/signals/faq.md
- projects/ngrx.io/content/navigation.json
- projects/ngrx.io/src/styles/2-modules/details/_details-theme.scss
- projects/ngrx.io/src/styles/2-modules/details/_details.scss
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
I skimmed through discord/twitter/discussions to search frequently asked questions.
This page can start as a starting point, which we can extend later.
I didn't include the question "what's the difference with store / component store", because I think it would be better to give that it's own page. We could move https://ngrx.io/guide/component-store/comparison from a subpage to an index page and include …
> docs(signals): add FAQ

- projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
```
[ ] Bugfix
[ ] Feature
```
Added @timdeschryver's suggestion from the previous PR.
```
[ ] Yes
[x] No
```
> docs(signals): improve guide for custom SignalStore features

- projects/ngrx.io/content/guide/signals/faq.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): add answers on SignalStore type and constructor-based DI

- projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): improve SignalStore's Core Concepts page

- projects/ngrx.io/content/guide/signals/rxjs-integration.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): improve RxJS Integration page

- modules/eslint-plugin/package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
It is fixing a yarn dependency error
```
[ ] Yes
[x] No
```
> refactor(eslint-plugin): use latest typescript versions in peerDependencies

- projects/ngrx.io/content/marketing/workshops.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add April workshop and remove Jan

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add operators to issue template

- modules/signals/spec/signal-store.spec.ts
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Added missing test
```
```
[ ] Yes
[x] No
```
> test(signals): verify that onInit hook is executed in injection context

- projects/ngrx.io/content/guide/signals/signal-store/lifecycle-hooks.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): improve Lifecycle Hooks page

- modules/signals/spec/types/signal-store.types.spec.ts
- modules/signals/src/signal-store-models.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4246
```
[ ] Yes
[x] No
```
> fix(signals): correctly infer the type of methods with generics

- projects/ngrx.io/content/marketing/workshops.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: update European workshop for May

- projects/ngrx.io/content/guide/signals/index.md
- projects/ngrx.io/content/guide/signals/signal-state.md
- projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): improve SignalState docs

- modules/component-store/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(component-store): deprecate `tapResponse` export

- projects/ngrx.io/src/pwa-manifest.json
```
[x] Bugfix
[ ] Feature
```
The correct path is set for PWA icons.
```
[ ] Yes
[x] No
```
> fix(ngrx.io): set correct path for pwa icons

- modules/effects/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(effects): deprecate `concatLatestFrom` export

- projects/ngrx.io/content/guide/store/feature-creators.md
```
[ ] Bugfix
[ ] Feature
```
#4244
Closes #4244
```
[ ] Yes
[x] No
```
> docs(store): add example of reusing extra selectors

- modules/schematics/src/effect/index.ts
- modules/schematics/src/feature/index.spec.ts
- modules/schematics/src/reducer/index.ts
```
[ ] Bugfix
[ ] Feature
```
The current steps on the website result in an error. https://ngrx.io/guide/schematics/feature
```
ng generate module User --flat false
ng generate feature user/User -m user.module.ts --group
```
Closes #4281
The feature schematic creates and updates the desired files:
```
[ ] Yes
[x] No
```
> fix(schematics): correct module while generating a feature

- projects/ngrx.io/content/examples/store-walkthrough/src/app/tests/app.component.1.spec.ts
```
[ ] Bugfix
[ ] Feature
```
The "Using Mock Selectors" section does not have example codes of the usage of the `overrideSelector` method.
Closes #4100
Now readers can check the example code right from the document.
```
[ ] Yes
[x] No
```
> docs(store): include example code for using overrideSelector #4100

- projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4287
```
[ ] Yes
[ ] No
```
> docs(signals): improve example code snipped for rxMethod

- modules/operators/src/concat_latest_from.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(operators): fix imports paths in examples in concat_latest_from.ts

- modules/schematics/src/feature/schema.json
closes #4278
```
[x] Bugfix
[ ] Feature
```
The default entity value is `"false"` in place of `false`
Closes #4278
The default value is `false`, as a boolean
```
[ ] Yes
[x] No
```
> fix(schematics): set correct default value type

- projects/ngrx.io/content/examples/store-walkthrough/src/app/app.component.ts
- projects/ngrx.io/content/examples/store-walkthrough/src/app/book-list/books.service.ts
- projects/ngrx.io/content/examples/testing-store/src/app/app.component.ts
- projects/ngrx.io/content/examples/testing-store/src/app/book-list/books.service.ts
```
[ ] Bugfix
[ ] Feature
```
There are some code examples that have lint errors.
Fix the lint errors
```
[ ] Yes
[x] No
```
> docs(store): fix lint issues in example code

- modules/eslint-plugin/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #4322 
```
[ ] Yes
[x] No
```
There's no test because the schematic runner doesn't update the package.json file.
I verified this change locally.
> fix(eslint-plugin): add as devDependency via ng add

- .devcontainer/devcontainer.json
- .devcontainer/ngrx.io/devcontainer.json
```
[ ] Bugfix
[ ] Feature
```
Closes https://github.com/ngrx/platform/issues/4286#issuecomment-2134014232
```
[ ] Yes
[ ] No
```
> chore: update devcontainers

- projects/ngrx.io/content/guide/migration/v18.md
- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
Closes #4376
```
[ ] Yes
[x] No
```
> docs: add v18 migration guide

- projects/ngrx.io/content/guide/eslint-plugin/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4381
```
[ ] Yes
[x] No
```
> docs(eslint-plugin): re-generate config

- .eslintrc.json
- modules/data/src/utils/default-logger.ts
- modules/entity/spec/fixtures/book.ts
- modules/eslint-plugin/package.json
- modules/eslint-plugin/scripts/generate-config.ts
- modules/eslint-plugin/spec/exported-rules.spec.ts
- modules/eslint-plugin/src/configs/effects.json
- modules/eslint-plugin/src/configs/signals.json
- modules/eslint-plugin/src/rule-creator.ts
- modules/eslint-plugin/src/rules/index.ts
- modules/eslint-plugin/src/utils/helper-functions/rules.ts
- modules/eslint-plugin/src/utils/helper-functions/versions.ts
- modules/schematics/src/store/__snapshots__/index.spec.ts.snap
- modules/schematics/src/store/index.spec.ts
- modules/store/migrations/8_0_0-rc/index.ts
- package.json
- projects/ngrx.io/.eslintrc.json
- projects/ngrx.io/content/guide/eslint-plugin/index.md
- projects/ngrx.io/src/app/custom-elements/api/api-list.component.spec.ts
- projects/ngrx.io/src/app/custom-elements/resource/resource.service.spec.ts
- yarn.lock
```
[x] Bugfix
[ ] Feature
```
Closes #4385
```
[ ] Yes
[ ] No
```
> fix(eslint-plugin): include signals to ESLint v8 rules

- projects/ngrx.io/content/marketing/workshops.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add new workshop dates

- projects/example-app/README.md
- projects/ngrx.io/content/guide/component-store/install.md
- projects/ngrx.io/content/guide/component/install.md
- projects/ngrx.io/content/guide/data/extension-points.md
- projects/ngrx.io/content/guide/data/install.md
- projects/ngrx.io/content/guide/data/limitations.md
- projects/ngrx.io/content/guide/effects/index.md
- projects/ngrx.io/content/guide/effects/install.md
- projects/ngrx.io/content/guide/entity/install.md
- projects/ngrx.io/content/guide/eslint-plugin/install.md
- projects/ngrx.io/content/guide/migration/v13.md
- projects/ngrx.io/content/guide/operators/install.md
- projects/ngrx.io/content/guide/router-store/install.md
- projects/ngrx.io/content/guide/schematics/index.md
- projects/ngrx.io/content/guide/schematics/install.md
- projects/ngrx.io/content/guide/signals/install.md
- projects/ngrx.io/content/guide/store-devtools/install.md
- projects/ngrx.io/content/guide/store/install.md
- projects/ngrx.io/content/guide/store/reducers.md
- projects/ngrx.io/content/guide/store/why.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: update angular.io references to angular.dev

- projects/ngrx.io/content/guide/eslint-plugin/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4375
```
[ ] Yes
[x] No
```
> docs(eslint-plugin): update docs and include ESLint v9 details

- modules/eslint-plugin/spec/rules/effects/no-multiple-actions-in-effects.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
> chore(eslint-plugin): fix typo in test

- modules/eslint-plugin/spec/rules/effects/use-effects-lifecycle-interface.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #4429
```
[ ] Yes
[x] No
```
Since this was a problem before, I added the reproduction to prevent regression in the future.
> test(eslint-plugin): reproduce issue 4429

- projects/ngrx.io/content/guide/signals/signal-store/entity-management.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): update entity management guide

- modules/signals/src/signal-store-feature.ts
- modules/signals/src/signal-store.ts
```
[ ] Bugfix
[x] Feature
```
- `signalStore` accepts up to 9 features
- `signalStoreFeature` accepts up to 6 features
Closes #4314
- `signalStore` accepts up to 15 features
- `signalStoreFeature` accepts up to 10 features
```
[ ] Yes
[x] No
```
> feat(signals): add additional signatures for signalStore and signalStoreFeature

- projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
- projects/ngrx.io/content/guide/signals/signal-store/index.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4274
```
[ ] Yes
[x] No
```
> docs(signals): add note about TS issue for custom features with static input

- modules/signals/entities/src/index.ts
```
[ ] Bugfix
[x] Feature
```
This type will be useful when defining custom features that depend on `entities` array:
```ts
export function withFoo<Entity>() {
return signalStoreFeature(
{ computed: type<EntityComputed<Entity>>() },
// `entities` computed signal is available here
withComputed(({ entities }) => ({
/* ... */
}))
);
}
```
```
[ ] Yes
[x] No
```
> feat(signals): add EntityComputed to the public API

- modules/signals/entities/src/with-entities.ts
- modules/signals/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Closes #4272
```
[ ] Yes
[x] No
```
> feat(signals): add models for building advanced features to the public API

- modules/signals/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(signals): add StateWatcher to the public API

- projects/ngrx.io/content/navigation.json
#4452 
```
[ ] Bugfix
[ ] Feature
```
Now users can access ngrx linkedin page with just one click!
Closes #
```
[ ] Yes
[ ] No
```
> docs: add LinkedIn link to footer

- projects/ngrx.io/content/guide/signals/index.md
```
[ ] Bugfix
[ ] Feature
```
In v18.0.0, the `@ngrx/signals` package will be marked as stable.
```
[ ] Yes
[x] No
```
> docs(signals): remove developer preview flag

- modules/component-store/package.json
- modules/component/package.json
- modules/data/package.json
- modules/effects/package.json
- modules/entity/package.json
- modules/eslint-plugin/package.json
- modules/operators/package.json
- modules/router-store/package.json
- modules/schematics/package.json
- modules/signals/package.json
- modules/store-devtools/package.json
- modules/store/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #
When running `ng update @ngrx/store` or `nx migrate @ngrx/store@latest`, the `@ngrx/operators` package is upgraded also
```
[ ] Yes
[x] No
```
> fix(operators): add @ngrx/operators to packageGroup for updates

- .github/ISSUE_TEMPLATE/bug-report.yml
This links the current (and outdated) Stackblitz template for the Signal Store to a GitHub repo, which is much easier to update.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(signals): update stackblitz link

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
All of our builds are suddenly failing.
After some research it seems due to a timeout during the CI build.
> ci: increase test timeout

- projects/ngrx.io/content/guide/eslint-plugin/index.md
Eslint plugin doc updated
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs(eslint-plugin): use correct extends

- modules/component-store/package.json
```
[x] Bugfix
[ ] Feature
```
Closes #4524
```
[ ] Yes
[x] No
```
> fix(component-store): remove @ngrx/operators from dependencies

- projects/ngrx.io/content/guide/effects/index.md
```
[ ] Bugfix
[ ] Feature
```
`standalone: true` is redundant in v19
```
[ ] Yes
[x] No
```
> docs(effects): remove redundant standalone flag

- modules/component/src/let/let.directive.ts
- modules/component/src/push/push.pipe.ts
- projects/ngrx.io/content/guide/component/let.md
- projects/ngrx.io/content/guide/component/push.md
```
[ ] Bugfix
[ ] Feature
```
`standalone: true` is default in v19
```
[ ] Yes
[x] No
```
> docs(component): remove redundant standalone flag

- modules/signals/rxjs-interop/spec/rx-method.spec.ts
- modules/signals/spec/helpers.ts
- projects/ngrx.io/content/guide/signals/signal-state.md
- projects/ngrx.io/content/guide/signals/signal-store/index.md
- projects/ngrx.io/content/guide/signals/signal-store/testing.md
```
[ ] Bugfix
[ ] Feature
```
`standalone: true` is default in v19
```
[ ] Yes
[x] No
```
> docs(signals): remove redundant standalone flag

- projects/ngrx.io/content/navigation.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: remove "Getting Started" link from topbar

- .github/workflows/main.yml
```
[ ] Bugfix
[ ] Feature
```
The main build fails on the `build` task.
The main build should be green.
```
[ ] Yes
[ ] No
```
> ci: fix main build command

- README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
update ci status badge
```
[ ] Yes
[ ] No
```
> docs: udpate ci status badge

- .github/workflows/ci.yml
- .github/workflows/main.yml
```
[ ] Bugfix
[ ] Feature
```
Closes #
Fixes issue with corepack failing on signature validations
https://github.com/nodejs/corepack/issues/612
```
[ ] Yes
[ ] No
```
> ci: install pinned version of corepack

- .devcontainer/devcontainer.json
```
[ ] Bugfix
[ ] Feature
```
Closes #4704
```
[ ] Yes
[ ] No
```
> chore: fix devcontainer creation

- modules/store/src/provide_store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(store): replace deprecated ENVIRONMENT_INITIALIZER

- modules/effects/spec/provide_effects.spec.ts
- modules/effects/src/provide_effects.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(effects): replace deprecated ENVIRONMENT_INITIALIZER

- modules/router-store/src/provide_router_store.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(router-store): replace deprecated ENVIRONMENT_INITIALIZER

- modules/data/src/provide-entity-data.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(data): replace deprecated ENVIRONMENT_INITIALIZER

- projects/ngrx.io/content/guide/eslint-plugin/rules/no-dispatch-in-effects.md
- [X ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
Closes #4740
```
[ ] Yes
[X ] No
```
> docs(eslint-plugin): correct documentation no-dispatch-in-effects.md

- projects/ngrx.io/content/marketing/workshops.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update workshops page

- projects/ngrx.io/src/app/custom-elements/contact-form/contact-form.component.ts
Adjust the contacts for the workshop.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: adjust contacts for the workshop

- projects/ngrx.io/src/app/app.module.ts
Adding Firebase's app-check that is using reCAPTCHA v3 under the hood. Once the change is live I'll turn on the protection on the firebase side.
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[x] No
```
> docs: add app-check to avoid spam

- CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
Fix typo error on changelog
Closes #
```
[ ] Yes
[x] No
```
> fix(changelog): correct anchor tag for 19.0.0-beta

- projects/ngrx.io/content/guide/signals/signal-store/custom-store-features.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(signals): move withFeature section after custom features with input; improve description

- projects/www/src/app/app.component.ts
- projects/www/src/styles.scss
```
[x] Bugfix
[ ] Feature
```
Scrollbars are shown on Chrome on Windows
Closes #4806
Scrollbars are hidden on Chrome on Windows
```
[ ] Yes
[x] No
```
> fix(www): remove horizontal scrollbar

- projects/ngrx.io/content/guide/migration/v20.md
- projects/www/src/app/pages/guide/migration/v20.md
```
[ ] Bugfix
[ ] Feature
```
Closes #4842
```
[ ] Yes
[x] No
```
> docs: add v20 migration guide

- modules/signals/entities/spec/types/with-entities.types.spec.ts
- modules/signals/spec/types/patch-state.types.spec.ts
- modules/signals/src/state-source.ts
- modules/signals/src/with-feature.ts
- modules/signals/src/with-hooks.ts
- modules/signals/src/with-methods.ts
- modules/signals/src/with-props.ts
```
[x] Bugfix
[ ] Feature
```
Closes #4638
```
[ ] Yes
[x] No
```
> fix(signals): allow generic template literals as state keys

- projects/ngrx.io/content/guide/migration/v20.md
- projects/www/src/app/pages/guide/migration/v20.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(migration): update NgRx package commands to stable versions

- projects/www/src/app/app.config.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
Enabling `anchorScrolling` fixes the behavior when a side-nav menu item is clicked, that the page scrolls to the content of the header. Because of the smooth scrolling behavior it might happen that the wrong text will be highlighted as active due to the scroll position.
```
[ ] Yes
[x] No
```
> docs(www): fix sidenav click behavior

- projects/www/src/app/pages/(home).page.ts
Closes #4944
```
[ ] Bugfix
[ ] Feature
```
Closes #4944
```
[ ] Yes
[x] No
```
> docs(www): add learn signalStore button
